force-app/main/default/objects/VIAffaire__c/VIAffaire__c.object-meta.xml
<CustomObject>
    <label>Affaire</label>
    <nameField>
        <label>Code Affaire</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Affaires</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VIAffaire__c/fields/Entite_BW__c.field-meta.xml
<CustomField>
    <fullName>Entite_BW__c</fullName>
    <label>Entité BW</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>EntiteBW</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/VIAffaire__c/fields/Nom_affaire__c.field-meta.xml
<CustomField>
    <fullName>Nom_affaire__c</fullName>
    <label>Nom de l&apos;affaire</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VIAvenant__c/VIAvenant__c.object-meta.xml
<CustomObject>
    <label>Avenant</label>
    <nameField>
        <displayFormat>A{0000000}</displayFormat>
        <label>Ref de Avenant</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Avenants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VIAvenant__c/fields/Affaire__c.field-meta.xml
<CustomField>
    <fullName>Affaire__c</fullName>
    <label>Affaire</label>
    <referenceTo>VIAffaire__c</referenceTo>
    <relationshipLabel>Avenants</relationshipLabel>
    <relationshipName>Avenants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VIAvenant__c/fields/Code_avenant__c.field-meta.xml
<CustomField>
    <fullName>Code_avenant__c</fullName>
    <label>Code avenant</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VIAvenant__c/fields/Complet__c.field-meta.xml
<CustomField>
    <fullName>Complet__c</fullName>
    <label>Complet</label>
    <summarizedField>VILigne_Budget__c.Complet__c</summarizedField>
    <summaryForeignKey>VILigne_Budget__c.Avenant__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/VIAvenant__c/fields/Complet_E__c.field-meta.xml
<CustomField>
    <fullName>Complet_E__c</fullName>
    <label>Complet €</label>
    <summarizedField>VILigne_Budget__c.Complet_E__c</summarizedField>
    <summaryForeignKey>VILigne_Budget__c.Avenant__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/VIAvenant__c/fields/Debours__c.field-meta.xml
<CustomField>
    <fullName>Debours__c</fullName>
    <label>Debours</label>
    <summarizedField>VILigne_Budget__c.Debours__c</summarizedField>
    <summaryForeignKey>VILigne_Budget__c.Avenant__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/VIAvenant__c/fields/Debours_E__c.field-meta.xml
<CustomField>
    <fullName>Debours_E__c</fullName>
    <label>Debours €</label>
    <summarizedField>VILigne_Budget__c.Debours_E__c</summarizedField>
    <summaryForeignKey>VILigne_Budget__c.Avenant__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/VIAvenant__c/fields/Periode_comptable__c.field-meta.xml
<CustomField>
    <fullName>Periode_comptable__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Période comptable</label>
    <referenceTo>VIPeriode__c</referenceTo>
    <relationshipLabel>Avenants</relationshipLabel>
    <relationshipName>Avenants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VIAvenant__c/fields/PRI__c.field-meta.xml
<CustomField>
    <fullName>PRI__c</fullName>
    <label>PRI</label>
    <summarizedField>VILigne_Budget__c.PRI__c</summarizedField>
    <summaryForeignKey>VILigne_Budget__c.Avenant__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/VIAvenant__c/fields/PRI_E__c.field-meta.xml
<CustomField>
    <fullName>PRI_E__c</fullName>
    <label>PRI €</label>
    <summarizedField>VILigne_Budget__c.PRI_E__c</summarizedField>
    <summaryForeignKey>VILigne_Budget__c.Avenant__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/VIAvenant__c/fields/Statut_avenant__c.field-meta.xml
<CustomField>
    <fullName>Statut_avenant__c</fullName>
    <defaultValue>&apos;10 Prévue&apos;</defaultValue>
    <label>Statut de l&apos;avenant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Affaire_Statut</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/VICentre_Section__c/VICentre_Section__c.object-meta.xml
<CustomObject>
    <label>Centre / Section</label>
    <nameField>
        <label>Nom de Centre / Section</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Centres / Sections</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VILigne_Budget__c/VILigne_Budget__c.object-meta.xml
<CustomObject>
    <label>Ligne de budget</label>
    <nameField>
        <displayFormat>B{00000000}</displayFormat>
        <label>Ref de ligne de budget</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lignes de budgets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VILigne_Budget__c/fields/Avenant__c.field-meta.xml
<CustomField>
    <fullName>Avenant__c</fullName>
    <label>Avenant</label>
    <referenceTo>VIAvenant__c</referenceTo>
    <relationshipLabel>Lignes de budgets</relationshipLabel>
    <relationshipName>Budgets_sur_affaires</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VILigne_Budget__c/fields/Centre_Section__c.field-meta.xml
<CustomField>
    <fullName>Centre_Section__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Centre / Section</label>
    <referenceTo>VICentre_Section__c</referenceTo>
    <relationshipName>Budgets_sur_affaires</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VILigne_Budget__c/fields/Complet_E__c.field-meta.xml
<CustomField>
    <fullName>Complet_E__c</fullName>
    <label>Complet €</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VILigne_Budget__c/fields/Debours__c.field-meta.xml
<CustomField>
    <fullName>Debours__c</fullName>
    <label>Débours</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VILigne_Budget__c/fields/Heures__c.field-meta.xml
<CustomField>
    <fullName>Heures__c</fullName>
    <label>Heures</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VILigne_Budget__c/fields/PRI__c.field-meta.xml
<CustomField>
    <fullName>PRI__c</fullName>
    <label>PRI</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VILigne_Budget__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <formula>text(Avenant__r.Statut_avenant__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Statut</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VILigne_Budget__c/fields/Type_de_depense__c.field-meta.xml
<CustomField>
    <fullName>Type_de_depense__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Type de dépense</label>
    <referenceTo>VIType_de_depense__c</referenceTo>
    <relationshipName>Budgets_sur_affaires</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/VILigne_d_affaire_mensuelle__c.object-meta.xml
<CustomObject>
    <label>Ligne d&apos;affaire mensuelle</label>
    <nameField>
        <label>Ref de Ligne d&apos;affaire mensuelle</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lignes d&apos;affaire mensuelles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/Affaire__c.field-meta.xml
<CustomField>
    <fullName>Affaire__c</fullName>
    <label>Affaire</label>
    <referenceTo>VIAffaire__c</referenceTo>
    <relationshipLabel>Lignes d&apos;affaire mensuelles</relationshipLabel>
    <relationshipName>Lignes_d_affaire_mensuelles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/Entite_BW__c.field-meta.xml
<CustomField>
    <fullName>Entite_BW__c</fullName>
    <formula>text(Affaire__r.Entite_BW__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Entité BW</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/Periode_comptable__c.field-meta.xml
<CustomField>
    <fullName>Periode_comptable__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Période comptable</label>
    <referenceTo>VIPeriode__c</referenceTo>
    <relationshipLabel>Lignes d&apos;affaire mensuelles</relationshipLabel>
    <relationshipName>Lignes_d_affaire_mensuelles</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VIPeriode__c/VIPeriode__c.object-meta.xml
<CustomObject>
    <label>Période comptable</label>
    <nameField>
        <label>Nom de Période</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Périodes comptables</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VIPeriode__c/fields/Date_de_debut__c.field-meta.xml
<CustomField>
    <fullName>Date_de_debut__c</fullName>
    <label>Date de début</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VIPeriode__c/fields/Date_de_fin__c.field-meta.xml
<CustomField>
    <fullName>Date_de_fin__c</fullName>
    <label>Date de fin</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VIPeriode__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Periode_comptable_statut</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/VIType_de_depense__c/VIType_de_depense__c.object-meta.xml
<CustomObject>
    <label>Type de dépense</label>
    <nameField>
        <label>Nom de Type de dépense</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Types de dépenses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/VIZoomBudgetController.cls
public class VIZoomBudgetController {

    public String Valeur{get;set;}    
    public string SortOrder { get; set; }
    public string SortOrderPrevious { get; set; }
    Public string Sens { get; set; }    
    public VILigne_d_affaire_mensuelle__c  lam { get; set; }
    public VICentre_Section__c  centre { get; set; }  
    public VItype_de_depense__c  td { get; set; }  

    public list<VIligne_budget__c> ListLigne_budget { get; set; }  
    public list<Ligne> ListLigne { get; set; }  
    Public Date StartExercise { get; set; }   
    

    Public Class Ligne{
        public string avenant  {get;set;}
        public date Date_avenant  {get;set;}
        public decimal heure  {get;set;}
        public string heure_conv  {get;set;}                
        public decimal Debours  {get;set;}                
        public string Debours_conv  {get;set;}                        
        public decimal PRI  {get;set;}                
        public string PRI_conv  {get;set;}                        
        public decimal Complet  {get;set;}                
        public string Complet_conv  {get;set;}                        
        public decimal Debours_E  {get;set;}                
        public string Debours_E_conv  {get;set;}                        
        public decimal PRI_E  {get;set;}                
        public string PRI_E_conv  {get;set;}                        
        public decimal Complet_E  {get;set;}                
        public string Complet_E_conv  {get;set;}                        
        

        public Ligne(string av, date da,   decimal h, decimal D, decimal I, decimal C, decimal D_E, decimal I_E, decimal C_E) {
            avenant = av ;
            Date_avenant = da ;
            heure = h ; 
            heure_conv = VIUtils.conv_number_thousand(h,2) ;             
            Debours = d ; 
            debours_conv = VIUtils.conv_number_thousand(d,2) ;             
            pri = i ; 
            pri_conv = VIUtils.conv_number_thousand(i,2) ;             
            Complet = C ; 
            Complet_conv = VIUtils.conv_number_thousand(c,2) ;             
            Debours_E = d_E ; 
            debours_E_conv = VIUtils.conv_number_thousand(d_E,2) ;             
            pri_E = i_E ; 
            pri_E_conv = VIUtils.conv_number_thousand(i_E,2) ;             
            Complet_E = C_E ; 
            Complet_E_conv = VIUtils.conv_number_thousand(c_E,2) ;             
        }
    }
    
    public VIZoomBudgetController() {
        lam= null;
        centre = null;
        td = null ; 
        
        String lamID = System.currentPageReference().getParameters().get('lam');
        list<VILigne_d_affaire_mensuelle__c>Listlam = [SELECT id, name ,  affaire__r.Nom_affaire__c,affaire__r.Entite_BW__c,
                                                              CurrencyIsoCode, periode_comptable__r.date_de_fin__c,
                                                              affaire__c,Periode_comptable__r.name,affaire__r.Name
                                                         FROM VILigne_d_affaire_mensuelle__c 
                                                        WHERE id=:lamID ];
        if(listlam.size()==1) {
            lam=ListLam[0];
        }
        VIPeriode__c PeriodeOuverte= [SELECT id,date_de_debut__c, date_de_fin__c, entite_bw__c
                                        FROM VIPeriode__c
                                       WHERE statut__c=:VIConstant.PERIODE_OUVERTE
                                         AND entite_bw__c=:lam.affaire__r.Entite_BW__c];
        
        StartExercise=date.newinstance(PeriodeOuverte.date_de_debut__c.year(),1,1);
        if(lam.affaire__r.name.left(1)!='9')
            StartExercise=date.newinstance(2000,1,1);
        
        String CentreID = System.currentPageReference().getParameters().get('Centre');    
        list<VICentre_Section__c>ListCentre = [SELECT id, name
                                                 FROM VICentre_Section__c 
                                                WHERE id=:CentreID];
        if(ListCentre.size()==1) {
            centre=ListCentre[0];
        }
        
        String tdID = System.currentPageReference().getParameters().get('td');    
        list<VIType_de_depense__c>ListType_de_depense = [SELECT id, name
                                                 FROM VIType_de_depense__c 
                                                WHERE id=:tdID];
        if(ListType_de_depense.size()==1) {
            td=ListType_de_depense[0];
        }

        Valeur='Debours';
        SortByDate();
        ReadLigneBudget();
    }

    public void ReadLigneBudget() {
        if(lam==null || centre==null|| td==null) {
            return;
        }

        if(SortOrder==SortOrderPrevious){
            if(Sens=='ASC') {
                Sens='DESC';
            } else {
                Sens='ASC';
            } 
        } else {
            Sens='ASC';
        }

        String query = 'SELECT avenant__c,avenant__r.name, avenant__r.date__c, ';
        query = query +'       Centre_Section__r.name, type_de_depense__r.name,avenant__r.Code_avenant__c , ';
        query = query +'       CurrencyIsoCode, heures__c, ';
        query = query +'       debours__c, debours_E__c, ';
        query = query +'       PRI__c, PRI_E__c, ';
        query = query +'       complet__c, complet_E__c ';
        query = query +'  FROM VILigne_budget__c ';
        query = query +' WHERE Avenant__r.Affaire__c =\''+lam.affaire__c+'\' ';
        query = query +'   AND Centre_Section__c =\''+centre.id+'\' ';
        query = query +'   AND type_de_depense__c =\''+td.id+'\' ';
        query = query +'   AND avenant__r.Periode_comptable__r.name <=\''+lam.Periode_comptable__r.name+'\' '; 
        query = query +'   AND (not avenant__r.Statut_avenant__c like \'10\')  ';
        query = query +'   AND avenant__r.date__c>='+string.valueof(StartExercise).left(10);

        
        if(SortOrder=='Date') {
            query = query +' ORDER BY avenant__r.date__c ';
        } else if(SortOrder=='Avenant') {
            query = query +' ORDER BY avenant__r.name ';
        } 
        query = query +sens ; 
        ListLigne_budget = Database.query(query) ;         
        SortOrderPrevious=SortOrder;

        VILigne_budget__c BudgetTotal = new VILigne_budget__c();
        BudgetTotal.debours__c = 0;
        BudgetTotal.PRI__c = 0;
        BudgetTotal.complet__c = 0;        
        BudgetTotal.debours_E__c = 0;
        BudgetTotal.PRI_E__c = 0;
        BudgetTotal.complet_E__c = 0;        
        for(VILigne_budget__c p :ListLigne_budget) {
            BudgetTotal.Debours__c = BudgetTotal.Debours__c  + (p.debours__c==null ? 0 : p.debours__c) ;
            BudgetTotal.PRI__c     = BudgetTotal.PRI__c      + (p.PRI__c==null ? 0     : p.PRI__c) ;
            BudgetTotal.Complet__c = BudgetTotal.Complet__c  + (p.Complet__c==null ? 0 : p.Complet__c) ;            
            BudgetTotal.Debours_E__c = BudgetTotal.Debours_E__c  + (p.debours_E__c==null ? 0 : p.debours_E__c) ;
            BudgetTotal.PRI_E__c     = BudgetTotal.PRI_E__c      + (p.PRI_E__c==null ? 0     : p.PRI_E__c) ;
            BudgetTotal.Complet_E__c = BudgetTotal.Complet_E__c  + (p.Complet_E__c==null ? 0 : p.Complet_E__c) ;            
        }       
        ListLigne_budget.add(BudgetTotal);
        ListLigne = new List<Ligne>();
        for(VILigne_budget__c bu:ListLigne_budget) {
            ListLigne.add(new ligne(bu.avenant__r.code_avenant__c, bu.avenant__r.date__c, bu.heures__c ,
                      bu.debours__c,bu.pri__c,bu.Complet__c,
                      bu.debours_E__c,bu.pri_E__c,bu.Complet_E__c));
        }

        
        
    }
    
    public void SortByDate() {
        SortOrder='Date';
        ReadLigneBudget();
    }
    public void SortByAvenant() {
        SortOrder='Avenant';
        ReadLigneBudget();
    }

    public void SOQL_verif() {
        // This function is never used. It's just here to keep tracks of field used in the table
        // 

       list<VILigne_budget__c>ListBu = [SELECT avenant__c,avenant__r.name, avenant__r.date__c, 
                                   Centre_Section__r.name, type_de_depense__r.name, 
                                   CurrencyIsoCode, heures__c,
                                   debours__c, debours_E__c,
                                   PRI__c, PRI_E__c,
                                   complet__c, complet_E__c
                              FROM VILigne_budget__c
                             WHERE Avenant__r.Affaire__c =:lam.affaire__c
                               AND Centre_Section__c =:centre.id
                               AND type_de_depense__c =:td.id      
                               AND (not avenant__r.Statut_avenant__c like '10')
                         ORDER BY type_de_depense__r.name,avenant__r.date__c DESC];            

    }

    public List<SelectOption> getValeurOptions() 
    {
            List<SelectOption> ValeurOptions = new List<SelectOption>();        
             
            ValeurOptions.add(new SelectOption('Debours','Debours'));
            ValeurOptions.add(new SelectOption('Industriel','Industriel'));
            ValeurOptions.add(new SelectOption('Complet','Complet'));
  
            return ValeurOptions;
    }

    
}