force-app/main/default/objects/VIAffaire__c/VIAffaire__c.object-meta.xml
<CustomObject>
    <label>Affaire</label>
    <nameField>
        <label>Code Affaire</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Affaires</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VIAffaire__c/fields/Code_commande_Nom_affaire__c.field-meta.xml
<CustomField>
    <fullName>Code_commande_Nom_affaire__c</fullName>
    <formula>Code_Commande__c +&apos; &apos; + Nom_affaire__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Code commande + Nom affaire</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VIAutorisation_pointage__c/VIAutorisation_pointage__c.object-meta.xml
<CustomObject>
    <label>Autorisation de pointage</label>
    <nameField>
        <displayFormat>B{0000000}</displayFormat>
        <label>Ref de Autorisation de pointage</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Autorisations de pointage</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VIAutorisation_pointage__c/fields/Code_affaire__c.field-meta.xml
<CustomField>
    <fullName>Code_affaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Code affaire</label>
    <referenceTo>VIAffaire__c</referenceTo>
    <relationshipLabel>Autorisations de pointage</relationshipLabel>
    <relationshipName>Autorisations_de_pointage</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VIAutorisation_pointage__c/fields/Sous_chapitre__c.field-meta.xml
<CustomField>
    <fullName>Sous_chapitre__c</fullName>
    <label>Sous chapitre</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sous_chapitre</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/VI01_VIAutorisation_pointage.cls
/*
* @author: Henri Saslawsky
* @description: 
*/

public class VI01_VIAutorisation_pointage {

/*
* @description: Method to fill up the libelle
* 
* @param: List of VI01_VIAutorisation_pointage__c
* @return : void
* 
*/

    public static void Load_Libelle (List <VIAutorisation_pointage__c> listAd) { 
        system.debug('entrée dans VI01_VIAutorisation_pointage.Load_libelle');

        list<Schema.PicklistEntry> PicklistEntries = VIAutorisation_pointage__c.sous_chapitre__c.getDescribe().getPicklistValues();
        map<String,String> MApToLabel = new map<String,String>();
        for (Schema.PicklistEntry pe : PicklistEntries){
            MapToLabel.put(pe.getValue(),pe.getLabel().right(pe.getLabel().length()-6));
        }        

        list<id>ListIdAffaire = new list<id>();
        for(VIAutorisation_pointage__c ad:listAd) {
            ListIdAffaire.add(ad.Code_Affaire__c );
        }
        map<id,string>MapNomAffaire = new map<id,string>();
        for(VIAffaire__c Aff : [SELECT id, name, Code_commande_Nom_affaire__c 
                                  FROM VIAffaire__c
                                WHERE id in :ListIdAffaire]) {
            MapNomAffaire.put(aff.id, aff.Code_commande_Nom_affaire__c);
        }
        
        for(VIAutorisation_pointage__c ad:listAd) {
            if(ad.libelle__c==null) {
                
                if(ad.sous_chapitre__c=='00-00') {
                    ad.libelle__c=MapNomAffaire.get(ad.Code_Affaire__c );
                } else {
                    ad.libelle__c=MapToLabel.get(ad.sous_chapitre__c);
                }
            }
        }
        
        
        
    }
}