force-app/main/default/objects/VIAffaire__c/VIAffaire__c.object-meta.xml
<CustomObject>
    <label>Affaire</label>
    <nameField>
        <label>Code Affaire</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Affaires</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VIAffaire__c/fields/Compte__c.field-meta.xml
<CustomField>
    <fullName>Compte__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Compte</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Affaires</relationshipLabel>
    <relationshipName>Affaires</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VIAffaire__c/fields/Entite_BW__c.field-meta.xml
<CustomField>
    <fullName>Entite_BW__c</fullName>
    <label>Entité BW</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>EntiteBW</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/VIAffaire__c/fields/Produit_SousDomaine__c.field-meta.xml
<CustomField>
    <fullName>Produit_SousDomaine__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Produit - SousDomaine</label>
    <referenceTo>VISousDomaine__c</referenceTo>
    <relationshipLabel>Affaires</relationshipLabel>
    <relationshipName>Affaires</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VICompte_general__c/VICompte_general__c.object-meta.xml
<CustomObject>
    <label>Compte général</label>
    <nameField>
        <label>Nom de Compte général</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Comptes généraux</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VICompte_general__c/fields/Type_enregistrement__c.field-meta.xml
<CustomField>
    <fullName>Type_enregistrement__c</fullName>
    <formula>if( Alimentation_PR_PV__c =&apos;PR&apos;, &apos;R&apos;, if(Alimentation_PR_PV__c =&apos;PV&apos;, &apos;A&apos;,&apos;&apos;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type d&apos;enregistrement</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VIEntiteBW__c/VIEntiteBW__c.object-meta.xml
<CustomObject>
    <label>EntiteBW</label>
    <nameField>
        <label>Nom de l&apos;EntiteBW</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EntiteBW</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VIEntiteBW__c/fields/Compte_Bilan_Garantie_Groupe__c.field-meta.xml
<CustomField>
    <fullName>Compte_Bilan_Garantie_Groupe__c</fullName>
    <label>Compte Bilan Garantie Groupe</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VIEntiteBW__c/fields/Compte_Bilan_Garantie_Local__c.field-meta.xml
<CustomField>
    <fullName>Compte_Bilan_Garantie_Local__c</fullName>
    <label>Compte Bilan Garantie Local</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VIEntiteBW__c/fields/Compte_Charge_Garantie_Groupe__c.field-meta.xml
<CustomField>
    <fullName>Compte_Charge_Garantie_Groupe__c</fullName>
    <label>Compte Charge Garantie Groupe</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VIEntiteBW__c/fields/Compte_Charge_Garantie_Local__c.field-meta.xml
<CustomField>
    <fullName>Compte_Charge_Garantie_Local__c</fullName>
    <label>Compte Charge Garantie Local</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VIEntiteBW__c/fields/Compte_Charge_Reprise_Garantie_Groupe__c.field-meta.xml
<CustomField>
    <fullName>Compte_Charge_Reprise_Garantie_Groupe__c</fullName>
    <label>Compte Charge Reprise Garantie Groupe</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VIEntiteBW__c/fields/Compte_Charge_Reprise_Garantie_Local__c.field-meta.xml
<CustomField>
    <fullName>Compte_Charge_Reprise_Garantie_Local__c</fullName>
    <label>Compte Charge Reprise Garantie Local</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VIEntiteBW__c/fields/Compte_Client_Avancement_Groupe__c.field-meta.xml
<CustomField>
    <fullName>Compte_Client_Avancement_Groupe__c</fullName>
    <label>Compte Client Avancement Groupe</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VIEntiteBW__c/fields/Compte_Client_Avancement_Local__c.field-meta.xml
<CustomField>
    <fullName>Compte_Client_Avancement_Local__c</fullName>
    <label>Compte Client Avancement Local</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VIEntiteBW__c/fields/Compte_Loc_AMP_Groupe__c.field-meta.xml
<CustomField>
    <fullName>Compte_Loc_AMP_Groupe__c</fullName>
    <label>Compte Loc AMP Groupe</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VIEntiteBW__c/fields/Compte_Loc_AMP_Local__c.field-meta.xml
<CustomField>
    <fullName>Compte_Loc_AMP_Local__c</fullName>
    <label>Compte Loc AMP Local</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VIEntiteBW__c/fields/Compte_Loc_EMM_Groupe__c.field-meta.xml
<CustomField>
    <fullName>Compte_Loc_EMM_Groupe__c</fullName>
    <label>Compte Loc EMM Groupe</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VIEntiteBW__c/fields/Compte_Loc_EMM_Local__c.field-meta.xml
<CustomField>
    <fullName>Compte_Loc_EMM_Local__c</fullName>
    <label>Compte Loc EMM Local</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VIEntiteBW__c/fields/Compte_Loc_FOL_Groupe__c.field-meta.xml
<CustomField>
    <fullName>Compte_Loc_FOL_Groupe__c</fullName>
    <label>Compte Loc FOL Groupe</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VIEntiteBW__c/fields/Compte_Loc_FOL_Local__c.field-meta.xml
<CustomField>
    <fullName>Compte_Loc_FOL_Local__c</fullName>
    <label>Compte Loc FOL Local</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VIEntiteBW__c/fields/Entite_BW__c.field-meta.xml
<CustomField>
    <fullName>Entite_BW__c</fullName>
    <label>Entité BW</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>EntiteBW</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/VIEntiteBW__c/fields/ID_Affaire_location__c.field-meta.xml
<CustomField>
    <fullName>ID_Affaire_location__c</fullName>
    <label>ID Affaire location</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VIEntiteBW__c/fields/Type_de_depense_AMP__c.field-meta.xml
<CustomField>
    <fullName>Type_de_depense_AMP__c</fullName>
    <label>Type de dépense AMP</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VIEntiteBW__c/fields/Type_de_depense_Avancement__c.field-meta.xml
<CustomField>
    <fullName>Type_de_depense_Avancement__c</fullName>
    <label>Type de dépense Avancement</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VIEntiteBW__c/fields/Type_de_depense_EMM__c.field-meta.xml
<CustomField>
    <fullName>Type_de_depense_EMM__c</fullName>
    <label>Type de dépense EMM</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VIEntiteBW__c/fields/Type_de_depense_FOL__c.field-meta.xml
<CustomField>
    <fullName>Type_de_depense_FOL__c</fullName>
    <label>Type de dépense FOL</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VIEntiteBW__c/fields/Type_de_depense_garantie__c.field-meta.xml
<CustomField>
    <fullName>Type_de_depense_garantie__c</fullName>
    <label>Type de dépense garantie</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VIFacture__c/VIFacture__c.object-meta.xml
<CustomObject>
    <label>Facture</label>
    <nameField>
        <label>Nom de Facture</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Factures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VIFacture__c/fields/Affaire__c.field-meta.xml
<CustomField>
    <fullName>Affaire__c</fullName>
    <label>Affaire</label>
    <referenceTo>VIAffaire__c</referenceTo>
    <relationshipLabel>Factures</relationshipLabel>
    <relationshipName>Factures</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VIFacture__c/fields/BU__c.field-meta.xml
<CustomField>
    <fullName>BU__c</fullName>
    <formula>Affaire__r.Produit_SousDomaine__r.Code_BU__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>BU</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VIFacture__c/fields/Compte__c.field-meta.xml
<CustomField>
    <fullName>Compte__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Compte</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Factures</relationshipLabel>
    <relationshipName>Factures</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VIFacture__c/fields/Date_de_comptabilisation__c.field-meta.xml
<CustomField>
    <fullName>Date_de_comptabilisation__c</fullName>
    <label>Date de comptabilisation</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VIFacture__c/fields/Sous_Domaine__c.field-meta.xml
<CustomField>
    <fullName>Sous_Domaine__c</fullName>
    <formula>Affaire__r.Produit_SousDomaine__r.Code_sous_domaine__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sous-Domaine</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VILigne_comptable__c/VILigne_comptable__c.object-meta.xml
<CustomObject>
    <label>Ligne comptable</label>
    <nameField>
        <displayFormat>L{000000000}</displayFormat>
        <label>Ref de la ligne comptable</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lignes comptables</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VILigne_comptable__c/fields/Affaire__c.field-meta.xml
<CustomField>
    <fullName>Affaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Affaire</label>
    <referenceTo>VIAffaire__c</referenceTo>
    <relationshipLabel>Lignes comptables (Affaire)</relationshipLabel>
    <relationshipName>Ecritures_comptables</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VILigne_comptable__c/fields/Type_enregistrement__c.field-meta.xml
<CustomField>
    <fullName>Type_enregistrement__c</fullName>
    <label>Type d&apos;enregistrement</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/VILigne_d_affaire_mensuelle__c.object-meta.xml
<CustomObject>
    <label>Ligne d&apos;affaire mensuelle</label>
    <nameField>
        <label>Ref de Ligne d&apos;affaire mensuelle</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lignes d&apos;affaire mensuelles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/Affaire__c.field-meta.xml
<CustomField>
    <fullName>Affaire__c</fullName>
    <label>Affaire</label>
    <referenceTo>VIAffaire__c</referenceTo>
    <relationshipLabel>Lignes d&apos;affaire mensuelles</relationshipLabel>
    <relationshipName>Lignes_d_affaire_mensuelles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/Entite_BW__c.field-meta.xml
<CustomField>
    <fullName>Entite_BW__c</fullName>
    <formula>text(Affaire__r.Entite_BW__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Entité BW</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/Sous_Domaine__c.field-meta.xml
<CustomField>
    <fullName>Sous_Domaine__c</fullName>
    <formula>Affaire__r.Produit_SousDomaine__r.Libelle_sous_domaine__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sous-Domaine</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VIPays__c/VIPays__c.object-meta.xml
<CustomObject>
    <label>Pays</label>
    <nameField>
        <label>Nom de Pays</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pays</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VIPays__c/fields/UE__c.field-meta.xml
<CustomField>
    <fullName>UE__c</fullName>
    <defaultValue>false</defaultValue>
    <label>UE</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VIPeriode__c/VIPeriode__c.object-meta.xml
<CustomObject>
    <label>Période comptable</label>
    <nameField>
        <label>Nom de Période</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Périodes comptables</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VIPeriode__c/fields/Date_de_debut__c.field-meta.xml
<CustomField>
    <fullName>Date_de_debut__c</fullName>
    <label>Date de début</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VIPeriode__c/fields/Date_de_fin__c.field-meta.xml
<CustomField>
    <fullName>Date_de_fin__c</fullName>
    <label>Date de fin</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VIPeriode__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Periode_comptable_statut</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/VIBatchGenerateFactSAV.cls
//
//   This batch generate the ecriture_comptable__C for invoice on Affaire closed
//  
//  
// 
/*  for running by hand : 
 VIBatchGenerateFactSAV v = new VIBatchGenerateFactSAV('','1' );
 v.execute(null);

*  for running every hour at xx:16
     VIBatchGenerateFactSAV m = new VIBatchGenerateFactSAV();
     String sch = '0 16 * * * ?';
     String jobID = system.schedule('VIBatchGenerateFactSAV', sch, m);
*/
global class VIBatchGenerateFactSAV implements Schedulable,Database.Batchable<sObject>, Database.Stateful  {

    Global double num_record = 0; 
    Global String IDLog ='';  
    Global String Statut_definitif ='';  
    Global Map<string,VIperiode__c>MapPeriode = new Map<string,VIperiode__c>();    
    Global Map<string,VIEntiteBW__c>Mapentite_bw = new Map<string,VIEntiteBW__c>();  
    Global Map<String, VICompte_general__c >MapCompteGeneral = new Map<String, VICompte_general__c>();
    Global Map<string, VIPays__c >MapPays = new Map<String, VIPays__c>();
    Global List<VILigne_d_affaire_mensuelle__c>ListLam = new List<VILigne_d_affaire_mensuelle__c>();       
    private boolean definitif ; 
    private string AffaireAGenerer; 
    private string Entite_bw ;
    
     public VIBatchGenerateFactSAV(String Param1,String Param2 ) {
        AffaireAGenerer = Param1;        
        Entite_bw = Param2;                
    }


    global Iterable<sObject> start(Database.BatchableContext BC) {

        
        for(VIPeriode__c per: [SELECT id,name, entite_bw__c, date_de_debut__c, date_de_fin__c 
                                 FROM VIPeriode__c
                               WHERE Statut__c=:VIConstant.PERIODE_OUVERTE
                                 AND Entite_bw__c=:Entite_bw]) {
            MapPeriode.put(per.entite_bw__c, per);
        }

        for(VICompte_general__c cg: [SELECT id,name, type_enregistrement__c
                                       FROM VICompte_general__c]) {
            MapCompteGeneral.put(cg.name, cg);
        }

        for(VIPays__c pays : [select name, UE__c from VIPays__C]) {
            MapPays.put(pays.name,pays);
        }

        for(VIEntiteBW__c Ebw: [SELECT id,name, ID_Affaire_location__c, Entite_bw__c,
                                    Compte_Client_Avancement_Local__c,  Compte_Client_Avancement_Groupe__c,
                                    Type_de_depense_Avancement__c, 
                                    Compte_Bilan_Garantie_Local__c,     Compte_Bilan_Garantie_Groupe__c,                             
                                    Compte_Charge_Garantie_Local__c,    Compte_Charge_Garantie_Groupe__c,
                                    Compte_Charge_Reprise_Garantie_Local__c , Compte_Charge_Reprise_Garantie_Groupe__c,
                                    Type_de_depense_garantie__c,
                                    Compte_loc_AMP_local__c,            Compte_loc_AMP_Groupe__c,
                                    Type_de_depense_AMP__c,
                                    Compte_loc_EMM_local__c,            Compte_loc_EMM_Groupe__c,
                                    Type_de_depense_EMM__c,                             
                                    Compte_loc_FOL_local__c,            Compte_loc_FOL_Groupe__c,
                                    Type_de_depense_FOL__c                             
                               FROM VIentiteBW__c 
                               WHERE Entite_bw__c=:Entite_bw]) {
            Mapentite_bw.put(Ebw.Entite_bw__c, Ebw);                                   
        }

        IDLog=VIUtils.LogWrite('VIBatchGenerateFactSAV','4 Running','','Start ');
        num_record = 0 ;

        string sAffaireAGenerer = AffaireAGenerer+'%';
        
        string query = 'SELECT id, name, affaire__c, affaire__r.name,affaire__r.entite_bw__c, compte__r.name, bu__c,sous_domaine__c,  ';
        query = query+'        affaire__r.Produit_SousDomaine__r.Compte__c, affaire__r.compte__r.billingCountryCode, ';
        query = query+'        date__c, date_de_comptabilisation__c, montant_ht__c, Facture_SAV_comptabilisee__c ';                
        query = query+'   FROM VIFacture__c ';
        query = query+'  WHERE Facture_SAV_traitee__c =true  ';
        if(!Test.isRunningTest() ) {
             query = query+'    AND Facture_sur_Affaire_SAV__c=true  '; 
             query = query+'    AND Periode_comptable__r.Statut__c =\''+VIConstant.PERIODE_OUVERTE+'\'';        
             query = query+'    AND Facture_SAV_comptabilisee__c =false  ';
        }
        query = query+'    AND affaire__r.entite_bw__c = \''+Entite_bw+'\'  ';

        query = query+'    AND affaire__r.name Like \''+sAffaireAGenerer+'\'  ';
        query = query+'   Order by affaire__r.name desc  ';        
        system.debug(query);
        return Database.getQueryLocator(query);

    }

    global void execute(Database.BatchableContext BC, List<VIfacture__c> scope) {

        list<VIligne_comptable__c>ListInsertEcriture = new list<VIligne_comptable__c>() ;
        list<VIFacture__c>ListUpsertFacture = new list<VIFacture__c>() ;
        Map<string,id>MapLAM = new Map<string,id>();
        list<id>ListIDAffaire = new list<id>();
        for(VIfacture__c fac:scope) {
            ListIDAffaire.add(fac.affaire__c) ;
        }
        for(VILigne_d_affaire_mensuelle__c lam : [SELECT id ,affaire__c
                                                    FROM VILigne_d_affaire_mensuelle__c 
                                                   WHERE Affaire__c in :ListIDAffaire
                                                     AND Periode_comptable_statut__c =:VIConstant.PERIODE_OUVERTE]){
            MapLam.put(lam.affaire__c, lam.id);
        }

        for(VIFacture__c fac:scope) {
            VIPeriode__c per = mapPeriode.get(fac.affaire__r.entite_bw__c) ;
            VIEntitebw__c entite_bw = Mapentite_bw.get(fac.affaire__r.entite_bw__c) ;
            
            string localisation='030';
            if(MapPays.containskey(fac.affaire__r.compte__r.billingCountryCode)) {
                if(fac.affaire__r.compte__r.billingCountryCode=='FR'){
                    localisation='000';
                } else {
                    if(MapPays.get(fac.affaire__r.compte__r.billingCountryCode).UE__c) {
                        localisation='020';
                   }
                }
            }            
            
            
                    VIligne_comptable__c ecFin1 = new VIligne_comptable__c(periode_comptable__c=per.id, 
                                                                 compte_comptable_groupe__c = entite_bw.Compte_Client_Avancement_Groupe__c,      
                                                                 comptecomptable_local__c = MapCompteGeneral.get(entite_bw.Compte_Client_Avancement_local__c).id, 
                                                                 chapitre__c='00',
                                                                 sous_chapitre__c='00-00',
                                                                 Type_de_depense__c=entite_bw.Type_de_depense_Avancement__c,                                                                           
                                                                 Date_ecriture__c =(fac.date__c==null ? fac.date_de_comptabilisation__c : fac.date__c),              
                                                                 Statut_ecriture_comptable__c = VIConstant.EC_A_PRENDRE,                                                                           
                                                                 affaire__c=fac.affaire__c,
                                                                 affaire_de_rattachement__c=fac.affaire__c,          
                                                                 libelle__c=VIConstant.EC_CA_SUR_AFFAIRE_EN_SAV,                                                                                 
                                                                 centre__c='800',
                                                                 ligne_affaire_mensuelle__c=MapLam.get(fac.affaire__c),
                                                                 type_ligne_comptable__c='FSA',          
                                                                 sens__c = 'D',
                                                                 montant__c=fac.montant_ht__c,
                                                                 type_enregistrement__c=MapCompteGeneral.get(entite_bw.Compte_Client_Avancement_local__c).type_enregistrement__c);
                    ListInsertEcriture.add(ecFin1);

                    VIligne_comptable__c ecFin2 = new VIligne_comptable__c(periode_comptable__c=per.id, 
                                                                 compte_comptable_groupe__c = fac.affaire__r.Produit_SousDomaine__r.Compte__c+localisation,      
                                                                 comptecomptable_local__c =MapCompteGeneral.get(fac.affaire__r.Produit_SousDomaine__r.Compte__c+localisation).id , 
                                                                 chapitre__c='00',
                                                                 sous_chapitre__c='00-00',
                                                                 Type_de_depense__c=entite_bw.Type_de_depense_Avancement__c,                                                                                                                                                      
                                                                 Date_ecriture__c =(fac.date__c==null ? fac.date_de_comptabilisation__c : fac.date__c),              
                                                                 Statut_ecriture_comptable__c = VIConstant.EC_A_PRENDRE,                                                                                                                                                      
                                                                 affaire__c=fac.affaire__c,
                                                                 affaire_de_rattachement__c=fac.affaire__c,                                                                                     
                                                                 libelle__c=VIConstant.EC_CA_SUR_AFFAIRE_EN_SAV,                                                                                 
                                                                 centre__c='800',
                                                                 ligne_affaire_mensuelle__c=MapLam.get(fac.affaire__c),
                                                                 type_ligne_comptable__c='FSA',          
                                                                 sens__c = 'C',
                                                                 montant__c=fac.montant_ht__c,
                                                                 type_enregistrement__c=MapCompteGeneral.get(fac.affaire__r.Produit_SousDomaine__r.Compte__c+localisation).type_enregistrement__c  );
                    ListInsertEcriture.add(ecFin2);            
            fac.Facture_SAV_comptabilisee__c=true;
        }

        list<VIligne_comptable__c>ListInsertEcriture1 = new list<VIligne_comptable__c>();        
        for(VIligne_comptable__c lc:ListInsertEcriture) {
            if(lc.montant__c<0) {
                lc.montant__c = lc.montant__c *(-1);
                if(lc.sens__c=='C') {
                    lc.sens__c='D';
                } else {
                    lc.sens__c='C';        
                }
            } 
            if (lc.montant__c>0) {
                ListInsertEcriture1.add(lc);
            }
        }

        if(!Test.isRunningTest())
            insert ListInsertEcriture1;

        
        update scope ; 
        
    }   

    global void finish(Database.BatchableContext BC) {
        
        IDLog=VIUtils.LogWrite('VIBatchGenerateFactSAV','1 Normal',IDLog,'End '+num_record);


    }
    

    global void execute(SchedulableContext scon) {
        Database.executeBatch(new VIBatchGenerateFactSAV(AffaireAGenerer, Entite_bw),VIBatchGenerateFactSAV.NBR_LOT);

    }

    public static final integer NBR_LOT =200;    
    
}