force-app/main/default/objects/VIAffaire__c/VIAffaire__c.object-meta.xml
<CustomObject>
    <label>Affaire</label>
    <nameField>
        <label>Code Affaire</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Affaires</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VIAffaire__c/fields/Date_de_fin_de_garantie__c.field-meta.xml
<CustomField>
    <fullName>Date_de_fin_de_garantie__c</fullName>
    <formula>if(!isnull(Date_de_SAV_reelle__c) , 
     ADDMONTHS( Date_de_SAV_reelle__c, Produit_SousDomaine__r.Duree_garantie__c  ),
     null)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Date de fin de garantie</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VIAffaire__c/fields/Date_de_SAV_previsionnelle__c.field-meta.xml
<CustomField>
    <fullName>Date_de_SAV_previsionnelle__c</fullName>
    <label>Date de SAV prévisionnelle</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VIAffaire__c/fields/Date_de_SAV_reelle__c.field-meta.xml
<CustomField>
    <fullName>Date_de_SAV_reelle__c</fullName>
    <label>Date de SAV réelle</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VIAffaire__c/fields/Date_max_mouvement__c.field-meta.xml
<CustomField>
    <fullName>Date_max_mouvement__c</fullName>
    <label>Date max mouvement</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VIAffaire__c/fields/Date_ouverture_affaire__c.field-meta.xml
<CustomField>
    <fullName>Date_ouverture_affaire__c</fullName>
    <label>Date d&apos;ouverture d&apos;affaire</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VIAffaire__c/fields/Entite_BW__c.field-meta.xml
<CustomField>
    <fullName>Entite_BW__c</fullName>
    <label>Entité BW</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>EntiteBW</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/VIAffaire__c/fields/Type_Imputation__c.field-meta.xml
<CustomField>
    <fullName>Type_Imputation__c</fullName>
    <formula>text(Produit_SousDomaine__r.Type_d_imputation__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type Imputation</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/VILigne_d_affaire_mensuelle__c.object-meta.xml
<CustomObject>
    <label>Ligne d&apos;affaire mensuelle</label>
    <nameField>
        <label>Ref de Ligne d&apos;affaire mensuelle</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lignes d&apos;affaire mensuelles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/Affaire__c.field-meta.xml
<CustomField>
    <fullName>Affaire__c</fullName>
    <label>Affaire</label>
    <referenceTo>VIAffaire__c</referenceTo>
    <relationshipLabel>Lignes d&apos;affaire mensuelles</relationshipLabel>
    <relationshipName>Lignes_d_affaire_mensuelles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/Date_de_fin_de_garantie__c.field-meta.xml
<CustomField>
    <fullName>Date_de_fin_de_garantie__c</fullName>
    <formula>Affaire__r.Date_de_fin_de_garantie__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Date de fin de garantie</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/Date_de_SAV_previsionnelle__c.field-meta.xml
<CustomField>
    <fullName>Date_de_SAV_previsionnelle__c</fullName>
    <formula>Affaire__r.Date_de_SAV_previsionnelle__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Date de SAV prévisionnelle</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/Devis_Heure__c.field-meta.xml
<CustomField>
    <fullName>Devis_Heure__c</fullName>
    <label>Devis - Heure</label>
    <precision>6</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/Devis_MontantI__c.field-meta.xml
<CustomField>
    <fullName>Devis_MontantI__c</fullName>
    <label>Devis - MontantI</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/Dont_comptabiliseC__c.field-meta.xml
<CustomField>
    <fullName>Dont_comptabiliseC__c</fullName>
    <label>Dont comptabiliséC</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/Dont_comptabiliseC_E__c.field-meta.xml
<CustomField>
    <fullName>Dont_comptabiliseC_E__c</fullName>
    <label>Dont comptabiliséC	€</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/Dont_comptabiliseD__c.field-meta.xml
<CustomField>
    <fullName>Dont_comptabiliseD__c</fullName>
    <label>Dont comptabiliséD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/Dont_comptabiliseI__c.field-meta.xml
<CustomField>
    <fullName>Dont_comptabiliseI__c</fullName>
    <label>Dont comptabiliséI</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/Dont_comptabiliseI_E__c.field-meta.xml
<CustomField>
    <fullName>Dont_comptabiliseI_E__c</fullName>
    <label>Dont comptabiliséI €</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/Ecart_C_A_F_MontantC__c.field-meta.xml
<CustomField>
    <fullName>Ecart_C_A_F_MontantC__c</fullName>
    <label>Ecart C.A.F - MontantC</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/Ecart_C_A_F_MontantC_E__c.field-meta.xml
<CustomField>
    <fullName>Ecart_C_A_F_MontantC_E__c</fullName>
    <label>Ecart C.A.F - MontantC €</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/Ecart_C_A_F_MontantD_E__c.field-meta.xml
<CustomField>
    <fullName>Ecart_C_A_F_MontantD_E__c</fullName>
    <label>Ecart C.A.F - MontantD €</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/Ecart_C_A_F_MontantI__c.field-meta.xml
<CustomField>
    <fullName>Ecart_C_A_F_MontantI__c</fullName>
    <label>Ecart C.A.F - MontantI</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/Ecart_C_A_F_MontantI_E__c.field-meta.xml
<CustomField>
    <fullName>Ecart_C_A_F_MontantI_E__c</fullName>
    <label>Ecart C.A.F - MontantI €</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/EMM__c.field-meta.xml
<CustomField>
    <fullName>EMM__c</fullName>
    <label>EMM</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/Engage_brut_arrete_Heure__c.field-meta.xml
<CustomField>
    <fullName>Engage_brut_arrete_Heure__c</fullName>
    <label>Engagé brut à l&apos;arrêté - Heure</label>
    <precision>8</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/Engage_brut_arrete_MontantC__c.field-meta.xml
<CustomField>
    <fullName>Engage_brut_arrete_MontantC__c</fullName>
    <label>Engagé brut à l&apos;arrêté - MontantC</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/Engage_brut_arrete_MontantC_E__c.field-meta.xml
<CustomField>
    <fullName>Engage_brut_arrete_MontantC_E__c</fullName>
    <label>Engagé brut à l&apos;arrêté - MontantC €</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/Engage_brut_arrete_MontantD__c.field-meta.xml
<CustomField>
    <fullName>Engage_brut_arrete_MontantD__c</fullName>
    <label>Engagé brut à l&apos;arrêté - MontantD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/Engage_brut_arrete_MontantD_E__c.field-meta.xml
<CustomField>
    <fullName>Engage_brut_arrete_MontantD_E__c</fullName>
    <label>Engagé brut à l&apos;arrêté - MontantD €</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/Entite_BW__c.field-meta.xml
<CustomField>
    <fullName>Entite_BW__c</fullName>
    <formula>text(Affaire__r.Entite_BW__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Entité BW</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/Garantie_dotation__c.field-meta.xml
<CustomField>
    <fullName>Garantie_dotation__c</fullName>
    <label>Garantie - Dotation</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/Garantie_dotation_E__c.field-meta.xml
<CustomField>
    <fullName>Garantie_dotation_E__c</fullName>
    <label>Garantie - Dotation €</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/Garantie_reprise__c.field-meta.xml
<CustomField>
    <fullName>Garantie_reprise__c</fullName>
    <label>Garantie - Reprises cumulées</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/Garantie_reprise_E__c.field-meta.xml
<CustomField>
    <fullName>Garantie_reprise_E__c</fullName>
    <label>Garantie - Reprises cumulées €</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/Periode_comptable__c.field-meta.xml
<CustomField>
    <fullName>Periode_comptable__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Période comptable</label>
    <referenceTo>VIPeriode__c</referenceTo>
    <relationshipLabel>Lignes d&apos;affaire mensuelles</relationshipLabel>
    <relationshipName>Lignes_d_affaire_mensuelles</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/PV_Encaisse__c.field-meta.xml
<CustomField>
    <fullName>PV_Encaisse__c</fullName>
    <label>PV Encaissé</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/PV_Encaisse_HT__c.field-meta.xml
<CustomField>
    <fullName>PV_Encaisse_HT__c</fullName>
    <label>PV Encaissé HT</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/PV_Encaisse_HTE__c.field-meta.xml
<CustomField>
    <fullName>PV_Encaisse_HTE__c</fullName>
    <label>PV Encaissé HT €</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/PV_EncaisseE__c.field-meta.xml
<CustomField>
    <fullName>PV_EncaisseE__c</fullName>
    <label>PV Encaissé €</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/PV_Facture__c.field-meta.xml
<CustomField>
    <fullName>PV_Facture__c</fullName>
    <label>PV Facturé</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/PV_FactureE__c.field-meta.xml
<CustomField>
    <fullName>PV_FactureE__c</fullName>
    <label>PV Facturé €</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/PV_Total__c.field-meta.xml
<CustomField>
    <fullName>PV_Total__c</fullName>
    <label>PV Devis</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/PV_TotalE__c.field-meta.xml
<CustomField>
    <fullName>PV_TotalE__c</fullName>
    <label>PV Devis €</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VIPeriode__c/VIPeriode__c.object-meta.xml
<CustomObject>
    <label>Période comptable</label>
    <nameField>
        <label>Nom de Période</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Périodes comptables</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VIPeriode__c/fields/Date_de_debut__c.field-meta.xml
<CustomField>
    <fullName>Date_de_debut__c</fullName>
    <label>Date de début</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VIPeriode__c/fields/Date_de_fin__c.field-meta.xml
<CustomField>
    <fullName>Date_de_fin__c</fullName>
    <label>Date de fin</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VIPeriode__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Periode_comptable_statut</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/VIBatchRegenerateLAM.cls
/*
 Database.executeBatch(new VIBatchRegenerateLAM('',false), VIBatchRegenerateLAM.nbr_lot());
*/
global class VIBatchRegenerateLAM implements Schedulable,Database.Batchable<sObject>,Database.Stateful{
    global Map<String,VIPeriode__c> MapEntite_bwPeriode = new  Map<String,VIPeriode__c>();  
    global Date  StartExercise ; 
    
    private string AffaireAGenerer; 
    private boolean Enchaine ;
    
     public VIBatchRegenerateLAM(String Param1,Boolean Param2 ) {
        AffaireAGenerer = Param1;        
        Enchaine = Param2;                
    }


    global Database.QueryLocator start(Database.BatchableContext BC){

        system.debug('debut VIBatchRegenerateLAM ');
        for(VIPeriode__c per : [SELECT ID,name, entite_bw__c, statut__c, date_de_debut__c, date_de_fin__c 
                                  FROM VIPeriode__c
                                 WHERE entite_bw__c='1'  ]) {
             MapEntite_bwPeriode.put(per.name,per);
             if(per.statut__c==VIConstant.PERIODE_OUVERTE)  {
                StartExercise=date.newinstance(per.date_de_debut__c.year(),1,1);       
             }
        }

        string query ='select id, name, Date_ouverture_affaire__c, ';
        query = query+'       Date_de_SAV_previsionnelle__c , Date_de_SAV_reelle__c , ';
        query = query+'       Date_de_fin_de_garantie__c ,date_de_livraison__c,date_max_mouvement__c,type_imputation__c ';
        query = query+'  FROM Viaffaire__c ';
        query = query+' WHERE (name like \''+AffaireAGenerer+'%\' ) ';
        query = query+'  order by Name desc ';
                                    
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<Viaffaire__c > scope){
        
        Map<string,VILigne_d_affaire_mensuelle__c >MapLam = new Map<string,VILigne_d_affaire_mensuelle__c >();
        for(VILigne_d_affaire_mensuelle__c LAM : [select id, name
                                                    FROM VILigne_d_affaire_mensuelle__c
                                                   WHERE affaire__c in : scope]) {
            MapLam.put(LAM.name, LAM) ;
        }
        
        list<VILigne_d_affaire_mensuelle__c>listInsertLam = new list<VILigne_d_affaire_mensuelle__c>();
        list<VILigne_d_affaire_mensuelle__c>listupdateLam = new list<VILigne_d_affaire_mensuelle__c>();
        
        for(ViAffaire__c Aff : scope){ 
            
            
            date date_minimum= aff.Date_ouverture_affaire__c;
            date date_maximum= aff.Date_de_SAV_previsionnelle__c;
            if(aff.name.left(1)=='9') {
                date_minimum=StartExercise;
            } else if (aff.name.left(1)=='L' || aff.name.left(1)=='P' || aff.name.left(1)=='R' || aff.name.left(1)=='S' || aff.name.left(1)=='V') {
                date_minimum=date_minimum.addmonths(-2);
            }
                                  
            if(aff.Date_de_SAV_reelle__c>date_maximum)
                date_maximum=aff.Date_de_SAV_reelle__c;
                                  
            if(aff.Date_de_SAV_reelle__c==null)
                date_maximum=system.today();
                                  
            if(aff.Date_de_SAV_reelle__c>date_maximum)
                date_maximum=aff.Date_de_SAV_reelle__c;
                                  
            if(aff.Date_de_fin_de_garantie__c>date_maximum)
                date_maximum=aff.Date_de_fin_de_garantie__c;
                                  
            if(aff.Date_max_mouvement__c>date_maximum)
                date_maximum=aff.Date_max_mouvement__c;
                                  
            if(aff.date_de_livraison__c>date_maximum)
                date_maximum=aff.date_de_livraison__c;

            if(date_minimum<=date.newinstance(2018,01,01) ) {
                date_minimum=date.newinstance(2018,01,01);
            }
                                    
            if(date_maximum<date_minimum ) {
                date_maximum=date_minimum;
            }
            
            
            date d=date_minimum ; 

            system.debug('Affaire '+aff.name+' '+d+' '+date_maximum);
            string precedent ='';            
                
            while(d<=date_maximum) {
                string p = string.valueof(d.year())+('00'+string.valueof(d.month())).right(2)+'BW FRA';
                string p1 = aff.name+'-'+p; 
                if(!MapLam.containskey(p1)) {
                    VILigne_d_affaire_mensuelle__c lam = new VILigne_d_affaire_mensuelle__c();
                    lam.affaire__c = Aff.id ; 
                    lam.periode_comptable__c = MapEntite_BWPeriode.get(p).id;
                    lam.name = p1 ; 
                    lam.Garantie_dotation__c=0;
                    lam.Garantie_dotation_E__c=0;
                    lam.Garantie_reprise__c=0;
                    lam.Garantie_reprise_E__c=0;
                    lam.devis_heure__c=0;    
                    lam.devis_MontantD__c=0;
                    lam.devis_MontantI__c=0;               
                    lam.devis_MontantC__c=0;                               
                    lam.devis_MontantD_E__c=0;
                    lam.devis_MontantI_E__c=0;               
                    lam.devis_MontantC_E__c=0;                               
                    lam.Engage_brut_arrete_Heure__c =0;
                    lam.Engage_brut_arrete_MontantD__c =0;
                    lam.Engage_brut_arrete_MontantI__c =0;
                    lam.Engage_brut_arrete_MontantC__c =0;        
                    lam.Engage_brut_arrete_MontantD_E__c =0;
                    lam.Engage_brut_arrete_MontantI_E__c =0;
                    lam.Engage_brut_arrete_MontantC_E__c =0;  
                    lam.Dont_comptabiliseD__c =0;
                    lam.Dont_comptabiliseI__c =0;
                    lam.Dont_comptabiliseC__c =0;        
                    lam.Dont_comptabiliseD_E__c =0;
                    lam.Dont_comptabiliseI_E__c =0;
                    lam.Dont_comptabiliseC_E__c =0;   
                    lam.Ecart_C_A_F_Heure__c =0;
                    lam.Ecart_C_A_F_MontantD__c =0;        
                    lam.Ecart_C_A_F_MontantI__c =0;        
                    lam.Ecart_C_A_F_MontantC__c =0;                
                    lam.Ecart_C_A_F_MontantD_E__c =0;        
                    lam.Ecart_C_A_F_MontantI_E__c =0;        
                    lam.Ecart_C_A_F_MontantC_E__c =0;  

                    lam.PV_Total__c=0;
                    lam.PV_TotalE__c=0;                
                
                    lam.PV_Facture__c=0;
                    lam.PV_FactureE__c=0;                
                    lam.PV_Encaisse__c=0;                                
                    lam.PV_EncaisseE__c=0;                                                
                    lam.PV_Encaisse_HT__c=0;                                
                    lam.PV_Encaisse_HTE__c=0;                                                
                
                    lam.EMM__c=0;
                    lam.EMM_E__c=0;
                    lam.AMP__c=0;
                    lam.AMP_E__c=0;
                    lam.FOL__c=0;
                    lam.FOL_E__c=0;
                
                    lam.garantie_reprise__c=0;
                    lam.garantie_reprise_E__c=0;                
                    lam.garantie_dotation__c=0;                
                    lam.garantie_dotation_E__c=0;                
                    lam.garantie_depense__c=0;                
                    lam.garantie_depense_E__c=0;                                
 
                    MapLam.put(p1,lam);
                    listInsertLam.add(lam);
                } else {
                    VILigne_d_affaire_mensuelle__c lam =MapLam.get(p1) ; 
                    if(precedent!='') {
                        lam.Ligne_d_affaire_mensuelle_precedente__c = precedent;
                        listupdateLam.add(lam);
                    }
                    precedent=lam.id;
                }
                d=d.addmonths(1);
                d=date.newinstance(d.year(),d.month(),01);
            }
        }
        insert listInsertLam;
        update listupdateLam;
        
    }

    global void finish(Database.BatchableContext BC) {
        if(enchaine) {
            VIBatchRegenerateTotal v = new VIBatchRegenerateTotal(AffaireAGenerer,Enchaine,false);
            v.execute(null);
        }
    }

    global void execute(SchedulableContext scon) {
        Database.executeBatch(new VIBatchRegenerateLAM(AffaireAGenerer,Enchaine),VIBatchRegenerateLAM.NBR_LOT());
    }
    
    public static  integer NBR_LOT () {
         VIParametres__c param = VIParametres__c.getInstance(UserInfo.getUserId()); 
         integer i ; 
         if(param.Sans_Calcul_de_PRI__c) {
             i=200 ; 
         } else {
             i=200;    
         }
         return i;
    }


    
}