force-app/main/default/objects/VIAffaire__c/VIAffaire__c.object-meta.xml
<CustomObject>
    <label>Affaire</label>
    <nameField>
        <label>Code Affaire</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Affaires</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VIAffaire__c/fields/Date_de_SAV_reelle__c.field-meta.xml
<CustomField>
    <fullName>Date_de_SAV_reelle__c</fullName>
    <label>Date de SAV réelle</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VIAffaire__c/fields/Entite_BW__c.field-meta.xml
<CustomField>
    <fullName>Entite_BW__c</fullName>
    <label>Entité BW</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>EntiteBW</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/VICentre_Section__c/VICentre_Section__c.object-meta.xml
<CustomObject>
    <label>Centre / Section</label>
    <nameField>
        <label>Nom de Centre / Section</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Centres / Sections</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VILigne_affaire__c/VILigne_affaire__c.object-meta.xml
<CustomObject>
    <label>Ligne d&apos;affaire</label>
    <nameField>
        <displayFormat>L{000000000}</displayFormat>
        <label>Ref de Ligne d&apos;affaire</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lignes d&apos;affaire</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VILigne_affaire__c/fields/Ecart_C_A_F_MontantD__c.field-meta.xml
<CustomField>
    <fullName>Ecart_C_A_F_MontantD__c</fullName>
    <label>Ecart C.A.F - MontantD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VILigne_affaire__c/fields/Entite_BW__c.field-meta.xml
<CustomField>
    <fullName>Entite_BW__c</fullName>
    <formula>Text( Ligne_d_affaire_mensuelle__r.Affaire__r.Entite_BW__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Entité BW</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VILigne_affaire__c/fields/Type_depense__c.field-meta.xml
<CustomField>
    <fullName>Type_depense__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Type de dépense</label>
    <referenceTo>VIType_de_depense__c</referenceTo>
    <relationshipLabel>Lignes d&apos;affaire</relationshipLabel>
    <relationshipName>Lignes_d_affaire</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VIPeriode__c/VIPeriode__c.object-meta.xml
<CustomObject>
    <label>Période comptable</label>
    <nameField>
        <label>Nom de Période</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Périodes comptables</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VIPeriode__c/fields/Date_de_debut__c.field-meta.xml
<CustomField>
    <fullName>Date_de_debut__c</fullName>
    <label>Date de début</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VIPeriode__c/fields/Date_de_fin__c.field-meta.xml
<CustomField>
    <fullName>Date_de_fin__c</fullName>
    <label>Date de fin</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VIPeriode__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Periode_comptable_statut</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/VIType_de_depense__c/VIType_de_depense__c.object-meta.xml
<CustomObject>
    <label>Type de dépense</label>
    <nameField>
        <label>Nom de Type de dépense</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Types de dépenses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/VIAffaireListUpdateController_test.cls
@isTest
public class VIAffaireListUpdateController_test {


    static testmethod void VIAffaireListUpdateController_test() {
    
        VIInsertDataTest.VIInsertData_EUR_Affaire();
        VIInsertDataTest.VIInsertData_Achat();        

        VIAffaire__c aff = [select id,Date_de_sav_reelle__c from VIAffaire__c LIMIT 1];
        VItype_de_depense__c tdMO  = new VItype_de_depense__c();
        VItype_de_depense__c tdGAR = new VItype_de_depense__c();
        VItype_de_depense__c tdEMM = new VItype_de_depense__c();
        VItype_de_depense__c tdAMP = new VItype_de_depense__c();
        VItype_de_depense__c tdFOL = new VItype_de_depense__c();     
        VICentre_section__c CS801= new VICentre_section__c();
    
        Map<string,VIperiode__c>MapEntite_bwPeriode = new Map<string,VIperiode__c>();
        

        for(VIType_de_depense__c td : [SELECT ID,name from VIType_de_depense__c where name like 'MO %' or name like 'GAR%' or name like 'EMM%' or name like 'AMP%' or name like 'FOL%']) {
            if(td.name.startswith('MO '))
                 tdMO=td ; 

            if(td.name.startswith('GAR'))
                 tdGAR=td ; 

            if(td.name.startswith('EMM'))
                 tdEMM=td ; 

            if(td.name.startswith('AMP'))
                 tdAMP=td ; 

            if(td.name.startswith('FOL'))
                 tdFOL=td ; 
        }
        CS801 = [select id from VICentre_section__c where name like '801%' ];        

        VIPeriode__c periode_ouverte  ;              
        for(VIPeriode__c per : [SELECT ID,name, entite_bw__c, date_de_debut__c, date_de_fin__c ,statut__c
                                  FROM VIPeriode__c
                                 WHERE entite_bw__c='1' 
                              ORDER BY date_de_debut__c]) {
             MapEntite_bwPeriode.put(per.name,per);
             if(per.statut__c==VIConstant.PERIODE_OUVERTE)  {
                 periode_ouverte=per; 
             }                                  
         }


        
        
        
        VIUtils.recalc(aff.id,true, true, tdMO,tdGAR, tdEMM, tdAMP, tdFOl, cs801, MapEntite_bwPeriode,periode_ouverte.date_de_debut__c );
        

        VILigne_affaire__c la=[SELECT type_depense__c, Ecart_C_A_F_MontantD__c  FROM VILigne_affaire__c limit 1];
        la.Ecart_C_A_F_MontantD__c =1;
        update la;
        la.type_depense__c=tdMo.id;
        la.Ecart_C_A_F_MontantD__c =2;
        update la;
       
        ApexPages.StandardController sc = new ApexPages.StandardController(aff);
        VIAffaireListUpdateController testaff = new VIAffaireListUpdateController (sc);  
        
        PageReference pageRef = Page.VIAffaireListUpdate; 
        pageRef.getParameters().put('id',aff.Id);

        testaff.testcoverage();

        
        VISchedBatchDeleteLA v = new VISchedBatchDeleteLA('',false);
        v.execute(null);

        
        
    }

   
    
}