force-app/main/default/objects/VIAffaire__c/VIAffaire__c.object-meta.xml
<CustomObject>
    <label>Affaire</label>
    <nameField>
        <label>Code Affaire</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Affaires</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VIAffaire__c/fields/Date_ouverture_affaire__c.field-meta.xml
<CustomField>
    <fullName>Date_ouverture_affaire__c</fullName>
    <label>Date d&apos;ouverture d&apos;affaire</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VIPeriode__c/VIPeriode__c.object-meta.xml
<CustomObject>
    <label>Période comptable</label>
    <nameField>
        <label>Nom de Période</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Périodes comptables</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VIPeriode__c/fields/Date_de_debut__c.field-meta.xml
<CustomField>
    <fullName>Date_de_debut__c</fullName>
    <label>Date de début</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VIPeriode__c/fields/Date_de_fin__c.field-meta.xml
<CustomField>
    <fullName>Date_de_fin__c</fullName>
    <label>Date de fin</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VIPeriode__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Periode_comptable_statut</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/VIBatchCalcLAMExerPrec_test.cls
@isTest
public class VIBatchCalcLAMExerPrec_test {

    static testmethod void VIBatchCalcLAMExerPrec_test() {
    
        VIInsertDataTest.VIInsertData_GBP_Avenant();
        List<VIperiode__c>ListPer =  [SELECT id, name, date_de_debut__c, date_de_fin__c, statut__c
                                      FROM VIPeriode__c];
        for(VIperiode__c per: ListPer) {
            per.statut__c=viConstant.PERIODE_OUVERTE ; 
        }
        update listPer; 
        
        VIAffaire__c aff =[select id,Date_ouverture_affaire__c from VIAffaire__c];
        aff.Date_ouverture_affaire__c=system.today().addyears(-1);
        update aff; 
        

        VIBatchCalcLAMExerPrec v = new VIBatchCalcLAMExerPrec();
        database.executebatch(v,10);  
        
    }
}