force-app/main/default/objects/VIAffaire__c/VIAffaire__c.object-meta.xml
<CustomObject>
    <label>Affaire</label>
    <nameField>
        <label>Code Affaire</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Affaires</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VIAffaire__c/fields/Date_de_SAV_reelle__c.field-meta.xml
<CustomField>
    <fullName>Date_de_SAV_reelle__c</fullName>
    <label>Date de SAV réelle</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VIAffaire__c/fields/Mode_de_calcul_de_l_avancement__c.field-meta.xml
<CustomField>
    <fullName>Mode_de_calcul_de_l_avancement__c</fullName>
    <formula>Case(text( Produit_SousDomaine__r.Mode_de_calcul_de_l_avancement__c ),
   &apos;1&apos;, &apos;1- Avancement par les coûts&apos;, 
   &apos;2&apos;, &apos;2- En fonction de la facturation client&apos;, 
   &apos;3&apos;, &apos;3- Au prorata temporis&apos;,
   &apos;9&apos;, &apos;9-Pas de calcul à l avancement&apos;,
   &apos;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mode de calcul de l&apos;avancement</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VICompte_general__c/VICompte_general__c.object-meta.xml
<CustomObject>
    <label>Compte général</label>
    <nameField>
        <label>Nom de Compte général</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Comptes généraux</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VILigne_affaire__c/VILigne_affaire__c.object-meta.xml
<CustomObject>
    <label>Ligne d&apos;affaire</label>
    <nameField>
        <displayFormat>L{000000000}</displayFormat>
        <label>Ref de Ligne d&apos;affaire</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lignes d&apos;affaire</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VILigne_affaire__c/fields/Ecart_C_A_F_MontantD__c.field-meta.xml
<CustomField>
    <fullName>Ecart_C_A_F_MontantD__c</fullName>
    <label>Ecart C.A.F - MontantD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VILigne_affaire__c/fields/Engage_brut_arrete_MontantD__c.field-meta.xml
<CustomField>
    <fullName>Engage_brut_arrete_MontantD__c</fullName>
    <label>Engagé brut à l&apos;arrêté - MontantD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VIPeriode__c/VIPeriode__c.object-meta.xml
<CustomObject>
    <label>Période comptable</label>
    <nameField>
        <label>Nom de Période</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Périodes comptables</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VIPeriode__c/fields/Date_de_fin__c.field-meta.xml
<CustomField>
    <fullName>Date_de_fin__c</fullName>
    <label>Date de fin</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VIPeriode__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Periode_comptable_statut</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/VISousDomaine__c/VISousDomaine__c.object-meta.xml
<CustomObject>
    <label>Produit - SousDomaine</label>
    <nameField>
        <label>SousDomaine</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Produits - SousDomaines</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VISousDomaine__c/fields/Mode_de_calcul_de_l_avancement__c.field-meta.xml
<CustomField>
    <fullName>Mode_de_calcul_de_l_avancement__c</fullName>
    <label>Mode de calcul de l&apos;avancement</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Mode_de_calcul_de_l_avancement</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/VIBatchGenerate_test.cls
@isTest
public class VIBatchGenerate_test {

    static testmethod void ViBatchGenerate_test() {
    
        VIInsertDataTest.VIInsertData_EUR_Affaire();
        VIInsertDataTest.VIInsertData_Achat();
        //VIInsertDataTest.VIInsertData_Pointage();
        VIInsertDataTest.VIInsertData_Facture();
        
        VISousDomaine__c sd = [select  Mode_de_calcul_de_l_avancement__c from VISousDomaine__c];
        sd.Mode_de_calcul_de_l_avancement__c='2';
        update sd ; 

        
        list<VIperiode__c>ListPeriode=[SELECT id,date_de_fin__c 
                                         FROM VIperiode__c 
                                       WHERE Statut__c =:VIConstant.PERIODE_OUVERTE
                                     ORDER BY NAME LIMIT 1];
        
        VICompte_general__c cc = new  VICompte_general__c  (name='7');
        insert cc ; 

        VIBatchGenerate b1 = new VIBatchGenerate('','1'); 
        database.executebatch(b1,10);  
                
        VIAffaire__c aff = [select id,Date_de_SAV_reelle__c from VIAffaire__c ] ;
        aff.Date_de_SAV_reelle__c = ListPeriode[0].date_de_fin__c;
        update aff; 

        VIBatchGenerate b2 = new VIBatchGenerate('','1'); 
        database.executebatch(b2,10);  
        
        b2.code_coverage();
        
/*      henri
        list<VILigne_Affaire__c>ListLa= [SELECT id, Cout_terminaison_MontantD__c, Engage_brut_arrete_MontantD__c,Ecart_C_A_F_MontantD__c   
                                           FROM VILigne_Affaire__c ] ;

        ListLa[0].Ecart_C_A_F_MontantD__c=1;
        update ListLa ; 
        System.assertEquals(2, listLa.size());
        System.assertEquals(101, listLa[0].Engage_brut_arrete_MontantD__c);
*/
        
    }
}