force-app/main/default/objects/VIAffaire__c/VIAffaire__c.object-meta.xml
<CustomObject>
    <label>Affaire</label>
    <nameField>
        <label>Code Affaire</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Affaires</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VICentre_Section__c/VICentre_Section__c.object-meta.xml
<CustomObject>
    <label>Centre / Section</label>
    <nameField>
        <label>Nom de Centre / Section</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Centres / Sections</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VILigne_affaire__c/VILigne_affaire__c.object-meta.xml
<CustomObject>
    <label>Ligne d&apos;affaire</label>
    <nameField>
        <displayFormat>L{000000000}</displayFormat>
        <label>Ref de Ligne d&apos;affaire</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lignes d&apos;affaire</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VILigne_affaire__c/fields/Centre_Section__c.field-meta.xml
<CustomField>
    <fullName>Centre_Section__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Centre / Section</label>
    <referenceTo>VICentre_Section__c</referenceTo>
    <relationshipLabel>Lignes d&apos;affaire</relationshipLabel>
    <relationshipName>Lignes_d_affaire</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VILigne_affaire__c/fields/Ligne_d_affaire_mensuelle__c.field-meta.xml
<CustomField>
    <fullName>Ligne_d_affaire_mensuelle__c</fullName>
    <label>Ligne d&apos;affaire mensuelle</label>
    <referenceTo>VILigne_d_affaire_mensuelle__c</referenceTo>
    <relationshipLabel>Lignes d&apos;affaire</relationshipLabel>
    <relationshipName>Lignes_d_affaire</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VILigne_affaire__c/fields/Type_de_ligne_d_affaire__c.field-meta.xml
<CustomField>
    <fullName>Type_de_ligne_d_affaire__c</fullName>
    <label>Type de ligne d&apos;affaire</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type_de_ligne_d_affaire</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/VILigne_affaire__c/fields/Type_depense__c.field-meta.xml
<CustomField>
    <fullName>Type_depense__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Type de dépense</label>
    <referenceTo>VIType_de_depense__c</referenceTo>
    <relationshipLabel>Lignes d&apos;affaire</relationshipLabel>
    <relationshipName>Lignes_d_affaire</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/VILigne_d_affaire_mensuelle__c.object-meta.xml
<CustomObject>
    <label>Ligne d&apos;affaire mensuelle</label>
    <nameField>
        <label>Ref de Ligne d&apos;affaire mensuelle</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lignes d&apos;affaire mensuelles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VIType_de_depense__c/VIType_de_depense__c.object-meta.xml
<CustomObject>
    <label>Type de dépense</label>
    <nameField>
        <label>Nom de Type de dépense</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Types de dépenses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/VIEtatMensuelController_test.cls
@isTest
private class VIEtatMensuelController_test {

    static testmethod void VIEtatMensuelControllerEUR_test() {
    
        VIInsertDataTest.VIInsertData_EUR_Affaire();
        VIInsertDataTest.VIInsertData_Achat();
        VIAffaire__c aff = [select id from VIAffaire__c LIMIT 1];

        list<id> ListAffid = new list<id>();
        listAffId.add(aff.id);
//        VIUtils.recalcul_LA(listAffId);
               
        String currentuserId = UserInfo.getUserId();
        User currentUserInfo = [select LanguageLocaleKey from User where Id = :UserInfo.getUserId()];
        currentUserInfo.LanguageLocaleKey = 'pt_BR';
        update currentUserInfo;        
        
        ApexPages.StandardController sc = new ApexPages.StandardController(aff);
        VIEtatMensuelController testaff = new VIEtatMensuelController (sc);  
        
        PageReference pageRef = Page.VIEtatMensuel; 
        pageRef.getParameters().put('id',aff.Id);       

        testaff.Chargement();
        
        list<VILigne_d_affaire_mensuelle__c>ListLAM = [select currencyIsoCode from  VILigne_d_affaire_mensuelle__c];
        system.debug('ListLam '+ListLam);
        for(VILigne_d_affaire_mensuelle__c lam : ListLam) {
            lam.currencyIsoCode='EUR';
        }
        update ListLam;

        VIType_de_depense__c depense = [SELECT id, name 
                                              FROM  VIType_de_depense__c limit 1];
        VIcentre_section__c cs=[select id from VIcentre_section__c LIMIT 1 ];
        
        VILigne_affaire__c NewLa = VIUtils.init_la();
        NewLa.Ligne_d_affaire_mensuelle__c = ListLam[0].id;
        NewLa.Type_de_ligne_d_affaire__c = 'I';
        NewLa.Centre_Section__c= cs.id;
        NewLa.Type_depense__c  =  depense.id ; 
        insert NewLa ; 

        
        testaff.currencyType='EUR';
        Test.setCurrentPage(pageRef);
        testaff.saveData();
        testaff.getValeurOptions();
        testaff.getCurrencyOptions();    
        testaff.getLAMOptions();    

        testaff.currencyType='EUR';
        testaff.Valeur='Industriel';
        testaff.ReRead();

        testaff.Valeur='Complet';
        testaff.ReRead();

        testaff.Valeur='Debours';
        testaff.ReRead();

        testaff.SortCentre();
        testaff.SortDepense();        
        testaff.SOQL_verif();        
        testaff.Refresh();        
        
//        testaff.Suivant();                
//        testaff.Precedent();                

    }


    static testmethod void VIEtatMensuelControllerGBP_Test() {
    
        VIInsertDataTest.VIInsertData_GBP_Avenant();
        VIInsertDataTest.VIInsertData_Achat();
        VIAffaire__c aff = [select id from VIAffaire__c LIMIT 1];

        list<id> ListAffid = new list<id>();
        listAffId.add(aff.id);

        ApexPages.StandardController sc = new ApexPages.StandardController(aff);
        VIEtatMensuelController testaff = new VIEtatMensuelController (sc);  
        
        PageReference pageRef = Page.VIEtatMensuel; 
        pageRef.getParameters().put('id',aff.Id);
        testaff.currencyType='GBP';
        Test.setCurrentPage(pageRef);

     //   testaff.Chargement();
        
/*
        testaff.saveData();
        testaff.getValeurOptions();
        testaff.getCurrencyOptions();    
*/       
        testaff.Valeur='Industriel';
        testaff.ReRead();


        testaff.Valeur='Complet';
        testaff.ReRead();
        
        testaff.Valeur='Debours';
        testaff.ReRead();

        testaff.SortCentre();
        testaff.SortDepense();        
        testaff.SOQL_verif();    

        testaff.suivant();
        testaff.precedent();
        testaff.ValSav=true;
        testaff.sav();        
        
    }
    
    
}