force-app/main/default/objects/VIAffaire__c/VIAffaire__c.object-meta.xml
<CustomObject>
    <label>Affaire</label>
    <nameField>
        <label>Code Affaire</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Affaires</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VIAffaire__c/fields/Date_de_SAV_reelle__c.field-meta.xml
<CustomField>
    <fullName>Date_de_SAV_reelle__c</fullName>
    <label>Date de SAV réelle</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VICompte_general__c/VICompte_general__c.object-meta.xml
<CustomObject>
    <label>Compte général</label>
    <nameField>
        <label>Nom de Compte général</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Comptes généraux</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VIFacture__c/VIFacture__c.object-meta.xml
<CustomObject>
    <label>Facture</label>
    <nameField>
        <label>Nom de Facture</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Factures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VIFacture__c/fields/Date_de_SAV_reelle__c.field-meta.xml
<CustomField>
    <fullName>Date_de_SAV_reelle__c</fullName>
    <formula>Affaire__r.Date_de_SAV_reelle__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Date de SAV réelle</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VIFacture__c/fields/Facture_SAV_Comptabilisee__c.field-meta.xml
<CustomField>
    <fullName>Facture_SAV_Comptabilisee__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Indique que la ligne a été envoyée en comptabilité</inlineHelpText>
    <label>Facture SAV Comptabilisée</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VIFacture__c/fields/Facture_SAV_traitee__c.field-meta.xml
<CustomField>
    <fullName>Facture_SAV_traitee__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Facture SAV traitée</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VIFacture__c/fields/Facture_sur_Affaire_SAV__c.field-meta.xml
<CustomField>
    <fullName>Facture_sur_Affaire_SAV__c</fullName>
    <formula>if( Affaire__r.Date_de_SAV_reelle__c &lt;  Date_de_comptabilisation__c  ,true, false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Facture sur Affaire SAV</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VIPeriode__c/VIPeriode__c.object-meta.xml
<CustomObject>
    <label>Période comptable</label>
    <nameField>
        <label>Nom de Période</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Périodes comptables</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VIPeriode__c/fields/Date_de_fin__c.field-meta.xml
<CustomField>
    <fullName>Date_de_fin__c</fullName>
    <label>Date de fin</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VIPeriode__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Periode_comptable_statut</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/VIBatchGenerateFactSAV_test.cls
@isTest
public class VIBatchGenerateFactSAV_test {

    static testmethod void VIBatchGenerateFactSAV_test() {
    
        VIInsertDataTest.VIInsertData_EUR_Affaire();
        VIInsertDataTest.VIInsertData_Achat();
        VIInsertDataTest.VIInsertData_Facture();
        
        
        list<VIperiode__c>ListPeriode=[SELECT id,date_de_fin__c 
                                         FROM VIperiode__c 
                                       WHERE Statut__c =:VIConstant.PERIODE_OUVERTE
                                     ORDER BY NAME LIMIT 1];
        
        VICompte_general__c cc = new  VICompte_general__c  (name='7');
        insert cc ; 
        VICompte_general__c cc1 = new  VICompte_general__c  (name='null000');        
        insert cc1 ; 

                
        VIAffaire__c aff = [select id,Date_de_SAV_reelle__c from VIAffaire__c ] ;
        aff.Date_de_SAV_reelle__c = ListPeriode[0].date_de_fin__c;
        update aff; 

        VIfacture__c fac = [select id,Facture_SAV_traitee__c,Facture_SAV_comptabilisee__c,date__c,Facture_sur_Affaire_SAV__c  from VIfacture__c ] ;
        fac.date__c=aff.Date_de_SAV_reelle__c.adddays(1);
        fac.Facture_SAV_traitee__c = true;
        fac.Facture_SAV_comptabilisee__c =false;
        
        update fac; 
        
        
        
        VIBatchGenerateFactSAV b2 = new VIBatchGenerateFactSAV('','1'); 
        database.executebatch(b2,10);  
        
    }
}