force-app/main/default/objects/VIAffaire__c/VIAffaire__c.object-meta.xml
<CustomObject>
    <label>Affaire</label>
    <nameField>
        <label>Code Affaire</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Affaires</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VIAutorisation_depense__c/VIAutorisation_depense__c.object-meta.xml
<CustomObject>
    <label>Autorisation de dépense</label>
    <nameField>
        <displayFormat>A{0000000}</displayFormat>
        <label>Ref de Autorisation de dépense</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Autorisations de dépense</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VIAutorisation_depense__c/fields/Code_Affaire__c.field-meta.xml
<CustomField>
    <fullName>Code_Affaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Code Affaire</label>
    <referenceTo>VIAffaire__c</referenceTo>
    <relationshipLabel>Autorisations de dépense</relationshipLabel>
    <relationshipName>Autorisations_de_depense</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VIAutorisation_depense__c/fields/Etat_du_mouvement__c.field-meta.xml
<CustomField>
    <fullName>Etat_du_mouvement__c</fullName>
    <label>Etat du mouvement</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Affaire_etat_Mouvement</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/VIAutorisation_depense__c/fields/Sous_chapitre__c.field-meta.xml
<CustomField>
    <fullName>Sous_chapitre__c</fullName>
    <label>Sous chapitre</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sous_chapitre</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/VIAutorisation_depense__c/fields/Statut_autorisation_depense__c.field-meta.xml
<CustomField>
    <fullName>Statut_autorisation_depense__c</fullName>
    <label>Statut autorisation dépense</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Statut_ecriture_comptable</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/VIGenereAutorisationController.cls
public class VIGenereAutorisationController {


    public string IDAffaire {get; set;}
    public VIaffaire__c Affaire {get; set;}
    private ApexPages.StandardController stdCtrl;
       
    public VIGenereAutorisationController(ApexPages.StandardController std) {        
        stdCtrl=std;
        IDaffaire= std.getId();

        system.debug('IDAffaire '+IDAffaire);
        
    }       

    public void  SupprimerTout() {
/*        
        list<VIAutorisation_depense__c>ListAut= [SELECT id 
                                                   FROM VIAutorisation_depense__c 
                                                  WHERE Code_Affaire__c=:IDAffaire ];
        delete ListAut;
*/        

    }

    public void  CreerOuvert() {   
        list<VIAutorisation_depense__c>ListAut= [SELECT id, Code_Affaire__c , sous_Chapitre__c,
                                                        Date_du_mouvement__c ,Etat_du_mouvement__c , Statut_autorisation_depense__c 
                                                   FROM VIAutorisation_depense__c 
                                                  WHERE Code_Affaire__c=:IDAffaire
                                                    AND Etat_du_mouvement__c ='Open'];
        list<VIAutorisation_depense__c>ListNewAut = new list<VIAutorisation_depense__c>();
        for(VIAutorisation_depense__c aut:ListAut) {
            VIAutorisation_depense__c NewAut = new VIAutorisation_depense__c(
                Code_Affaire__c = idaffaire,
                sous_Chapitre__c = aut.sous_chapitre__c,
                Date_du_mouvement__c = system.today(),
                Etat_du_mouvement__c ='Open', 
                Statut_autorisation_depense__c='20') ;
           ListNewAut.add(NewAut);
        }
        insert ListNewAut;
    }

    public void  CreerFerme() { 
        list<VIAutorisation_depense__c>ListAut= [SELECT id, Code_Affaire__c , sous_Chapitre__c,
                                                        Date_du_mouvement__c ,Etat_du_mouvement__c , Statut_autorisation_depense__c 
                                                   FROM VIAutorisation_depense__c 
                                                  WHERE Code_Affaire__c=:IDAffaire
                                                    AND Etat_du_mouvement__c ='Open'];
        list<VIAutorisation_depense__c>ListNewAut = new list<VIAutorisation_depense__c>();
        for(VIAutorisation_depense__c aut:ListAut) {
            VIAutorisation_depense__c NewAut = new VIAutorisation_depense__c(
                Code_Affaire__c = idaffaire,
                sous_Chapitre__c = aut.sous_chapitre__c,
                Date_du_mouvement__c = system.today(),
                Etat_du_mouvement__c ='Close', 
                Statut_autorisation_depense__c='20') ;
           ListNewAut.add(NewAut);
        }
        insert ListNewAut;
       
        
    }
    
}