force-app/main/default/objects/VIAffaire__c/VIAffaire__c.object-meta.xml
<CustomObject>
    <label>Affaire</label>
    <nameField>
        <label>Code Affaire</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Affaires</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VIAffaire__c/fields/Affaire_reouverte__c.field-meta.xml
<CustomField>
    <fullName>Affaire_reouverte__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Affaire ré-ouverte pour la dépense ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VIAffaire__c/fields/Date_de_SAV_reelle__c.field-meta.xml
<CustomField>
    <fullName>Date_de_SAV_reelle__c</fullName>
    <label>Date de SAV réelle</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VIPeriode__c/VIPeriode__c.object-meta.xml
<CustomObject>
    <label>Période comptable</label>
    <nameField>
        <label>Nom de Période</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Périodes comptables</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VIPeriode__c/fields/Date_de_fin__c.field-meta.xml
<CustomField>
    <fullName>Date_de_fin__c</fullName>
    <label>Date de fin</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VIPeriode__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Periode_comptable_statut</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/VIBatchGenereAutorisation_test.cls
@isTest
public class VIBatchGenereAutorisation_test {

    static testmethod void VIBatchGenereAutorisation_CAS1_test() {
    
        VIInsertDataTest.VIInsertData_GBP_Avenant();

        list<VIperiode__c>ListPeriode=[SELECT id,date_de_fin__c 
                                         FROM VIperiode__c 
                                       WHERE Statut__c =:VIConstant.PERIODE_OUVERTE
                                     ORDER BY NAME LIMIT 1];

        VIAffaire__c aff = [SELECT Date_de_SAV_reelle__c from VIAffaire__c];
        aff.Date_de_SAV_reelle__c = ListPeriode[0].date_de_fin__c;
        update aff ; 

        
        VIBatchGenereAutorisation v = new VIBatchGenereAutorisation(true);
        v.execute(null);

        aff.Affaire_reouverte__c=true;
        update aff; 
        Database.executeBatch(new VIBatchGenereAutorisation(true),VIBatchGenereAutorisation.NBR_LOT);
        
        v.code_coverage();
        
    }
  
    
}