force-app/main/default/objects/VIAffaire__c/VIAffaire__c.object-meta.xml
<CustomObject>
    <label>Affaire</label>
    <nameField>
        <label>Code Affaire</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Affaires</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VIAffaire__c/fields/Entite_BW__c.field-meta.xml
<CustomField>
    <fullName>Entite_BW__c</fullName>
    <label>Entité BW</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>EntiteBW</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/VILigne_comptable__c/VILigne_comptable__c.object-meta.xml
<CustomObject>
    <label>Ligne comptable</label>
    <nameField>
        <displayFormat>L{000000000}</displayFormat>
        <label>Ref de la ligne comptable</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lignes comptables</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VILigne_comptable__c/fields/Affaire__c.field-meta.xml
<CustomField>
    <fullName>Affaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Affaire</label>
    <referenceTo>VIAffaire__c</referenceTo>
    <relationshipLabel>Lignes comptables (Affaire)</relationshipLabel>
    <relationshipName>Ecritures_comptables</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VILigne_comptable__c/fields/Statut_ecriture_comptable__c.field-meta.xml
<CustomField>
    <fullName>Statut_ecriture_comptable__c</fullName>
    <defaultValue>&apos;10&apos;</defaultValue>
    <label>Statut écriture comptable</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Statut_ecriture_comptable</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/VIBatchEnvoiEcriture.cls
//
//   This batch send the ecriture
//  
//  
// 
global class VIBatchEnvoiEcriture implements Database.Batchable<sObject>, Database.Stateful {

    private String  EcrituresAEnvoyer;
    private String  entite_bw;    
    Public Integer num_record = 0; 
    Global String IDLog ='';

    public VIBatchEnvoiEcriture(String Param1,String Param2 ) {
        EcrituresAEnvoyer = Param1;        
        entite_bw = Param2;                
    }

    global Database.QueryLocator start(Database.BatchableContext BC) {
        String     query='SELECT Id,affaire__c, Statut_ecriture_comptable__c ';
        query = query + '   FROM VILigne_comptable__c ';
        query = query + '  WHERE Statut_ecriture_comptable__c =\''+VIConstant.EC_BROUILLON+'\'';
        query = query + '    AND Affaire__r.entite_bw__c =\''+entite_bw+'\'';        
        if(EcrituresAEnvoyer=='Avancement') {
            query = query + '    AND (libelle__c=\''+VIConstant.EC_CA_AVENCEMENT+'\' ';
            query = query + '       OR libelle__c=\''+VIConstant.EC_PROVISION_AMORTISSEMENT_AVCT+'\' ';            
            query = query + '       OR libelle__c=\''+VIConstant.EC_PROVISION_FINANCEMENT_AVCT+'\') ';                        
        } else if (EcrituresAEnvoyer=='Reprise de garantie') {
            query = query + '    AND libelle__c=\''+VIConstant.EC_REPRISE_PROVISION_GARANTIE+'\'';            
        } else {
            query = query + '    AND 1=0 '; // We don't want to run the programm
        }
        system.debug(query);
        IDLog=VIUtils.LogWrite('VIBatchEnvoiEcriture','4 Running','','Start ');
        
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<VILigne_comptable__c> scope) {
        for(VILigne_comptable__c lc:scope) {
             lc.Statut_ecriture_comptable__c=VIConstant.EC_A_PRENDRE  ;
        }
        update scope;
        num_record = num_record + scope.size();
    }   

    global void finish(Database.BatchableContext BC) {
        IDLog=VIUtils.LogWrite('VIBatchEnvoiEcriture','1 Normal',IDLog,'nbr '+num_record);    
        
    }
    public static final integer NBR_LOT = 20;
    
}