force-app/main/default/objects/VIAffaire__c/VIAffaire__c.object-meta.xml
<CustomObject>
    <label>Affaire</label>
    <nameField>
        <label>Code Affaire</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Affaires</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VIAffaire__c/fields/Date_de_SAV_reelle__c.field-meta.xml
<CustomField>
    <fullName>Date_de_SAV_reelle__c</fullName>
    <label>Date de SAV réelle</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VIAffaire__c/fields/Entite_BW__c.field-meta.xml
<CustomField>
    <fullName>Entite_BW__c</fullName>
    <label>Entité BW</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>EntiteBW</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/VILigne_d_affaire_mensuelle__c.object-meta.xml
<CustomObject>
    <label>Ligne d&apos;affaire mensuelle</label>
    <nameField>
        <label>Ref de Ligne d&apos;affaire mensuelle</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lignes d&apos;affaire mensuelles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/Affaire__c.field-meta.xml
<CustomField>
    <fullName>Affaire__c</fullName>
    <label>Affaire</label>
    <referenceTo>VIAffaire__c</referenceTo>
    <relationshipLabel>Lignes d&apos;affaire mensuelles</relationshipLabel>
    <relationshipName>Lignes_d_affaire_mensuelles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/Affaire_a_fermer__c.field-meta.xml
<CustomField>
    <fullName>Affaire_a_fermer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Affaire à fermer ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/Entite_BW__c.field-meta.xml
<CustomField>
    <fullName>Entite_BW__c</fullName>
    <formula>text(Affaire__r.Entite_BW__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Entité BW</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/Nom_de_l_affaire__c.field-meta.xml
<CustomField>
    <fullName>Nom_de_l_affaire__c</fullName>
    <formula>Affaire__r.Nom_affaire__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nom de l&apos;affaire</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VIPeriode__c/VIPeriode__c.object-meta.xml
<CustomObject>
    <label>Période comptable</label>
    <nameField>
        <label>Nom de Période</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Périodes comptables</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VIPeriode__c/fields/Date_de_fin__c.field-meta.xml
<CustomField>
    <fullName>Date_de_fin__c</fullName>
    <label>Date de fin</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VIPeriode__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Periode_comptable_statut</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/VIMajSavController.cls
public class VIMajSavController {

    public List<VIPeriode__c >ListPeriode { get; set; }

    Public List<VILigne_d_affaire_mensuelle__c>ListLam {get; set;}
    Public List<VILigne_d_affaire_mensuelle__c>ListLam1 {get; set;}
    public Map<string, ViAffaire__c> MapAffaire = new Map<string, ViAffaire__c>();
    Map<string, date>MapEntite_bw = new Map<string, date>();

    ApexPages.StandardSetController mycon;
       
    public VIMajSavController(ApexPages.StandardSetController mycon) {        
        this.MyCon = Mycon;        
        //Mycon.setPageSize(Mycon.getResultSize());
        ListLam=Mycon.getSelected();
        List<id>ListId = new List<id>();
        for(VILigne_d_affaire_mensuelle__c lam:ListLam) {
            ListID.add(lam.id);
        }
        
        ListLam1 = new List<VILigne_d_affaire_mensuelle__c>();
        for(VILigne_d_affaire_mensuelle__c lam:[SELECT id, Nom_de_l_affaire__c, affaire__r.name, Affaire_a_fermer__c, affaire__c
                                                  FROM VILigne_d_affaire_mensuelle__c
                                                WHERE id in : ListID]) {
            lam.Affaire_a_fermer__c=true;                                                    
            ListLam1.add(lam);
       }
                
        for(VIPeriode__c per:[SELECT id, entite_bw__c, date_de_fin__c 
                                 FROM VIPeriode__c
                                WHERE Statut__c=:VIConstant.PERIODE_OUVERTE]) {
            MapEntite_bw.put(per.entite_bw__c,per.date_de_fin__c) ;
        }
        ListPeriode=[SELECT entite_bw__c, date_de_fin__c FROM VIperiode__c WHERE Statut__c=:VIConstant.PERIODE_OUVERTE ORDER BY entite_bw__c];        
        
    }       

    public PageReference  Enregistrer() {
        
        ListLam=Mycon.getselected();

        for(VILigne_d_affaire_mensuelle__c lam: ListLam1) {
            if(lam.Affaire_a_fermer__c) {
              MapAffaire.put(lam.affaire__c,null);
            }
        }
        for(VIaffaire__c aff: [SELECT id, date_de_sav_reelle__c, entite_bw__c
                                 FROM VIAffaire__c
                               WHERE id in :MapAffaire.keyset()]) {
            aff.date_de_sav_reelle__c = MapEntite_bw.get(aff.entite_bw__c);
            MapAffaire.put(aff.id,aff) ;
        }
        update MapAffaire.values();
        
        return mycon.cancel();
    }

}