force-app/main/default/objects/VIAffaire__c/VIAffaire__c.object-meta.xml
<CustomObject>
    <label>Affaire</label>
    <nameField>
        <label>Code Affaire</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Affaires</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VIAffaire__c/fields/Date_de_fin_de_garantie__c.field-meta.xml
<CustomField>
    <fullName>Date_de_fin_de_garantie__c</fullName>
    <formula>if(!isnull(Date_de_SAV_reelle__c) , 
     ADDMONTHS( Date_de_SAV_reelle__c, Produit_SousDomaine__r.Duree_garantie__c  ),
     null)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Date de fin de garantie</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VILigne_affaire__c/VILigne_affaire__c.object-meta.xml
<CustomObject>
    <label>Ligne d&apos;affaire</label>
    <nameField>
        <displayFormat>L{000000000}</displayFormat>
        <label>Ref de Ligne d&apos;affaire</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lignes d&apos;affaire</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VILigne_affaire__c/fields/Ecart_C_A_F_MontantD__c.field-meta.xml
<CustomField>
    <fullName>Ecart_C_A_F_MontantD__c</fullName>
    <label>Ecart C.A.F - MontantD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VILigne_affaire__c/fields/Ligne_d_affaire_mensuelle__c.field-meta.xml
<CustomField>
    <fullName>Ligne_d_affaire_mensuelle__c</fullName>
    <label>Ligne d&apos;affaire mensuelle</label>
    <referenceTo>VILigne_d_affaire_mensuelle__c</referenceTo>
    <relationshipLabel>Lignes d&apos;affaire</relationshipLabel>
    <relationshipName>Lignes_d_affaire</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/VILigne_d_affaire_mensuelle__c.object-meta.xml
<CustomObject>
    <label>Ligne d&apos;affaire mensuelle</label>
    <nameField>
        <label>Ref de Ligne d&apos;affaire mensuelle</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lignes d&apos;affaire mensuelles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/Affaire__c.field-meta.xml
<CustomField>
    <fullName>Affaire__c</fullName>
    <label>Affaire</label>
    <referenceTo>VIAffaire__c</referenceTo>
    <relationshipLabel>Lignes d&apos;affaire mensuelles</relationshipLabel>
    <relationshipName>Lignes_d_affaire_mensuelles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/Date_de_fin_de_garantie__c.field-meta.xml
<CustomField>
    <fullName>Date_de_fin_de_garantie__c</fullName>
    <formula>Affaire__r.Date_de_fin_de_garantie__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Date de fin de garantie</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VIParametres__c/VIParametres__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>VIParametres</label>
</CustomObject>

force-app/main/default/objects/VIParametres__c/fields/Nb_jours_conservation_LA__c.field-meta.xml
<CustomField>
    <fullName>Nb_jours_conservation_LA__c</fullName>
    <defaultValue>60</defaultValue>
    <inlineHelpText>Nombre de jours pendant lesquels on conserve les lignes  d&apos;affaire</inlineHelpText>
    <label>Nb_jours_conservation_LA</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VIParametres__c/fields/Sans_Calcul_de_PRI__c.field-meta.xml
<CustomField>
    <fullName>Sans_Calcul_de_PRI__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Si coché, on fait le calcul avec les taux.Sinon, on prend les montants tel quel</inlineHelpText>
    <label>Sans Calcul de PRI ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/VISchedBatchDeleteLA.cls
/*
*
*  Delete all the ligne d'affaire after a number of days. We don't need the LA, LAM are enough
*
*
*  for running by hand : 
 VISchedBatchDeleteLA v = new VISchedBatchDeleteLA('',false);
 v.execute(null);
*
*
*/
global class VISchedBatchDeleteLA implements Schedulable,Database.Batchable<sObject>,Database.Stateful{

    private string AffaireAGenerer; 
    private boolean Enchaine ;
    
     public VISchedBatchDeleteLA(String Param1,Boolean Param2 ) {
        AffaireAGenerer = Param1;        
        Enchaine = Param2;                
    }
    
    
    global Database.QueryLocator start(Database.BatchableContext BC){        
        
        VIParametres__c param = VIParametres__c.getInstance(UserInfo.getUserId());  
        string d1 = string.valueof(system.today().adddays(integer.valueof(param.Nb_jours_conservation_LA__c) * (-1) )).left(10) ; 
        
        string query = 'SELECT id,Date_de_fin_de_garantie__c ';
        query = query+'   FROM VIaffaire__c   ';
        query = query+'  WHERE (name Like \''+AffaireAGenerer+'%\')  ';  
        if(!test.isrunningtest()) {
            query = query+'    and Date_de_fin_de_garantie__c<'+d1 ;  
        }
        query = query+'  order by name Desc  ';                
        system.debug(query);
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<Viaffaire__c > scope){
        list<viLigne_affaire__c>listladelete = new list<viLigne_affaire__c>();
        map<string,VIaffaire__c>MapAffaire = new map<string,VIaffaire__c>();
        for(Viaffaire__c aff: scope) {
            MapAffaire.put(aff.id,aff);
        }
        for(viLigne_affaire__c la: [SELECT id
                                      FROM viLigne_affaire__c
                                     WHERE Ligne_d_affaire_mensuelle__r.affaire__c in :MapAffaire.keyset()
                                       AND Ecart_C_A_F_MontantD__c =0]) {
            listladelete.add(la);
        }
        delete listladelete;

    }

    global void finish(Database.BatchableContext BC){

    }

    global void execute(SchedulableContext scon) {
        Database.executeBatch(new VISchedBatchDeleteLA(AffaireAGenerer,Enchaine),VISchedBatchDeleteLA.NBR_LOT());
    }
    
    public static  integer NBR_LOT () {
         VIParametres__c param = VIParametres__c.getInstance(UserInfo.getUserId()); 
         integer i ; 
         if(param.Sans_Calcul_de_PRI__c) {
             i=40 ;
         } else {
             i=8;    
         }
         return i;
    }
    
}