force-app/main/default/objects/VIAffaire__c/VIAffaire__c.object-meta.xml
<CustomObject>
    <label>Affaire</label>
    <nameField>
        <label>Code Affaire</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Affaires</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VIAffaire__c/fields/Entite_BW__c.field-meta.xml
<CustomField>
    <fullName>Entite_BW__c</fullName>
    <label>Entité BW</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>EntiteBW</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/VIAffaire__c/fields/Produit_SousDomaine__c.field-meta.xml
<CustomField>
    <fullName>Produit_SousDomaine__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Produit - SousDomaine</label>
    <referenceTo>VISousDomaine__c</referenceTo>
    <relationshipLabel>Affaires</relationshipLabel>
    <relationshipName>Affaires</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VILigne_affaire__c/VILigne_affaire__c.object-meta.xml
<CustomObject>
    <label>Ligne d&apos;affaire</label>
    <nameField>
        <displayFormat>L{000000000}</displayFormat>
        <label>Ref de Ligne d&apos;affaire</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lignes d&apos;affaire</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VILigne_affaire__c/fields/Centre_Section__c.field-meta.xml
<CustomField>
    <fullName>Centre_Section__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Centre / Section</label>
    <referenceTo>VICentre_Section__c</referenceTo>
    <relationshipLabel>Lignes d&apos;affaire</relationshipLabel>
    <relationshipName>Lignes_d_affaire</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VILigne_affaire__c/fields/Ecart_C_A_F_Heure__c.field-meta.xml
<CustomField>
    <fullName>Ecart_C_A_F_Heure__c</fullName>
    <label>Ecart C.A.F - Heure</label>
    <precision>6</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VILigne_affaire__c/fields/Ecart_C_A_F_MontantD__c.field-meta.xml
<CustomField>
    <fullName>Ecart_C_A_F_MontantD__c</fullName>
    <label>Ecart C.A.F - MontantD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VILigne_affaire__c/fields/Entite_BW__c.field-meta.xml
<CustomField>
    <fullName>Entite_BW__c</fullName>
    <formula>Text( Ligne_d_affaire_mensuelle__r.Affaire__r.Entite_BW__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Entité BW</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VILigne_affaire__c/fields/Ligne_d_affaire_mensuelle__c.field-meta.xml
<CustomField>
    <fullName>Ligne_d_affaire_mensuelle__c</fullName>
    <label>Ligne d&apos;affaire mensuelle</label>
    <referenceTo>VILigne_d_affaire_mensuelle__c</referenceTo>
    <relationshipLabel>Lignes d&apos;affaire</relationshipLabel>
    <relationshipName>Lignes_d_affaire</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VILigne_affaire__c/fields/Type_depense__c.field-meta.xml
<CustomField>
    <fullName>Type_depense__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Type de dépense</label>
    <referenceTo>VIType_de_depense__c</referenceTo>
    <relationshipLabel>Lignes d&apos;affaire</relationshipLabel>
    <relationshipName>Lignes_d_affaire</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/VILigne_d_affaire_mensuelle__c.object-meta.xml
<CustomObject>
    <label>Ligne d&apos;affaire mensuelle</label>
    <nameField>
        <label>Ref de Ligne d&apos;affaire mensuelle</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lignes d&apos;affaire mensuelles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/Affaire__c.field-meta.xml
<CustomField>
    <fullName>Affaire__c</fullName>
    <label>Affaire</label>
    <referenceTo>VIAffaire__c</referenceTo>
    <relationshipLabel>Lignes d&apos;affaire mensuelles</relationshipLabel>
    <relationshipName>Lignes_d_affaire_mensuelles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/Cout_terminaison_MontantD__c.field-meta.xml
<CustomField>
    <fullName>Cout_terminaison_MontantD__c</fullName>
    <formula>Devis_MontantD__c + Ecart_C_A_F_MontantD__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Coût à terminaison - MontantD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/Ecart_C_A_F_MontantC__c.field-meta.xml
<CustomField>
    <fullName>Ecart_C_A_F_MontantC__c</fullName>
    <label>Ecart C.A.F - MontantC</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/Ecart_C_A_F_MontantC_E__c.field-meta.xml
<CustomField>
    <fullName>Ecart_C_A_F_MontantC_E__c</fullName>
    <label>Ecart C.A.F - MontantC €</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/Ecart_C_A_F_MontantD_E__c.field-meta.xml
<CustomField>
    <fullName>Ecart_C_A_F_MontantD_E__c</fullName>
    <label>Ecart C.A.F - MontantD €</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/Ecart_C_A_F_MontantI__c.field-meta.xml
<CustomField>
    <fullName>Ecart_C_A_F_MontantI__c</fullName>
    <label>Ecart C.A.F - MontantI</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/Ecart_C_A_F_MontantI_E__c.field-meta.xml
<CustomField>
    <fullName>Ecart_C_A_F_MontantI_E__c</fullName>
    <label>Ecart C.A.F - MontantI €</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/Entite_BW__c.field-meta.xml
<CustomField>
    <fullName>Entite_BW__c</fullName>
    <formula>text(Affaire__r.Entite_BW__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Entité BW</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/Periode_comptable__c.field-meta.xml
<CustomField>
    <fullName>Periode_comptable__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Période comptable</label>
    <referenceTo>VIPeriode__c</referenceTo>
    <relationshipLabel>Lignes d&apos;affaire mensuelles</relationshipLabel>
    <relationshipName>Lignes_d_affaire_mensuelles</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VIParametres__c/VIParametres__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>VIParametres</label>
</CustomObject>

force-app/main/default/objects/VIParametres__c/fields/Sans_Calcul_de_PRI__c.field-meta.xml
<CustomField>
    <fullName>Sans_Calcul_de_PRI__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Si coché, on fait le calcul avec les taux.Sinon, on prend les montants tel quel</inlineHelpText>
    <label>Sans Calcul de PRI ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VIPeriode__c/VIPeriode__c.object-meta.xml
<CustomObject>
    <label>Période comptable</label>
    <nameField>
        <label>Nom de Période</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Périodes comptables</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VIPeriode__c/fields/Date_de_debut__c.field-meta.xml
<CustomField>
    <fullName>Date_de_debut__c</fullName>
    <label>Date de début</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VIPeriode__c/fields/Date_de_fin__c.field-meta.xml
<CustomField>
    <fullName>Date_de_fin__c</fullName>
    <label>Date de fin</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VIPeriode__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Periode_comptable_statut</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/VITauxHoraire__c/VITauxHoraire__c.object-meta.xml
<CustomObject>
    <label>Taux horaire</label>
    <nameField>
        <displayFormat>TH{00000}</displayFormat>
        <label>Ref de Taux horare</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Taux horaires</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VITauxHoraire__c/fields/Centre_Section__c.field-meta.xml
<CustomField>
    <fullName>Centre_Section__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Centre / Section</label>
    <referenceTo>VICentre_Section__c</referenceTo>
    <relationshipName>Taux</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VITauxHoraire__c/fields/Date_de_fin__c.field-meta.xml
<CustomField>
    <fullName>Date_de_fin__c</fullName>
    <label>Date de fin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VITauxHoraire__c/fields/Taux_devis_conversion_Complet__c.field-meta.xml
<CustomField>
    <fullName>Taux_devis_conversion_Complet__c</fullName>
    <label>Taux devis conversion Complet</label>
    <precision>16</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VITauxHoraire__c/fields/Taux_devis_conversion_PRI__c.field-meta.xml
<CustomField>
    <fullName>Taux_devis_conversion_PRI__c</fullName>
    <label>Taux devis conversion PRI</label>
    <precision>16</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VITauxHoraire__c/fields/taux_devis_horaire__c.field-meta.xml
<CustomField>
    <fullName>taux_devis_horaire__c</fullName>
    <label>Taux devis horaire</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VITauxIncorporation__c/VITauxIncorporation__c.object-meta.xml
<CustomObject>
    <label>Taux d&apos;incorporation</label>
    <nameField>
        <displayFormat>TI{00000}</displayFormat>
        <label>Ref de Taux d&apos;incorporation</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Taux d&apos;incorporation</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VITauxIncorporation__c/fields/Date_de_debut__c.field-meta.xml
<CustomField>
    <fullName>Date_de_debut__c</fullName>
    <label>Date de début</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VITauxIncorporation__c/fields/Date_de_fin__c.field-meta.xml
<CustomField>
    <fullName>Date_de_fin__c</fullName>
    <label>Date de fin</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VITauxIncorporation__c/fields/Entite_BW__c.field-meta.xml
<CustomField>
    <fullName>Entite_BW__c</fullName>
    <label>Entité BW</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>EntiteBW</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/VITauxIncorporation__c/fields/Produit_SousDomaine__c.field-meta.xml
<CustomField>
    <fullName>Produit_SousDomaine__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produit - SousDomaine</label>
    <referenceTo>VISousDomaine__c</referenceTo>
    <relationshipLabel>Taux d&apos;incorporation</relationshipLabel>
    <relationshipName>Taux_d_incorporation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VITauxIncorporation__c/fields/Taux_complet__c.field-meta.xml
<CustomField>
    <fullName>Taux_complet__c</fullName>
    <label>Taux complet</label>
    <precision>16</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VITauxIncorporation__c/fields/Taux_PRI__c.field-meta.xml
<CustomField>
    <fullName>Taux_PRI__c</fullName>
    <label>Taux PRI</label>
    <precision>16</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VITauxIncorporation__c/fields/Type_de_depense__c.field-meta.xml
<CustomField>
    <fullName>Type_de_depense__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Type de dépense</label>
    <referenceTo>VIType_de_depense__c</referenceTo>
    <relationshipLabel>Taux d&apos;incorporation</relationshipLabel>
    <relationshipName>Taux_d_incorporation</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VIType_de_depense__c/VIType_de_depense__c.object-meta.xml
<CustomObject>
    <label>Type de dépense</label>
    <nameField>
        <label>Nom de Type de dépense</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Types de dépenses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/VI01_Ligne_affaire.cls
/*
* @author: Henri Saslawsky
* @description: 
*/

public class VI01_Ligne_affaire {


/*
* @description: Method to check if it's possible to delete the Ligne d'affaire
* 
* @param: List of VILigne_affaire
* @return : true or false
* 
*/

    public static boolean CanDelete (List <VILigne_Affaire__c> listLa) { 

        system.debug('entrée dans VI01_Ligne_affaire.CanDelete');
        boolean check =false ;        
        VIParametres__c param = VIParametres__c.getInstance(UserInfo.getUserId()); 
        if(!param.Sans_Calcul_de_PRI__c) {                 
            for(VILigne_Affaire__c La:listLa){
                if(la.Cout_terminaison_MontantD__c!=0) {
                    la.AddError(label.VIErreur005);
                    check=true ; 
                }
            }
        }        
        return check;
    }
    

/*
* @description: Method to compute the total on VILigne_affaire from VIligne_affaire
* 
* @param: List of VILigne_affaire
* @return : void
* 
*/
    public static list<string> ReProcess_LA (List <VILigne_affaire__c> listLa, Map<id,VILigne_affaire__c> MapOldLa) { 

        system.debug('entrée dans VI01_Ligne_affaire.reprocess_la');
        Map<string,string>MapIDAff = new Map<string,string>();
        list<id>ListIDLAM = new List<id>();
        
        // We recompute the LAM only when the LA is deleted, or when the Ecart_C_A_F_MontantD__c is modified
        for(VILigne_affaire__c la : listLa) { 
            if(MapOldLa==null ) {
                ListIDLAM.add(la.ligne_d_affaire_mensuelle__c); 
            } else {
                VILigne_affaire__c oldLA = MapOldLa.get(la.ID);
                if(la.Ecart_C_A_F_MontantD__c != oldLA.Ecart_C_A_F_MontantD__c) {
                    ListIDLAM.add(la.ligne_d_affaire_mensuelle__c); 
                }
            }
        }
        for(VIligne_d_affaire_mensuelle__c lam : [SELECT affaire__r.name 
                                                    FROM VIligne_d_affaire_mensuelle__c
                                                  WHERE id in :ListIDLAM ]) {
            MapIDaff.put(lam.affaire__r.name,lam.affaire__r.name);
        } 
        return MapIDaff.values() ;
    }
    
    
    
/*
* @description: From Debours, we need to compute "industriel" and "complet"
* 
* @param: List of Ligne_affaire
* @return : void
* 
*/ 
    
    public static void Compute_Value (List <VILigne_affaire__c> listLA) {
        system.debug('entrée dans VI01_Ligne_affaire.Compute_Value');
        
        list<String> ListEntite_bw     = new list<string>();
        list<String> ListCurrency      = new list<string>();
        list<String> ListCentreSection = new list<string>(); 
        list<String> ListTypeDepense   = new list<string>(); 
        list<String> ListLAM       = new list<string>();         

        date date_minimum=system.today().addmonths(-5); //We don't need the currency rates below this date
        string MOid=[SELECT id FROM VItype_de_depense__c WHERE name like 'MO %' LIMIT 1][0].id;
        
        
        for(VILigne_affaire__c la:ListLA){
            ListEntite_bw.add(la.entite_bw__c);
            ListCurrency.add(la.CurrencyIsoCode);
            ListCentreSection.add(la.Centre_Section__c);  
            ListTypeDepense.add(la.Type_Depense__c);
            ListLAM.add(la.Ligne_d_affaire_mensuelle__c );
        }

        Map<string,VILigne_d_affaire_mensuelle__c >MapLam = new  Map<string,VILigne_d_affaire_mensuelle__c >();
        for(VILigne_d_affaire_mensuelle__c lam: [SELECT id, affaire__r.produit_sousdomaine__c,Periode_comptable__r.date_de_debut__c
                                                   FROM VILigne_d_affaire_mensuelle__c
                                                 WHERE id in:ListLAM]) {
            MapLam.put(lam.id,lam);                                             
        }
        
        
        // I can only modify the LA for the current period. So all the rates are the rates of the open period
        Map<string,date>MapDate = new Map<string,date>();
        for(VIPeriode__c per:[SELECT id,name, entite_bw__c, date_de_debut__c
                                   FROM VIPeriode__c
                                  WHERE entite_bw__c in :ListEntite_bw
                                    AND Statut__c=:VIConstant.PERIODE_OUVERTE]) {
            MapDate.put(per.entite_bw__c,per.date_de_debut__c);
        }     
        
        // Let's fetch the currency rates needed
        List<DatedConversionRate> currencyTypeList = [SELECT Id, IsoCode, ConversionRate, StartDate, NextStartDate 
                                                        FROM DatedConversionRate 
                                                       WHERE IsoCode in :ListCurrency
                                                         AND (NextStartDate<:date_minimum or NextStartDate>9998-01-01 ) 
                                                    ORDER BY IsoCode, NextStartDate DESC];
        

        // Let's fetch all the rates we need to use later
        // WHERE entite_bw__c in :Listentite_bw  AND CurrencyIsoCode in :ListCurrency
        //                  AND Centre_Section__c in :ListCentreSection
        // 
        list<VITauxHoraire__c>ListTaux = new List<VItauxHoraire__c>();
        for(VItauxHoraire__c t:[SELECT Centre_Section__c,entite_bw__c, CurrencyIsoCode,Date_de_debut__c,Date_de_fin__c,
                                       taux_devis_horaire__c , Taux_devis_conversion_PRI__c , Taux_devis_conversion_complet__c
                                  FROM VItauxHoraire__c
                                 WHERE centre_section__c in :ListCentreSection]) {
              ListTaux.add(t);             
         }

        list<VITauxIncorporation__c>ListTauxIncorporation = new List<VITauxIncorporation__c>();

        for(VITauxIncorporation__c t:[SELECT CurrencyIsoCode,Date_de_debut__c,Date_de_fin__c,
                                             Produit_SousDomaine__c  , Type_de_depense__c ,
                                             Taux_PRI__c , Taux_complet__c, entite_bw__c   
                                        FROM VITauxIncorporation__c
                                       WHERE CurrencyIsoCode in :ListCurrency
                                         AND Type_de_depense__c in :ListTypeDepense
                                         AND entite_bw__c in :ListEntite_bw
                                         AND date_de_debut__c<=:date_minimum
                                         AND date_de_fin__c>=:date_minimum ]) {
              ListTauxIncorporation.add(t);             
         }
        
        
        for(VILigne_affaire__c la:ListLA){

            if(la.type_depense__c==MOid) {
               // We need to find the correct line in the list
                VItauxHoraire__c t_correct = new VItauxHoraire__c();
                t_correct = null;
                for(VItauxHoraire__c t:ListTaux) {
                    if(t.CurrencyIsoCode   == la.CurrencyIsoCode && 
                       t.Centre_Section__c == la.Centre_Section__c   &&
                       t.date_de_debut__c  <= MapDate.get(la.entite_bw__c)	 && 
                       t.date_de_fin__c    >= MapDate.get(la.entite_bw__c)  ) {
                      t_correct=t ; 
                      break ;     
                   }   
                }
                // Hope we found the correct line
                if(t_correct!=null) {                
                    decimal nb_heure_ecart = (la.Ecart_C_A_F_Heure__c  == null ? 0 :la.Ecart_C_A_F_Heure__c  );
                    la.Ecart_C_A_F_MontantD__c  = nb_heure_ecart * t_correct.taux_devis_horaire__c ;
                    la.Ecart_C_A_F_MontantI__c  =la.Ecart_C_A_F_MontantD__c*t_correct.Taux_devis_conversion_PRI__c;
                    la.Ecart_C_A_F_MontantC__c  =la.Ecart_C_A_F_MontantD__c*t_correct.Taux_devis_conversion_Complet__c;                
                }    
            }  else {
                VItauxIncorporation__c t_correct = new VItauxIncorporation__c();
                t_correct = null;
                for(VItauxIncorporation__c t:ListTauxIncorporation) {
                    
                    if(t.entite_bw__c   == la.entite_bw__c	 && 
                       t.Produit_SousDomaine__c == MapLam.get(la.Ligne_d_affaire_mensuelle__c ).affaire__r.Produit_SousDomaine__c &&
                       t.type_de_depense__c == la.type_depense__c &&                       
                       t.date_de_debut__c  <= MapLam.get(la.Ligne_d_affaire_mensuelle__c).Periode_comptable__r.date_de_debut__c && 
                       t.date_de_fin__c  >= MapLam.get(la.Ligne_d_affaire_mensuelle__c).Periode_comptable__r.date_de_debut__c  ) {
                      t_correct=t ; 
                      break ;     
                   }   
                }
                // Hope we found the correct line
                if(t_correct!=null) {
                    la.Ecart_C_A_F_MontantI__c  =la.Ecart_C_A_F_MontantD__c*t_correct.Taux_PRI__c;
                    la.Ecart_C_A_F_MontantC__c  =la.Ecart_C_A_F_MontantD__c*t_correct.Taux_complet__c;                
                } else {
                    la.Ecart_C_A_F_MontantI__c  =la.Ecart_C_A_F_MontantD__c;
                    la.Ecart_C_A_F_MontantC__c  =la.Ecart_C_A_F_MontantD__c;                
                    
                }               
            }               
            // If we are in EUR,we don't have to do any currency conversion
            if(la.CurrencyIsoCode=='EUR') {
                la.Ecart_C_A_F_MontantD_E__c=la.Ecart_C_A_F_MontantD__c;                
                la.Ecart_C_A_F_MontantI_E__c=la.Ecart_C_A_F_MontantI__c;                
                la.Ecart_C_A_F_MontantC_E__c=la.Ecart_C_A_F_MontantC__c;                                
            } else {
                // We are in a currency
                // So let's loop until we find the correct line
                DatedConversionRate r_correct = null ; 
                for(DatedConversionRate r: currencyTypeList) {
                    if(r.IsoCode==la.CurrencyIsoCode &&  
                       r.StartDate<=MapDate.get(la.entite_bw__c) &&  
                       r.NextStartDate>=MapDate.get(la.entite_bw__c)) {
                        r_correct = r;
                        break ; 
                    }
                }
                if(r_correct!=null) {
                    if(la.Ecart_C_A_F_MontantD__c!=null) {
                        la.Ecart_C_A_F_MontantD_E__c=la.Ecart_C_A_F_MontantD__c*(1/r_correct.ConversionRate).SetScale(2);                
                        la.Ecart_C_A_F_MontantI_E__c=la.Ecart_C_A_F_MontantI__c*(1/r_correct.ConversionRate).SetScale(2);                
                        la.Ecart_C_A_F_MontantC_E__c=la.Ecart_C_A_F_MontantC__c*(1/r_correct.ConversionRate).SetScale(2);                                
                    }
                }
            }
        }  
    }
    
}