force-app/main/default/objects/VIAffaire__c/VIAffaire__c.object-meta.xml
<CustomObject>
    <label>Affaire</label>
    <nameField>
        <label>Code Affaire</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Affaires</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VIAffaire__c/fields/Date_max_mouvement__c.field-meta.xml
<CustomField>
    <fullName>Date_max_mouvement__c</fullName>
    <label>Date max mouvement</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VICentre_Section__c/VICentre_Section__c.object-meta.xml
<CustomObject>
    <label>Centre / Section</label>
    <nameField>
        <label>Nom de Centre / Section</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Centres / Sections</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/VILigne_d_affaire_mensuelle__c.object-meta.xml
<CustomObject>
    <label>Ligne d&apos;affaire mensuelle</label>
    <nameField>
        <label>Ref de Ligne d&apos;affaire mensuelle</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lignes d&apos;affaire mensuelles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/Affaire__c.field-meta.xml
<CustomField>
    <fullName>Affaire__c</fullName>
    <label>Affaire</label>
    <referenceTo>VIAffaire__c</referenceTo>
    <relationshipLabel>Lignes d&apos;affaire mensuelles</relationshipLabel>
    <relationshipName>Lignes_d_affaire_mensuelles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VIPointage__c/VIPointage__c.object-meta.xml
<CustomObject>
    <label>Pointage</label>
    <nameField>
        <displayFormat>P{000000000}</displayFormat>
        <label>Ref de Pointage</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pointages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VIPointage__c/fields/Affaire__c.field-meta.xml
<CustomField>
    <fullName>Affaire__c</fullName>
    <label>Affaire</label>
    <referenceTo>VIAffaire__c</referenceTo>
    <relationshipLabel>Pointages</relationshipLabel>
    <relationshipName>Pointages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VIPointage__c/fields/Centre_Section__c.field-meta.xml
<CustomField>
    <fullName>Centre_Section__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Centre / Section</label>
    <referenceTo>VICentre_Section__c</referenceTo>
    <relationshipLabel>Pointages</relationshipLabel>
    <relationshipName>Pointages</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VIPointage__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Date Pointage</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VIPointage__c/fields/Employe__c.field-meta.xml
<CustomField>
    <fullName>Employe__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employé</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Pointages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VIPointage__c/fields/Heures__c.field-meta.xml
<CustomField>
    <fullName>Heures__c</fullName>
    <label>Heures</label>
    <precision>4</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VIPointage__c/fields/Numero_unique__c.field-meta.xml
<CustomField>
    <fullName>Numero_unique__c</fullName>
    <label>Numéro_unique</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VIPointage__c/fields/Sous_chapitre__c.field-meta.xml
<CustomField>
    <fullName>Sous_chapitre__c</fullName>
    <label>Sous chapitre</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sous_chapitre</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/VIBatchRegenerate_test.cls
@isTest
public class VIBatchRegenerate_test {

    static testmethod void VIBatchRegenerateLAM_test() {
    
        VIInsertDataTest.VIInsertData_EUR_affaire();

        VICentre_section__c cs = [SELECT id from VICentre_section__c LIMIT 1 ];
        VIAffaire__c aff       = [SELECT id,name,CurrencyIsoCode,date_max_mouvement__c from VIAffaire__c LIMIT 1 ];        
        VIPointage__c po= new VIPointage__c(affaire__c=aff.id,date__c=system.today().addmonths(6),heures__c=1, Centre_Section__c =cs.id, 
                                             CurrencyIsoCode=aff.CurrencyIsoCode,employe__c=UserInfo.getUserId(),numero_unique__c='AAA',
                                             sous_chapitre__c='00-00');
        insert po;

        VIInsertDataTest.VIInsertData_Achat();
        
        list<VILigne_d_affaire_mensuelle__c>listLam=[select id from VILigne_d_affaire_mensuelle__c];
        delete ListLam;
        
        Database.executeBatch(new VIBatchRegenerateLAM(aff.name,false), 1);
        viutils.code_coverage(); 

    }

    static testmethod void VIBatchRegenerateTotal_test() {
    
        VIInsertDataTest.VIInsertData_EUR_affaire();

        VICentre_section__c cs = [SELECT id from VICentre_section__c LIMIT 1 ];
        VIAffaire__c aff       = [SELECT id,name,CurrencyIsoCode,date_max_mouvement__c from VIAffaire__c LIMIT 1 ];        
        VIPointage__c po= new VIPointage__c(affaire__c=aff.id,date__c=system.today().addmonths(6),heures__c=1, Centre_Section__c =cs.id, 
                                             CurrencyIsoCode=aff.CurrencyIsoCode,employe__c=UserInfo.getUserId(),numero_unique__c='AAA',
                                             sous_chapitre__c='00-00');
        insert po;

        VIInsertDataTest.VIInsertData_Achat();
        VIInsertDataTest.VIInsertData_Avenant_sans_update();
                 
        
        Database.executeBatch(new VIBatchRegenerateTotal(aff.name,false,false), 1);

    }

}