force-app/main/default/objects/VIAffaire__c/VIAffaire__c.object-meta.xml
<CustomObject>
    <label>Affaire</label>
    <nameField>
        <label>Code Affaire</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Affaires</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VIAffaire__c/fields/Date_de_SAV_reelle__c.field-meta.xml
<CustomField>
    <fullName>Date_de_SAV_reelle__c</fullName>
    <label>Date de SAV réelle</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VIAffaire__c/fields/Entite_BW__c.field-meta.xml
<CustomField>
    <fullName>Entite_BW__c</fullName>
    <label>Entité BW</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>EntiteBW</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/VIAffaire__c/fields/Type_Imputation__c.field-meta.xml
<CustomField>
    <fullName>Type_Imputation__c</fullName>
    <formula>text(Produit_SousDomaine__r.Type_d_imputation__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type Imputation</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VICentre_Section__c/VICentre_Section__c.object-meta.xml
<CustomObject>
    <label>Centre / Section</label>
    <nameField>
        <label>Nom de Centre / Section</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Centres / Sections</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VICompte_general__c/VICompte_general__c.object-meta.xml
<CustomObject>
    <label>Compte général</label>
    <nameField>
        <label>Nom de Compte général</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Comptes généraux</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VIEntiteBW__c/VIEntiteBW__c.object-meta.xml
<CustomObject>
    <label>EntiteBW</label>
    <nameField>
        <label>Nom de l&apos;EntiteBW</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EntiteBW</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VIEntiteBW__c/fields/Entite_BW__c.field-meta.xml
<CustomField>
    <fullName>Entite_BW__c</fullName>
    <label>Entité BW</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>EntiteBW</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/VIEntiteBW__c/fields/Libelle__c.field-meta.xml
<CustomField>
    <fullName>Libelle__c</fullName>
    <label>Libellé</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VILigne_affaire__c/VILigne_affaire__c.object-meta.xml
<CustomObject>
    <label>Ligne d&apos;affaire</label>
    <nameField>
        <displayFormat>L{000000000}</displayFormat>
        <label>Ref de Ligne d&apos;affaire</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lignes d&apos;affaire</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VILigne_affaire__c/fields/Ecart_C_A_F_MontantD__c.field-meta.xml
<CustomField>
    <fullName>Ecart_C_A_F_MontantD__c</fullName>
    <label>Ecart C.A.F - MontantD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VILigne_affaire__c/fields/Engage_brut_arrete_MontantD__c.field-meta.xml
<CustomField>
    <fullName>Engage_brut_arrete_MontantD__c</fullName>
    <label>Engagé brut à l&apos;arrêté - MontantD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VILigne_affaire__c/fields/Entite_BW__c.field-meta.xml
<CustomField>
    <fullName>Entite_BW__c</fullName>
    <formula>Text( Ligne_d_affaire_mensuelle__r.Affaire__r.Entite_BW__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Entité BW</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VILigne_comptable__c/VILigne_comptable__c.object-meta.xml
<CustomObject>
    <label>Ligne comptable</label>
    <nameField>
        <displayFormat>L{000000000}</displayFormat>
        <label>Ref de la ligne comptable</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lignes comptables</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VILigne_comptable__c/fields/Affaire__c.field-meta.xml
<CustomField>
    <fullName>Affaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Affaire</label>
    <referenceTo>VIAffaire__c</referenceTo>
    <relationshipLabel>Lignes comptables (Affaire)</relationshipLabel>
    <relationshipName>Ecritures_comptables</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VILigne_comptable__c/fields/Affaire_de_rattachement__c.field-meta.xml
<CustomField>
    <fullName>Affaire_de_rattachement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Affaire de rattachement</label>
    <referenceTo>VIAffaire__c</referenceTo>
    <relationshipLabel>Lignes comptables (Affaire de rattachement)</relationshipLabel>
    <relationshipName>Lignes_comptables</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VILigne_comptable__c/fields/CompteComptable_local__c.field-meta.xml
<CustomField>
    <fullName>CompteComptable_local__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Compte comptable local</label>
    <referenceTo>VICompte_general__c</referenceTo>
    <relationshipLabel>Lignes comptables</relationshipLabel>
    <relationshipName>Lignes_comptables</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VILigne_comptable__c/fields/Montant__c.field-meta.xml
<CustomField>
    <fullName>Montant__c</fullName>
    <label>Montant</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VILigne_comptable__c/fields/Periode_comptable__c.field-meta.xml
<CustomField>
    <fullName>Periode_comptable__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Période comptable</label>
    <referenceTo>VIPeriode__c</referenceTo>
    <relationshipName>Ecritures_comptables</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VILigne_comptable__c/fields/Sens__c.field-meta.xml
<CustomField>
    <fullName>Sens__c</fullName>
    <label>Sens</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sens_ecriture_comptable</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/VILigne_comptable__c/fields/Sous_Chapitre__c.field-meta.xml
<CustomField>
    <fullName>Sous_Chapitre__c</fullName>
    <label>Sous-Chapitre</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sous_chapitre</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/VILigne_comptable__c/fields/Statut_ecriture_comptable__c.field-meta.xml
<CustomField>
    <fullName>Statut_ecriture_comptable__c</fullName>
    <defaultValue>&apos;10&apos;</defaultValue>
    <label>Statut écriture comptable</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Statut_ecriture_comptable</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/VIPeriode__c/VIPeriode__c.object-meta.xml
<CustomObject>
    <label>Période comptable</label>
    <nameField>
        <label>Nom de Période</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Périodes comptables</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VIPeriode__c/fields/Date_de_debut__c.field-meta.xml
<CustomField>
    <fullName>Date_de_debut__c</fullName>
    <label>Date de début</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VIPeriode__c/fields/Date_de_fin__c.field-meta.xml
<CustomField>
    <fullName>Date_de_fin__c</fullName>
    <label>Date de fin</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VIPeriode__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Periode_comptable_statut</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/VIType_de_depense__c/VIType_de_depense__c.object-meta.xml
<CustomObject>
    <label>Type de dépense</label>
    <nameField>
        <label>Nom de Type de dépense</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Types de dépenses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/VILancementBatchController_Test.cls
@isTest
public class VILancementBatchController_Test {

    static testmethod void VILancementBatchController_Test() {
    
        VIInsertDataTest.VIInsertData_EUR_affaire();
        VIInsertDataTest.VIInsertData_Achat();
        VIInsertDataTest.VIInsertData_Pointage();
        VIInsertDataTest.VIInsertData_Facture();

        VILancementBatchController testlb = new VILancementBatchController ();  

        list<VIperiode__c>ListPeriode=[SELECT id,date_de_fin__c 
                                         FROM VIperiode__c 
                                       WHERE Statut__c =:VIConstant.PERIODE_OUVERTE
                                     ORDER BY NAME LIMIT 1];
        
        PageReference pageRef = Page.VILancementBatch; 
        
        testlb.getEntite_bwOptions();
        testlb.Entite_bw=[SELECT entite_bw__c FROM VIEntiteBW__c LIMIT 1].entite_bw__c;
        
        VIAffaire__c aff = [select id,Date_de_SAV_reelle__c,Type_Imputation__c  from VIAffaire__c LIMIT 1] ;
       // aff.Date_de_SAV_reelle__c = ListPeriode[0].date_de_fin__c;
       // update aff; 

        VItype_de_depense__c tdMO  = new VItype_de_depense__c();
        VItype_de_depense__c tdGAR = new VItype_de_depense__c();
        VItype_de_depense__c tdEMM = new VItype_de_depense__c();
        VItype_de_depense__c tdAMP = new VItype_de_depense__c();
        VItype_de_depense__c tdFOL = new VItype_de_depense__c();     
        VICentre_section__c CS801= new VICentre_section__c();
    
        Map<string,VIperiode__c>MapEntite_bwPeriode = new Map<string,VIperiode__c>();
        

        for(VIType_de_depense__c td : [SELECT ID,name from VIType_de_depense__c where name like 'MO %' or name like 'GAR%' or name like 'EMM%' or name like 'AMP%' or name like 'FOL%']) {
            if(td.name.startswith('MO '))
                 tdMO=td ; 

            if(td.name.startswith('GAR'))
                 tdGAR=td ; 

            if(td.name.startswith('EMM'))
                 tdEMM=td ; 

            if(td.name.startswith('AMP'))
                 tdAMP=td ; 

            if(td.name.startswith('FOL'))
                 tdFOL=td ; 
        }
        CS801 = [select id from VICentre_section__c where name like '801%' ];        

        VIPeriode__c periode_ouverte  ;      
        for(VIPeriode__c per : [SELECT ID,name, entite_bw__c, date_de_debut__c, date_de_fin__c ,statut__c
                                  FROM VIPeriode__c
                                 WHERE entite_bw__c='1'  ]) {
             MapEntite_bwPeriode.put(per.name,per);
             if(per.statut__c==VIConstant.PERIODE_OUVERTE)  {
                 periode_ouverte=per; 
             }
                                     
         }

        VIUtils.recalc(aff.id,true, true, tdMO,tdGAR, tdEMM, tdAMP, tdFOl, cs801, MapEntite_bwPeriode,periode_ouverte.date_de_debut__c );



        testlb.Entite_bw1='1';
        testlb.callBatchGenerate(); 
        testlb.callBatchGenereAutorisation(); 
        
        
        
/*        
        list<VILigne_Affaire__c>ListLa= [SELECT id, Cout_terminaison_MontantD__c, Engage_brut_arrete_MontantD__c,Ecart_C_A_F_MontantD__c   
                                           FROM VILigne_Affaire__c ] ;
        
        ListLa[0].Ecart_C_A_F_MontantD__c=1;
        update ListLa ; 
        System.assertEquals(10, listLa.size());
        System.assertEquals(0, listLa[0].Engage_brut_arrete_MontantD__c);

        delete listLa ; 
*/        
    }
    
    static testmethod void VILancementBatchController1_Test() {
        VIInsertDataTest.VIInsertData_EUR_affaire();

        VISchedCreatePeriode v = new VISchedCreatePeriode();
        v.execute(null);
        
        VILancementBatchController testlb = new VILancementBatchController (); 
        PageReference pageRef = Page.VILancementBatch;
        testlb.getPeriodeEntite_bwOptions();
        
    }    
    
    static testmethod void VILancementBatchController2_Test() {
        VIInsertDataTest.VIInsertData_EUR_Affaire();
        
        VILancementBatchController testlb = new VILancementBatchController (); 
        PageReference pageRef = Page.VILancementBatch;

        testlb.Entite_bw=[SELECT entite_bw__c FROM VIEntiteBW__c LIMIT 1].entite_bw__c;
        
        testlb.getPeriodeEntite_bwOptions();

        list<VIperiode__c>ListPeriode=[SELECT id,date_de_fin__c 
                                         FROM VIperiode__c 
                                       WHERE Statut__c =:VIConstant.PERIODE_OUVERTE
                                     ORDER BY NAME LIMIT 1];
        VIInsertDataTest.VIInsertData_Achat();
        VIInsertDataTest.VIInsertData_Pointage();
        //VIInsertDataTest.VIInsertData_Avenant();
        VIInsertDataTest.VIInsertData_facture();        

        //VIAffaire__c aff = [SELECT Date_de_SAV_reelle__c from VIAffaire__c];
        //aff.Date_de_SAV_reelle__c = ListPeriode[0].date_de_fin__c;
        //update aff ; 
        
        testlb.CallBatchCalcTDBGazelle();        
    }    
    
    static testmethod void VILancementBatchController3_Test() {
        VIInsertDataTest.VIInsertData_EUR_Affaire();
        
        VILancementBatchController testlb = new VILancementBatchController (); 
        PageReference pageRef = Page.VILancementBatch;
        
        VICompte_general__c cc = new  VICompte_general__c  (name='7');
        insert cc ; 

        list<VIperiode__c>ListPeriode=[SELECT id,date_de_fin__c 
                                         FROM VIperiode__c 
                                       WHERE Statut__c =:VIConstant.PERIODE_OUVERTE
                                     ORDER BY NAME LIMIT 1];
        VIAffaire__c aff = [select id,Date_de_SAV_reelle__c from VIAffaire__c LIMIT 1] ;        
        VILigne_comptable__c Lc = new VILigne_comptable__c(Statut_ecriture_comptable__c=VIConstant.EC_BROUILLON,
                                                           CompteComptable_local__c = cc.id,
                                                           libelle__c=VIConstant.EC_CA_AVENCEMENT,
                                                           periode_comptable__c=ListPeriode[0].id,
                                                           affaire__c=aff.id);
        insert lc;
        testlb.EcrituresAEnvoyer='Avancement';
        testlb.Entite_bw=[SELECT entite_bw__c FROM VIEntiteBW__c LIMIT 1].entite_bw__c;
        
        testlb.callBatchEnvoiEcriture();        
    }    

    static testmethod void VILancementBatchController_batchCloture_Test() {
        VIInsertDataTest.VIInsertData_EUR_Affaire();
        
        VILancementBatchController testlb = new VILancementBatchController (); 
        PageReference pageRef = Page.VILancementBatch;

        testlb.Entite_bw=[SELECT entite_bw__c FROM VIEntiteBW__c LIMIT 1].entite_bw__c;
        
        testlb.getPeriodeEntite_bwOptions();
        testlb.entite_bw='1';
        testlb.callBatchCloture() ;
    }    

    static testmethod void VILancementBatchController_batchenvoiecriture_Test() {
        VIInsertDataTest.VIInsertData_EUR_Affaire();
        
        VILancementBatchController testlb = new VILancementBatchController (); 
        PageReference pageRef = Page.VILancementBatch;

        testlb.Entite_bw=[SELECT entite_bw__c FROM VIEntiteBW__c LIMIT 1].entite_bw__c;

        VIAffaire__c aff = [select id,entite_bw__c from VIAffaire__c limit 1];
        aff.entite_bw__c = '1';
        update aff; 
        
        VIperiode__c per_ouverte =[SELECT id,name
                                     FROM VIperiode__c 
                                    WHERE statut__c=:VIConstant.PERIODE_OUVERTE ];
       
        list<VICompte_general__c>ListCG = new list<VICompte_general__c>();
        listCG.add(new  VICompte_general__c  (name='903000'));        
        insert ListCG ; 
        
        VICompte_general__c cg = [select id from VICompte_general__c LIMIT 1];
        
        
        VILigne_comptable__c lc = new VILigne_comptable__c(affaire_de_rattachement__c=aff.id, 
                                                           Periode_comptable__c=per_ouverte.id,
                                                           statut_ecriture_comptable__c='20',
                                                           sens__c='D',
                                                           montant__c=1,
                                                           CompteComptable_local__c=cg.id,
                                                           libelle__c=VIConstant.EC_CA_AVENCEMENT, 
                                                           sous_chapitre__c='00-00');
        insert lc;
        
        testlb.getPeriodeEntite_bwOptions();
        testlb.EcrituresAEnvoyer='Avancement';
        testlb.entite_bw='1';
        testlb.callBatchEnvoiEcriture() ;
    }    

    static testmethod void VILancementBatchController_batchImportAffaire_Test() {
        VIInsertDataTest.VIInsertData_EUR_Affaire();
        
        VILancementBatchController testlb = new VILancementBatchController (); 
        PageReference pageRef = Page.VILancementBatch;

        testlb.Entite_bw=[SELECT entite_bw__c FROM VIEntiteBW__c LIMIT 1].entite_bw__c;
        
        testlb.getPeriodeEntite_bwOptions();
        testlb.entite_bw='1';
        testlb.callImportAffaire(); 
    }    


    static testmethod void VILancementBatchController_recalcul_Test() {
        VIInsertDataTest.VIInsertData_EUR_Affaire();
        VIInsertDataTest.VIInsertData_Pointage();
       
        VILancementBatchController testlb = new VILancementBatchController (); 
        PageReference pageRef = Page.VILancementBatch;

        testlb.Entite_bw=[SELECT entite_bw__c FROM VIEntiteBW__c LIMIT 1].entite_bw__c;
        
        testlb.getPeriodeEntite_bwOptions();
        testlb.entite_bw='1';
        testlb.date_minimum=system.today();
        testlb.date_maximum=system.today();
        
        testlb.callRecalcul();

    }    

    
}