force-app/main/default/objects/VIAffaire__c/VIAffaire__c.object-meta.xml
<CustomObject>
    <label>Affaire</label>
    <nameField>
        <label>Code Affaire</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Affaires</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VIAffaire__c/fields/Compte__c.field-meta.xml
<CustomField>
    <fullName>Compte__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Compte</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Affaires</relationshipLabel>
    <relationshipName>Affaires</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VIAffaire__c/fields/Date_de_SAV_reelle__c.field-meta.xml
<CustomField>
    <fullName>Date_de_SAV_reelle__c</fullName>
    <label>Date de SAV réelle</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VIAffaire__c/fields/Entite_BW__c.field-meta.xml
<CustomField>
    <fullName>Entite_BW__c</fullName>
    <label>Entité BW</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>EntiteBW</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/VIFacture__c/VIFacture__c.object-meta.xml
<CustomObject>
    <label>Facture</label>
    <nameField>
        <label>Nom de Facture</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Factures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VIFacture__c/fields/Affaire__c.field-meta.xml
<CustomField>
    <fullName>Affaire__c</fullName>
    <label>Affaire</label>
    <referenceTo>VIAffaire__c</referenceTo>
    <relationshipLabel>Factures</relationshipLabel>
    <relationshipName>Factures</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VIFacture__c/fields/BU__c.field-meta.xml
<CustomField>
    <fullName>BU__c</fullName>
    <formula>Affaire__r.Produit_SousDomaine__r.Code_BU__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>BU</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VIFacture__c/fields/Compte__c.field-meta.xml
<CustomField>
    <fullName>Compte__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Compte</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Factures</relationshipLabel>
    <relationshipName>Factures</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VIFacture__c/fields/Date_d_ouverture_d_affaire__c.field-meta.xml
<CustomField>
    <fullName>Date_d_ouverture_d_affaire__c</fullName>
    <formula>Affaire__r.Date_ouverture_affaire__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Date d&apos;ouverture d&apos;affaire</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VIFacture__c/fields/Date_de_comptabilisation__c.field-meta.xml
<CustomField>
    <fullName>Date_de_comptabilisation__c</fullName>
    <label>Date de comptabilisation</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VIFacture__c/fields/Date_de_SAV_reelle__c.field-meta.xml
<CustomField>
    <fullName>Date_de_SAV_reelle__c</fullName>
    <formula>Affaire__r.Date_de_SAV_reelle__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Date de SAV réelle</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VIFacture__c/fields/Facture_SAV_Comptabilisee__c.field-meta.xml
<CustomField>
    <fullName>Facture_SAV_Comptabilisee__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Indique que la ligne a été envoyée en comptabilité</inlineHelpText>
    <label>Facture SAV Comptabilisée</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VIFacture__c/fields/Facture_SAV_traitee__c.field-meta.xml
<CustomField>
    <fullName>Facture_SAV_traitee__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Facture SAV traitée</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VIFacture__c/fields/Montant_HT__c.field-meta.xml
<CustomField>
    <fullName>Montant_HT__c</fullName>
    <label>Montant HT</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VIFacture__c/fields/Sous_Domaine__c.field-meta.xml
<CustomField>
    <fullName>Sous_Domaine__c</fullName>
    <formula>Affaire__r.Produit_SousDomaine__r.Code_sous_domaine__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sous-Domaine</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VIPeriode__c/VIPeriode__c.object-meta.xml
<CustomObject>
    <label>Période comptable</label>
    <nameField>
        <label>Nom de Période</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Périodes comptables</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VIPeriode__c/fields/Date_de_fin__c.field-meta.xml
<CustomField>
    <fullName>Date_de_fin__c</fullName>
    <label>Date de fin</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VIPeriode__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Periode_comptable_statut</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/VIMajFactureSAVController.cls
public class VIMajFactureSAVController {

    public List<VIPeriode__c >ListPeriode { get; set; }

    Public List<VIFacture__c>ListFac {get; set;}
    Public List<VIFacture__c>ListFac1 {get; set;}
    public Map<string, ViAffaire__c> MapAffaire = new Map<string, ViAffaire__c>();
    Map<string, date>MapEntite_bw = new Map<string, date>();

    ApexPages.StandardSetController mycon;
       
    public VIMajFactureSAVController(ApexPages.StandardSetController mycon) {        
        this.MyCon = Mycon;        
        //Mycon.setPageSize(Mycon.getResultSize());
        ListFac=Mycon.getSelected();
        List<id>ListId = new List<id>();
        for(VIfacture__c fac:ListFac) {
            ListID.add(fac.id);
        }
        
        ListFac1 = new List<VIFacture__c>();
        for(VIFacture__c fac:[SELECT id, name, affaire__c, affaire__r.name, compte__r.name, bu__c,sous_domaine__c,
                                     Date_d_ouverture_d_affaire__c ,Date_de_SAV_reelle__c ,
                                     date__c, date_de_comptabilisation__c, montant_ht__c, Facture_SAV_traitee__c , Facture_SAV_Comptabilisee__c 
                                FROM VIFacture__c
                               WHERE id in : ListID]) {
            fac.Facture_SAV_traitee__c=true;                                                    
            Listfac1.add(fac);
       }
                
        for(VIPeriode__c per:[SELECT id, entite_bw__c, date_de_fin__c 
                                 FROM VIPeriode__c
                                WHERE Statut__c=:VIConstant.PERIODE_OUVERTE]) {
            MapEntite_bw.put(per.entite_bw__c,per.date_de_fin__c) ;
        }
        ListPeriode=[SELECT Tolabel(entite_bw__c), date_de_fin__c FROM VIperiode__c WHERE Statut__c=:VIConstant.PERIODE_OUVERTE ORDER BY entite_bw__c];        
        
    }       

    public PageReference  Enregistrer() {
        for(VIFacture__c fac:listfac1) {
            if(fac.Facture_SAV_Comptabilisee__c)
                fac.Facture_SAV_traitee__c=true;                                                    
        }
        
        update listfac1;
        if(!Test.isRunningTest() )
            Database.executeBatch(new VIBatchGenerateFactSAV('', '1'),VIBatchGenerateFactSAV.NBR_LOT);
        
        return mycon.cancel();
    }

}