force-app/main/default/objects/VICentralisation__c/VICentralisation__c.object-meta.xml
<CustomObject>
    <label>Centralisation</label>
    <nameField>
        <label>Nom de Centralisation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Centralisation</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VICentralisation__c/fields/Compte__c.field-meta.xml
<CustomField>
    <fullName>Compte__c</fullName>
    <label>Compte</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VICentralisation__c/fields/PR_PV__c.field-meta.xml
<CustomField>
    <fullName>PR_PV__c</fullName>
    <label>PR PV</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VICompte_general__c/VICompte_general__c.object-meta.xml
<CustomObject>
    <label>Compte général</label>
    <nameField>
        <label>Nom de Compte général</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Comptes généraux</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VICompte_general__c/fields/Alimentation_PR_PV__c.field-meta.xml
<CustomField>
    <fullName>Alimentation_PR_PV__c</fullName>
    <label>Alimentation PR/PV</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VILigne_comptable__c/VILigne_comptable__c.object-meta.xml
<CustomObject>
    <label>Ligne comptable</label>
    <nameField>
        <displayFormat>L{000000000}</displayFormat>
        <label>Ref de la ligne comptable</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lignes comptables</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VILigne_comptable__c/fields/Affaire__c.field-meta.xml
<CustomField>
    <fullName>Affaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Affaire</label>
    <referenceTo>VIAffaire__c</referenceTo>
    <relationshipLabel>Lignes comptables (Affaire)</relationshipLabel>
    <relationshipName>Ecritures_comptables</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VILigne_comptable__c/fields/Centre__c.field-meta.xml
<CustomField>
    <fullName>Centre__c</fullName>
    <label>Centre</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VILigne_comptable__c/fields/CompteComptable_local__c.field-meta.xml
<CustomField>
    <fullName>CompteComptable_local__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Compte comptable local</label>
    <referenceTo>VICompte_general__c</referenceTo>
    <relationshipLabel>Lignes comptables</relationshipLabel>
    <relationshipName>Lignes_comptables</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VILigne_comptable__c/fields/Date_ecriture__c.field-meta.xml
<CustomField>
    <fullName>Date_ecriture__c</fullName>
    <label>Date écriture</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VILigne_comptable__c/fields/Montant__c.field-meta.xml
<CustomField>
    <fullName>Montant__c</fullName>
    <label>Montant</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VILigne_comptable__c/fields/Montant_avec_signe__c.field-meta.xml
<CustomField>
    <fullName>Montant_avec_signe__c</fullName>
    <formula>if( text(Sens__c) =&apos;C&apos;, Montant__c * (-1) , Montant__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Montant avec signe</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VILigne_comptable__c/fields/Periode_comptable__c.field-meta.xml
<CustomField>
    <fullName>Periode_comptable__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Période comptable</label>
    <referenceTo>VIPeriode__c</referenceTo>
    <relationshipName>Ecritures_comptables</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VILigne_comptable__c/fields/Statut_ecriture_comptable__c.field-meta.xml
<CustomField>
    <fullName>Statut_ecriture_comptable__c</fullName>
    <defaultValue>&apos;10&apos;</defaultValue>
    <label>Statut écriture comptable</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Statut_ecriture_comptable</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/VILigne_comptable__c/fields/Type_de_depense__c.field-meta.xml
<CustomField>
    <fullName>Type_de_depense__c</fullName>
    <label>Type de dépense</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VIPeriode__c/VIPeriode__c.object-meta.xml
<CustomObject>
    <label>Période comptable</label>
    <nameField>
        <label>Nom de Période</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Périodes comptables</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VIPeriode__c/fields/Date_de_debut__c.field-meta.xml
<CustomField>
    <fullName>Date_de_debut__c</fullName>
    <label>Date de début</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VIPeriode__c/fields/Date_de_fin__c.field-meta.xml
<CustomField>
    <fullName>Date_de_fin__c</fullName>
    <label>Date de fin</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VIPeriode__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Periode_comptable_statut</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/VISchedGenereCentralis1.cls
/*
*
*  Calculation of centralisation  
*
*
*  for running by hand : 
 VISchedGenereCentralis1 v = new VISchedGenereCentralis1();
 v.execute(null);
*
*  for running every day at xx:22
     VISchedGenereCentralis1 m = new VISchedGenereCentralis1();
     String sch = '0 0 22 * * ?';
     String jobID = system.schedule('VISchedGenereCentralis1', sch, m);
*
*
*/
global class VISchedGenereCentralis1 implements Schedulable,Database.Batchable<sObject>,Database.Stateful{

    Global double num_record = 0;
    Global String IDLog ='';   
    Global String entite_bw ='';
    Global Map<String, double>MapTotalDerniere = new Map<String, double>();
    Global Map<String, double>MapTotalOuverte = new Map<String, double>();
    Global Map<String, double>MapTotalPreOuverte = new Map<String, double>();    
    private VIPeriode__c Periode_derniere ;
    private VIPeriode__c Periode_Ouverte ;    
    private VIPeriode__c Periode_PreOuverte ;    
    
    Private Map<string, VICompte_general__c>MapCompte    = new Map<string, VICompte_general__c>();    
    
     
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        IDLog=VIUtils.LogWrite('VISchedGenereCentralis1','4 Running','','Start ');
        entite_bw='1';

        for(VICompte_general__c compte : [SELECT id, name , Alimentation_PR_PV__c 
                                            FROM  VICompte_general__c]) {
            MapCompte.put(compte.name, compte) ;
        }
        
        Periode_PreOuverte= [SELECT id,date_de_debut__c, date_de_fin__c, entite_bw__c
                            FROM VIPeriode__c
                           WHERE statut__c=:VIConstant.PERIODE_PREOUVERTE
                             AND entite_bw__c=:entite_bw];
        Periode_Ouverte= [SELECT id,date_de_debut__c, date_de_fin__c, entite_bw__c
                            FROM VIPeriode__c
                           WHERE statut__c=:VIConstant.PERIODE_OUVERTE
                             AND entite_bw__c=:entite_bw];
        Periode_derniere= [SELECT id,date_de_debut__c, date_de_fin__c, entite_bw__c
                            FROM VIPeriode__c
                           WHERE statut__c=:VIConstant.PERIODE_DERNIERE
                             AND entite_bw__c=:entite_bw];
        // le temps de tester 
/*        Periode_derniere= [SELECT id,date_de_debut__c, date_de_fin__c, entite_bw__c
                            FROM VIPeriode__c
                           WHERE name='202105BW FRA'
                             AND entite_bw__c=:entite_bw];
*/
        delete [select id from VICentralisation__c where source__c='VisionLC' and date__c=:Periode_Preouverte.date_de_debut__c];        
        delete [select id from VICentralisation__c where source__c='VisionLC' and date__c=:Periode_ouverte.date_de_debut__c];
        delete [select id from VICentralisation__c where source__c='VisionLC' and date__c=:Periode_derniere.date_de_debut__c];
        
        string query = 'SELECT Affaire__c ,Centre__c ,CompteComptable_local__r.name, Date_ecriture__c ,Montant_avec_signe__c , ';
        query = query+'        Periode_comptable__c     ';
        query = query+'   FROM VILigne_comptable__c  ';
        query = query+'  WHERE (Periode_comptable__c =\''+Periode_PreOuverte.id+'\' or Periode_comptable__c =\''+Periode_Ouverte.id+'\' or Periode_comptable__c =\''+Periode_derniere.id+'\') ';
        query = query+'    and Statut_ecriture_comptable__c in ( \'40\') ';   //\'10\',\'20\', \'30\',
        //query = query+'        and type_de_depense__c in ( \'AVT\') '; 
        if(!Test.isRunningTest())
            query = query+'    and CompteComptable_local__r.name!=\'473000\'  ';
        query = query+'   Order by Affaire__c asc  ';     

        system.debug(query);
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<VILigne_comptable__c > scope){

        for(VILigne_comptable__c lc:scope) {
            if(lc.Date_ecriture__c>=Periode_Derniere.date_de_debut__c && lc.Date_ecriture__c<=Periode_Derniere.date_de_fin__c) {
                if(!MapTotalDerniere.containskey(lc.CompteComptable_local__r.name)) {
                    MapTotalDerniere.put(lc.CompteComptable_local__r.name,0);
                }
                MapTotalDerniere.put(lc.CompteComptable_local__r.name,MapTotalDerniere.get(lc.CompteComptable_local__r.name) + lc.Montant_avec_signe__c) ;             
            }
            if(lc.Date_ecriture__c>=Periode_Ouverte.date_de_debut__c && lc.Date_ecriture__c<=Periode_Ouverte.date_de_fin__c) {
                if(!MapTotalOuverte.containskey(lc.CompteComptable_local__r.name)) {
                    MapTotalOuverte.put(lc.CompteComptable_local__r.name,0);
                }
                MapTotalOuverte.put(lc.CompteComptable_local__r.name,MapTotalOuverte.get(lc.CompteComptable_local__r.name) + lc.Montant_avec_signe__c) ;             
            }
            if(lc.Date_ecriture__c>=Periode_PreOuverte.date_de_debut__c && lc.Date_ecriture__c<=Periode_PreOuverte.date_de_fin__c) {
                if(!MapTotalPreOuverte.containskey(lc.CompteComptable_local__r.name)) {
                    MapTotalPreOuverte.put(lc.CompteComptable_local__r.name,0);
                }
                MapTotalPreOuverte.put(lc.CompteComptable_local__r.name,MapTotalPreOuverte.get(lc.CompteComptable_local__r.name) + lc.Montant_avec_signe__c) ;             
            }
        }
    }

    global void finish(Database.BatchableContext BC){
        list< VICentralisation__c >ListInsertCentralisation = new list< VICentralisation__c >();
        for(string s:MapTotalDerniere.keyset()) {
            
             string PRPV='' ;
             if(MapCompte.containskey(s)) {
                PRPV=MapCompte.get(s).Alimentation_PR_PV__c ;
             }
             double sens = - 1;
             if(PRPV=='PV')
                 sens=1; 

             VICentralisation__c c = new VICentralisation__c (
                 compte__c=s ,
                 PR_PV__c =PRPV,
                 date__c=periode_derniere.date_de_debut__c,
                 montant__c=MapTotalDerniere.get(s) * sens,
                 source__c='VisionLC'
             );
            ListInsertCentralisation.add(c);
        }
        for(string s:MapTotalOuverte.keyset()) {
             string PRPV='' ;
             if(MapCompte.containskey(s)) {
                PRPV=MapCompte.get(s).Alimentation_PR_PV__c ;
             }
             double sens = - 1;
             if(PRPV=='PV')
                 sens=1; 
            
             VICentralisation__c c = new VICentralisation__c (
                 compte__c=s ,
                 PR_PV__c =PRPV,                 
                 date__c=periode_ouverte.date_de_debut__c,
                 montant__c=MapTotalOuverte.get(s) * sens,
                 source__c='VisionLC'
             );
            ListInsertCentralisation.add(c);
        }
        for(string s:MapTotalPreOuverte.keyset()) {
             string PRPV='' ;
             if(MapCompte.containskey(s)) {
                PRPV=MapCompte.get(s).Alimentation_PR_PV__c ;
             }
             double sens = - 1;
             if(PRPV=='PV')
                 sens=1; 
            
             VICentralisation__c c = new VICentralisation__c (
                 compte__c=s ,
                 PR_PV__c =PRPV,                 
                 date__c=periode_Preouverte.date_de_debut__c,
                 montant__c=MapTotalpreOuverte.get(s) * sens,
                 source__c='VisionLC'
             );
            ListInsertCentralisation.add(c);
        }
        insert ListInsertCentralisation ; 
        
        
        
        IDLog=VIUtils.LogWrite('VISchedGenereCentralis1','1 Normal',IDLog,'End '+num_record);
        Database.executeBatch(new VISchedGenereCentralis2(),VISchedGenereCentralis2.NBR_LOT()); 
    }

    global void execute(SchedulableContext scon) {
        Database.executeBatch(new VISchedGenereCentralis1(),NBR_LOT()); // Il faut laisser 1 pour la 1ère fois
    }
    public static  integer NBR_LOT () {
         integer i=500 ; 
         return i;
    }

    
    
}