force-app/main/default/objects/VICentralisation__c/VICentralisation__c.object-meta.xml
<CustomObject>
    <label>Centralisation</label>
    <nameField>
        <label>Nom de Centralisation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Centralisation</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VICentralisation__c/fields/Compte__c.field-meta.xml
<CustomField>
    <fullName>Compte__c</fullName>
    <label>Compte</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VICentralisation__c/fields/PR_PV__c.field-meta.xml
<CustomField>
    <fullName>PR_PV__c</fullName>
    <label>PR PV</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VIPeriode__c/VIPeriode__c.object-meta.xml
<CustomObject>
    <label>Période comptable</label>
    <nameField>
        <label>Nom de Période</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Périodes comptables</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VIPeriode__c/fields/Date_de_debut__c.field-meta.xml
<CustomField>
    <fullName>Date_de_debut__c</fullName>
    <label>Date de début</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VIPeriode__c/fields/Date_de_fin__c.field-meta.xml
<CustomField>
    <fullName>Date_de_fin__c</fullName>
    <label>Date de fin</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VIPeriode__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Periode_comptable_statut</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/VIPointage__c/VIPointage__c.object-meta.xml
<CustomObject>
    <label>Pointage</label>
    <nameField>
        <displayFormat>P{000000000}</displayFormat>
        <label>Ref de Pointage</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pointages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VIPointage__c/fields/Affaire__c.field-meta.xml
<CustomField>
    <fullName>Affaire__c</fullName>
    <label>Affaire</label>
    <referenceTo>VIAffaire__c</referenceTo>
    <relationshipLabel>Pointages</relationshipLabel>
    <relationshipName>Pointages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VIPointage__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Date Pointage</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VIPointage__c/fields/Debours__c.field-meta.xml
<CustomField>
    <fullName>Debours__c</fullName>
    <label>Debours</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VIPointage__c/fields/Heures__c.field-meta.xml
<CustomField>
    <fullName>Heures__c</fullName>
    <label>Heures</label>
    <precision>4</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VIPointage__c/fields/Periode_comptable__c.field-meta.xml
<CustomField>
    <fullName>Periode_comptable__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Période comptable</label>
    <referenceTo>VIPeriode__c</referenceTo>
    <relationshipLabel>Pointages</relationshipLabel>
    <relationshipName>Pointages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/VISchedGenereCentralis5.cls
/*
*
*  Calculation of centralisation 
*
*
*  for running by hand : 
 VISchedGenereCentralis5 v = new VISchedGenereCentralis5();
 v.execute(null);
*
*  for running every day at xx:22
     VISchedGenereCentralis5 m = new VISchedGenereCentralis5();
     String sch = '0 0 22 * * ?';
     String jobID = system.schedule('VISchedGenereCentralis5', sch, m);
*
*
*/
global class VISchedGenereCentralis5 implements Schedulable,Database.Batchable<sObject>,Database.Stateful{

    Global double num_record = 0;
    Global String IDLog ='';   
    Global String entite_bw ='';
    Global Map<date, double>MapTotalPreOuverteHeure = new Map<date, double>();
    Global Map<date, double>MapTotalPreOuverteDebours = new Map<date, double>();
    Global Map<date, double>MapTotalOuverteHeure = new Map<date, double>();
    Global Map<date, double>MapTotalOuverteDebours = new Map<date, double>();
    Global Map<date, double>MapTotalDerniereHeure = new Map<date, double>();
    Global Map<date, double>MapTotalDerniereDebours = new Map<date, double>();
    private VIPeriode__c Periode_PreOuverte ;
    private VIPeriode__c Periode_Ouverte ;
    private VIPeriode__c Periode_derniere ;
    
    
     
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        IDLog=VIUtils.LogWrite('VISchedGenereCentralis5','4 Running','','Start ');
        entite_bw='1';

        
        Periode_PreOuverte= [SELECT id,date_de_debut__c, date_de_fin__c, entite_bw__c
                            FROM VIPeriode__c
                           WHERE statut__c=:VIConstant.PERIODE_PREOUVERTE
                             AND entite_bw__c=:entite_bw];
        Periode_Ouverte= [SELECT id,date_de_debut__c, date_de_fin__c, entite_bw__c
                            FROM VIPeriode__c
                           WHERE statut__c=:VIConstant.PERIODE_OUVERTE
                             AND entite_bw__c=:entite_bw];
        Periode_derniere= [SELECT id,date_de_debut__c, date_de_fin__c, entite_bw__c
                            FROM VIPeriode__c
                           WHERE statut__c=:VIConstant.PERIODE_DERNIERE
                             AND entite_bw__c=:entite_bw];
        
        delete [select id from VICentralisation__c where source__c='VisionHeures' and date__c=:Periode_PreOuverte.date_de_debut__c];
        delete [select id from VICentralisation__c where source__c='VisionHeuresMontant' and date__c=:Periode_PreOuverte.date_de_debut__c];        
        delete [select id from VICentralisation__c where source__c='VisionHeures' and date__c=:Periode_Ouverte.date_de_debut__c];
        delete [select id from VICentralisation__c where source__c='VisionHeuresMontant' and date__c=:Periode_Ouverte.date_de_debut__c];        
        delete [select id from VICentralisation__c where source__c='VisionHeures' and date__c=:Periode_derniere.date_de_debut__c];
        delete [select id from VICentralisation__c where source__c='VisionHeuresMontant' and date__c=:Periode_derniere.date_de_debut__c];        
        
        string query = 'SELECT Affaire__c ,Date__c , Heures__c ,debours__c  , ';
        query = query+'        Periode_comptable__c,Periode_comptable__r.date_de_debut__c     ';
        query = query+'   FROM VIpointage__c  ';
        query = query+'  WHERE (Periode_comptable__c =\''+Periode_PreOuverte.id+'\' or Periode_comptable__c =\''+Periode_Ouverte.id+'\' or Periode_comptable__c =\''+Periode_derniere.id+'\') ';
        query = query+'   Order by Affaire__c asc  ';     

        system.debug(query);
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<VIpointage__c > scope){

        for(VIpointage__c po:scope) {
            if(po.Periode_comptable__c==Periode_Derniere.id ) {
                if(!MapTotalDerniereHeure.containskey(po.Periode_comptable__r.date_de_debut__c)) {
                    MapTotalDerniereHeure.put(po.Periode_comptable__r.date_de_debut__c,0);
                    MapTotalDerniereDebours.put(po.Periode_comptable__r.date_de_debut__c,0);                
                }
                MapTotalDerniereHeure.put(po.Periode_comptable__r.date_de_debut__c,MapTotalDerniereHeure.get(po.Periode_comptable__r.date_de_debut__c) + (po.heures__c==null ? 0 :po.heures__c)  );
                MapTotalDerniereDebours.put(po.Periode_comptable__r.date_de_debut__c,MapTotalDerniereDebours.get(po.Periode_comptable__r.date_de_debut__c) + (po.debours__c==null ? 0 :po.debours__c) );            
            }
            if(po.Periode_comptable__c==Periode_ouverte.id ) {
                if(!MapTotalouverteHeure.containskey(po.Periode_comptable__r.date_de_debut__c)) {
                    MapTotalouverteHeure.put(po.Periode_comptable__r.date_de_debut__c,0);
                    MapTotalouverteDebours.put(po.Periode_comptable__r.date_de_debut__c,0);                
                }
                MapTotalouverteHeure.put(po.Periode_comptable__r.date_de_debut__c,MapTotalouverteHeure.get(po.Periode_comptable__r.date_de_debut__c) + (po.heures__c==null ? 0 :po.heures__c)  );
                MapTotalouverteDebours.put(po.Periode_comptable__r.date_de_debut__c,MapTotalouverteDebours.get(po.Periode_comptable__r.date_de_debut__c) + (po.debours__c==null ? 0 :po.debours__c) );            
            }
            if(po.Periode_comptable__c==Periode_Preouverte.id ) {
                if(!MapTotalPreouverteHeure.containskey(po.Periode_comptable__r.date_de_debut__c)) {
                    MapTotalPreouverteHeure.put(po.Periode_comptable__r.date_de_debut__c,0);
                    MapTotalPreouverteDebours.put(po.Periode_comptable__r.date_de_debut__c,0);                
                }
                MapTotalPreouverteHeure.put(po.Periode_comptable__r.date_de_debut__c,MapTotalPreouverteHeure.get(po.Periode_comptable__r.date_de_debut__c) + (po.heures__c==null ? 0 :po.heures__c)  );
                MapTotalPreouverteDebours.put(po.Periode_comptable__r.date_de_debut__c,MapTotalPreouverteDebours.get(po.Periode_comptable__r.date_de_debut__c) + (po.debours__c==null ? 0 :po.debours__c) );            
            }
        }

    }

    global void finish(Database.BatchableContext BC){
        list< VICentralisation__c >ListInsertCentralisation = new list< VICentralisation__c >();
        for(date d:MapTotalDerniereHeure.keyset()) {
            
             VICentralisation__c c = new VICentralisation__c (
                 compte__c=null ,
                 PR_PV__c =null,
                 date__c=d,
                 montant__c=MapTotalDerniereHeure.get(d) *(-1),
                 source__c='VisionHeures'
             );
            ListInsertCentralisation.add(c);

            VICentralisation__c c1 = new VICentralisation__c (
                 compte__c=null ,
                 PR_PV__c =null,
                 date__c=d,
                 montant__c=MapTotalDerniereDebours.get(d) ,
                 source__c='VisionHeuresMontant'
             );
            //ListInsertCentralisation.add(c1);
        }
        for(date d:MapTotalOuverteHeure.keyset()) {
            
             VICentralisation__c c = new VICentralisation__c (
                 compte__c=null ,
                 PR_PV__c =null,
                 date__c=d,
                 montant__c=MapTotalOuverteHeure.get(d) *(-1),
                 source__c='VisionHeures'
             );
            ListInsertCentralisation.add(c);

            VICentralisation__c c1 = new VICentralisation__c (
                 compte__c=null ,
                 PR_PV__c =null,
                 date__c=d,
                 montant__c=MapTotalOuverteDebours.get(d),
                 source__c='VisionHeuresMontant'
             );
            //ListInsertCentralisation.add(c1);
        }
        for(date d:MapTotalPreOuverteHeure.keyset()) {
            
             VICentralisation__c c = new VICentralisation__c (
                 compte__c=null ,
                 PR_PV__c =null,
                 date__c=d,
                 montant__c=MapTotalPreOuverteHeure.get(d) *(-1),
                 source__c='VisionHeures'
             );
            ListInsertCentralisation.add(c);

            VICentralisation__c c1 = new VICentralisation__c (
                 compte__c=null ,
                 PR_PV__c =null,
                 date__c=d,
                 montant__c=MapTotalPreOuverteDebours.get(d),
                 source__c='VisionHeuresMontant'
             );
            //ListInsertCentralisation.add(c1);
        }
        insert ListInsertCentralisation ; 
                
        IDLog=VIUtils.LogWrite('VISchedGenereCentralis5','1 Normal',IDLog,'End '+num_record);
       // Database.executeBatch(new VIBatchCalcTDBGazelle('1'),VIBatchCalcTDBGazelle.NBR_LOT ) ; //VIBatchCalcTDBGazelle.NBR_LOT()); 
        
    }

    global void execute(SchedulableContext scon) {
        Database.executeBatch(new VISchedGenereCentralis5(),NBR_LOT());
    }
    public static  integer NBR_LOT () {
         integer i=500 ; 
         return i;
    }

    
    
}