force-app/main/default/objects/VILigne_affaire__c/VILigne_affaire__c.object-meta.xml
<CustomObject>
    <label>Ligne d&apos;affaire</label>
    <nameField>
        <displayFormat>L{000000000}</displayFormat>
        <label>Ref de Ligne d&apos;affaire</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lignes d&apos;affaire</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VILigne_affaire__c/fields/Ligne_d_affaire_mensuelle__c.field-meta.xml
<CustomField>
    <fullName>Ligne_d_affaire_mensuelle__c</fullName>
    <label>Ligne d&apos;affaire mensuelle</label>
    <referenceTo>VILigne_d_affaire_mensuelle__c</referenceTo>
    <relationshipLabel>Lignes d&apos;affaire</relationshipLabel>
    <relationshipName>Lignes_d_affaire</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/VILigne_d_affaire_mensuelle__c.object-meta.xml
<CustomObject>
    <label>Ligne d&apos;affaire mensuelle</label>
    <nameField>
        <label>Ref de Ligne d&apos;affaire mensuelle</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lignes d&apos;affaire mensuelles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/Periode_comptable__c.field-meta.xml
<CustomField>
    <fullName>Periode_comptable__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Période comptable</label>
    <referenceTo>VIPeriode__c</referenceTo>
    <relationshipLabel>Lignes d&apos;affaire mensuelles</relationshipLabel>
    <relationshipName>Lignes_d_affaire_mensuelles</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VIPeriode__c/VIPeriode__c.object-meta.xml
<CustomObject>
    <label>Période comptable</label>
    <nameField>
        <label>Nom de Période</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Périodes comptables</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/VIBatchReCalcLA.cls
//
//   This batch recalculate the Currency Value of each line
//  
//  
// 
global class VIBatchReCalcLA implements Database.Batchable<sObject>, Database.Stateful {

    private Date   DateDateMinimum;
    private Date   DateDateMaximum;
    Public Integer num_record = 0; 
    Global String IDLog ='';    

    public VIBatchReCalcLA(date DateParam2 ,date  DateParam3) {
        DateDateMinimum = DateParam2;        
        DateDateMaximum = DateParam3;                
    }

    global Database.QueryLocator start(Database.BatchableContext BC) {
        String     query='SELECT Id ';
        query = query + '   FROM VILigne_affaire__c  ';
        query = query + '  WHERE Ligne_d_affaire_mensuelle__r.periode_comptable__r.date_de_debut__c>='+string.valueof(DateDateMinimum) ;
        query = query + '    AND Ligne_d_affaire_mensuelle__r.periode_comptable__r.date_de_debut__c<='+string.valueof(DateDateMaximum) ;
        
        IDLog=VIUtils.LogWrite('VIBatchReCalcLA','4 Running','','Start ');
        
        
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<VILigne_affaire__c> scope) {
        // Let's handle the VILigne_affaire__c Table 
        // Ok I know, it's not good to put an update in a loop, but we are not suppose to have a big number of lines
        for(VILigne_affaire__c la:scope) {
             update la  ;
        }
        num_record = num_record + scope.size();
    }   

    global void finish(Database.BatchableContext BC) {
        IDLog=VIUtils.LogWrite('VIBatchReCalcLA','1 Normal',IDLog,'nbr '+num_record);            
    }
}