force-app/main/default/objects/Quote/fields/DEV_TypeDeDevis__c.field-meta.xml
<CustomField>
    <fullName>DEV_TypeDeDevis__c</fullName>
    <label>Type de devis</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Devis SF</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Devis ERP</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Devis Hors-Système</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/Tech_Talend_Export_Devis__c.field-meta.xml
<CustomField>
    <fullName>Tech_Talend_Export_Devis__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Si cette case est cochée &gt;&gt; Export vers Talend</description>
    <label>Tech_Talend_Export_Devis</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AP01_Account.cls
public class AP01_Account{
 
  public static void updateTechTalendExportDevis(List<Account> newAccounts)
      {
      
        Set<Id> accountset = new Set<Id>();
        
     
        for (Account acc : newAccounts) {
          accountset.add(acc.Id); 
        }
       
        //list <Quote> ListQuotes = new List <Quote>();
      Opportunity [] ListOpportunites=new Opportunity[]{};  
      Quote [] ListQuotes=new Quote[]{};
      Quote [] ListQuotesToUpdate=new Quote[]{};    
        

       
        
        map <Id, Account> mapAccountToOpportunities = 
        new map <Id, Account>([Select Id, 
                                   (Select Id
                                   From Opportunities where (StageName = 'Fermée Gagnée'))
                              From Account
                              where Id in :accountset]); 

       system.debug ('mapAccountToOpportunities :'+ mapAccountToOpportunities );
       
       
        map <Id, Opportunity> mapOpportunityToQuotes = 
        new map <Id, Opportunity>([Select Id, (Select Tech_Talend_Export_Devis__c 
        From Quotes where (Tech_Talend_Export_Devis__c = False AND Status = '3' AND (DEV_TypeDeDevis__c = '1' OR DEV_TypeDeDevis__c = '3'))) 
        From Opportunity where (StageName = 'Fermée Gagnée' AND AccountId in :newAccounts)]);
       system.debug ('mapOpportunityToQuotes:'+ mapOpportunityToQuotes);
            
    
      if (mapAccountToOpportunities.values().size()>0) {
       system.debug ('mapAccountToOpportunities.values():'+ mapAccountToOpportunities.values());
       
        for(Account acc : mapAccountToOpportunities.values()) {
         ListOpportunites = acc.Opportunities;
          system.debug ('ListOpportunites :'+ ListOpportunites);
           
       
         for(Opportunity opp : ListOpportunites ) {
         Opportunity oppEncours = mapOpportunityToQuotes.get(opp.Id);
         
           ListQuotes = oppEncours.Quotes;
           system.debug ('ListQuotes :'+ ListQuotes );
           
            for (Quote qu : ListQuotes) 
            {
             qu.Tech_Talend_Export_Devis__c = True;
             system.debug ('qu.Tech_Talend_Export_Devis__c:'+ qu.Tech_Talend_Export_Devis__c);
             ListQuotesToUpdate.add(qu);
           }
         } 
        }
     
       }
       if (ListQuotesToUpdate.size() >0) {     
       update ListQuotesToUpdate;  
        }
      }
   }