force-app/main/default/objects/Order/fields/ORD_Code_Agence_Regionale_BW__c.field-meta.xml
<CustomField>
    <fullName>ORD_Code_Agence_Regionale_BW__c</fullName>
    <label>Code Agence Régionale BW</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/ORD_Code_Secteur_Commercial__c.field-meta.xml
<CustomField>
    <fullName>ORD_Code_Secteur_Commercial__c</fullName>
    <label>Code Secteur Commercial</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VIAffaire__c/VIAffaire__c.object-meta.xml
<CustomObject>
    <label>Affaire</label>
    <nameField>
        <label>Code Affaire</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Affaires</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VIAffaire__c/fields/Date_de_fin_de_garantie__c.field-meta.xml
<CustomField>
    <fullName>Date_de_fin_de_garantie__c</fullName>
    <formula>if(!isnull(Date_de_SAV_reelle__c) , 
     ADDMONTHS( Date_de_SAV_reelle__c, Produit_SousDomaine__r.Duree_garantie__c  ),
     null)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Date de fin de garantie</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VIAffaire__c/fields/Date_de_SAV_previsionnelle__c.field-meta.xml
<CustomField>
    <fullName>Date_de_SAV_previsionnelle__c</fullName>
    <label>Date de SAV prévisionnelle</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VIAffaire__c/fields/Date_de_SAV_reelle__c.field-meta.xml
<CustomField>
    <fullName>Date_de_SAV_reelle__c</fullName>
    <label>Date de SAV réelle</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VIAffaire__c/fields/Date_max_mouvement__c.field-meta.xml
<CustomField>
    <fullName>Date_max_mouvement__c</fullName>
    <label>Date max mouvement</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VIAffaire__c/fields/Date_ouverture_affaire__c.field-meta.xml
<CustomField>
    <fullName>Date_ouverture_affaire__c</fullName>
    <label>Date d&apos;ouverture d&apos;affaire</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VIAffaire__c/fields/Entite_BW__c.field-meta.xml
<CustomField>
    <fullName>Entite_BW__c</fullName>
    <label>Entité BW</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>EntiteBW</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/VIAffaire__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Commande</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Affaires</relationshipLabel>
    <relationshipName>Affaires</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VIEntiteBW__c/VIEntiteBW__c.object-meta.xml
<CustomObject>
    <label>EntiteBW</label>
    <nameField>
        <label>Nom de l&apos;EntiteBW</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EntiteBW</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VIEntiteBW__c/fields/Entite_BW__c.field-meta.xml
<CustomField>
    <fullName>Entite_BW__c</fullName>
    <label>Entité BW</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>EntiteBW</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/VILigne_d_affaire_mensuelle__c.object-meta.xml
<CustomObject>
    <label>Ligne d&apos;affaire mensuelle</label>
    <nameField>
        <label>Ref de Ligne d&apos;affaire mensuelle</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lignes d&apos;affaire mensuelles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/Affaire__c.field-meta.xml
<CustomField>
    <fullName>Affaire__c</fullName>
    <label>Affaire</label>
    <referenceTo>VIAffaire__c</referenceTo>
    <relationshipLabel>Lignes d&apos;affaire mensuelles</relationshipLabel>
    <relationshipName>Lignes_d_affaire_mensuelles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/Date_de_fin_de_garantie__c.field-meta.xml
<CustomField>
    <fullName>Date_de_fin_de_garantie__c</fullName>
    <formula>Affaire__r.Date_de_fin_de_garantie__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Date de fin de garantie</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/Date_de_SAV_previsionnelle__c.field-meta.xml
<CustomField>
    <fullName>Date_de_SAV_previsionnelle__c</fullName>
    <formula>Affaire__r.Date_de_SAV_previsionnelle__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Date de SAV prévisionnelle</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/Devis_Heure__c.field-meta.xml
<CustomField>
    <fullName>Devis_Heure__c</fullName>
    <label>Devis - Heure</label>
    <precision>6</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/Devis_MontantI__c.field-meta.xml
<CustomField>
    <fullName>Devis_MontantI__c</fullName>
    <label>Devis - MontantI</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/Dont_comptabiliseC__c.field-meta.xml
<CustomField>
    <fullName>Dont_comptabiliseC__c</fullName>
    <label>Dont comptabiliséC</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/Dont_comptabiliseC_E__c.field-meta.xml
<CustomField>
    <fullName>Dont_comptabiliseC_E__c</fullName>
    <label>Dont comptabiliséC	€</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/Dont_comptabiliseD__c.field-meta.xml
<CustomField>
    <fullName>Dont_comptabiliseD__c</fullName>
    <label>Dont comptabiliséD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/Dont_comptabiliseI__c.field-meta.xml
<CustomField>
    <fullName>Dont_comptabiliseI__c</fullName>
    <label>Dont comptabiliséI</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/Dont_comptabiliseI_E__c.field-meta.xml
<CustomField>
    <fullName>Dont_comptabiliseI_E__c</fullName>
    <label>Dont comptabiliséI €</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/Ecart_C_A_F_MontantC__c.field-meta.xml
<CustomField>
    <fullName>Ecart_C_A_F_MontantC__c</fullName>
    <label>Ecart C.A.F - MontantC</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/Ecart_C_A_F_MontantC_E__c.field-meta.xml
<CustomField>
    <fullName>Ecart_C_A_F_MontantC_E__c</fullName>
    <label>Ecart C.A.F - MontantC €</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/Ecart_C_A_F_MontantD_E__c.field-meta.xml
<CustomField>
    <fullName>Ecart_C_A_F_MontantD_E__c</fullName>
    <label>Ecart C.A.F - MontantD €</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/Ecart_C_A_F_MontantI__c.field-meta.xml
<CustomField>
    <fullName>Ecart_C_A_F_MontantI__c</fullName>
    <label>Ecart C.A.F - MontantI</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/Ecart_C_A_F_MontantI_E__c.field-meta.xml
<CustomField>
    <fullName>Ecart_C_A_F_MontantI_E__c</fullName>
    <label>Ecart C.A.F - MontantI €</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/Engage_brut_arrete_Heure__c.field-meta.xml
<CustomField>
    <fullName>Engage_brut_arrete_Heure__c</fullName>
    <label>Engagé brut à l&apos;arrêté - Heure</label>
    <precision>8</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/Engage_brut_arrete_MontantC__c.field-meta.xml
<CustomField>
    <fullName>Engage_brut_arrete_MontantC__c</fullName>
    <label>Engagé brut à l&apos;arrêté - MontantC</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/Engage_brut_arrete_MontantC_E__c.field-meta.xml
<CustomField>
    <fullName>Engage_brut_arrete_MontantC_E__c</fullName>
    <label>Engagé brut à l&apos;arrêté - MontantC €</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/Engage_brut_arrete_MontantD__c.field-meta.xml
<CustomField>
    <fullName>Engage_brut_arrete_MontantD__c</fullName>
    <label>Engagé brut à l&apos;arrêté - MontantD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/Engage_brut_arrete_MontantD_E__c.field-meta.xml
<CustomField>
    <fullName>Engage_brut_arrete_MontantD_E__c</fullName>
    <label>Engagé brut à l&apos;arrêté - MontantD €</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/Entite_BW__c.field-meta.xml
<CustomField>
    <fullName>Entite_BW__c</fullName>
    <formula>text(Affaire__r.Entite_BW__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Entité BW</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/Ligne_d_affaire_mensuelle_precedente__c.field-meta.xml
<CustomField>
    <fullName>Ligne_d_affaire_mensuelle_precedente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ligne d&apos;affaire mensuelle précédente</label>
    <referenceTo>VILigne_d_affaire_mensuelle__c</referenceTo>
    <relationshipLabel>Lignes d&apos;affaire mensuelles</relationshipLabel>
    <relationshipName>Lignes_d_affaire_mensuelles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/Periode_comptable__c.field-meta.xml
<CustomField>
    <fullName>Periode_comptable__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Période comptable</label>
    <referenceTo>VIPeriode__c</referenceTo>
    <relationshipLabel>Lignes d&apos;affaire mensuelles</relationshipLabel>
    <relationshipName>Lignes_d_affaire_mensuelles</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/PV_EncaisseE__c.field-meta.xml
<CustomField>
    <fullName>PV_EncaisseE__c</fullName>
    <label>PV Encaissé €</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/PV_Facture__c.field-meta.xml
<CustomField>
    <fullName>PV_Facture__c</fullName>
    <label>PV Facturé</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/PV_FactureE__c.field-meta.xml
<CustomField>
    <fullName>PV_FactureE__c</fullName>
    <label>PV Facturé €</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VIParametres__c/VIParametres__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>VIParametres</label>
</CustomObject>

force-app/main/default/objects/VIParametres__c/fields/Sans_Calcul_de_PRI__c.field-meta.xml
<CustomField>
    <fullName>Sans_Calcul_de_PRI__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Si coché, on fait le calcul avec les taux.Sinon, on prend les montants tel quel</inlineHelpText>
    <label>Sans Calcul de PRI ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VIPeriode__c/VIPeriode__c.object-meta.xml
<CustomObject>
    <label>Période comptable</label>
    <nameField>
        <label>Nom de Période</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Périodes comptables</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VIPeriode__c/fields/Date_de_debut__c.field-meta.xml
<CustomField>
    <fullName>Date_de_debut__c</fullName>
    <label>Date de début</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VIPeriode__c/fields/Date_de_fin__c.field-meta.xml
<CustomField>
    <fullName>Date_de_fin__c</fullName>
    <label>Date de fin</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VIPeriode__c/fields/Periode_comptable_precedente__c.field-meta.xml
<CustomField>
    <fullName>Periode_comptable_precedente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Période comptable précédente</label>
    <referenceTo>VIPeriode__c</referenceTo>
    <relationshipLabel>Périodes comptables</relationshipLabel>
    <relationshipName>Periodes_comptables</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VIPeriode__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Periode_comptable_statut</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/VI01_Affaire.cls
/*
* @author: Henri Saslawsky
* @description: 
*/

public class VI01_Affaire {

    public static boolean VerifDate (boolean test_date_ouverture, List <VIAffaire__c> listAff, Map <id,VIAffaire__c> MapAffOld ) { 

        boolean check =false ; 
                
        VIParametres__c param = VIParametres__c.getInstance(UserInfo.getUserId());  
             
        Map<string, VIPeriode__c>MapPeriodeOuverte= new Map<string, VIPeriode__c>();
        for(VIPeriode__c per:[SELECT date_de_debut__c, date_de_fin__c, entite_bw__c
                                FROM VIPeriode__c
                              WHERE statut__c=:VIConstant.PERIODE_OUVERTE ]) {
            MapPeriodeOuverte.put(per.entite_bw__c, per);
        }

        for(VIAffaire__c aff:listAff){
            if(aff.Date_de_SAV_previsionnelle__c <aff.Date_ouverture_affaire__c ) {
                aff.Date_de_SAV_previsionnelle__c =aff.Date_ouverture_affaire__c ;
            }
            if(aff.date_ouverture_affaire__c==null ) {
                aff.date_ouverture_affaire__c =aff.Date_de_livraison__c  ;
            }
            if(aff.date_max_mouvement__c<aff.Date_de_fin_de_garantie__c  ) {
                aff.date_max_mouvement__c=aff.Date_de_fin_de_garantie__c  ;
            }

            if(param.Sans_Calcul_de_PRI__c)
                continue ; 

            if(test_date_ouverture) {
                if(aff.date_ouverture_affaire__c<MapPeriodeOuverte.get(aff.entite_bw__c).date_de_debut__c) {
                    Aff.AddError(label.VIErreur007+' '+aff.date_ouverture_affaire__c);
                    check=true ; 
                }
            } 
            if(aff.date_ouverture_affaire__c>system.today().adddays(1)) {
                Aff.AddError(label.VIErreur015);
                check=true ; 
            }

            if(MapAffOld!=null) {
                if(MapAffOld.containskey(aff.id)) {
                    VIAffaire__c OldAff = MapAffOld.get(aff.id);
                    if(OldAff.date_de_sav_reelle__c==null && aff.date_de_sav_reelle__c!=null ) {
                        if(aff.date_de_sav_reelle__c!=MapPeriodeOuverte.get(aff.entite_bw__c).date_de_fin__c) {
                            Aff.AddError(label.VIErreur011);                    
                        }
                    }  
                    if(OldAff.date_de_sav_reelle__c!=null && aff.date_de_sav_reelle__c!=null && OldAff.date_de_sav_reelle__c!=aff.date_de_sav_reelle__c ) {
                            Aff.AddError(label.VIErreur012+' '+OldAff.date_de_sav_reelle__c+' '+aff.date_de_sav_reelle__c); 
                    }
                }
            }
        }        
        return check;
    }

    
/*
* @description: We need to create an open LAM for each affaire and for each month
* 
* @param: List of Affaire
* @return : void
* 
*/ 
    
    public static void Creation_lam (List <VIAffaire__c> listA) {

        // Let's fetch all the Affaire
        Map<id,string>MapAffaire           = new Map<id,string>();
        map<id,string>MapAffaireEntite_bw  = new map<id,string>();
        map<id,string>MapAffaireCurrency   = new map<id,string>();
        date date_minimum=null ; 
        date date_maximum=null ; 

        Map<String,string>MapEntite_bw = new Map<String,string>();
        for(VIEntiteBW__c entite_bw : [Select entite_bw__c,name FROM VIEntiteBW__C ] ) {
            MapEntite_bw.put(entite_bw.entite_bw__c,entite_bw.name);
        }
        
        for(VIAffaire__c a : listA) {
                
            MapAffaire.put(a.id,a.name);
            MapAffaireEntite_bw.put(a.id,MapEntite_bw.get(a.Entite_bw__c));
            MapAffaireCurrency.put(a.id,a.CurrencyIsoCode); 
            if(date_minimum==null || date_minimum>a.Date_ouverture_affaire__c)
                date_minimum=a.Date_ouverture_affaire__c ; 
                                                       
            if(date_maximum==null || date_maximum<a.date_de_sav_previsionnelle__c) 
                date_maximum=a.Date_de_sav_previsionnelle__c ; 
            if(a.date_de_fin_de_garantie__c!=null && date_maximum<a.date_de_fin_de_garantie__c) 
                date_maximum=a.date_de_fin_de_garantie__c ; 
            
        }
        if(date_maximum==null)
            date_maximum=date_minimum ;

        if(date_minimum==null  || date_minimum<=date.newinstance(2018,01,01) ) {
            date_minimum=date.newinstance(2018,01,01);
        }

        if(date_maximum==null  || date_maximum<date_minimum)
            date_maximum=date_minimum;
                
        date_minimum=date_minimum.addmonths(-1).toStartOfMonth();
        date_maximum=date_maximum.addmonths(+2).toStartOfMonth();        
        // At this stage, we have the minimum and the maximun date for each affaire. 
        // So we know wich LAM we need for each affaire
        
        
        Map<string,VIPeriode__c>MapPeriode = new Map<string,VIPeriode__c>();
        for (VIPeriode__c pe : [SELECT id, name,
                                       entite_bw__c,
                                       date_de_fin__c,
                                       Periode_comptable_precedente__r.name
                                  FROM VIPeriode__c
                                 WHERE date_de_debut__c>:date_minimum
                                   AND date_de_debut__c<=:date_maximum]) {
            MapPeriode.put(pe.name, pe);
        }

        
        map<string,VILigne_d_affaire_mensuelle__c>MapLAM = new map<String,VILigne_d_affaire_mensuelle__c>();
        for(VILigne_d_affaire_mensuelle__c lam : [SELECT id,name, CurrencyIsoCode, Affaire__c 
                                                    FROM VILigne_d_affaire_mensuelle__c
                                                   WHERE affaire__c in :MapAffaire.keyset()
                                                     AND periode_comptable__r.date_de_debut__c>:date_minimum
                                                     AND periode_comptable__r.date_de_debut__c<=:date_maximum]) {
            MapLAM.put(lam.name,lam) ;  
        }

        List<VILigne_d_affaire_mensuelle__c>ListNewLAM = new List<VILigne_d_affaire_mensuelle__c>();
        for(VIAffaire__c a : listA) {
            
            date_minimum=a.Date_ouverture_affaire__c ;
            date_maximum=a.Date_de_sav_previsionnelle__c ;
            if(a.date_de_fin_de_garantie__c>date_maximum) {
                date_maximum=a.date_de_fin_de_garantie__c;
            }

            if(date_minimum==null  || date_minimum<=date.newinstance(2018,01,01) ) {
                date_minimum=date.newinstance(2018,01,01);
            }
            if(date_maximum==null  || date_maximum<date_minimum)
                date_maximum=date_minimum;
            
            date_maximum=date_maximum.addmonths(1).toStartOfMonth() ;

            date d=date_minimum.toStartOfMonth() ; 
            while(d<date_maximum) {
                string key=a.name+'-'+string.valueof(d.Year())+string.valueof(d.month()).leftpad(2,'0')+MapAffaireEntite_bw.get(a.id) ;
                if(!MapLam.containskey(key)) {
                    VILigne_d_affaire_mensuelle__c LAM = new VILigne_d_affaire_mensuelle__c();
                    lam.name=key;
                    lam.affaire__c=a.id;
                    lam.Periode_comptable__c=MapPeriode.get(string.valueof(d.Year())+string.valueof(d.month()).leftpad(2,'0')+MapAffaireEntite_bw.get(a.id)).id ;
                    lam.CurrencyIsoCode=MapAffaireCurrency.get(a.id) ;
                    lam.Devis_Heure__c =0; 
                    lam.Devis_MontantD__c=0; 
                    lam.Devis_MontantI__c=0;
                    lam.Devis_MontantC__c=0;                                                       
                    lam.Devis_MontantD_E__c=0; 
                    lam.Devis_MontantI_E__c=0;
                    lam.Devis_MontantC_E__c=0; 
                    lam.engage_brut_arrete_Heure__c =0;
                    lam.engage_brut_arrete_MontantD__c=0; 
                    lam.engage_brut_arrete_MontantI__c=0;
                    lam.engage_brut_arrete_MontantC__c=0;                                                       
                    lam.engage_brut_arrete_MontantD_E__c=0; 
                    lam.engage_brut_arrete_MontantI_E__c=0;
                    lam.engage_brut_arrete_MontantC_E__c=0;                                                       
                    lam.Dont_comptabiliseD__c =0; 
                    lam.Dont_comptabiliseI__c =0;
                    lam.Dont_comptabiliseC__c =0;                                                       
                    lam.Dont_comptabiliseD_E__c =0; 
                    lam.Dont_comptabiliseI_E__c =0;
                    lam.Dont_comptabiliseC_E__c =0;                                                       
                    lam.Ecart_C_A_F_Heure__c =0; 
                    lam.Ecart_C_A_F_MontantD__c=0; 
                    lam.Ecart_C_A_F_MontantI__c =0; 
                    lam.Ecart_C_A_F_MontantC__c =0;                                                        
                    lam.Ecart_C_A_F_MontantD_E__c=0; 
                    lam.Ecart_C_A_F_MontantI_E__c =0; 
                    lam.Ecart_C_A_F_MontantC_E__c =0;  
                    lam.pv_facture__c=0;
                    lam.PV_FactureE__c=0;
                    lam.PV_EncaisseE__c=0;
                    lam.PV_EncaisseE__c=0;
                    ListNewLAM.add(LAM);
                }
                d=d.addmonths(1);
            }
        }        
        if(ListNewLAM.size()>0)
            insert ListNewLAM;

        // Let's update the field Ligne_d_affaire_mensuelle_precedente__c 
        MapLAM = new map<String,VILigne_d_affaire_mensuelle__c>();
        for(VILigne_d_affaire_mensuelle__c lam : [SELECT id,name, CurrencyIsoCode, Affaire__c ,Affaire__r.name,
                                                         Ligne_d_affaire_mensuelle_precedente__c,
                                                         periode_comptable__r.name
                                                    FROM VILigne_d_affaire_mensuelle__c
                                                   WHERE affaire__c in :MapAffaire.keyset()
                                                     AND periode_comptable__r.date_de_fin__c>=:date_minimum
                                                     AND periode_comptable__r.date_de_fin__c<=:date_maximum]) {
            MapLAM.put(lam.name,lam) ;  
        }

        List<VILigne_d_affaire_mensuelle__c>ListUpdateLAM = new List<VILigne_d_affaire_mensuelle__c>();
        for(VILigne_d_affaire_mensuelle__c lam : MapLAM.values()) {
            if(lam.Ligne_d_affaire_mensuelle_precedente__c==null) {
                string periode_current =  lam.periode_comptable__r.name;
                string periode_prec =null ; 
                if(MapPeriode.containskey(periode_current)) {
                    periode_prec=MapPeriode.get(periode_current).periode_comptable_precedente__r.name;
                    if(MapLam.containskey(lam.affaire__r.name+'-'+periode_prec)) {
                        lam.Ligne_d_affaire_mensuelle_precedente__c=MapLam.get(lam.affaire__r.name+'-'+periode_prec).id;
                        ListUpdateLAM.add(lam);
                    }
                }
            }
        }
        if(ListUpdateLAM.size()>0)
            update ListUpdateLAM;

        
    }   

    
    public static void Maj_Region_secteur (List <VIAffaire__c> listA) {
        Map<string, Order>MapOrder =new Map<string, Order>();
        List<string>ListIDOrder = new List<string>();
        for(VIAffaire__c a : listA) {
            ListIDOrder.add(a.Order__c );
        }   
        for(Order ord : [SELECT id ,ORD_Code_Agence_Regionale_BW__c , ORD_Code_Secteur_Commercial__c 
                           FROM Order
                           WHERE id in :ListIDorder ]) {
            MapOrder.put(ord.id,ord); 
        }

        for(VIAffaire__c a : listA) {
            if(MapOrder.containskey(a.Order__c)) {
                a.Agence_Regionale_BW_commande__c = MapOrder.get(a.order__c).ORD_Code_Agence_Regionale_BW__c;
                a.Secteur_commande__c             = MapOrder.get(a.order__c).ORD_Code_Secteur_Commercial__c ;
            } else {
                a.Agence_Regionale_BW_commande__c ='';
                a.Secteur_commande__c             ='';
            }
        }
    }
    
    
}