force-app/main/default/objects/VIFacture__c/VIFacture__c.object-meta.xml
<CustomObject>
    <label>Facture</label>
    <nameField>
        <label>Nom de Facture</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Factures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VIFacture__c/fields/Affaire__c.field-meta.xml
<CustomField>
    <fullName>Affaire__c</fullName>
    <label>Affaire</label>
    <referenceTo>VIAffaire__c</referenceTo>
    <relationshipLabel>Factures</relationshipLabel>
    <relationshipName>Factures</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/VIMajFactureSAVController_test.cls
@isTest
public class VIMajFactureSAVController_test {

    static testmethod void VIMajFactureSAVController_test() {
    
        VIInsertDataTest.VIInsertData_EUR_Affaire();
        VIInsertDataTest.VIInsertData_Facture();

        list<VIfacture__c>Listfac = [select id, affaire__c from VIfacture__c ];

        Test.startTest();
        Test.setCurrentPage(Page.VIMajFactureSAV);
        ApexPages.StandardSetController stdSetController = new ApexPages.StandardSetController(Listfac);
        stdSetController.setSelected(Listfac);
        VIMajFactureSAVController ext = new VIMajFactureSAVController(stdSetController);
        ext.Enregistrer();
        
        Test.stopTest();
        
        
    }
}