force-app/main/default/objects/Asset/fields/ASS_Commande__c.field-meta.xml
<CustomField>
    <fullName>ASS_Commande__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Commande</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Équipements</relationshipLabel>
    <relationshipName>Equipements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/ASS_NumeroIdentite__c.field-meta.xml
<CustomField>
    <fullName>ASS_NumeroIdentite__c</fullName>
    <description>Numéro d&apos;identification de l&quot;équipement</description>
    <label>Numéro d&apos;identité</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Produit_command__c.field-meta.xml
<CustomField>
    <fullName>Produit_command__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produit commandé</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Équipements</relationshipLabel>
    <relationshipName>equipements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/recordTypes/Equipement.recordType-meta.xml
<RecordType>
    <fullName>Equipement</fullName>
    <active>true</active>
    <description>Equipement client</description>
    <label>Equipement</label>
</RecordType>

force-app/main/default/objects/Order/fields/ORD_ClientLivre__c.field-meta.xml
<CustomField>
    <fullName>ORD_ClientLivre__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Compte livré</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Commandes</relationshipLabel>
    <relationshipName>Commandes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Equipement_cree__c.field-meta.xml
<CustomField>
    <fullName>Equipement_cree__c</fullName>
    <defaultValue>false</defaultValue>
    <description>La case est cochée automatiquement quand un équipment est créé sur le produit commandé</description>
    <label>Equipement créé</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Nbre_Equipements__c.field-meta.xml
<CustomField>
    <fullName>Nbre_Equipements__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Nbre Equipements</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/PC_Numero_de_PFI__c.field-meta.xml
<CustomField>
    <fullName>PC_Numero_de_PFI__c</fullName>
    <formula>Order.ORD_ReferenceCommande__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Numéro de PFI</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Equipement.recordType-meta.xml
<RecordType>
    <fullName>Equipement</fullName>
    <active>true</active>
    <label>Equipement</label>
</RecordType>

force-app/main/default/classes/VFC01_GenereEquipment.cls
public with sharing class VFC01_GenereEquipment {
    
    Private final orderItem thisOrderItem;
    
    public VFC01_GenereEquipment(ApexPages.StandardController stdcontroller){
        This.thisOrderItem=(orderItem) stdcontroller.getrecord();
    }    
    
    public pageReference createAsset(){
        orderItem orderItemdetails=[SELECT product2.Name, order.AccountId,order.ORD_ClientLivre__c, Product2Id, OrderId, Quantity, Nbre_Equipements__c, Equipement_cree__c, PC_Numero_de_PFI__c 
                                    FROM orderItem
                                    WHERE Id=:thisOrderItem.Id];
        
        //orderItemdetails.Nbre_Equipements__c = 0;
        
        Asset newAsset=new Asset();
        newAsset.Name=orderItemdetails.product2.Name;
        newAsset.RecordTypeId = Schema.SObjectType.Asset.getRecordTypeInfosByDeveloperName().get(label.Equipement).getRecordTypeId();
        newAsset.AccountId = orderItemdetails.order.ORD_ClientLivre__c;
        newAsset.Product2Id = orderItemdetails.Product2Id;
        newAsset.ASS_Commande__c = orderItemdetails.OrderId;
        newAsset.Produit_command__c=orderItemdetails.Id;
        newAsset.ASS_NumeroIdentite__c=orderItemdetails.PC_Numero_de_PFI__c;
        
        try{
            
            insert newAsset;
            orderItemdetails.Nbre_Equipements__c = orderItemdetails.Nbre_Equipements__c + 1;
            if (orderItemdetails.Nbre_Equipements__c == orderItemdetails.Quantity) {
            orderItemdetails.Equipement_cree__c=true;
            }
            update orderItemdetails;
            
            PageReference assetView=new PageReference('/'+newAsset.id); 
            assetView.setRedirect(true);
            return assetView;     
            
        } 
        
        
        catch (Exception e){
            string errorMessage=e.getMessage().substringAfter('FIELD_CUSTOM_VALIDATION_EXCEPTION,').substringBefore('[]');
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error,errorMessage));
            return null;
        
        }
        
       
    }  
}