force-app/main/default/objects/int_Budget__c/int_Budget__c.object-meta.xml
<CustomObject>
    <label>int_Budget</label>
    <nameField>
        <label>Nom de int_Budget</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>int_Budgets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/int_Budget__c/fields/Avenant__c.field-meta.xml
<CustomField>
    <fullName>Avenant__c</fullName>
    <label>Avenant</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/int_Budget__c/fields/codeAffaire__c.field-meta.xml
<CustomField>
    <fullName>codeAffaire__c</fullName>
    <label>codeAffaire</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/int_Budget__c/fields/codeCentre__c.field-meta.xml
<CustomField>
    <fullName>codeCentre__c</fullName>
    <label>codeCentre</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/int_Budget__c/fields/codeChapitre__c.field-meta.xml
<CustomField>
    <fullName>codeChapitre__c</fullName>
    <label>codeChapitre</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/int_Budget__c/fields/codeSousChapitre__c.field-meta.xml
<CustomField>
    <fullName>codeSousChapitre__c</fullName>
    <label>codeSousChapitre</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/int_Budget__c/fields/DatePublication__c.field-meta.xml
<CustomField>
    <fullName>DatePublication__c</fullName>
    <label>DatePublication</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/int_Budget__c/fields/mntEur__c.field-meta.xml
<CustomField>
    <fullName>mntEur__c</fullName>
    <label>mntEur</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/int_Budget__c/fields/nbrHeures__c.field-meta.xml
<CustomField>
    <fullName>nbrHeures__c</fullName>
    <label>nbrHeures</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/int_Budget__c/fields/Nom_frn__c.field-meta.xml
<CustomField>
    <fullName>Nom_frn__c</fullName>
    <label>Nom_frn</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/int_Budget__c/fields/typeDepense__c.field-meta.xml
<CustomField>
    <fullName>typeDepense__c</fullName>
    <label>typeDepense</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VIAffaire__c/VIAffaire__c.object-meta.xml
<CustomObject>
    <label>Affaire</label>
    <nameField>
        <label>Code Affaire</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Affaires</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VIAffaire__c/fields/Date_max_mouvement__c.field-meta.xml
<CustomField>
    <fullName>Date_max_mouvement__c</fullName>
    <label>Date max mouvement</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VIAffaire__c/fields/Date_ouverture_affaire__c.field-meta.xml
<CustomField>
    <fullName>Date_ouverture_affaire__c</fullName>
    <label>Date d&apos;ouverture d&apos;affaire</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VIAvenant__c/VIAvenant__c.object-meta.xml
<CustomObject>
    <label>Avenant</label>
    <nameField>
        <displayFormat>A{0000000}</displayFormat>
        <label>Ref de Avenant</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Avenants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VIAvenant__c/fields/Affaire__c.field-meta.xml
<CustomField>
    <fullName>Affaire__c</fullName>
    <label>Affaire</label>
    <referenceTo>VIAffaire__c</referenceTo>
    <relationshipLabel>Avenants</relationshipLabel>
    <relationshipName>Avenants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VIAvenant__c/fields/Annulation_complete__c.field-meta.xml
<CustomField>
    <fullName>Annulation_complete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Annulation complète</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VIAvenant__c/fields/Code_avenant__c.field-meta.xml
<CustomField>
    <fullName>Code_avenant__c</fullName>
    <label>Code avenant</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VIAvenant__c/fields/Debours__c.field-meta.xml
<CustomField>
    <fullName>Debours__c</fullName>
    <label>Debours</label>
    <summarizedField>VILigne_Budget__c.Debours__c</summarizedField>
    <summaryForeignKey>VILigne_Budget__c.Avenant__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/VIAvenant__c/fields/Statut_avenant__c.field-meta.xml
<CustomField>
    <fullName>Statut_avenant__c</fullName>
    <defaultValue>&apos;10 Prévue&apos;</defaultValue>
    <label>Statut de l&apos;avenant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Affaire_Statut</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/VICentre_Section__c/VICentre_Section__c.object-meta.xml
<CustomObject>
    <label>Centre / Section</label>
    <nameField>
        <label>Nom de Centre / Section</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Centres / Sections</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VILigne_Budget__c/VILigne_Budget__c.object-meta.xml
<CustomObject>
    <label>Ligne de budget</label>
    <nameField>
        <displayFormat>B{00000000}</displayFormat>
        <label>Ref de ligne de budget</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lignes de budgets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VILigne_Budget__c/fields/Avenant__c.field-meta.xml
<CustomField>
    <fullName>Avenant__c</fullName>
    <label>Avenant</label>
    <referenceTo>VIAvenant__c</referenceTo>
    <relationshipLabel>Lignes de budgets</relationshipLabel>
    <relationshipName>Budgets_sur_affaires</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VILigne_Budget__c/fields/Centre_Section__c.field-meta.xml
<CustomField>
    <fullName>Centre_Section__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Centre / Section</label>
    <referenceTo>VICentre_Section__c</referenceTo>
    <relationshipName>Budgets_sur_affaires</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VILigne_Budget__c/fields/Debours__c.field-meta.xml
<CustomField>
    <fullName>Debours__c</fullName>
    <label>Débours</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VILigne_Budget__c/fields/Heures__c.field-meta.xml
<CustomField>
    <fullName>Heures__c</fullName>
    <label>Heures</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VILigne_Budget__c/fields/Nom_frn__c.field-meta.xml
<CustomField>
    <fullName>Nom_frn__c</fullName>
    <label>Nom_frn</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VILigne_Budget__c/fields/Type_de_depense__c.field-meta.xml
<CustomField>
    <fullName>Type_de_depense__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Type de dépense</label>
    <referenceTo>VIType_de_depense__c</referenceTo>
    <relationshipName>Budgets_sur_affaires</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VIParametres__c/VIParametres__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>VIParametres</label>
</CustomObject>

force-app/main/default/objects/VIParametres__c/fields/Sans_Calcul_de_PRI__c.field-meta.xml
<CustomField>
    <fullName>Sans_Calcul_de_PRI__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Si coché, on fait le calcul avec les taux.Sinon, on prend les montants tel quel</inlineHelpText>
    <label>Sans Calcul de PRI ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VIType_de_depense__c/VIType_de_depense__c.object-meta.xml
<CustomObject>
    <label>Type de dépense</label>
    <nameField>
        <label>Nom de Type de dépense</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Types de dépenses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/VISchedImportBudget.cls
/*
*
*  We have to launch the import files 
*
*  for running by hand : 
 VISchedImportBudget v = new VISchedImportBudget();
 v.execute(null);
*
*  for running every hour at xx:16
     VISchedImportBudget m = new VISchedImportBudget();
     String sch = '0 16 * * * ?';
     String jobID = system.schedule('VISchedImportBudget', sch, m);
*
*
*/
global class VISchedImportBudget implements Schedulable,Database.Batchable<sObject>,Database.Stateful{

    Global double num_record = 0;
    Global String IDLog ='';    
    Global Map<string, VICentre_Section__c>MapCentre = new Map<string, VICentre_Section__c>();
    Global Map<string, VIType_de_depense__c>MapDepense = new Map<string, VIType_de_depense__c>();
    
    
    private string AffaireAGenerer; 
    private boolean Enchaine ;
    private boolean toute ;
    
     public VISchedImportBudget(String Param1,Boolean Param2,Boolean Param3 ) {
        AffaireAGenerer = Param1;        
        Enchaine = Param2;                
        toute = Param3;                
     }

    
    global Database.QueryLocator start(Database.BatchableContext BC){
        IDLog=VIUtils.LogWrite('VISchedImportBudget','4 Running','','Start ');

        for(VIType_de_depense__c td : [Select name, id from VIType_de_depense__c]) {
            MapDepense.put(td.name.left(3), td);
        }
        for(VICentre_Section__c cs : [Select name, id from VICentre_Section__c]) {
            MapCentre.put(cs.name.Left(3), cs);
        }
                                               
        string query = 'SELECT id,codeAffaire__c, codecentre__c,codechapitre__c, codeSousChapitre__c , ';
        query = query+'        DatePublication__c , Import_Status__c  ,mntEur__c    , nbrHeures__c  ,    ';
        query = query+'        Nom_frn__c  , num_frn__c   ,typeDepense__c,typeEvenement__c,avenant__c     ';        
        query = query+'   FROM Int_budget__c ';
        query = query+'   WHERE codeaffaire__c!=null ';
        if(!toute)
            query = query+'     AND (Import_Status__c =\'1\' or Import_Status__c =null) ';

        query = query+'     AND (codeAffaire__c Like \''+AffaireAGenerer+'%\')  ';
        query = query+' ORDER BY codeAffaire__c desc   ';
        
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<Int_budget__c> scope){
        num_record = 0;
        Map<string, VIAvenant__c>MapAvenant      = new Map<string, VIAvenant__c>();
        Map<string, VIAffaire__c>MapAffaire      = new Map<string, VIAffaire__c>();
        Map<string, VILigne_budget__c>MapBudget  = new Map<string, VILigne_budget__c>();
        

        List<string>ListIDAffaire = new List<string>();
                
        for(Int_budget__c bud:scope) {
            num_record = num_record+1;
            ListIDAffaire.add(bud.codeAffaire__c);
        }       

        for(VIAvenant__c ave : [SELECT id, name ,affaire__r.name, code_avenant__c, Annulation_complete__c 
                                  FROM VIAvenant__c 
                                 WHERE affaire__r.name in :ListIDAffaire]) {
            MapAvenant.put(ave.affaire__r.name+'-'+ave.code_Avenant__c, ave);
        }

        for(VIAffaire__c aff : [SELECT id, name ,Date_ouverture_affaire__c ,date_max_mouvement__c
                                  FROM VIAffaire__c 
                                 WHERE name in :ListIDAffaire]) {
            MapAffaire.put(aff.name, aff);
        }
        for(VILigne_budget__c bud : [SELECT id, name ,Centre_Section__r.name,type_de_depense__r.name,
                                            avenant__r.code_Avenant__c, avenant__r.affaire__r.name,
                                            Heures__c,debours__c
                                       FROM VILigne_budget__c 
                                      WHERE avenant__r.affaire__r.name in :ListIDAffaire]) {
            string key = bud.avenant__r.affaire__r.name+'-'+bud.avenant__r.code_Avenant__c+'-'+bud.Centre_Section__r.name.left(3)+'-'+bud.type_de_depense__r.name.left(3);                              
            MapBudget.put(key, bud);
        }

        List<VIAvenant__c>ListUpdateAve = new List<VIAvenant__c>();
        
        for(Int_budget__c bud:scope) {
            system.debug(' affaire en cours '+bud.codeaffaire__c);
            VILigne_budget__c budget = new VILigne_budget__c();
            string code_avenant ; 
            if( bud.typeEvenement__c==null) {
                if(bud.avenant__c=='0') {
                    code_avenant='CI';
                } else {
                    code_avenant='AV';
                }
            } else {
                code_avenant = bud.typeEvenement__c;                 
            }

            if(code_avenant!='CI')
                code_avenant=code_avenant+'-'+bud.avenant__c;

            string key = bud.codeaffaire__c+'-'+code_avenant+'-'+bud.codecentre__c+'-'+(bud.typeDepense__c+' ').left(3);
            if(!MapBudget.containskey(key)) {
            
                if(!MapAvenant.containskey(bud.codeaffaire__c+'-'+code_avenant)) {
                   if(MapAffaire.containskey(bud.codeaffaire__c)) {
                       VIAffaire__c aff=MapAffaire.get(bud.codeaffaire__c);
                    
                       if(aff.date_max_mouvement__c<bud.DatePublication__c)
                           aff.date_max_mouvement__c=bud.DatePublication__c;

                        date d1 ;
                        if(bud.DatePublication__c==null) {
                            d1= aff.Date_ouverture_affaire__c ;
                        } else {
                            d1=bud.DatePublication__c;
                        }
                    
                        VIAvenant__c ave =new VIAvenant__c (affaire__c=aff.id,
                                                    code_avenant__c=code_avenant,    
                                                    date__c=d1,
                                                    Statut_avenant__c =VIConstant.AVENANT_PREVU);
                        insert ave ; 
                        ListUpdateAve.add(ave);
                        MapAvenant.put(bud.codeaffaire__c+'-'+code_avenant, ave);

                    }      

                } 
                if(!MapAvenant.containskey(bud.codeaffaire__c+'-'+code_avenant)) {
                    VIUtils.LogWrite('VISchedImportBudget','3 Error','','code avenant inconnu '+bud.codeaffaire__c+'-'+code_avenant);
                    continue ; 
                }
                    
                    
                budget.avenant__c=MapAvenant.get(bud.codeaffaire__c+'-'+code_avenant).id;
                    

                if(!MapCentre.containskey(bud.codecentre__c)) {
                    VIUtils.LogWrite('VISchedImportBudget','3 Error','','code centre inconnu '+bud.codecentre__c+' '+bud.id);
                    continue ; 
                }
                if(!MapDepense.containskey((bud.typeDepense__c+' ').left(3))) {
                    VIUtils.LogWrite('VISchedImportBudget','3 Error','','code depense inconnu '+bud.typeDepense__c+' '+bud.id);
                    continue ; 
                }

                budget.Centre_Section__c =MapCentre.get(bud.codecentre__c).id;
                budget.type_de_depense__c= MapDepense.get((bud.typeDepense__c+' ').left(3)).id;
            } else {
                 budget=MapBudget.get(key);
            }

            // si on est sur une annulation complète, on laisse tomber la ligne budget car elle a déjà été annulé complètement
            if(MapAvenant.get(bud.codeaffaire__c+'-'+code_avenant).Annulation_complete__c==true ) {
                bud.Import_Status__c='2';
                continue ; 
            }

            if((bud.typeDepense__c+' ').left(3)=='MO ')
                budget.Heures__c =bud.nbrHeures__c;

            budget.Debours__c  =bud.mntEur__c;  

            bud.Import_Status__c='2';
            
            MapBudget.put(key,budget) ;

        }
        upsert MapBudget.Values();
        update MapAffaire.values() ;
        update scope ; 
        for(VIAvenant__c ave:ListUpdateAve) {
            ave.Statut_avenant__c =VIConstant.AVENANT_EN_COURS;
        }
        update ListUpdateAve;
        
    }

    global void finish(Database.BatchableContext BC){
        IDLog=VIUtils.LogWrite('VISchedImportBudget','1 Normal',IDLog,'End '+num_record);
        if(enchaine)
            Database.executeBatch(new VISchedImportFacture(AffaireAGenerer, enchaine, toute),VISchedImportFacture.NBR_LOT());
        
    }

    global void execute(SchedulableContext scon) {
        Database.executeBatch(new VISchedImportBudget(AffaireAGenerer, enchaine, toute),VISchedImportBudget.NBR_LOT());
    }

    public static  integer NBR_LOT () {
         VIParametres__c param = VIParametres__c.getInstance(UserInfo.getUserId()); 
         integer i ; 
         if(param.Sans_Calcul_de_PRI__c) {
             i=20 ;
         } else {
             i=20;    
         }
         return i;
    }

    
     
}