force-app/main/default/objects/int_Budget__c/int_Budget__c.object-meta.xml
<CustomObject>
    <label>int_Budget</label>
    <nameField>
        <label>Nom de int_Budget</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>int_Budgets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/int_Budget__c/fields/codeAffaire__c.field-meta.xml
<CustomField>
    <fullName>codeAffaire__c</fullName>
    <label>codeAffaire</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/int_Budget__c/fields/codeCentre__c.field-meta.xml
<CustomField>
    <fullName>codeCentre__c</fullName>
    <label>codeCentre</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/int_Budget__c/fields/codeChapitre__c.field-meta.xml
<CustomField>
    <fullName>codeChapitre__c</fullName>
    <label>codeChapitre</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/int_Budget__c/fields/codeSousChapitre__c.field-meta.xml
<CustomField>
    <fullName>codeSousChapitre__c</fullName>
    <label>codeSousChapitre</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/int_Budget__c/fields/DatePublication__c.field-meta.xml
<CustomField>
    <fullName>DatePublication__c</fullName>
    <label>DatePublication</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/int_Budget__c/fields/mntEur__c.field-meta.xml
<CustomField>
    <fullName>mntEur__c</fullName>
    <label>mntEur</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/int_Budget__c/fields/nbrHeures__c.field-meta.xml
<CustomField>
    <fullName>nbrHeures__c</fullName>
    <label>nbrHeures</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/int_Budget__c/fields/typeDepense__c.field-meta.xml
<CustomField>
    <fullName>typeDepense__c</fullName>
    <label>typeDepense</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VICentre_Section__c/VICentre_Section__c.object-meta.xml
<CustomObject>
    <label>Centre / Section</label>
    <nameField>
        <label>Nom de Centre / Section</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Centres / Sections</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VIType_de_depense__c/VIType_de_depense__c.object-meta.xml
<CustomObject>
    <label>Type de dépense</label>
    <nameField>
        <label>Nom de Type de dépense</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Types de dépenses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/VISchedImportBudget_test.cls
@isTest
public class VISchedImportBudget_test {

    static testmethod void VISchedImportBudget_test() {
    
        VIInsertDataTest.VIInsertData_EUR_Affaire();

        VIType_de_depense__c td = [select name from VIType_de_depense__c limit 1];
        VICentre_Section__c cs = [select name from VICentre_Section__c limit 1];
                
        Int_budget__c bud = new Int_budget__c (
                               codeAffaire__c='B80000',
                               codechapitre__c='00', 
                               codeSousChapitre__c='00',
                               codecentre__c=cs.name.left(3),
                               typeDepense__c=td.name.left(3), 
                               DatePublication__c  =System.today(), 
                               mntEur__c=1,
                               nbrHeures__c=1) ;
        insert bud;
        
        VISchedImportBudget v1 = new VISchedImportBudget('B80000',false,false);
        v1.execute(null);
    }
}