force-app/main/default/objects/int_Affaire__c/int_Affaire__c.object-meta.xml
<CustomObject>
    <label>int_Affaire</label>
    <nameField>
        <label>Nom de int_Affaire</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>int_affaires</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/int_Affaire__c/fields/Code_produit__c.field-meta.xml
<CustomField>
    <fullName>Code_produit__c</fullName>
    <label>Code produit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/int_Affaire__c/fields/codeClient__c.field-meta.xml
<CustomField>
    <fullName>codeClient__c</fullName>
    <label>codeClient</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/int_Affaire__c/fields/dateLivraison__c.field-meta.xml
<CustomField>
    <fullName>dateLivraison__c</fullName>
    <label>dateLivraison</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/int_Affaire__c/fields/DateMiseService__c.field-meta.xml
<CustomField>
    <fullName>DateMiseService__c</fullName>
    <label>DateMiseService</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/int_Affaire__c/fields/dateOuvAffaire__c.field-meta.xml
<CustomField>
    <fullName>dateOuvAffaire__c</fullName>
    <label>dateOuvAffaire</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/int_Affaire__c/fields/DateReception__c.field-meta.xml
<CustomField>
    <fullName>DateReception__c</fullName>
    <label>DateReception</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/int_Affaire__c/fields/DateSortieVentePrev__c.field-meta.xml
<CustomField>
    <fullName>DateSortieVentePrev__c</fullName>
    <label>DateSortieVentePrev</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/int_Affaire__c/fields/FlagAnnulation__c.field-meta.xml
<CustomField>
    <fullName>FlagAnnulation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>FlagAnnulation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/int_Affaire__c/fields/libelleAffaire__c.field-meta.xml
<CustomField>
    <fullName>libelleAffaire__c</fullName>
    <label>libelleAffaire</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/int_Affaire__c/fields/lll_aff__c.field-meta.xml
<CustomField>
    <fullName>lll_aff__c</fullName>
    <label>lll_aff</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/int_Affaire__c/fields/montantProvisionsGarantie__c.field-meta.xml
<CustomField>
    <fullName>montantProvisionsGarantie__c</fullName>
    <label>montantProvisionsGarantie</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/int_Affaire__c/fields/montantPv__c.field-meta.xml
<CustomField>
    <fullName>montantPv__c</fullName>
    <label>montantPv</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/int_Affaire__c/fields/NumAvCde__c.field-meta.xml
<CustomField>
    <fullName>NumAvCde__c</fullName>
    <label>Numéro avenant</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/int_Affaire__c/fields/raisonSocialeClient__c.field-meta.xml
<CustomField>
    <fullName>raisonSocialeClient__c</fullName>
    <label>raisonSocialeClient</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/int_Affaire__c/fields/typeEvenement__c.field-meta.xml
<CustomField>
    <fullName>typeEvenement__c</fullName>
    <label>typeEvenement</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/VISchedImportAffaire_test.cls
@isTest
public class VISchedImportAffaire_test {

    static testmethod void VISchedImportAffaire_test() {
    
        VIInsertDataTest.VIInsertData_EUR_Affaire();

        
        VIInsertDataTest.VIInsertData_Achat(); 
        string code_affaire='B80000';
        
        int_affaire__c aff = new int_affaire__c (Code_produit__c='PRE',
                               raisonSocialeClient__c='test',                  
                               codeAffaire__c='B80002',
                               codeClient__c='1234' ,
                               dateLivraison__c =System.today(),
                               DateMiseService__c =null,
                               dateOuvAffaire__c =System.today(),
                               DateReception__c =System.today(),
                               DateSortieVentePrev__c =System.today(),
                               libelleAffaire__c='aa',
                               lll_aff__c='aa', 
                               montantPv__c =123,
                               typeEvenement__c='CI',               
                               montantProvisionsGarantie__c =123) ;
        insert aff;

        int_affaire__c aff1 = new int_affaire__c (Code_produit__c='PRE',
                               raisonSocialeClient__c='test',                  
                               codeAffaire__c=code_affaire,
                               codeClient__c='1234' ,
                               dateLivraison__c =System.today(),
                               DateMiseService__c =null,
                               dateOuvAffaire__c =System.today(),
                               DateReception__c =System.today(),
                               DateSortieVentePrev__c =System.today(),
                               libelleAffaire__c='aa',
                               lll_aff__c='aa', 
                               montantPv__c =123,
                               typeEvenement__c='AV', 
                               NumAvCde__c='1',                  
                               montantProvisionsGarantie__c =123) ;
        insert aff1;
        
        VISchedImportAffaire v1 = new VISchedImportAffaire(code_affaire,false,true,1);
        v1.execute(null);

        VISchedImportAffaire v2 = new VISchedImportAffaire(code_affaire,false,true,1);
        v2.execute(null);

        VISchedImportAffaire v3 = new VISchedImportAffaire(code_affaire,false,true,1);
        v3.execute(null);

        VISchedImportAffaire v3a = new VISchedImportAffaire(code_affaire,false,true,1);
        v3a.execute(null);

        VIInsertDataTest.VIInsertData_Avenant();
        
        aff = [select flagannulation__c, import_status__c,typeevenement__c, NumAvCde__c from int_affaire__c where codeAffaire__c='B80000'];
        aff.flagannulation__c = true ; 
        aff.import_status__c='';
        aff.typeevenement__c='AV' ;
        aff.NumAvCde__c='2';
        update aff ; 

        VISchedImportAffaire v4 = new VISchedImportAffaire(code_affaire,false,true,1);
        v4.execute(null);
        
        v4.code_Coverage();
        
    }
}