force-app/main/default/objects/Account/fields/Acc_CodeAgence__c.field-meta.xml
<CustomField>
    <fullName>Acc_CodeAgence__c</fullName>
    <label>Code Agence Régionale BW</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Acc_CodeSecteur__c.field-meta.xml
<CustomField>
    <fullName>Acc_CodeSecteur__c</fullName>
    <label>Code Secteur Commercial</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ACC_Region__c.field-meta.xml
<CustomField>
    <fullName>ACC_Region__c</fullName>
    <label>Agence régionale BW</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ACC_Entite_BW__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>AgenceRegionaleBW</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ACC_SecteurCommercial__c.field-meta.xml
<CustomField>
    <fullName>ACC_SecteurCommercial__c</fullName>
    <label>Secteur commercial</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ACC_Region__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>SecteurCommercial</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/ORD_Agence_Regionale_BW__c.field-meta.xml
<CustomField>
    <fullName>ORD_Agence_Regionale_BW__c</fullName>
    <label>Agence Régionale BW</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>AgenceRegionaleBW</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/ORD_BusinessUnit__c.field-meta.xml
<CustomField>
    <fullName>ORD_BusinessUnit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>3</fullName>
                <label>Chaudières</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Traitement de l&apos;eau</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Air</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Services</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Location</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>INCINEX</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/ORD_Code_Agence_Regionale_BW__c.field-meta.xml
<CustomField>
    <fullName>ORD_Code_Agence_Regionale_BW__c</fullName>
    <label>Code Agence Régionale BW</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/ORD_Code_Secteur_Commercial__c.field-meta.xml
<CustomField>
    <fullName>ORD_Code_Secteur_Commercial__c</fullName>
    <label>Code Secteur Commercial</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Ord_Domaine__c.field-meta.xml
<CustomField>
    <fullName>Ord_Domaine__c</fullName>
    <label>Code Business Unit</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/ORD_Secteur_Commercial__c.field-meta.xml
<CustomField>
    <fullName>ORD_Secteur_Commercial__c</fullName>
    <label>Secteur Commercial</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ORD_Agence_Regionale_BW__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>SecteurCommercial</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/ORD_SousDomaine__c.field-meta.xml
<CustomField>
    <fullName>ORD_SousDomaine__c</fullName>
    <label>Sous-Domaine</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>ADOUCISSEUR</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>AÉROTHERMES</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>AUTRES CHAUDIÈRES</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>AUTRES TA SPÉCIFIQUES</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>AUTRES TA STANDARD</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>AUTRES TE SPECIFIQUES</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>AUTRES TE STANDARD</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>BACHE DÉGAZANTE</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>BRÚLEURS</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>BWB</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>BWD</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>BWR</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>CENTRALE FOYER ÉCHANGEUR</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>CHAUDIERES EAU CHAUDE &lt; 5MW</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>CHAUDIÈRE VAPORISATION BASSE PRESSION</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>CONTRATS CHAUDIÈRES</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>CHAUDIERES EAU CHAUDE &gt; 5MW</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>CONTRAT LOW COST</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>CONTRATS AIR</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>CONTRATS EAU</label>
            </value>
            <value>
                <fullName>21</fullName>
                <label>CONTRATS GLOBAUX</label>
            </value>
            <value>
                <fullName>22</fullName>
                <label>DÉCARBONATATION</label>
            </value>
            <value>
                <fullName>23</fullName>
                <label>DÉGAZEURS</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>DÉMINÉRALISATION</label>
            </value>
            <value>
                <fullName>25</fullName>
                <label>EQUIPEMENT / INSTALLATION</label>
            </value>
            <value>
                <fullName>26</fullName>
                <label>EQUIPEMENTS CHAUFFERIE</label>
            </value>
            <value>
                <fullName>27</fullName>
                <label>FILTRES</label>
            </value>
            <value>
                <fullName>28</fullName>
                <label>FORMATION</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>GENERATEUR</label>
            </value>
            <value>
                <fullName>31</fullName>
                <label>GROS TRAVAUX</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/ord_visSousDomain__c.field-meta.xml
<CustomField>
    <fullName>ord_visSousDomain__c</fullName>
    <label>Code Sous Domaine</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BatchOrderVisionSynchro.cls
/**
 * @description       : 
 * @author            : SCHIBOUT
 * @group             : 
 * @last modified on  : 29-09-2021
 * @last modified by  : SCHIBOUT
**/
global class BatchOrderVisionSynchro  implements Database.Batchable<sObject>,  Database.Stateful, Schedulable {
    global Database.QueryLocator start(Database.BatchableContext info){
        List<AsyncApexJob> previousJobList = [SELECT Id, CompletedDate  FROM AsyncApexJob WHERE ApexClass.Name ='BatchOrderVisionSynchro' 
                                    AND CompletedDate != null ORDER BY CompletedDate desc];
         Datetime previousRundate ;                            	
        if (previousJobList.size()> 0)   { previousRundate = previousJobList[0].CompletedDate ;}
        else {
            previousRundate = Date.today()-1 ; }
        // all accounts     
        /*return Database.getQueryLocator([SELECT Id,ord_visSousDomain__c,Ord_Domaine__c,ORD_SousDomaine__c ,ORD_BusinessUnit__c,Account.Acc_CodeSecteur__c
                                        ,Account.Acc_CodeAgence__c,Account.ACC_SecteurCommercial__c,Account.ACC_Region__c,ORD_Code_Secteur_Commercial__c
                                        ,ORD_Secteur_Commercial__c,ORD_Agence_Regionale_BW__c,ORD_Code_Agence_Regionale_BW__c
                                        FROM Order WHERE ORD_Code_Secteur_Commercial__c =null 
                                        OR ORD_Code_Agence_Regionale_BW__c =null 
                                        OR ORD_Agence_Regionale_BW__c = null
                                        OR ORD_Secteur_Commercial__c = null OR Ord_Domaine__c  = null OR ord_visSousDomain__c = null]);*/

        return Database.getQueryLocator([SELECT Id,ord_visSousDomain__c,Ord_Domaine__c,ORD_SousDomaine__c ,ORD_BusinessUnit__c,Account.Acc_CodeSecteur__c
                                        ,Account.Acc_CodeAgence__c,Account.ACC_SecteurCommercial__c,Account.ACC_Region__c,ORD_Code_Secteur_Commercial__c
                                        ,ORD_Secteur_Commercial__c,ORD_Agence_Regionale_BW__c,ORD_Code_Agence_Regionale_BW__c
                                        FROM Order WHERE LastModifiedDate >= :previousRundate ]);                                
    } 

    global void execute(Database.BatchableContext BC, List<Order> orderList){
        
       //Update Orders 
       List<Order> orderListToUpdate = new List<Order>();
       for(Order ord : orderList){                      
           
            Boolean addToList  = false ;
            if (ord.ord_visSousDomain__c != BwUtils.getTranscoVisionValue('Sous domaine',ord.ORD_SousDomaine__c) ) ord.ord_visSousDomain__c = BwUtils.getTranscoVisionValue('Sous domaine',ord.ORD_SousDomaine__c) ;
            if (ord.Ord_Domaine__c !=BwUtils.getTranscoVisionValue('BU',ord.ORD_BusinessUnit__c)) { ord.Ord_Domaine__c =BwUtils.getTranscoVisionValue('BU',ord.ORD_BusinessUnit__c);addToList = true ;}
            if (ord.ORD_Code_Secteur_Commercial__c != ord.Account.Acc_CodeSecteur__c){ ord.ORD_Code_Secteur_Commercial__c =ord.Account.Acc_CodeSecteur__c;addToList = true ;}
            if (ord.ORD_Secteur_Commercial__c != ord.Account.ACC_SecteurCommercial__c) { ord.ORD_Secteur_Commercial__c=ord.Account.ACC_SecteurCommercial__c;addToList = true ;}
            if (ord.ORD_Agence_Regionale_BW__c != ord.Account.ACC_Region__c) { ord.ORD_Agence_Regionale_BW__c=ord.Account.ACC_Region__c;addToList = true ;}
            if (ord.ORD_Code_Agence_Regionale_BW__c != ord.Account.Acc_CodeAgence__c){ ord.ORD_Code_Agence_Regionale_BW__c=ord.Account.Acc_CodeAgence__c;addToList = true ;}
            if (addToList) (orderListToUpdate.add(ord));

       }
       Database.update(orderListToUpdate, false);
    }
    
    global void finish(Database.BatchableContext BC){
            
    }

    global void execute(SchedulableContext sc) {
        BatchOrderVisionSynchro batch = new BatchOrderVisionSynchro();
        Database.executeBatch(batch);
    }

    global static void run(){
        BatchOrderVisionSynchro batch = new BatchOrderVisionSynchro();
        Database.executeBatch(batch);
    }
}