force-app/main/default/objects/Account/fields/ACC_revenu_n_1__c.field-meta.xml
<CustomField>
    <fullName>ACC_revenu_n_1__c</fullName>
    <label>Revenu n-1</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/ACC_revenu_n_2__c.field-meta.xml
<CustomField>
    <fullName>ACC_revenu_n_2__c</fullName>
    <label>Revenu n-2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/ACC_Revenu_n__c.field-meta.xml
<CustomField>
    <fullName>ACC_Revenu_n__c</fullName>
    <label>Revenu n</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/ACC_SIREN__c.field-meta.xml
<CustomField>
    <fullName>ACC_SIREN__c</fullName>
    <label>SIREN</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/ORD_MontantHT_ERP__c.field-meta.xml
<CustomField>
    <fullName>ORD_MontantHT_ERP__c</fullName>
    <label>Montant HT ERP</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order/fields/ORD_SousDomaine__c.field-meta.xml
<CustomField>
    <fullName>ORD_SousDomaine__c</fullName>
    <label>Sous-Domaine</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>ADOUCISSEUR</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>AÉROTHERMES</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>AUTRES CHAUDIÈRES</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>AUTRES TA SPÉCIFIQUES</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>AUTRES TA STANDARD</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>AUTRES TE SPECIFIQUES</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>AUTRES TE STANDARD</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>BACHE DÉGAZANTE</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>BRÚLEURS</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>BWB</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>BWD</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>BWR</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>CENTRALE FOYER ÉCHANGEUR</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>CHAUDIERES EAU CHAUDE &lt; 5MW</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>CHAUDIÈRE VAPORISATION BASSE PRESSION</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>CONTRATS CHAUDIÈRES</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>CHAUDIERES EAU CHAUDE &gt; 5MW</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>CONTRAT LOW COST</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>CONTRATS AIR</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>CONTRATS EAU</label>
            </value>
            <value>
                <fullName>21</fullName>
                <label>CONTRATS GLOBAUX</label>
            </value>
            <value>
                <fullName>22</fullName>
                <label>DÉCARBONATATION</label>
            </value>
            <value>
                <fullName>23</fullName>
                <label>DÉGAZEURS</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>DÉMINÉRALISATION</label>
            </value>
            <value>
                <fullName>25</fullName>
                <label>EQUIPEMENT / INSTALLATION</label>
            </value>
            <value>
                <fullName>26</fullName>
                <label>EQUIPEMENTS CHAUFFERIE</label>
            </value>
            <value>
                <fullName>27</fullName>
                <label>FILTRES</label>
            </value>
            <value>
                <fullName>28</fullName>
                <label>FORMATION</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>GENERATEUR</label>
            </value>
            <value>
                <fullName>31</fullName>
                <label>GROS TRAVAUX</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/USER_ByPassProcessBuilder__c.field-meta.xml
<CustomField>
    <fullName>USER_ByPassProcessBuilder__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ByPass Process Builder</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/USER_ByPassRegleValidation__c.field-meta.xml
<CustomField>
    <fullName>USER_ByPassRegleValidation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ByPass Règle de validation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VISousDomaine__c/VISousDomaine__c.object-meta.xml
<CustomObject>
    <label>Produit - SousDomaine</label>
    <nameField>
        <label>SousDomaine</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Produits - SousDomaines</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VISousDomaine__c/fields/Code_API_Sous_domaine__c.field-meta.xml
<CustomField>
    <fullName>Code_API_Sous_domaine__c</fullName>
    <label>Code API - Sous domaine</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VISousDomaine__c/fields/Mode_de_calcul_de_l_avancement__c.field-meta.xml
<CustomField>
    <fullName>Mode_de_calcul_de_l_avancement__c</fullName>
    <label>Mode de calcul de l&apos;avancement</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Mode_de_calcul_de_l_avancement</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/VISousDomaine__c/fields/use_cutomer_segment__c.field-meta.xml
<CustomField>
    <fullName>use_cutomer_segment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Inclure dans la segmentation client</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Batch_AccCaluculateRevenuTest.cls
@isTest
public class Batch_AccCaluculateRevenuTest {
    @IsTest
    static void methodName(){
        user API=[SELECT USER_ByPassRegleValidation__c, USER_ByPassProcessBuilder__c
        FROM user 
        WHERE lastName=:label.API
        LIMIT 1];

        API.USER_ByPassRegleValidation__c=true;
        API.USER_ByPassProcessBuilder__c = true;

        update API;
        Test.startTest();
        System.runAs(API){

            Account newAccount=new Account(Name='Test Account For Update Quote',
            ShippingCity='Lebanon',
            ShippingPostalCode='123',
            RecordTypeId = '0120O000000kqhw',
            ACC_SIREN__c='123456789');
            insert newAccount;
			Account newAccount_1=new Account(Name='Test1',
            ShippingCity='France',
            ShippingPostalCode='1123',
            RecordTypeId = '0120O000000kqhw',
            ACC_SIREN__c='123467811');
            insert newAccount_1;
            VISousDomaine__c vis= new VISousDomaine__c(Name='BRU',Code_API_Sous_domaine__c='1',Mode_de_calcul_de_l_avancement__c='1',use_cutomer_segment__c=true);
            insert vis ;
            list<order> listNewOrders=new list<order>();
            
            order newOrder1=new Order();
            newOrder1.AccountId=newAccount.Id;
            newOrder1.ORD_SousDomaine__c=vis.Code_API_Sous_domaine__c;
            newOrder1.EffectiveDate=Date.today() + 10;
            newOrder1.status='3';
            newOrder1.ORD_MontantHT_ERP__c =50 ;
            listNewOrders.add(newOrder1);
			//
            //
            order newOrder2=new Order();
            newOrder2.ORD_SousDomaine__c=vis.Code_API_Sous_domaine__c;
            newOrder2.AccountId=newAccount.Id;
            newOrder2.EffectiveDate=Date.today() + 10;
            newOrder2.ORD_MontantHT_ERP__c =100 ;
            newOrder2.status='3';
            listNewOrders.add(newOrder2);
            //----------------
            //
            order newOrder2_1=new Order();
            newOrder2_1.ORD_SousDomaine__c=vis.Code_API_Sous_domaine__c;
            newOrder2_1.AccountId=newAccount.Id;
            newOrder2_1.EffectiveDate=Date.today() + 10;
            newOrder2_1.ORD_MontantHT_ERP__c =100 ;
            newOrder2_1.status='3';
            listNewOrders.add(newOrder2_1);
            //Assert current revenu = 250
            //
            order newOrder3=new Order();
            newOrder3.ORD_SousDomaine__c=vis.Code_API_Sous_domaine__c;
            newOrder3.AccountId=newAccount.Id;
            newOrder3.EffectiveDate=Date.today() -365;
            newOrder3.status='3';
            newOrder3.ORD_SousDomaine__c=vis.Code_API_Sous_domaine__c;
            newOrder3.ORD_MontantHT_ERP__c =75 ;
            listNewOrders.add(newOrder3);
            
            order newOrder4=new Order();
            newOrder4.ORD_SousDomaine__c=vis.Code_API_Sous_domaine__c;
            newOrder4.AccountId=newAccount.Id;
            newOrder4.EffectiveDate=Date.today()  -365;
            newOrder4.ORD_MontantHT_ERP__c =200 ;
            newOrder4.status='3';
            listNewOrders.add(newOrder4);
            //Revenu - 1 = 275
            
            order newOrder1_1=new Order();
            newOrder1_1.ORD_SousDomaine__c=vis.Code_API_Sous_domaine__c;
            newOrder1_1.AccountId=newAccount_1.Id;
            newOrder1_1.EffectiveDate=Date.today() + 10;
            newOrder1_1.status='3';
            newOrder1_1.ORD_MontantHT_ERP__c =125 ;
            listNewOrders.add(newOrder1_1);
            System.debug('newOrder1_1 '+newOrder1_1);
            order newOrder1_2=new Order();
            newOrder1_2.ORD_SousDomaine__c=vis.Code_API_Sous_domaine__c;
            newOrder1_2.AccountId=newAccount_1.Id;
            newOrder1_2.EffectiveDate=Date.today() -365;
            newOrder1_2.status='3';
            newOrder1_2.ORD_MontantHT_ERP__c =145 ;
            listNewOrders.add(newOrder1_2);
            
            
            insert listNewOrders;
            Batch_AccCaluculateRevenu.run();
        
        Test.stopTest();
        Account act = [SELECT  Id, ACC_Revenu_n__c, ACC_revenu_n_1__c,ACC_revenu_n_2__c FROM Account WHERE Name='Test Account For Update Quote' LIMIT 1];
        System.debug('act ='+act);
        System.assertEquals(act.ACC_Revenu_n__c, 250.0,'First Assertion');
        System.assertEquals(act.ACC_revenu_n_1__c, 275.0,'second Assertion');    
        Account acct1 = [SELECT  Id, ACC_Revenu_n__c, ACC_revenu_n_1__c,ACC_revenu_n_2__c FROM Account WHERE Name='Test1' LIMIT 1];
        System.debug('acct1 ='+acct1);
        System.assertEquals(acct1.ACC_Revenu_n__c, 125.0,'Third Assertion');
        System.assertEquals(acct1.ACC_revenu_n_1__c, 145.0,'Forth Assertion');    
    }
    }
    Public static Opportunity createOppy(Id AccountId,Date closeDate,String stageName, String entryName){
        return (new opportunity(AccountId = AccountId,
                                closedate=closeDate,
                                stageName=stageName,
                                Name = entryName));
    }
    
    Public static Id getPricebookId(){
        Pricebook2 standardPricebook = new Pricebook2(
            Id = Test.getStandardPricebookId(),
            IsActive = true );
        	update standardPricebook;
            Id StandardPricebookID = Test.getStandardPricebookId();
 			return StandardPricebookID ;       
    }
    Public static Order createOrder(String Name,Id AccountId,Date closeDate,String stageName, String entryName ){
        Opportunity oppy = createOppy(AccountId,closeDate,stageName, entryName);
        insert oppy ;
        Id standardPricebookId = getPricebookId();
        
        Order ord = New Order();
        return ord;
    }
}