force-app/main/default/objects/Account/fields/ACC_Entite_BW__c.field-meta.xml
<CustomField>
    <fullName>ACC_Entite_BW__c</fullName>
    <label>Entité BW</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>EntiteBW</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ACC_Region__c.field-meta.xml
<CustomField>
    <fullName>ACC_Region__c</fullName>
    <label>Agence régionale BW</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ACC_Entite_BW__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>AgenceRegionaleBW</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ACC_SecteurCommercial__c.field-meta.xml
<CustomField>
    <fullName>ACC_SecteurCommercial__c</fullName>
    <label>Secteur commercial</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ACC_Region__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>SecteurCommercial</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ACC_SIREN__c.field-meta.xml
<CustomField>
    <fullName>ACC_SIREN__c</fullName>
    <label>SIREN</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/ORD_MontantHT_ERP__c.field-meta.xml
<CustomField>
    <fullName>ORD_MontantHT_ERP__c</fullName>
    <label>Montant HT ERP</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/UnitePrixPar__c.field-meta.xml
<CustomField>
    <fullName>UnitePrixPar__c</fullName>
    <label>Unité (Prix Par)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Heure</fullName>
            </value>
            <value>
                <fullName>Jour</fullName>
            </value>
            <value>
                <fullName>Année</fullName>
            </value>
            <value>
                <fullName>Intervention</fullName>
            </value>
            <value>
                <fullName>Produit</fullName>
            </value>
            <value>
                <fullName>Bidon</fullName>
            </value>
            <value>
                <fullName>Fût</fullName>
            </value>
            <value>
                <fullName>IBC</fullName>
            </value>
            <value>
                <fullName>Sac</fullName>
            </value>
            <value>
                <fullName>Tonneau</fullName>
            </value>
            <value>
                <fullName>Unité</fullName>
            </value>
            <value>
                <fullName>KG</fullName>
            </value>
            <value>
                <fullName>KM</fullName>
            </value>
            <value>
                <fullName>LT</fullName>
            </value>
            <value>
                <fullName>GG</fullName>
            </value>
            <value>
                <fullName>MQ</fullName>
            </value>
            <value>
                <fullName>MC</fullName>
            </value>
            <value>
                <fullName>Mètre</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/DEV_Charg_daffaire__c.field-meta.xml
<CustomField>
    <fullName>DEV_Charg_daffaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Permet d&apos;indiquer le nom du chargé d&apos;affaire</description>
    <inlineHelpText>Indiquer le nom du chargé d&apos;affaire lorsque vous accepté un Devis</inlineHelpText>
    <label>Chargé d&apos;affaire</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Devis1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/USER_ByPassProcessBuilder__c.field-meta.xml
<CustomField>
    <fullName>USER_ByPassProcessBuilder__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ByPass Process Builder</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/USER_ByPassRegleValidation__c.field-meta.xml
<CustomField>
    <fullName>USER_ByPassRegleValidation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ByPass Règle de validation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/DataFactorySobjetcs.cls
/**
* @description       : 
* @author            : SCHIBOUT
* @group             : 
* @last modified on  : 13-10-2021
* @last modified by  : SCHIBOUT
**/
public class DataFactorySobjetcs {
    
    
    /**
    * @description 
    * @author SCHIBOUT | 08-10-2021 
    * @param accountName 
    * @return Account 
    **/
    public static Account CreateSingleAccounts (String accountName, Boolean insertNow) { 
        
        Account newAccount=new Account(Name='BatchAccountVisionSynchroTest',
        ShippingCity='Lebanon',
        ACC_Entite_BW__c='1',
        ShippingPostalCode='123',
        RecordTypeId = '0120O000000kqi1',
        ACC_SecteurCommercial__c='1',
        ACC_Region__c = '1',
        ACC_SIREN__c='123456789');
        if (insertNow) insert newAccount;
        return newAccount;
    }
    
    public static List<HeaderGpicFile__c> getFileHerders() {
        
        //List<HeaderGpicFile__c> = System.Test.loadData(sobjectType, staticResourceName)
        return (System.Test.loadData(HeaderGpicFile__c.sObjectType, 'gpicFile'));
    }
    /**
    * @description 
    * @author SCHIBOUT | 11-10-2021 
    * @param AccountId 
    * @param closeDate 
    * @param stageName 
    * @param entryName 
    * @param insertNow 
    * @return Opportunity 
    **/
    public static Opportunity createSingleOppy(Id AccountId,Date closeDate,String stageName, String entryName, Boolean insertNow){
        opportunity Opp =new opportunity(AccountId = AccountId,
        closedate=closeDate,
        stageName=stageName,
        Name = entryName);
        if (insertNow) insert Opp;
        return Opp;                         
    }
    
    public static Opportunity createOppyWithAccount(String entryName, Boolean insertNow) {
        Account acct = CreateSingleAccounts(entryName, true);
        Opportunity oppy = createSingleOppy(acct.Id, Date.today() +30 , 'Qualification', entryName, insertNow);
        return Oppy ;
    }
    
    public static Order createSingleOrderWithOppyAndAccount(String entryName) {
        return null ;
    }
    
    public static User getRandomUser() {
        return [SELECT Id FROM User WHERE IsActive = true LIMIT 1];
    }
    
    /**
    * @description 
    * @author SCHIBOUT | 08-10-2021 
    * @param objectApiName 
    * @param fieldName 
    * @return List<String> 
    **/
    public static List<String> getPicklistValues(String objectApiName,String fieldName){ 
        
        List<String> lstPickvals=new List<String>();
        Schema.SObjectType targetType = Schema.getGlobalDescribe().get(objectApiName);//From the Object Api name retrieving the SObject
        Sobject objectName = targetType.newSObject();
        Schema.sObjectType sobjectType = objectName.getSObjectType(); //grab the sobject that was passed
        Schema.DescribeSObjectResult sobjectDescribe = sobjectType.getDescribe(); //describe the sobject
        Map<String, Schema.SObjectField> fieldMap = sobjectDescribe.fields.getMap(); //get a map of fields for the passed sobject
        List<Schema.PicklistEntry> pickListValues = fieldMap.get(fieldName).getDescribe().getPickListValues(); //grab the list of picklist values for the passed field on the sobject
        for (Schema.PicklistEntry a : pickListValues) { //for all values in the picklist list
            lstPickvals.add(a.getValue());//add the value  to our final list
        }
        
        return lstPickvals;
    }
    public static List<Account> getAccounts () {
        
        return (System.Test.loadData(Account.sObjectType, 'Account'));
    }
    
    /**
    * @description 
    * @author SCHIBOUT | 12-10-2021 
    * @return List<Opportunity> 
    **/
    public static List<Opportunity> getOpportunitys () {
        
        return (System.Test.loadData(Opportunity.sObjectType, 'Opportunity'));
    }
    /**
    * 
    */
    public static List<Product2> getProduct2s () {
        
        return (System.Test.loadData(Product2.sObjectType, 'Product2'));
    }
    
    /**
    * @description 
    * @author SCHIBOUT | 12-10-2021 
    * @return User 
    **/
    public static User getApiUser() {
        
        User API=[SELECT Id, USER_ByPassRegleValidation__c, USER_ByPassProcessBuilder__c
        FROM User 
        WHERE lastName=:label.API
        LIMIT 1];
        API.USER_ByPassRegleValidation__c=true;
        API.USER_ByPassProcessBuilder__c = true;
        update API;
        return API;
        
    }   
    
    /**
    * @description 
    * @author SCHIBOUT | 12-10-2021 
    * @return Id 
    **/
    public static Id getPricebookId(){
        Pricebook2 standardPricebook = new Pricebook2(
        Id = Test.getStandardPricebookId(),
        IsActive = true );
        update standardPricebook;
        Id StandardPricebookID = Test.getStandardPricebookId();
        return StandardPricebookID ;       
    }
    
    /**
    * @description 
    * @author SCHIBOUT | 12-10-2021 
    * @param entryName 
    * @param insertNow 
    * @return Quote 
    **/
    public static Quote createSingleQuote(String entryName,Boolean insertNow) {
        Opportunity Oppy = createOppyWithAccount(entryName, true);
        Id StandardPricebookID = getPricebookId();
        Quote Newquote=new quote(Name=entryName,
        opportunityId=Oppy.Id,
        status='4',
        pricebook2Id=StandardPricebookID,
        DEV_Charg_daffaire__c=getRandomUser().Id
        );
        if (insertNow) insert Newquote;
        return Newquote ;                              
    }
    
    public static QuoteLineItem createQuoteLineItem (Id QuoteId, Decimal Quantity ,Boolean insertNow) {
        QuoteLineItem qutlineitemtest = new QuoteLineItem(QuoteId = QuoteId , Quantity = Quantity  ,UnitPrice = 12 , PricebookEntryId = createPricebookEntry(true).Id);
        if (insertNow) insert qutlineitemtest;
        return qutlineitemtest ;     
    }
    /**
    * 
    */
    public static Product2 createProduct(Boolean insertNow) {
        product2 newproduct2=new product2(Name='Test product',IsActive=true);
        if (insertNow) insert newproduct2;
        return newproduct2 ; 
    }
    
    public static PricebookEntry createPricebookEntry(Boolean insertNow) {
        PricebookEntry newPricebookEntry=new PricebookEntry(pricebook2Id=getPricebookId(),
        product2Id=createProduct(true).Id,
        unitPrice=200,
        UnitePrixPar__c='Heure',
        IsActive=true);
        if (insertNow) insert newPricebookEntry;
        return newPricebookEntry ; 
    }
    
    public static Order createSingleOrder(Quote qte,Boolean insertNow) {
        order newOrder=new Order();
        newOrder.EffectiveDate=Date.today() ;
        newOrder.ORD_MontantHT_ERP__c =200 ;
        newOrder.quoteId = qte.Id ;
        newOrder.AccountId=qte.AccountId ;
        newOrder.status='3';
        if (insertNow) insert newOrder;
        return newOrder ; 
        
    }
    
    public static Order createFullSingleOrder(String entryName,Boolean insertNow) {
        Quote qte = createSingleQuote(entryName, insertNow);
        QuoteLineItem qlte = createQuoteLineItem (qte.Id, 10 , insertNow);
        order newOrder=new Order();
        newOrder.EffectiveDate=Date.today() ;
        newOrder.ORD_MontantHT_ERP__c =200 ;
        newOrder.quoteId = qte.Id ;
        newOrder.AccountId=qte.AccountId ;
        newOrder.status='3';
        if (insertNow) insert newOrder;
        return newOrder ; 
        
    }
}