force-app/main/default/objects/Account/fields/Acc_CodeAgence__c.field-meta.xml
<CustomField>
    <fullName>Acc_CodeAgence__c</fullName>
    <label>Code Agence Régionale BW</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Acc_CodeSecteur__c.field-meta.xml
<CustomField>
    <fullName>Acc_CodeSecteur__c</fullName>
    <label>Code Secteur Commercial</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ACC_Entite_BW__c.field-meta.xml
<CustomField>
    <fullName>ACC_Entite_BW__c</fullName>
    <label>Entité BW</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>EntiteBW</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ACC_Region__c.field-meta.xml
<CustomField>
    <fullName>ACC_Region__c</fullName>
    <label>Agence régionale BW</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ACC_Entite_BW__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>AgenceRegionaleBW</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ACC_SecteurCommercial__c.field-meta.xml
<CustomField>
    <fullName>ACC_SecteurCommercial__c</fullName>
    <label>Secteur commercial</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ACC_Region__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>SecteurCommercial</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ACC_SIREN__c.field-meta.xml
<CustomField>
    <fullName>ACC_SIREN__c</fullName>
    <label>SIREN</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BwTranscodification__c/BwTranscodification__c.object-meta.xml
<CustomObject>
    <description>Objets comportant les différents valeurs des systems</description>
    <label>Transcodification</label>
    <nameField>
        <displayFormat>TRS-{0000}</displayFormat>
        <label>Transcodification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transcodifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BwTranscodification__c/fields/DataType__c.field-meta.xml
<CustomField>
    <fullName>DataType__c</fullName>
    <label>DataType</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BU</fullName>
            </value>
            <value>
                <fullName>Agence Régionale</fullName>
            </value>
            <value>
                <fullName>Sous domaine</fullName>
            </value>
            <value>
                <fullName>Secteur</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BwTranscodification__c/fields/MbApi__c.field-meta.xml
<CustomField>
    <fullName>MbApi__c</fullName>
    <label>Mobility API</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BwTranscodification__c/fields/VsApi__c.field-meta.xml
<CustomField>
    <fullName>VsApi__c</fullName>
    <label>Vision API</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/USER_ByPassProcessBuilder__c.field-meta.xml
<CustomField>
    <fullName>USER_ByPassProcessBuilder__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ByPass Process Builder</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/USER_ByPassRegleValidation__c.field-meta.xml
<CustomField>
    <fullName>USER_ByPassRegleValidation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ByPass Règle de validation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/BatchAccountVisionSynchroTest.cls
@isTest
public class BatchAccountVisionSynchroTest {
		@IsTest
 		static void methodName(){
        user API=[SELECT USER_ByPassRegleValidation__c, USER_ByPassProcessBuilder__c
        FROM user 
        WHERE lastName=:label.API
        LIMIT 1];

        API.USER_ByPassRegleValidation__c=true;
        API.USER_ByPassProcessBuilder__c = true;

        update API;
        Test.startTest();
        System.runAs(API){
        
        System.debug('Setup data'+getPicklistValues('Account','ACC_Region__c'));
        //List<Account> acctList = Test.loadData(Account.sObjectType, 'Account');
        Account newAccount=new Account(Name='BatchAccountVisionSynchroTest',
        ShippingCity='Lebanon',
        ACC_Entite_BW__c='1',
        ShippingPostalCode='123',
		RecordTypeId = '0120O000000kqi1',
		ACC_SecteurCommercial__c='1',
        ACC_Region__c = '1',
        ACC_SIREN__c='123456789');
        insert newAccount;
        
        List<Account> acctListResult =[SELECT Name FROM Account WHERE Name LIKE 'BatchAccountVisionSynchroTest'];
        System.assertEquals(1, acctListResult.size() , 'Not Good' );

        List<BwTranscodification__c> transcoList = new List<BwTranscodification__c>();
        transcoList.add(new BwTranscodification__c(DataType__c='Sous domaine',MbApi__c='36',VsApi__c='LOC'));
        transcoList.add(new BwTranscodification__c(DataType__c='BU',MbApi__c='36',VsApi__c='LOC'));
        transcoList.add(new BwTranscodification__c(DataType__c='Agence Régionale',MbApi__c='1',VsApi__c='LOC'));
        transcoList.add(new BwTranscodification__c(DataType__c='Secteur',MbApi__c='1',VsApi__c='LOC'));
        Database.insert(transcoList,false);
		System.assertEquals(4, transcoList.size() , 'BwTranscodification__c Not Good' );
    
        BatchAccountVisionSynchro.run();
        /*List<Account> acctList1 =[SELECT Id,ACC_SecteurCommercial__c,Acc_CodeSecteur__c,Acc_CodeAgence__c,ACC_Region__c  FROM Account WHERE Name LIKE 'BatchAccountVisionSynchroTest'];
        
        system.assertEquals (acctList1.size() , 1,'Not Equals Test Methode');
        For(Account acct :acctList1) {
         System.assertEquals('LOC', acct.Acc_CodeSecteur__c,'Code secteur');
         System.assertEquals('LOC', acct.Acc_CodeAgence__c,'Code region');
        }*/

    }
}
     /**
   * 
   */
        public static List<String> getPicklistValues(String objectApiName,String fieldName){ 

            List<String> lstPickvals=new List<String>();
            Schema.SObjectType targetType = Schema.getGlobalDescribe().get(objectApiName);//From the Object Api name retrieving the SObject
            Sobject objectName = targetType.newSObject();
            Schema.sObjectType sobjectType = objectName.getSObjectType(); //grab the sobject that was passed
            Schema.DescribeSObjectResult sobjectDescribe = sobjectType.getDescribe(); //describe the sobject
            Map<String, Schema.SObjectField> fieldMap = sobjectDescribe.fields.getMap(); //get a map of fields for the passed sobject
            List<Schema.PicklistEntry> pickListValues = fieldMap.get(fieldName).getDescribe().getPickListValues(); //grab the list of picklist values for the passed field on the sobject
            for (Schema.PicklistEntry a : pickListValues) { //for all values in the picklist list
            lstPickvals.add(a.getValue());//add the value  to our final list
        }

        return lstPickvals;
        }
}