force-app/main/default/objects/Account/fields/ACC_Entite_BW__c.field-meta.xml
<CustomField>
    <fullName>ACC_Entite_BW__c</fullName>
    <label>Entité BW</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>EntiteBW</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ACC_Langue_Documentation__c.field-meta.xml
<CustomField>
    <fullName>ACC_Langue_Documentation__c</fullName>
    <label>Langue de Documentation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Anglais</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Français</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Allemand</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Italien</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Espagnol</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ACC_SIREN__c.field-meta.xml
<CustomField>
    <fullName>ACC_SIREN__c</fullName>
    <label>SIREN</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DEV_Ajout_Piece_Jointe__c.field-meta.xml
<CustomField>
    <fullName>DEV_Ajout_Piece_Jointe__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ajout_Piece-Jointe</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DEV_Charg_daffaire__c.field-meta.xml
<CustomField>
    <fullName>DEV_Charg_daffaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Permet d&apos;indiquer le nom du chargé d&apos;affaire</description>
    <inlineHelpText>Indiquer le nom du chargé d&apos;affaire lorsque vous accepté un Devis</inlineHelpText>
    <label>Chargé d&apos;affaire</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Devis1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DEV_DelaisLivraison__c.field-meta.xml
<CustomField>
    <fullName>DEV_DelaisLivraison__c</fullName>
    <inlineHelpText>This field contains the Delivery Terms in weeks. 
Termini di consegna in settimane dalla ricezione dell&apos;ordine o dalla ricezione del pagamento</inlineHelpText>
    <label>Délais Livraison</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DEV_NumCommandeClient__c.field-meta.xml
<CustomField>
    <fullName>DEV_NumCommandeClient__c</fullName>
    <label>N° Commande du client</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/USER_ByPassRegleValidation__c.field-meta.xml
<CustomField>
    <fullName>USER_ByPassRegleValidation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ByPass Règle de validation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/USER_EntiteBW__c.field-meta.xml
<CustomField>
    <fullName>USER_EntiteBW__c</fullName>
    <label>Entité BW</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>EntiteBW</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/AP01_Quote_Test.cls
@isTest
public class AP01_Quote_Test {
    
    @isTest 
    static  void AddAttachment() {
        User u = [Select id, name, email from User where id=: UserInfo.getUserId()];
        u.USER_ByPassRegleValidation__c=true;
        u.USER_EntiteBW__c=Label.BW_ITA;
        Update u;
        System.runAs(u) {
            
             Account newAccount = new Account (Name = 'Test Account 1', ShippingCity = 'Lebanon', 
                                              ShippingPostalCode = '123', ACC_SIREN__c = '123456789');
            newAccount.ACC_Entite_BW__c=Label.BW_ITA ;
            newAccount.ACC_Langue_Documentation__c='4';
            insert newAccount;
        opportunity newOpportunity=new opportunity();
        newOpportunity.name='Test Opportunity';
        newOpportunity.closedate=Date.today() + 10;
        newOpportunity.stageName='Qualification';
            newOpportunity.AccountId=newAccount.id;
        insert newOpportunity;
        
        Pricebook2 standardPricebook = new Pricebook2(
            Id = Test.getStandardPricebookId(),
            IsActive = true );
        update standardPricebook;
        Id StandardPricebookID = Test.getStandardPricebookId();
        
        quote Newquote=new quote(Name='Test quote',
                                 opportunityId=newOpportunity.Id,
                                 status='1',
                                 DEV_Ajout_Piece_Jointe__c=false,
                                 DEV_NumCommandeClient__c='123',
                                 DEV_Charg_daffaire__c = UserInfo.getUserId(),
                                 pricebook2Id=StandardPricebookID);
        insert Newquote;
        
        
        quote Newquote3=new quote(Name='Test quote 3',
                                 opportunityId=newOpportunity.Id,
                                 status='2', 
                                 DEV_Ajout_Piece_Jointe__c=false,
                                 DEV_DelaisLivraison__c=22,
                                 DEV_Charg_daffaire__c = UserInfo.getUserId(),
                                 pricebook2Id=StandardPricebookID);
        insert Newquote3;
        
        //contentversion creation
        ContentVersion cv1 = new ContentVersion();
        cv1.title = 'Tariffe estero_ita'; 
        cv1.PathOnClient = 'Tariffe estero_ita.pdf';
        cv1.VersionData =Blob.valueOf('Unit Test Attachment Body');
        insert cv1;
        
        
        Quote NewQuote2 = [select id from quote where id =: Newquote.Id];
        NewQuote2.DEV_Ajout_Piece_Jointe__c=true; 
        update NewQuote2;
        
        List<Quote> lstQuote = new List<Quote>();
        
        Map<Id, Quote> oldmap = new Map<Id, Quote> (); 
        oldmap.put(Newquote3.Id, Newquote3);
        List<ContentDocumentLink> CheckCDL =[select id, LinkedEntity.id from ContentDocumentLink where LinkedEntity.id=:NewQuote2.id];
       // system.assertEquals(1, CheckCDL.size());
        Test.startTest();
        Newquote3.Status = '3'; 
       	update Newquote3;
        lstQuote.add(Newquote3);
        AP01_Quote.updateDateLivraisonOppt(lstQuote, oldmap);
        Test.stopTest();
    }
    }
}