force-app/main/default/objects/Account/fields/ACC_SIREN__c.field-meta.xml
<CustomField>
    <fullName>ACC_SIREN__c</fullName>
    <label>SIREN</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DEV_NumCommandeClient__c.field-meta.xml
<CustomField>
    <fullName>DEV_NumCommandeClient__c</fullName>
    <label>N° Commande du client</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DEV_TypeDeDevis__c.field-meta.xml
<CustomField>
    <fullName>DEV_TypeDeDevis__c</fullName>
    <label>Type de devis</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Devis SF</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Devis ERP</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Devis Hors-Système</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/Tech_Talend_Export_Devis__c.field-meta.xml
<CustomField>
    <fullName>Tech_Talend_Export_Devis__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Si cette case est cochée &gt;&gt; Export vers Talend</description>
    <label>Tech_Talend_Export_Devis</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/USER_ByPassRegleValidation__c.field-meta.xml
<CustomField>
    <fullName>USER_ByPassRegleValidation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ByPass Règle de validation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Test_AP01_Account.cls
@isTest
public class Test_AP01_Account {
    
    public static testMethod void test_AccountAfterUpdate()  { 
        
        user API=[SELECT USER_ByPassRegleValidation__c 
                  FROM user 
                  WHERE lastName=:label.API
                  LIMIT 1];
        API.USER_ByPassRegleValidation__c=true;
        
        update API;
        
        System.runAs(API){
            
           Account newAccount=new Account(Name='Test Account For Update Quote',
                                           ShippingCity='Lebanon',
                                           ShippingPostalCode='123',
                                           RecordTypeId = '0120O000000kqhw',
                                           ACC_SIREN__c='123456789');
            insert newAccount;
            
            opportunity newOpportunity=new opportunity();
            newOpportunity.AccountId = newAccount.Id;
            newOpportunity.name='Test Opportunity For Update Quote';
            newOpportunity.closedate=Date.today() + 10;
            newOpportunity.stageName='Fermée Gagnée';
            insert newOpportunity;
            
            Id StandardPricebookID = Test.getStandardPricebookId();
            
            quote Newquote=new quote(Name='Test quote For Update Quote',
                                     opportunityId=newOpportunity.Id,
                                     status='3',
                                     DEV_TypeDeDevis__c = '1',
                                     DEV_NumCommandeClient__c='123',
                                     pricebook2Id=StandardPricebookID);
            insert Newquote;
            
         
           /* 
            list<order> listNewOrders=new list<order>();
            
            order newOrder1=new Order();
            newOrder1.AccountId=newAccount.Id;
            newOrder1.EffectiveDate=Date.today() + 10;
            newOrder1.status='3';
            newOrder1.quoteId=Newquote.Id;
            listNewOrders.add(newOrder1);
            
            order newOrder2=new Order();
            newOrder2.AccountId=newAccount.Id;
            newOrder2.EffectiveDate=Date.today() + 10;
            newOrder2.status='3';
            newOrder2.quoteId=Newquote.Id;
            listNewOrders.add(newOrder2);
            
            insert listNewOrders;
            
            order Orderpricebook=[SELECT pricebook2Id
                                  FROM order
                                  LIMIT 1]; 
            
            */
            
           test.startTest();
            
            newAccount.RecordTypeId = '0120O000000kqi1'; 
            update newAccount;
        
           test.stopTest();
           

            List <Quote> listNewQuotes=[SELECT Id, Tech_Talend_Export_Devis__c 
                                  FROM Quote
                                  where Id =: Newquote.Id
                                  LIMIT 1]; 
            
           system.assert(listNewQuotes[0].Tech_Talend_Export_Devis__c , True);
            
        }
    }
}