force-app/main/default/objects/Account/fields/ACC_revenu_n_1__c.field-meta.xml
<CustomField>
    <fullName>ACC_revenu_n_1__c</fullName>
    <label>Revenu n-1</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/ACC_revenu_n_2__c.field-meta.xml
<CustomField>
    <fullName>ACC_revenu_n_2__c</fullName>
    <label>Revenu n-2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/ACC_Revenu_n__c.field-meta.xml
<CustomField>
    <fullName>ACC_Revenu_n__c</fullName>
    <label>Revenu n</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order/fields/ORD_BusinessUnit__c.field-meta.xml
<CustomField>
    <fullName>ORD_BusinessUnit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>3</fullName>
                <label>Chaudières</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Traitement de l&apos;eau</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Air</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Services</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Location</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>INCINEX</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/ORD_MontantERP__c.field-meta.xml
<CustomField>
    <fullName>ORD_MontantERP__c</fullName>
    <label>Montant TTC ERP</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order/fields/ORD_MontantHT_ERP__c.field-meta.xml
<CustomField>
    <fullName>ORD_MontantHT_ERP__c</fullName>
    <label>Montant HT ERP</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order/fields/ORD_SousDomaine__c.field-meta.xml
<CustomField>
    <fullName>ORD_SousDomaine__c</fullName>
    <label>Sous-Domaine</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>ADOUCISSEUR</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>AÉROTHERMES</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>AUTRES CHAUDIÈRES</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>AUTRES TA SPÉCIFIQUES</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>AUTRES TA STANDARD</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>AUTRES TE SPECIFIQUES</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>AUTRES TE STANDARD</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>BACHE DÉGAZANTE</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>BRÚLEURS</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>BWB</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>BWD</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>BWR</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>CENTRALE FOYER ÉCHANGEUR</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>CHAUDIERES EAU CHAUDE &lt; 5MW</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>CHAUDIÈRE VAPORISATION BASSE PRESSION</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>CONTRATS CHAUDIÈRES</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>CHAUDIERES EAU CHAUDE &gt; 5MW</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>CONTRAT LOW COST</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>CONTRATS AIR</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>CONTRATS EAU</label>
            </value>
            <value>
                <fullName>21</fullName>
                <label>CONTRATS GLOBAUX</label>
            </value>
            <value>
                <fullName>22</fullName>
                <label>DÉCARBONATATION</label>
            </value>
            <value>
                <fullName>23</fullName>
                <label>DÉGAZEURS</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>DÉMINÉRALISATION</label>
            </value>
            <value>
                <fullName>25</fullName>
                <label>EQUIPEMENT / INSTALLATION</label>
            </value>
            <value>
                <fullName>26</fullName>
                <label>EQUIPEMENTS CHAUFFERIE</label>
            </value>
            <value>
                <fullName>27</fullName>
                <label>FILTRES</label>
            </value>
            <value>
                <fullName>28</fullName>
                <label>FORMATION</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>GENERATEUR</label>
            </value>
            <value>
                <fullName>31</fullName>
                <label>GROS TRAVAUX</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Batch_AccCaluculateRevenu.cls
//
//   This batch send the ecriture
//  
//  
// 
global class Batch_AccCaluculateRevenu implements Database.Batchable<sObject>,  Database.Stateful, Schedulable{
    
    global Database.QueryLocator start(Database.BatchableContext info){
     List<AsyncApexJob> previousJobList = [SELECT Id, CompletedDate  FROM AsyncApexJob WHERE ApexClass.Name ='Batch_AccCaluculateRevenu' 
                                    AND CompletedDate != null ORDER BY CompletedDate desc];
         Datetime previousRundate ;                            	
        if (previousJobList.size()> 0)   { previousRundate = previousJobList[0].CompletedDate ;}
        else {
            previousRundate = Date.today()-1 ; }

        return Database.getQueryLocator([SELECT Id, ACC_Revenu_n__c, ACC_revenu_n_1__c,ACC_revenu_n_2__c FROM Account WHERE LastModifiedDate >= :previousRundate ]);
    } 

global void execute(Database.BatchableContext BC, List<Account> accountList){

//UserInfo.USER_ByPassRegleValidation__c = true ;


Date  lowDate =date.valueOf(((System.now().year())-2)+'-01-01');
Map<Id, Account> accountMap = new Map<Id,Account>(accountList);
Set<Id> accountIds = accountMap.keySet();


List<Order> orderList = [SELECT TotalAmount,ORD_MontantHT_ERP__c, ORD_MontantERP__c,EffectiveDate,AccountId,ORD_SousDomaine__c,ORD_BusinessUnit__c  
                         FROM Order WHERE AccountId IN :accountIds  AND EffectiveDate >= :lowDate Order by AccountId ];
 Integer numberElement = orderList.size();
 Double revenu_n = 0 , revenu_n_1=0, revenu_n_2=0, erpAmount=0;
 Id currentAccountId =  null;
 Integer currentYear = System.Today().year();
 Integer  count = 0 ; 
 List<Account> accountListToUpdate = new List<Account>();
for (Order ord : orderList) {
    if (count == 0) currentAccountId = ord.AccountId ;
    if (ord.ORD_MontantHT_ERP__c !=null){erpAmount = ord.ORD_MontantHT_ERP__c ;} else{erpAmount =0 ;} 
    Account acct = (Account)accountMap.get(currentAccountId);
    if ((currentAccountId != ord.AccountId) && (count != numberElement-1)) {
		if ((acct.ACC_Revenu_n__c != revenu_n)||(acct.ACC_revenu_n_1__c != revenu_n_1 )||(acct.ACC_revenu_n_2__c != revenu_n_2 )) { 
			acct.ACC_Revenu_n__c = revenu_n ;
            acct.ACC_revenu_n_1__c = revenu_n_1 ;
            acct.ACC_revenu_n_2__c = revenu_n_2 ;
            accountListToUpdate.add(acct);
		}
        revenu_n = 0 ;  
        revenu_n_1 = 0 ;
        revenu_n_2 = 0 ;
        currentAccountId = ord.AccountId ;
    }
    
    if (ord.EffectiveDate.year() ==  currentYear) Revenu_n = Revenu_n  + erpAmount ;
    if (ord.EffectiveDate.year() ==  currentYear - 1) revenu_n_1 = revenu_n_1  + erpAmount ;
    if (ord.EffectiveDate.year() ==  currentYear - 2) revenu_n_2 = revenu_n_2  + erpAmount ; 
     
    if (count == numberElement-1) {
        acct = (Account)accountMap.get(ord.AccountId);
		if ((acct.ACC_Revenu_n__c != revenu_n)||(acct.ACC_revenu_n_1__c != revenu_n_1 )||(acct.ACC_revenu_n_2__c != revenu_n_2 )) { 
			if (acct.ACC_Revenu_n__c != Revenu_n )acct.ACC_Revenu_n__c = Revenu_n ;
			if (acct.ACC_revenu_n_1__c != revenu_n_1) acct.ACC_revenu_n_1__c = revenu_n_1;
			if (acct.ACC_revenu_n_2__c != revenu_n_2)acct.ACC_revenu_n_2__c = revenu_n_2 ;
			accountListToUpdate.add(acct);
		}
    }
  count++;
}
    Database.SaveResult[] srList = Database.update(accountListToUpdate, false);
}
global void finish(Database.BatchableContext BC){
    
}

global void execute(SchedulableContext sc) {
    Batch_AccCaluculateRevenu batch = new Batch_AccCaluculateRevenu();
    Database.executeBatch(batch);
}

global static void run(){
    Batch_AccCaluculateRevenu batch = new Batch_AccCaluculateRevenu();
    Database.executeBatch(batch);
}
}