force-app/main/default/objects/Account/fields/ACC_SIREN__c.field-meta.xml
<CustomField>
    <fullName>ACC_SIREN__c</fullName>
    <label>SIREN</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/ASS_Commande__c.field-meta.xml
<CustomField>
    <fullName>ASS_Commande__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Commande</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Équipements</relationshipLabel>
    <relationshipName>Equipements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/ASS_NumeroIdentite__c.field-meta.xml
<CustomField>
    <fullName>ASS_NumeroIdentite__c</fullName>
    <description>Numéro d&apos;identification de l&quot;équipement</description>
    <label>Numéro d&apos;identité</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Produit_command__c.field-meta.xml
<CustomField>
    <fullName>Produit_command__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produit commandé</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Équipements</relationshipLabel>
    <relationshipName>equipements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/recordTypes/Equipement.recordType-meta.xml
<RecordType>
    <fullName>Equipement</fullName>
    <active>true</active>
    <description>Equipement client</description>
    <label>Equipement</label>
</RecordType>

force-app/main/default/objects/Order/fields/ORD_ReferenceCommande__c.field-meta.xml
<CustomField>
    <fullName>ORD_ReferenceCommande__c</fullName>
    <externalId>true</externalId>
    <label>Numéro de commande BW (Référence ERP)</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Equipement_cree__c.field-meta.xml
<CustomField>
    <fullName>Equipement_cree__c</fullName>
    <defaultValue>false</defaultValue>
    <description>La case est cochée automatiquement quand un équipment est créé sur le produit commandé</description>
    <label>Equipement créé</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/PC_Numero_de_PFI__c.field-meta.xml
<CustomField>
    <fullName>PC_Numero_de_PFI__c</fullName>
    <formula>Order.ORD_ReferenceCommande__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Numéro de PFI</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/UnitePrixPar__c.field-meta.xml
<CustomField>
    <fullName>UnitePrixPar__c</fullName>
    <label>Unité (Prix Par)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Heure</fullName>
            </value>
            <value>
                <fullName>Jour</fullName>
            </value>
            <value>
                <fullName>Année</fullName>
            </value>
            <value>
                <fullName>Intervention</fullName>
            </value>
            <value>
                <fullName>Produit</fullName>
            </value>
            <value>
                <fullName>Bidon</fullName>
            </value>
            <value>
                <fullName>Fût</fullName>
            </value>
            <value>
                <fullName>IBC</fullName>
            </value>
            <value>
                <fullName>Sac</fullName>
            </value>
            <value>
                <fullName>Tonneau</fullName>
            </value>
            <value>
                <fullName>Unité</fullName>
            </value>
            <value>
                <fullName>KG</fullName>
            </value>
            <value>
                <fullName>KM</fullName>
            </value>
            <value>
                <fullName>LT</fullName>
            </value>
            <value>
                <fullName>GG</fullName>
            </value>
            <value>
                <fullName>MQ</fullName>
            </value>
            <value>
                <fullName>MC</fullName>
            </value>
            <value>
                <fullName>Mètre</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Equipement.recordType-meta.xml
<RecordType>
    <fullName>Equipement</fullName>
    <active>true</active>
    <label>Equipement</label>
</RecordType>

force-app/main/default/classes/Test_VFC01_GenererEquipment.cls
@isTest
public class Test_VFC01_GenererEquipment {
    public static testmethod void test_insertEquipment(){
        
        Account newAccount=new Account(Name='Test Account',
                                       ShippingCity='Lebanon',
                                       ShippingPostalCode='123',
                                       ACC_SIREN__c='012345678');
        insert newAccount;
        
        Id pricebookId = Test.getStandardPricebookId();
        
        order newOrder=new Order();
        newOrder.AccountId=newAccount.Id;
        newOrder.EffectiveDate=Date.today() + 10;
        newOrder.status='3';
        newOrder.pricebook2Id=pricebookId;
        newOrder.ORD_ReferenceCommande__c='PFITEST01';
        
        
        insert newOrder;
        
        product2 newproduct2=new product2(Name='Test product',IsActive=true);
        insert newproduct2;
        
        PricebookEntry newPricebookEntry=new PricebookEntry(pricebook2Id=pricebookId,
                                                            product2Id=newproduct2.Id,
                                                            unitPrice=200,
                                                            UnitePrixPar__c='Heure',
                                                            IsActive=true);
        insert newPricebookEntry;
        
        OrderItem newOrderItem=new OrderItem();
        newOrderItem.OrderId = newOrder.Id;
        newOrderItem.Product2Id = newproduct2.Id;
        newOrderItem.quantity = 2;
        newOrderItem.UnitPrice = 150;
        newOrderItem.PricebookentryId = newPricebookEntry.Id;

                
        insert newOrderItem;
        
        PageReference pageRef = Page.VFP01_GenererEquipement;
        Test.setCurrentPage(pageRef);
        pageRef.getParameters().put('id',newOrderItem.Id);
        ApexPages.StandardController sc = new ApexPages.StandardController(newOrderItem);
        VFC01_GenereEquipment init =new VFC01_GenereEquipment(sc);
        init.createAsset();
        Asset insertedAsset=[SELECT Name,RecordTypeId,AccountId,Product2Id,ASS_Commande__c,Produit_command__c,ASS_NumeroIdentite__c
                             FROM Asset];
        
        OrderItem infoOrderItem=[SELECT product2.Name,order.AccountId,Product2Id,OrderId,Equipement_cree__c,PC_Numero_de_PFI__c
                                 FROM orderItem];
        
        system.assert(insertedAsset.Name==infoOrderItem.product2.Name);
        system.assert(insertedAsset.RecordTypeId==Schema.SObjectType.Asset.getRecordTypeInfosByDeveloperName().get(label.Equipement).getRecordTypeId()); 
        system.assert(insertedAsset.Product2Id==infoOrderItem.Product2Id);
        system.assert(insertedAsset.ASS_Commande__c==infoOrderItem.OrderId);
        system.assert(insertedAsset.Produit_command__c==infoOrderItem.Id); 
        system.assert(insertedAsset.ASS_NumeroIdentite__c==infoOrderItem.PC_Numero_de_PFI__c);
      

        
        PageReference pageRefFail = Page.VFP01_GenererEquipement;
        Test.setCurrentPage(pageRefFail);
        pageRefFail.getParameters().put('id',newOrderItem.Id);
        ApexPages.StandardController scFail = new ApexPages.StandardController(newOrderItem);
        VFC01_GenereEquipment initFail =new VFC01_GenereEquipment(scFail);
        initFail.createAsset();
        
        list<asset> listAssets=[SELECT Id
                                FROM asset]; 
    }
}