force-app/main/default/objects/Account/fields/ACC_Entite_BW__c.field-meta.xml
<CustomField>
    <fullName>ACC_Entite_BW__c</fullName>
    <label>Entité BW</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>EntiteBW</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OPP_Domaine__c/OPP_Domaine__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Transcodification de la liste domaine dans Opportunité</description>
    <label>OPP_Domaine</label>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/OPP_Domaine__c.field-meta.xml
<CustomField>
    <fullName>OPP_Domaine__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>3</fullName>
                <label>Chaudières</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Traitement de l&apos;eau</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Air</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Services</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Location</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>INCINEX</label>
            </value>
            <value>
                <fullName>19</fullName>
                <isActive>false</isActive>
                <label>AST : AIR STANDARD</label>
            </value>
            <value>
                <fullName>18</fullName>
                <isActive>false</isActive>
                <label>ESP : EAU SPECIFIQUES</label>
            </value>
            <value>
                <fullName>22</fullName>
                <isActive>false</isActive>
                <label>EST : EAU STANDARDS</label>
            </value>
            <value>
                <fullName>7</fullName>
                <isActive>false</isActive>
                <label>GTX : GROS TRAVAUX</label>
            </value>
            <value>
                <fullName>8</fullName>
                <isActive>false</isActive>
                <label>INV : INVESTISSEMENT</label>
            </value>
            <value>
                <fullName>9</fullName>
                <isActive>false</isActive>
                <label>LOC : LOCATION</label>
            </value>
            <value>
                <fullName>10</fullName>
                <isActive>false</isActive>
                <label>MAT : MATÉRIEL THERMIQUE</label>
            </value>
            <value>
                <fullName>11</fullName>
                <isActive>false</isActive>
                <label>OCC : OCCASION</label>
            </value>
            <value>
                <fullName>13</fullName>
                <isActive>false</isActive>
                <label>PRE : PIÈCES DE RECHANGE</label>
            </value>
            <value>
                <fullName>15</fullName>
                <isActive>false</isActive>
                <label>PRJ : PROJET INTERNE</label>
            </value>
            <value>
                <fullName>14</fullName>
                <isActive>false</isActive>
                <label>PRO : PRODUIT CONDITIONNEMENT</label>
            </value>
            <value>
                <fullName>12</fullName>
                <isActive>false</isActive>
                <label>PTX : PETIT TRAVAUX</label>
            </value>
            <value>
                <fullName>16</fullName>
                <isActive>false</isActive>
                <label>RED : RECHERCHE ET DEVELOPPEMENT</label>
            </value>
            <value>
                <fullName>17</fullName>
                <isActive>false</isActive>
                <label>SIN : SINISTRES</label>
            </value>
            <value>
                <fullName>20</fullName>
                <isActive>false</isActive>
                <label>STO : STOCK OCCASION</label>
            </value>
            <value>
                <fullName>21</fullName>
                <isActive>false</isActive>
                <label>TDF : TUBES DE FUMÉES</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/OPP_Special_Project__c.field-meta.xml
<CustomField>
    <fullName>OPP_Special_Project__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Special Project</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/ELD_MainProduct__c.field-meta.xml
<CustomField>
    <fullName>ELD_MainProduct__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Main Product</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/SerieProduit__c.field-meta.xml
<CustomField>
    <fullName>SerieProduit__c</fullName>
    <formula>Text(Product2.PDT_Serie__c)</formula>
    <label>SerieProduit</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Table_de_transcodage__c/Table_de_transcodage__c.object-meta.xml
<CustomObject>
    <label>Table de transcodage</label>
    <nameField>
        <label>Nom de Table de transcodage</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tables de transcodage</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Table_de_transcodage__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <label>Ligne</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Table_de_transcodage__c/fields/Serie__c.field-meta.xml
<CustomField>
    <fullName>Serie__c</fullName>
    <label>Serie</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>LNTA</fullName>
            </value>
            <value>
                <fullName>LNTG</fullName>
            </value>
            <value>
                <fullName>MODULO +</fullName>
            </value>
            <value>
                <fullName>OPTIMO</fullName>
            </value>
            <value>
                <fullName>TA</fullName>
            </value>
            <value>
                <fullName>Mixbloc</fullName>
            </value>
            <value>
                <fullName>REC</fullName>
            </value>
            <value>
                <fullName>SOV</fullName>
            </value>
            <value>
                <fullName>VAP EL</fullName>
            </value>
            <value>
                <fullName>EPC ES</fullName>
            </value>
            <value>
                <fullName>EPC H</fullName>
            </value>
            <value>
                <fullName>ESM</fullName>
            </value>
            <value>
                <fullName>TPC AS</fullName>
            </value>
            <value>
                <fullName>TPC B</fullName>
            </value>
            <value>
                <fullName>TPC LN</fullName>
            </value>
            <value>
                <fullName>TPC LNE</fullName>
            </value>
            <value>
                <fullName>VAP HP</fullName>
            </value>
            <value>
                <fullName>VAP LN</fullName>
            </value>
            <value>
                <fullName>VAP LNE</fullName>
            </value>
            <value>
                <fullName>VAP R</fullName>
            </value>
            <value>
                <fullName>VAP R  PREMIUM</fullName>
            </value>
            <value>
                <fullName>BWD</fullName>
            </value>
            <value>
                <fullName>BWD ESN</fullName>
            </value>
            <value>
                <fullName>BWD Premium</fullName>
            </value>
            <value>
                <fullName>BWR</fullName>
            </value>
            <value>
                <fullName>BWR ESN</fullName>
            </value>
            <value>
                <fullName>HEB</fullName>
            </value>
            <value>
                <fullName>HW3P</fullName>
            </value>
            <value>
                <fullName>HW3S</fullName>
            </value>
            <value>
                <fullName>HWI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AP01_QLI_PrincipalProduct.cls
/*
* Class to check principal product and return error
* @author: Joyce Saidy
* @date: 18-09-2020
* @Test: AP01_QLI_PrincipalProduct_Test
*/
public class AP01_QLI_PrincipalProduct{
    
    public static void CheckQLI(Map<id,Quotelineitem> NewMapQLI)
    {
        
        Set<Id> SetIdQuotes = new Set<Id>();
        Map<id,id> MapOLIidByQuoteid = new  Map<id,id>();
        for(Quotelineitem qli : NewMapQLI.values())
        {
            SetIdQuotes.add(qli.quoteid);
            MapOLIidByQuoteid.put(qli.quoteid, qli.Id);
        }
        
        map <Id, quote> mapIDQuote =  new map <Id, quote>([SELECT id,Opportunity.OPP_Special_Project__c, Opportunity.OPP_Domaine__c, Opportunity.Account.ACC_Entite_BW__c, 
                                                           (select id , ELD_MainProduct__c from QuoteLineItems where ELD_MainProduct__c = True) 
                                                           from quote 
                                                           where Id in :SetIdQuotes
                                                           and Opportunity.OPP_Special_Project__c = FALSE
                                                           and Opportunity.Account.ACC_Entite_BW__c = :Label.BW_ITA
                                                           and( Opportunity.OPP_Domaine__c = :Label.Chaudieres 
                                                               or Opportunity.OPP_Domaine__c=: Label.Traitement_de_leau
                                                               or Opportunity.OPP_Domaine__c= :Label.Air)
                                                          ]); 
        
        if(mapIDQuote != null && mapIDQuote.size()>0)
        {
            For(quote Q : mapIDQuote.values())
            { 
                if(q.QuoteLineItems.size() == 0)
                {
                    NewMapQLI.get(MapOLIidByQuoteid.get(q.id)).addError(label.AP01_QLI_ErrorMsg1) ;
                }
                else if(q.QuoteLineItems.size() > 1)
                {
                    NewMapQLI.get(MapOLIidByQuoteid.get(q.id)).addError(label.AP01_QLI_ErrorMsg2) ; 
                }
            }
            
        }
        
        
    }
    public static void AddErrorTableTransco(List<Quotelineitem> ListNewQLI)
    {
        Map<String, String> tabletranscodagemap = new Map<String, String>();
        List<Table_de_transcodage__c> tabletranscodage = [SELECT Serie__c, Code__c
                                                          FROM Table_de_transcodage__c];
        
        //assign values in the Map<Serie,Code>
        for (Table_de_transcodage__c tb : tabletranscodage) 
        {
            tabletranscodagemap.put(tb.Serie__c, tb.Code__c);  
        }
       for(Quotelineitem NewQLI:ListNewQLI)
       {
          if (NewQLI.SerieProduit__c!=null && tabletranscodagemap.containsKey(NewQLI.SerieProduit__c) && tabletranscodagemap.get(NewQLI.SerieProduit__c)==null)
            { 
                NewQLI.addError(System.Label.Value_not_in_table_de_transcodage);
            }
       }
    }
}