force-app/main/default/objects/Account/fields/ACC_SIREN__c.field-meta.xml
<CustomField>
    <fullName>ACC_SIREN__c</fullName>
    <label>SIREN</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BwTranscodification__c/BwTranscodification__c.object-meta.xml
<CustomObject>
    <description>Objets comportant les différents valeurs des systems</description>
    <label>Transcodification</label>
    <nameField>
        <displayFormat>TRS-{0000}</displayFormat>
        <label>Transcodification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transcodifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BwTranscodification__c/fields/DataType__c.field-meta.xml
<CustomField>
    <fullName>DataType__c</fullName>
    <label>DataType</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BU</fullName>
            </value>
            <value>
                <fullName>Agence Régionale</fullName>
            </value>
            <value>
                <fullName>Sous domaine</fullName>
            </value>
            <value>
                <fullName>Secteur</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BwTranscodification__c/fields/MbApi__c.field-meta.xml
<CustomField>
    <fullName>MbApi__c</fullName>
    <label>Mobility API</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BwTranscodification__c/fields/VsApi__c.field-meta.xml
<CustomField>
    <fullName>VsApi__c</fullName>
    <label>Vision API</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/ORD_BusinessUnit__c.field-meta.xml
<CustomField>
    <fullName>ORD_BusinessUnit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>3</fullName>
                <label>Chaudières</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Traitement de l&apos;eau</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Air</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Services</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Location</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>INCINEX</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Ord_Domaine__c.field-meta.xml
<CustomField>
    <fullName>Ord_Domaine__c</fullName>
    <label>Code Business Unit</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/ORD_MontantHT_ERP__c.field-meta.xml
<CustomField>
    <fullName>ORD_MontantHT_ERP__c</fullName>
    <label>Montant HT ERP</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order/fields/ORD_SousDomaine__c.field-meta.xml
<CustomField>
    <fullName>ORD_SousDomaine__c</fullName>
    <label>Sous-Domaine</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>ADOUCISSEUR</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>AÉROTHERMES</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>AUTRES CHAUDIÈRES</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>AUTRES TA SPÉCIFIQUES</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>AUTRES TA STANDARD</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>AUTRES TE SPECIFIQUES</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>AUTRES TE STANDARD</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>BACHE DÉGAZANTE</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>BRÚLEURS</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>BWB</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>BWD</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>BWR</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>CENTRALE FOYER ÉCHANGEUR</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>CHAUDIERES EAU CHAUDE &lt; 5MW</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>CHAUDIÈRE VAPORISATION BASSE PRESSION</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>CONTRATS CHAUDIÈRES</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>CHAUDIERES EAU CHAUDE &gt; 5MW</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>CONTRAT LOW COST</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>CONTRATS AIR</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>CONTRATS EAU</label>
            </value>
            <value>
                <fullName>21</fullName>
                <label>CONTRATS GLOBAUX</label>
            </value>
            <value>
                <fullName>22</fullName>
                <label>DÉCARBONATATION</label>
            </value>
            <value>
                <fullName>23</fullName>
                <label>DÉGAZEURS</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>DÉMINÉRALISATION</label>
            </value>
            <value>
                <fullName>25</fullName>
                <label>EQUIPEMENT / INSTALLATION</label>
            </value>
            <value>
                <fullName>26</fullName>
                <label>EQUIPEMENTS CHAUFFERIE</label>
            </value>
            <value>
                <fullName>27</fullName>
                <label>FILTRES</label>
            </value>
            <value>
                <fullName>28</fullName>
                <label>FORMATION</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>GENERATEUR</label>
            </value>
            <value>
                <fullName>31</fullName>
                <label>GROS TRAVAUX</label>
            </value>
            <value>
                <fullName>39</fullName>
                <label>OSMOSE</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/ord_visSousDomain__c.field-meta.xml
<CustomField>
    <fullName>ord_visSousDomain__c</fullName>
    <label>Code Sous Domaine</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/USER_ByPassProcessBuilder__c.field-meta.xml
<CustomField>
    <fullName>USER_ByPassProcessBuilder__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ByPass Process Builder</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/USER_ByPassRegleValidation__c.field-meta.xml
<CustomField>
    <fullName>USER_ByPassRegleValidation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ByPass Règle de validation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/BatchOrderVisionSynchroTest.cls
@isTest
public class BatchOrderVisionSynchroTest {

    @testSetup static void setup() {
        //
        user API=[SELECT USER_ByPassRegleValidation__c, USER_ByPassProcessBuilder__c
        FROM user 
        WHERE lastName=:label.API
        LIMIT 1];

        API.USER_ByPassRegleValidation__c=true;
        API.USER_ByPassProcessBuilder__c = true;

        update API;
        Test.startTest();
        //
       System.runAs(API){

             
            List<BwTranscodification__c> transcoList = new List<BwTranscodification__c>();
            transcoList.add(new BwTranscodification__c(DataType__c='Sous domaine',MbApi__c='24',VsApi__c='LOC'));
            transcoList.add(new BwTranscodification__c(DataType__c='BU',MbApi__c='4',VsApi__c='LOC'));
            transcoList.add(new BwTranscodification__c(DataType__c='Agence Régionale',MbApi__c='1',VsApi__c='LOC'));
            transcoList.add(new BwTranscodification__c(DataType__c='Secteur',MbApi__c='39',VsApi__c='LOC'));
            Database.insert(transcoList,false);
            System.assertEquals(4, transcoList.size() , 'BwTranscodification__c Not Good' );
        
            Account newAccount=new Account(Name='TestOrder',
            ShippingCity='Lebanon',
            ShippingPostalCode='123',
            RecordTypeId = '0120O000000kqhw',
            ACC_SIREN__c='123456789');
            insert newAccount;
			
            
            list<order> listNewOrders=new list<order>();
            
            order newOrder1=new Order();
            newOrder1.AccountId=newAccount.Id;
            newOrder1.EffectiveDate=Date.today() + 10;
            newOrder1.ORD_SousDomaine__c = '19';
            newOrder1.ORD_BusinessUnit__c ='4';
            newOrder1.status='3';
            newOrder1.ORD_MontantHT_ERP__c =50 ;
            listNewOrders.add(newOrder1);
			//
            //
            order newOrder2=new Order();
            newOrder2.AccountId=newAccount.Id;
            newOrder2.EffectiveDate=Date.today() + 10;
            newOrder2.ORD_SousDomaine__c = '19';
            newOrder2.ORD_BusinessUnit__c ='4';
            newOrder2.ORD_MontantHT_ERP__c =100 ;
            newOrder2.status='3';
            listNewOrders.add(newOrder2);
            //----------------
            //
            order newOrder2_1=new Order();
            newOrder2_1.AccountId=newAccount.Id;
            newOrder2_1.EffectiveDate=Date.today() + 10;
            newOrder2_1.ORD_SousDomaine__c = '19';
            newOrder2_1.ORD_BusinessUnit__c ='4';
            newOrder2_1.ORD_MontantHT_ERP__c =100 ;
            newOrder2_1.status='3';
            listNewOrders.add(newOrder2_1);
            //Assert current revenu = 250
            //
            order newOrder3=new Order();
            newOrder3.AccountId=newAccount.Id;
            newOrder3.EffectiveDate=Date.today() -365;
            newOrder3.status='3';
            newOrder3.ORD_SousDomaine__c = '19';
            newOrder3.ORD_BusinessUnit__c ='4';
            newOrder3.ORD_MontantHT_ERP__c =75 ;
            listNewOrders.add(newOrder3);
            
            order newOrder4=new Order();
            newOrder4.AccountId=newAccount.Id;
            newOrder4.EffectiveDate=Date.today()  -365;
            newOrder4.ORD_MontantHT_ERP__c =200 ;
            newOrder4.ORD_SousDomaine__c = '19';
            newOrder4.ORD_BusinessUnit__c ='4';
            newOrder4.status='3';
            listNewOrders.add(newOrder4);
            //Revenu - 1 = 275
            
            order newOrder1_1=new Order();
            newOrder1_1.AccountId=newAccount.Id;
            newOrder1_1.EffectiveDate=Date.today() + 10;
            newOrder1_1.status='3';
            newOrder1_1.ORD_MontantHT_ERP__c =125 ;
            newOrder1_1.ORD_SousDomaine__c = '19';
            newOrder1_1.ORD_BusinessUnit__c ='4';
            listNewOrders.add(newOrder1_1);
           
            System.debug('newOrder1_1 '+newOrder1_1);
            order newOrder1_2=new Order();
            newOrder1_2.AccountId=newAccount.Id;
            newOrder1_2.EffectiveDate=Date.today() -365;
            newOrder1_2.status='3';
            newOrder1_2.ORD_SousDomaine__c = '19';
            newOrder1_2.ORD_BusinessUnit__c ='4';
            newOrder1_2.ORD_MontantHT_ERP__c =145 ;
            listNewOrders.add(newOrder1_2);
            
            
            insert listNewOrders;
        }
    }
    
    @isTest static void testMethod1() {
        Account acct =  [SELECT Id FROM Account WHERE NAME ='TestOrder' LIMIT 1];
        List<Order> orderList =[SELECT Id,ord_visSousDomain__c,Ord_Domaine__c,ORD_SousDomaine__c ,ORD_BusinessUnit__c FROM Order WHERE AccountId  = :acct.Id];
        system.assertEquals (orderList.size() , 7,'Not Equals Test Methode');
        BatchOrderVisionSynchro.run();

    }

    Public static Opportunity createOppy(Id AccountId,Date closeDate,String stageName, String entryName){
        return (new opportunity(AccountId = AccountId,
                                closedate=closeDate,
                                stageName=stageName,
                                Name = entryName));
    }
    
    Public static Id getPricebookId(){
        Pricebook2 standardPricebook = new Pricebook2(
            Id = Test.getStandardPricebookId(),
            IsActive = true );
        	update standardPricebook;
            Id StandardPricebookID = Test.getStandardPricebookId();
 			return StandardPricebookID ;       
    }
    Public static Order createOrder(String Name,Id AccountId,Date closeDate,String stageName, String entryName ){
        Opportunity oppy = createOppy(AccountId,closeDate,stageName, entryName);
        insert oppy ;
        Id standardPricebookId = getPricebookId();
        Order ord = New Order();
        ord.AccountId=AccountId;
        ord.EffectiveDate=closeDate;
        ord.status='3';
        ord.Description=Name;
        ord.ORD_MontantHT_ERP__c =145 ;
        return ord;
    }
}