force-app/main/default/objects/Account/fields/ACC_Entite_BW__c.field-meta.xml
<CustomField>
    <fullName>ACC_Entite_BW__c</fullName>
    <label>Entité BW</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>EntiteBW</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ACC_SIREN__c.field-meta.xml
<CustomField>
    <fullName>ACC_SIREN__c</fullName>
    <label>SIREN</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OPP_Domaine__c/OPP_Domaine__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Transcodification de la liste domaine dans Opportunité</description>
    <label>OPP_Domaine</label>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/OPP_Domaine__c.field-meta.xml
<CustomField>
    <fullName>OPP_Domaine__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>3</fullName>
                <label>Chaudières</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Traitement de l&apos;eau</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Air</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Services</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Location</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>INCINEX</label>
            </value>
            <value>
                <fullName>19</fullName>
                <isActive>false</isActive>
                <label>AST : AIR STANDARD</label>
            </value>
            <value>
                <fullName>18</fullName>
                <isActive>false</isActive>
                <label>ESP : EAU SPECIFIQUES</label>
            </value>
            <value>
                <fullName>22</fullName>
                <isActive>false</isActive>
                <label>EST : EAU STANDARDS</label>
            </value>
            <value>
                <fullName>7</fullName>
                <isActive>false</isActive>
                <label>GTX : GROS TRAVAUX</label>
            </value>
            <value>
                <fullName>8</fullName>
                <isActive>false</isActive>
                <label>INV : INVESTISSEMENT</label>
            </value>
            <value>
                <fullName>9</fullName>
                <isActive>false</isActive>
                <label>LOC : LOCATION</label>
            </value>
            <value>
                <fullName>10</fullName>
                <isActive>false</isActive>
                <label>MAT : MATÉRIEL THERMIQUE</label>
            </value>
            <value>
                <fullName>11</fullName>
                <isActive>false</isActive>
                <label>OCC : OCCASION</label>
            </value>
            <value>
                <fullName>13</fullName>
                <isActive>false</isActive>
                <label>PRE : PIÈCES DE RECHANGE</label>
            </value>
            <value>
                <fullName>15</fullName>
                <isActive>false</isActive>
                <label>PRJ : PROJET INTERNE</label>
            </value>
            <value>
                <fullName>14</fullName>
                <isActive>false</isActive>
                <label>PRO : PRODUIT CONDITIONNEMENT</label>
            </value>
            <value>
                <fullName>12</fullName>
                <isActive>false</isActive>
                <label>PTX : PETIT TRAVAUX</label>
            </value>
            <value>
                <fullName>16</fullName>
                <isActive>false</isActive>
                <label>RED : RECHERCHE ET DEVELOPPEMENT</label>
            </value>
            <value>
                <fullName>17</fullName>
                <isActive>false</isActive>
                <label>SIN : SINISTRES</label>
            </value>
            <value>
                <fullName>20</fullName>
                <isActive>false</isActive>
                <label>STO : STOCK OCCASION</label>
            </value>
            <value>
                <fullName>21</fullName>
                <isActive>false</isActive>
                <label>TDF : TUBES DE FUMÉES</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/OPP_Special_Project__c.field-meta.xml
<CustomField>
    <fullName>OPP_Special_Project__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Special Project</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/UnitePrixPar__c.field-meta.xml
<CustomField>
    <fullName>UnitePrixPar__c</fullName>
    <label>Unité (Prix Par)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Heure</fullName>
            </value>
            <value>
                <fullName>Jour</fullName>
            </value>
            <value>
                <fullName>Année</fullName>
            </value>
            <value>
                <fullName>Intervention</fullName>
            </value>
            <value>
                <fullName>Produit</fullName>
            </value>
            <value>
                <fullName>Bidon</fullName>
            </value>
            <value>
                <fullName>Fût</fullName>
            </value>
            <value>
                <fullName>IBC</fullName>
            </value>
            <value>
                <fullName>Sac</fullName>
            </value>
            <value>
                <fullName>Tonneau</fullName>
            </value>
            <value>
                <fullName>Unité</fullName>
            </value>
            <value>
                <fullName>KG</fullName>
            </value>
            <value>
                <fullName>KM</fullName>
            </value>
            <value>
                <fullName>LT</fullName>
            </value>
            <value>
                <fullName>GG</fullName>
            </value>
            <value>
                <fullName>MQ</fullName>
            </value>
            <value>
                <fullName>MC</fullName>
            </value>
            <value>
                <fullName>Mètre</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/DEV_NumCommandeClient__c.field-meta.xml
<CustomField>
    <fullName>DEV_NumCommandeClient__c</fullName>
    <label>N° Commande du client</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/ELD_MainProduct__c.field-meta.xml
<CustomField>
    <fullName>ELD_MainProduct__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Main Product</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/USER_ByPassRegleValidation__c.field-meta.xml
<CustomField>
    <fullName>USER_ByPassRegleValidation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ByPass Règle de validation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AP01_QLI_PrincipalProduct_Test.cls
@isTest
public class AP01_QLI_PrincipalProduct_Test {
    
    public static testMethod void test_OrderBeforeInsert()  { 
        
        user API=[SELECT USER_ByPassRegleValidation__c 
                  FROM user 
                  WHERE lastName=:label.API
                  LIMIT 1];
        API.USER_ByPassRegleValidation__c=true;
        
        update API;
        
        System.runAs(API){
            Account newAccount=new Account(Name='Test Account',
                                           ShippingCity='Lebanon',
                                           ShippingPostalCode='123',
                                           ACC_SIREN__c='abcdrftdo',
                                           ACC_Entite_BW__c = '3');
            insert newAccount;
            
            opportunity newOpportunity=new opportunity();
            newOpportunity.name='Test Opportunity';
            newOpportunity.closedate=Date.today() + 10;
            newOpportunity.stageName='Qualification';
            newOpportunity.OPP_Special_Project__c = FALSE;
            newOpportunity.OPP_Domaine__c = Label.Chaudieres;
            newOpportunity.AccountId = newAccount.id;
            insert newOpportunity;
            
            Id StandardPricebookID = Test.getStandardPricebookId();
            Pricebook2 standardPricebook = new Pricebook2(
            Id = Test.getStandardPricebookId(),
            IsActive = true
        );
        update standardPricebook;
            
            product2 newproduct2=new product2(Name='Test product',IsActive=true);
            insert newproduct2;
            PricebookEntry newPricebookEntry=new PricebookEntry(pricebook2Id=StandardPricebookID,
                                                                product2Id=newproduct2.Id,
                                                                unitPrice=200,
                                                                UnitePrixPar__c='Heure',
                                                                IsActive=true);
            insert newPricebookEntry;
            quote Newquote=new quote(Name='Test quote',
                                     opportunityId=newOpportunity.Id,
                                     status='4',
                                     DEV_NumCommandeClient__c='123',
                                     pricebook2Id=StandardPricebookID);
            insert Newquote;
            
            QuoteLineItem qutlineitemtest = new QuoteLineItem ();
            qutlineitemtest = new QuoteLineItem(QuoteId = Newquote.id , Quantity = 3.00  ,UnitPrice = 12 , PricebookEntryId = newPricebookEntry.id);
            qutlineitemtest.ELD_MainProduct__c = true;
            
            QuoteLineItem qutlineitemtest2 = new QuoteLineItem ();
            qutlineitemtest2 = new QuoteLineItem(QuoteId = Newquote.id , Quantity = 3.00  ,UnitPrice = 12 , PricebookEntryId = newPricebookEntry.id);
            qutlineitemtest2.ELD_MainProduct__c = false;
            
            list<Quotelineitem> newlist = new list<Quotelineitem>();
            newlist.add(qutlineitemtest);
            newlist.add(qutlineitemtest2);
            test.startTest();
           insert newlist;
            test.stopTest();
           delete qutlineitemtest2;
            
        }
    }
}