force-app/main/default/objects/Account/fields/ACC_Entite_BW__c.field-meta.xml
<CustomField>
    <fullName>ACC_Entite_BW__c</fullName>
    <label>Entité BW</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>EntiteBW</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ACC_Langue_Documentation__c.field-meta.xml
<CustomField>
    <fullName>ACC_Langue_Documentation__c</fullName>
    <label>Langue de Documentation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Anglais</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Français</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Allemand</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Italien</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Espagnol</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ACC_SIREN__c.field-meta.xml
<CustomField>
    <fullName>ACC_SIREN__c</fullName>
    <label>SIREN</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/UnitePrixPar__c.field-meta.xml
<CustomField>
    <fullName>UnitePrixPar__c</fullName>
    <label>Unité (Prix Par)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Heure</fullName>
            </value>
            <value>
                <fullName>Jour</fullName>
            </value>
            <value>
                <fullName>Année</fullName>
            </value>
            <value>
                <fullName>Intervention</fullName>
            </value>
            <value>
                <fullName>Produit</fullName>
            </value>
            <value>
                <fullName>Bidon</fullName>
            </value>
            <value>
                <fullName>Fût</fullName>
            </value>
            <value>
                <fullName>IBC</fullName>
            </value>
            <value>
                <fullName>Sac</fullName>
            </value>
            <value>
                <fullName>Tonneau</fullName>
            </value>
            <value>
                <fullName>Unité</fullName>
            </value>
            <value>
                <fullName>KG</fullName>
            </value>
            <value>
                <fullName>KM</fullName>
            </value>
            <value>
                <fullName>LT</fullName>
            </value>
            <value>
                <fullName>GG</fullName>
            </value>
            <value>
                <fullName>MQ</fullName>
            </value>
            <value>
                <fullName>MC</fullName>
            </value>
            <value>
                <fullName>Mètre</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/DEV_Ajout_Piece_Jointe__c.field-meta.xml
<CustomField>
    <fullName>DEV_Ajout_Piece_Jointe__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ajout_Piece-Jointe</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DEV_Charg_daffaire__c.field-meta.xml
<CustomField>
    <fullName>DEV_Charg_daffaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Permet d&apos;indiquer le nom du chargé d&apos;affaire</description>
    <inlineHelpText>Indiquer le nom du chargé d&apos;affaire lorsque vous accepté un Devis</inlineHelpText>
    <label>Chargé d&apos;affaire</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Devis1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DEV_NumCommandeClient__c.field-meta.xml
<CustomField>
    <fullName>DEV_NumCommandeClient__c</fullName>
    <label>N° Commande du client</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/ELD_MainProduct__c.field-meta.xml
<CustomField>
    <fullName>ELD_MainProduct__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Main Product</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/USER_ByPassRegleValidation__c.field-meta.xml
<CustomField>
    <fullName>USER_ByPassRegleValidation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ByPass Règle de validation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/USER_EntiteBW__c.field-meta.xml
<CustomField>
    <fullName>USER_EntiteBW__c</fullName>
    <label>Entité BW</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>EntiteBW</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/VFE001_CloneQuoteQLI_Test.cls
@isTest 
public class VFE001_CloneQuoteQLI_Test {
    
    static testMethod void VFE001_CloneQuoteQLITest() {
        User u = [Select id, name, email from User where id=: UserInfo.getUserId()];
        u.USER_ByPassRegleValidation__c=true;
        u.USER_EntiteBW__c=Label.BW_ITA;
        Update u;
        System.runAs(u) {
            Account newAccount = new Account (Name = 'Test Account 1', ShippingCity = 'Lebanon', 
                                              ShippingPostalCode = '123', ACC_SIREN__c = '123456789');
            newAccount.ACC_Entite_BW__c=Label.BW_ITA ;
            newAccount.ACC_Langue_Documentation__c='4';
            insert newAccount;
            opportunity newOpportunity=new opportunity();
            newOpportunity.name='Test Opportunity';
            newOpportunity.closedate=Date.today() + 10;
            newOpportunity.stageName='Qualification';
            newOpportunity.AccountId=newAccount.id;
            insert newOpportunity;
            product2 newproduct2=new product2(Name='Test product',IsActive=true);
            insert newproduct2;
            Pricebook2 standardPricebook = new Pricebook2(
                Id = Test.getStandardPricebookId(),
                IsActive = true );
            update standardPricebook;
            Id StandardPricebookID = Test.getStandardPricebookId();
            PricebookEntry newPricebookEntry=new PricebookEntry(pricebook2Id=StandardPricebookID,
                                                                product2Id=newproduct2.Id,
                                                                unitPrice=200,
                                                                UnitePrixPar__c='Heure',
                                                                IsActive=true);
            insert newPricebookEntry;
            quote Newquote=new quote(Name='Test quote',
                                     opportunityId=newOpportunity.Id,
                                     status='1',
                                     DEV_Ajout_Piece_Jointe__c=false,
                                     DEV_NumCommandeClient__c='123',
                                     DEV_Charg_daffaire__c = UserInfo.getUserId(),
                                     pricebook2Id=StandardPricebookID);
            insert Newquote;
            QuoteLineItem qutlineitemtest = new QuoteLineItem ();
            qutlineitemtest = new QuoteLineItem(QuoteId = Newquote.id , Quantity = 3.00  ,UnitPrice = 12 , PricebookEntryId = newPricebookEntry.id);
            //qutlineitemtest.ELD_MainProduct__c = true;
            insert qutlineitemtest;
            ApexPages.StandardController controller = new ApexPages.StandardController(Newquote);
            test.startTest();
            VFE001_CloneQuoteQLI vfe07 = new VFE001_CloneQuoteQLI(controller);
            vfe07.cloneQuoteWithQLI();
            test.stopTest();
        }
    }
    
}