force-app/main/default/objects/Account/fields/ACC_SIREN__c.field-meta.xml
<CustomField>
    <fullName>ACC_SIREN__c</fullName>
    <label>SIREN</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/SC_CompteLivre__c.field-meta.xml
<CustomField>
    <fullName>SC_CompteLivre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compte Livré</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contrats d&apos;assistance technique (Compte Livré)</relationshipLabel>
    <relationshipName>Contrats_d_assistance_technique1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/SC_NAffaire__c.field-meta.xml
<CustomField>
    <fullName>SC_NAffaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Renseigner l&apos;Opportunité associée au CAT</inlineHelpText>
    <label>Opportunité</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Contrats d&apos;assistance technique</relationshipLabel>
    <relationshipName>Contrats_d_assistance_technique_opp</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/SC_NomDuCompteDeFacturation__c.field-meta.xml
<CustomField>
    <fullName>SC_NomDuCompteDeFacturation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compte Facturé</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contrats d&apos;assistance technique</relationshipLabel>
    <relationshipName>Contrats_d_assistance_technique</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/SC_SousDomaine__c.field-meta.xml
<CustomField>
    <fullName>SC_SousDomaine__c</fullName>
    <label>Sous-domaine</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>18</fullName>
                <label>CONTRAT LOW COST</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>CONTRATS AIR</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>CONTRATS CHAUDIÈRES</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>CONTRATS EAU</label>
            </value>
            <value>
                <fullName>21</fullName>
                <label>CONTRATS GLOBAUX</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/SC_Statut__c.field-meta.xml
<CustomField>
    <fullName>SC_Statut__c</fullName>
    <label>Etat</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>Avant projet</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Pour validation ERP</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Actif</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Suspendu</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Résilié</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Terminé</label>
            </value>
            <value>
                <fullName>Clos</fullName>
                <isActive>false</isActive>
                <label>Clos</label>
            </value>
            <value>
                <fullName>Proposition</fullName>
                <isActive>false</isActive>
                <label>Proposition</label>
            </value>
            <value>
                <fullName>Proposition gagnée</fullName>
                <isActive>false</isActive>
                <label>Proposition gagnée</label>
            </value>
            <value>
                <fullName>Proposition perdue</fullName>
                <isActive>false</isActive>
                <label>Proposition perdue</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/USER_ByPassRegleValidation__c.field-meta.xml
<CustomField>
    <fullName>USER_ByPassRegleValidation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ByPass Règle de validation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Test_AP01_ServiceContract.cls
@isTest
public class Test_AP01_ServiceContract {
    
    public static testMethod void test_ServiceContractAfterUpdate()  { 
        
      /*
         user UserEnCours=[SELECT USER_ByPassRegleValidation__c 
                  FROM user 
                  WHERE lastName != 'API'
                  LIMIT 1];
                  
        UserEnCours.USER_ByPassRegleValidation__c=true;
        
        update UserEnCours;
      */
        
        user API=[SELECT USER_ByPassRegleValidation__c 
                  FROM user 
                  WHERE lastName=:label.API
                  LIMIT 1];
                  
        API.USER_ByPassRegleValidation__c=true;
        
        update API;
        
     //   System.runAs(UserEnCours){
            
           Account newAccount=new Account(Name='Test Account For Update Maintenance Plan',
                                           ShippingCity='Lebanon',
                                           ShippingPostalCode='123',
                                           ShippingStreet='Test',
                                           BillingStreet='Test',
                                           BillingCity='Test',
                                           BillingPostalCode='1234',
                                           RecordTypeId = '0120O000000kqi1',
                                           ACC_SIREN__c='133456789');
            insert newAccount;
            
            opportunity newOpportunity=new opportunity();
            newOpportunity.AccountId = newAccount.Id;
            newOpportunity.name='Test Opportunity For Maintenance Plan';
            newOpportunity.closedate=Date.today() + 10;
            newOpportunity.stageName='Devis';
            insert newOpportunity;

            
            contact Newcontact=new contact(LastName='Test Contact',
                                     AccountId=newAccount.Id,
                                     Email='Test@gmail.com');
            insert Newcontact;
            
            ServiceContract newServiceContract=new ServiceContract ();
            newServiceContract.name='Test Contract For Maintenance Plan';
            newServiceContract.SC_Statut__c = '1';
            newServiceContract.SC_SousDomaine__c = '16';
            newServiceContract.StartDate =  Date.Today() + 8;
            newServiceContract.EndDate = Date.Today() + 356;
            newServiceContract.AccountId = newAccount.Id;
            newServiceContract.SC_CompteLivre__c = newAccount.Id;
            newServiceContract.SC_NomDuCompteDeFacturation__c = newAccount.Id;
            newServiceContract.ContactId = Newcontact.Id;
            newServiceContract.SC_NAffaire__c = newOpportunity.Id;
            insert newServiceContract;
             newServiceContract.name='Test';
            update newServiceContract;
             newServiceContract.SC_Statut__c = '3';
             newServiceContract.StartDate = Date.Today() + 8;
             newServiceContract.EndDate = Date.Today() + 357;
            
            MaintenancePlan newMaintenancePlan=new MaintenancePlan ();
            newMaintenancePlan.MaintenancePlanTitle='Test For Maintenance Plan';
            newMaintenancePlan.ServiceContractId = newServiceContract.Id; 
            newMaintenancePlan.StartDate = Date.Today() + 8;
            newMaintenancePlan.EndDate =  Date.Today() + 356;
            newMaintenancePlan.Frequency = 6;
            newMaintenancePlan.FrequencyType = 'Months';
            newMaintenancePlan.GenerationTimeframe = 12; 
            newMaintenancePlan.GenerationTimeframeType = 'Months';
            newMaintenancePlan.NextSuggestedMaintenanceDate = Date.Today() + 10;
            newMaintenancePlan.GenerationHorizon = 10;
            insert newMaintenancePlan;
            
          
          System.runAs(API){
           
           //  newServiceContract.SC_Statut__c = '3';
           //  newServiceContract.StartDate = Date.NewInstance (2020,04,03);
           //  newServiceContract.EndDate = Date.NewInstance (2021,04,02);
          
           test.startTest();  
            update newServiceContract; 
        
           test.stopTest();
             
              
        }
    }
}