force-app/main/default/objects/Int_pointage__c/Int_pointage__c.object-meta.xml
<CustomObject>
    <label>Int_pointage</label>
    <nameField>
        <displayFormat>P{000000000}</displayFormat>
        <label>Nom de Int_pointage</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Int_pointage</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Int_pointage__c/fields/Annee_Ori__c.field-meta.xml
<CustomField>
    <fullName>Annee_Ori__c</fullName>
    <label>Annee_Ori</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Int_pointage__c/fields/CodeAffaire__c.field-meta.xml
<CustomField>
    <fullName>CodeAffaire__c</fullName>
    <label>CodeAffaire</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Int_pointage__c/fields/CodeChapitre__c.field-meta.xml
<CustomField>
    <fullName>CodeChapitre__c</fullName>
    <label>CodeChapitre</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Int_pointage__c/fields/CodeSousChapitre__c.field-meta.xml
<CustomField>
    <fullName>CodeSousChapitre__c</fullName>
    <label>CodeSousChapitre</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Int_pointage__c/fields/NbrHeures__c.field-meta.xml
<CustomField>
    <fullName>NbrHeures__c</fullName>
    <label>NbrHeures</label>
    <precision>9</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Int_pointage__c/fields/Numero_unique__c.field-meta.xml
<CustomField>
    <fullName>Numero_unique__c</fullName>
    <label>Numéro_unique</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Int_pointage__c/fields/Salarie__c.field-meta.xml
<CustomField>
    <fullName>Salarie__c</fullName>
    <label>Salarié</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Int_pointage__c/fields/Semaine_ori__c.field-meta.xml
<CustomField>
    <fullName>Semaine_ori__c</fullName>
    <label>Semaine_ori</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VICentre_Section__c/VICentre_Section__c.object-meta.xml
<CustomObject>
    <label>Centre / Section</label>
    <nameField>
        <label>Nom de Centre / Section</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Centres / Sections</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VIType_de_depense__c/VIType_de_depense__c.object-meta.xml
<CustomObject>
    <label>Type de dépense</label>
    <nameField>
        <label>Nom de Type de dépense</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Types de dépenses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/VISchedImportPointage_test.cls
@isTest
public class VISchedImportPointage_test {

    static testmethod void VISchedImportPointage_test() {
    
        VIInsertDataTest.VIInsertData_EUR_Affaire();

        VIType_de_depense__c td = [select name from VIType_de_depense__c limit 1];
        VICentre_Section__c cs = [select name from VICentre_Section__c limit 1];

        VIInsertDataTest.VIInsertData_Achat(); 
        
        int_pointage__c po = new int_pointage__c (
                               codeAffaire__c='B80000',
                               codeCentre__c=cs.name.left(3) ,
                               codeChapitre__c='00',
                               codesousChapitre__c='00',            
                               Date__c =System.today(),
                               NbrHeures__c   =1,
                               salarie__c =null,
                               numero_unique__c='44',
                               semaine_ori__c = 1,
                               Annee_ori__c=System.today().year()) ;
        insert po;
        
        VISchedImportpointage v1 = new VISchedImportpointage('B80000',false,false);
        v1.execute(null);
        
        
        

    }
}