force-app/main/default/objects/BwTranscodification__c/BwTranscodification__c.object-meta.xml
<CustomObject>
    <description>Objets comportant les différents valeurs des systems</description>
    <label>Transcodification</label>
    <nameField>
        <displayFormat>TRS-{0000}</displayFormat>
        <label>Transcodification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transcodifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BwTranscodification__c/fields/DataType__c.field-meta.xml
<CustomField>
    <fullName>DataType__c</fullName>
    <label>DataType</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BU</fullName>
            </value>
            <value>
                <fullName>Agence Régionale</fullName>
            </value>
            <value>
                <fullName>Sous domaine</fullName>
            </value>
            <value>
                <fullName>Secteur</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BwTranscodification__c/fields/MbApi__c.field-meta.xml
<CustomField>
    <fullName>MbApi__c</fullName>
    <label>Mobility API</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BwTranscodification__c/fields/VsApi__c.field-meta.xml
<CustomField>
    <fullName>VsApi__c</fullName>
    <label>Vision API</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BwUtils.cls
public with sharing class BwUtils {
    
    static List<BwTranscodification__c> transcoList = [SELECT Id, MbApi__c,dataType__c,VsApi__c FROM BwTranscodification__c];
    public static String getTranscoVisionValue(String dataType,String lookupValue ) {
        if ((dataType ==null )||(lookupValue ==null )) return null ;
        for (BwTranscodification__c transco : transcoList) {

            if ((transco.dataType__c == dataType ) && (transco.MbApi__c == lookupValue)) return transco.VsApi__c;
        }
        return null ;
    }
}