force-app/main/default/objects/BwTranscodification__c/BwTranscodification__c.object-meta.xml
<CustomObject>
    <description>Objets comportant les différents valeurs des systems</description>
    <label>Transcodification</label>
    <nameField>
        <displayFormat>TRS-{0000}</displayFormat>
        <label>Transcodification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transcodifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BwTranscodification__c/fields/DataType__c.field-meta.xml
<CustomField>
    <fullName>DataType__c</fullName>
    <label>DataType</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BU</fullName>
            </value>
            <value>
                <fullName>Agence Régionale</fullName>
            </value>
            <value>
                <fullName>Sous domaine</fullName>
            </value>
            <value>
                <fullName>Secteur</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BwTranscodification__c/fields/MbApi__c.field-meta.xml
<CustomField>
    <fullName>MbApi__c</fullName>
    <label>Mobility API</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BwTranscodification__c/fields/VsApi__c.field-meta.xml
<CustomField>
    <fullName>VsApi__c</fullName>
    <label>Vision API</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BwUtilsTest.cls
/**
 * @description       : 
 * @author            : SCHIBOUT
 * @group             : 
 * @last modified on  : 29-09-2021
 * @last modified by  : SCHIBOUT
**/
@IsTest
public  class BwUtilsTest {
    
    @IsTest
    static void methodName(){
        User contextuser = DataFactorySobjetcs.getApiUser();    
        Test.startTest();
        System.runAs(contextuser){
            BwTranscodification__c  trs =  new BwTranscodification__c();
            trs.dataType__c ='BU';
            trs.MbApi__c='MBTest';
            trs.VsApi__c='VsTest';
            insert trs;
            
            String CalculatedValue = BwUtils.getTranscoVisionValue(null,null );
            System.assertEquals(null, CalculatedValue,'Null not managed');
            CalculatedValue = BwUtils.getTranscoVisionValue('BU','MBTest' );
            System.assertEquals('VsTest', CalculatedValue,'Field Complete');
            CalculatedValue = BwUtils.getTranscoVisionValue('BU','DataNotFound' );
            System.assertEquals(null, CalculatedValue,'Data Not Found ');
        }
        Test.stopTest();
        
    }
}