force-app/main/default/objects/PricebookEntry/fields/UnitePrixPar__c.field-meta.xml
<CustomField>
    <fullName>UnitePrixPar__c</fullName>
    <label>Unité (Prix Par)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Heure</fullName>
            </value>
            <value>
                <fullName>Jour</fullName>
            </value>
            <value>
                <fullName>Année</fullName>
            </value>
            <value>
                <fullName>Intervention</fullName>
            </value>
            <value>
                <fullName>Produit</fullName>
            </value>
            <value>
                <fullName>Bidon</fullName>
            </value>
            <value>
                <fullName>Fût</fullName>
            </value>
            <value>
                <fullName>IBC</fullName>
            </value>
            <value>
                <fullName>Sac</fullName>
            </value>
            <value>
                <fullName>Tonneau</fullName>
            </value>
            <value>
                <fullName>Unité</fullName>
            </value>
            <value>
                <fullName>KG</fullName>
            </value>
            <value>
                <fullName>KM</fullName>
            </value>
            <value>
                <fullName>LT</fullName>
            </value>
            <value>
                <fullName>GG</fullName>
            </value>
            <value>
                <fullName>MQ</fullName>
            </value>
            <value>
                <fullName>MC</fullName>
            </value>
            <value>
                <fullName>Mètre</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/DEV_NumCommandeClient__c.field-meta.xml
<CustomField>
    <fullName>DEV_NumCommandeClient__c</fullName>
    <label>N° Commande du client</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/USER_ByPassProcessBuilder__c.field-meta.xml
<CustomField>
    <fullName>USER_ByPassProcessBuilder__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ByPass Process Builder</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/USER_ByPassRegleValidation__c.field-meta.xml
<CustomField>
    <fullName>USER_ByPassRegleValidation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ByPass Règle de validation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Test_AP02_Order.cls
@isTest
public class Test_AP02_Order {
    
    public static testMethod void test_OrderBeforeInsert()  { 
        
        user API=[SELECT USER_ByPassRegleValidation__c, USER_ByPassProcessBuilder__c
                  FROM user 
                  WHERE lastName=:label.API
                  LIMIT 1];
        
        API.USER_ByPassRegleValidation__c=true;
        API.USER_ByPassProcessBuilder__c = true;
        
        update API;
        
        System.runAs(API){
            
            
            opportunity newOpportunity=new opportunity();
            newOpportunity.name='Test Opportunity';
            newOpportunity.closedate=Date.today() + 10;
            newOpportunity.stageName='Qualification';
            insert newOpportunity;
            
            
            Pricebook2 standardPricebook = new Pricebook2(
            Id = Test.getStandardPricebookId(),
            IsActive = true );
        	update standardPricebook;
            Id StandardPricebookID = Test.getStandardPricebookId();
            
            
            product2 newproduct2=new product2(Name='Test product',IsActive=true);
            insert newproduct2;
            
            PricebookEntry newPricebookEntry=new PricebookEntry(pricebook2Id=StandardPricebookID,
                                                                product2Id=newproduct2.Id,
                                                                unitPrice=200,
                                                                UnitePrixPar__c='Heure',
                                                                IsActive=true);
            insert newPricebookEntry;
            
            
            quote Newquote=new quote(Name='Test quote',
                                     opportunityId=newOpportunity.Id,
                                     status='3',
                                     DEV_NumCommandeClient__c='123',
                                     pricebook2Id=StandardPricebookID);
            insert Newquote;
            
            
            quoteLineItem newquoteLineItem=new quoteLineItem(product2Id=newproduct2.Id,
                                                             quantity=2,
                                                             quoteId=Newquote.Id,
                                                             pricebookentryId=newPricebookEntry.Id,
                                                             unitPrice=200);
            insert newquoteLineItem;
            
            
            Account newAccount=new Account(Name='Test Account');
            insert newAccount;
            
            
            list<order> listNewOrders=new list<order>();
            
            order newOrder1=new Order();
            newOrder1.AccountId=newAccount.Id;
            newOrder1.EffectiveDate=Date.today() + 10;
            newOrder1.status='3';
            newOrder1.quoteId=Newquote.Id;
            listNewOrders.add(newOrder1);
            
            order newOrder2=new Order();
            newOrder2.AccountId=newAccount.Id;
            newOrder2.EffectiveDate=Date.today() + 10;
            newOrder2.status='3';
            newOrder2.quoteId=Newquote.Id;
            listNewOrders.add(newOrder2);
            
            insert listNewOrders;
            
            orderItem OrderItem=[SELECT OrderId,Product2Id,quantity,UnitPrice,PricebookentryId
                                 FROM orderItem
                                 LIMIT 1];
            
            
            system.assert(OrderItem.OrderId==listNewOrders[0].Id);
            system.assert(OrderItem.Product2Id == newquoteLineItem.product2Id);
            system.assert(OrderItem.quantity == newquoteLineItem.quantity);
            system.assert(OrderItem.UnitPrice == newquoteLineItem.UnitPrice);
            system.assert(OrderItem.PricebookentryId == newQuoteLineItem.PricebookentryId);
            
        }
    }
}