force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/VILigne_d_affaire_mensuelle__c.object-meta.xml
<CustomObject>
    <label>Ligne d&apos;affaire mensuelle</label>
    <nameField>
        <label>Ref de Ligne d&apos;affaire mensuelle</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lignes d&apos;affaire mensuelles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/Affaire__c.field-meta.xml
<CustomField>
    <fullName>Affaire__c</fullName>
    <label>Affaire</label>
    <referenceTo>VIAffaire__c</referenceTo>
    <relationshipLabel>Lignes d&apos;affaire mensuelles</relationshipLabel>
    <relationshipName>Lignes_d_affaire_mensuelles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/VIMajSavController_Test.cls
@isTest
public class VIMajSavController_Test {

    static testmethod void VIMajSavController_Test() {
    
        VIInsertDataTest.VIInsertData_EUR_Affaire();

        list<VILigne_d_affaire_mensuelle__c>Listlam = [select id, affaire__c from VILigne_d_affaire_mensuelle__c ];

        Test.startTest();
        Test.setCurrentPage(Page.VIMajSav);
        ApexPages.StandardSetController stdSetController = new ApexPages.StandardSetController(Listlam);
        stdSetController.setSelected(Listlam);
        VIMajSavController ext = new VIMajSavController(stdSetController);
        ext.Enregistrer();
        
        Test.stopTest();
        
        
    }
}