force-app/main/default/objects/VILigne_comptable__c/VILigne_comptable__c.object-meta.xml
<CustomObject>
    <label>Ligne comptable</label>
    <nameField>
        <displayFormat>L{000000000}</displayFormat>
        <label>Ref de la ligne comptable</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lignes comptables</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VILigne_comptable__c/fields/CompteComptable_local__c.field-meta.xml
<CustomField>
    <fullName>CompteComptable_local__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Compte comptable local</label>
    <referenceTo>VICompte_general__c</referenceTo>
    <relationshipLabel>Lignes comptables</relationshipLabel>
    <relationshipName>Lignes_comptables</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VILigne_comptable__c/fields/Statut_ecriture_comptable__c.field-meta.xml
<CustomField>
    <fullName>Statut_ecriture_comptable__c</fullName>
    <defaultValue>&apos;10&apos;</defaultValue>
    <label>Statut écriture comptable</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Statut_ecriture_comptable</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/VIBatchDeleteLC_test.cls
@isTest
public class VIBatchDeleteLC_test {
    static testmethod void VIBatchDeleteLC_test() {   
        
      VIInsertDataTest.VIInsertData_EUR_Affaire();  
      VIInsertDataTest.VIInsertData_ligne_comptable();
      list<VILigne_comptable__c>ListLc = [SELECT id,CompteComptable_local__c,Statut_ecriture_comptable__c  FROM VILigne_comptable__c];
      for(VILigne_comptable__c lc : ListLc) {
            lc.Statut_ecriture_comptable__c='10';
      }
      update listLc ; 

      VIBatchDeleteLC v = new VIBatchDeleteLC('',false);
      v.execute(null);
    }
}