force-app/main/default/objects/int_gecart__c/int_gecart__c.object-meta.xml
<CustomObject>
    <label>int_gecart</label>
    <nameField>
        <label>Nom de int_gecart</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>int_gecart</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/int_gecart__c/fields/Centre__c.field-meta.xml
<CustomField>
    <fullName>Centre__c</fullName>
    <label>Centre</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/int_gecart__c/fields/Code_Affaire__c.field-meta.xml
<CustomField>
    <fullName>Code_Affaire__c</fullName>
    <label>Code_Affaire</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/int_gecart__c/fields/Import_Status__c.field-meta.xml
<CustomField>
    <fullName>Import_Status__c</fullName>
    <label>Import_Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Import_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/int_gecart__c/fields/Montant__c.field-meta.xml
<CustomField>
    <fullName>Montant__c</fullName>
    <label>Montant</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/int_gecart__c/fields/NB_heures__c.field-meta.xml
<CustomField>
    <fullName>NB_heures__c</fullName>
    <label>NB_heures</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/int_gecart__c/fields/Type_de_depense__c.field-meta.xml
<CustomField>
    <fullName>Type_de_depense__c</fullName>
    <label>Type_de_depense</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VIAffaire__c/VIAffaire__c.object-meta.xml
<CustomObject>
    <label>Affaire</label>
    <nameField>
        <label>Code Affaire</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Affaires</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VICentre_Section__c/VICentre_Section__c.object-meta.xml
<CustomObject>
    <label>Centre / Section</label>
    <nameField>
        <label>Nom de Centre / Section</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Centres / Sections</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VILigne_affaire__c/VILigne_affaire__c.object-meta.xml
<CustomObject>
    <label>Ligne d&apos;affaire</label>
    <nameField>
        <displayFormat>L{000000000}</displayFormat>
        <label>Ref de Ligne d&apos;affaire</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lignes d&apos;affaire</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VILigne_affaire__c/fields/Centre_Section__c.field-meta.xml
<CustomField>
    <fullName>Centre_Section__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Centre / Section</label>
    <referenceTo>VICentre_Section__c</referenceTo>
    <relationshipLabel>Lignes d&apos;affaire</relationshipLabel>
    <relationshipName>Lignes_d_affaire</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VILigne_affaire__c/fields/Ecart_C_A_F_Heure__c.field-meta.xml
<CustomField>
    <fullName>Ecart_C_A_F_Heure__c</fullName>
    <label>Ecart C.A.F - Heure</label>
    <precision>6</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VILigne_affaire__c/fields/Ecart_C_A_F_MontantD__c.field-meta.xml
<CustomField>
    <fullName>Ecart_C_A_F_MontantD__c</fullName>
    <label>Ecart C.A.F - MontantD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VILigne_affaire__c/fields/Ligne_d_affaire_mensuelle__c.field-meta.xml
<CustomField>
    <fullName>Ligne_d_affaire_mensuelle__c</fullName>
    <label>Ligne d&apos;affaire mensuelle</label>
    <referenceTo>VILigne_d_affaire_mensuelle__c</referenceTo>
    <relationshipLabel>Lignes d&apos;affaire</relationshipLabel>
    <relationshipName>Lignes_d_affaire</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VILigne_affaire__c/fields/Type_de_ligne_d_affaire__c.field-meta.xml
<CustomField>
    <fullName>Type_de_ligne_d_affaire__c</fullName>
    <label>Type de ligne d&apos;affaire</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type_de_ligne_d_affaire</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/VILigne_affaire__c/fields/Type_depense__c.field-meta.xml
<CustomField>
    <fullName>Type_depense__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Type de dépense</label>
    <referenceTo>VIType_de_depense__c</referenceTo>
    <relationshipLabel>Lignes d&apos;affaire</relationshipLabel>
    <relationshipName>Lignes_d_affaire</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/VILigne_d_affaire_mensuelle__c.object-meta.xml
<CustomObject>
    <label>Ligne d&apos;affaire mensuelle</label>
    <nameField>
        <label>Ref de Ligne d&apos;affaire mensuelle</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lignes d&apos;affaire mensuelles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/Affaire__c.field-meta.xml
<CustomField>
    <fullName>Affaire__c</fullName>
    <label>Affaire</label>
    <referenceTo>VIAffaire__c</referenceTo>
    <relationshipLabel>Lignes d&apos;affaire mensuelles</relationshipLabel>
    <relationshipName>Lignes_d_affaire_mensuelles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/Ecart_C_A_F_MontantD_E__c.field-meta.xml
<CustomField>
    <fullName>Ecart_C_A_F_MontantD_E__c</fullName>
    <label>Ecart C.A.F - MontantD €</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/fields/Periode_comptable__c.field-meta.xml
<CustomField>
    <fullName>Periode_comptable__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Période comptable</label>
    <referenceTo>VIPeriode__c</referenceTo>
    <relationshipLabel>Lignes d&apos;affaire mensuelles</relationshipLabel>
    <relationshipName>Lignes_d_affaire_mensuelles</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VIParametres__c/VIParametres__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>VIParametres</label>
</CustomObject>

force-app/main/default/objects/VIParametres__c/fields/Sans_Calcul_de_PRI__c.field-meta.xml
<CustomField>
    <fullName>Sans_Calcul_de_PRI__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Si coché, on fait le calcul avec les taux.Sinon, on prend les montants tel quel</inlineHelpText>
    <label>Sans Calcul de PRI ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VIPeriode__c/VIPeriode__c.object-meta.xml
<CustomObject>
    <label>Période comptable</label>
    <nameField>
        <label>Nom de Période</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Périodes comptables</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VIPeriode__c/fields/Date_de_debut__c.field-meta.xml
<CustomField>
    <fullName>Date_de_debut__c</fullName>
    <label>Date de début</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VIType_de_depense__c/VIType_de_depense__c.object-meta.xml
<CustomObject>
    <label>Type de dépense</label>
    <nameField>
        <label>Nom de Type de dépense</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Types de dépenses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/VISchedImportGEcart.cls
/*
*
*  We have to launch the import files 
*
*
*  for running by hand : 
 VISchedImportGEcart v = new VISchedImportGEcart('',false,true);
 v.execute(null);
*
*  for running every hour at xx:16
     VISchedImportGEcart m = new  VISchedImportGEcart();
     String sch = '0 16 * * * ?';
     String jobID = system.schedule(' v', sch, m);
*
*
*/
global class VISchedImportGEcart implements Schedulable,Database.Batchable<sObject>,Database.Stateful{

    Global double num_record = 0;
    Global String IDLog ='';    
    Global Map<string, VICentre_section__c>MapCentre    = new Map<string, VICentre_section__c>();    
    Global Map<string, VIType_de_depense__c>MapDepense  = new Map<string, VIType_de_depense__c>(); 
    Global VIType_de_depense__c tdGAR ; 
    
    
    private string AffaireAGenerer; 
    private boolean Enchaine ;
    private boolean toute ;    
    private Date DateImport ;    
    
     public VISchedImportGEcart(String Param1,Boolean Param2,Boolean Param3,date param4 ) {
        AffaireAGenerer = Param1;        
        Enchaine = Param2;                
        toute = Param3; 
        dateImport = param4;
    }

    
    global Database.QueryLocator start(Database.BatchableContext BC){
        IDLog=VIUtils.LogWrite('VISchedImportGEcart','4 Running','','Start ');

        for(VICentre_section__c centre : [SELECT id, name 
                                            FROM  VICentre_section__c]) {
            MapCentre.put(centre.name.left(3), centre) ;
        }

        for(VIType_de_depense__c depense : [SELECT id, name 
                                              FROM  VIType_de_depense__c]) {
            MapDepense.put(depense.name.left(3), depense) ;
            if(depense.name.left(3)=='GAR') 
                tdGAR=depense ; 
                                                  
        }

        string query = 'SELECT code_Affaire__c, date__c, Centre__c ,Type_de_depense__c ,NB_heures__c ,Montant__c ,Import_Status__c  ';
        query = query+'   FROM int_gecart__c   ';
        query = query+'   WHERE code_affaire__c!=null ';

        if(!toute)
            query = query+'     AND (Import_Status__c =\'1\' or Import_Status__c =null) ';

        query = query+'     AND (code_Affaire__c Like \''+AffaireAGenerer+'%\')  ';
        query = query+'     AND (date__c = '+string.valueof(DateImport).left(10)+')  ';        
        query = query+'   Order by code_affaire__c desc  ';        

        system.debug(query);
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<int_gecart__c > scope){
        num_record = 0;
        list<string>ListErreur = new list<string>();
        list<string>ListIDAffaire = new list<string>();
        for(int_gecart__c  g:scope) {
            ListIDAffaire.add(g.code_affaire__c);
        }    
        map<string, VIligne_affaire__c>MapLa = new map<string, VIligne_affaire__c>();
        for(VIligne_affaire__c la:[SELECT id, name, Centre_Section__r.name , Type_depense__r.name ,
                                          Ecart_C_A_F_Heure__c ,Ecart_C_A_F_MontantD__c ,
                                          Ligne_d_affaire_mensuelle__r.affaire__r.name,
                                          Ligne_d_affaire_mensuelle__r.Periode_comptable__r.date_de_debut__c                                 
                                     FROM VIligne_affaire__c
                               WHERE Ligne_d_affaire_mensuelle__r.affaire__r.name in :ListIDAffaire]) {
            string td = (la.Type_depense__r.name+'   ').left(3);
            string key = la.Ligne_d_affaire_mensuelle__r.affaire__r.name+'-'+la.Centre_Section__r.name.left(3)+'-'+td+'-'+la.Ligne_d_affaire_mensuelle__r.Periode_comptable__r.date_de_debut__c ;
            MapLa.put(key,la); 
        }                       
        map<string, VIligne_d_affaire_mensuelle__c>MapLam = new map<string, VIligne_d_affaire_mensuelle__c>();
        for(VIligne_d_affaire_mensuelle__c lam:[SELECT id, name, 
                                                       Ecart_C_A_F_Heure__c ,Ecart_C_A_F_MontantD__c ,
                                                       affaire__r.name,
                                                       Periode_comptable__r.date_de_debut__c                                 
                                                  FROM VIligne_d_affaire_mensuelle__c
                                                 WHERE affaire__r.name in :ListIDAffaire]) {
            string key = lam.affaire__r.name+'-'+lam.Periode_comptable__r.date_de_debut__c ;
            MapLam.put(key,lam); 
        }                       

        for(int_gecart__c g:scope) {
            string key = g.code_affaire__c+'-'+g.Centre__c+'-'+(g.Type_de_depense__c+'   ').left(3)+'-'+g.date__c;
            if(MapLa.containskey(key)) {
                VIligne_affaire__c la = MapLa.get(key) ;
                la.Ecart_C_A_F_Heure__c      =(g.NB_heures__c==null ? 0 :g.NB_heures__c) ;
                la.Ecart_C_A_F_MontantD__c   =(g.montant__c==null   ? 0 :g.montant__c);
                la.Ecart_C_A_F_MontantD_E__c =(g.montant__c==null   ? 0 :g.montant__c);                
                
            } else {
                VIligne_affaire__c la = new VIligne_affaire__c();
                if(!MapLam.containskey(g.code_affaire__c+'-'+g.date__c)) {
                    listErreur.add('Ecart inconnu'+g.code_affaire__c+'-'+g.date__c);
                    continue ; 
                }
                VIligne_d_affaire_mensuelle__c lam = MapLam.get(g.code_affaire__c+'-'+g.date__c);
                la.Ligne_d_affaire_mensuelle__c=lam.id ;
                la.Centre_Section__c=MapCentre.get(g.Centre__c).id;

                string td = (g.Type_de_depense__c+'   ').left(3);
                la.Type_depense__c  =MapDepense.get(td).id;

                if(la.Type_depense__c==TDGAR.id) {
                    la.Type_de_ligne_d_affaire__c='G';
                } else {
                    la.Type_de_ligne_d_affaire__c='I';
                }

                la.Ecart_C_A_F_Heure__c      =(g.NB_heures__c==null ? 0 :g.NB_heures__c)  ;
                la.Ecart_C_A_F_MontantD__c   =(g.montant__c==null   ? 0 :g.montant__c);
                la.Ecart_C_A_F_MontantD_E__c =(g.montant__c==null   ? 0 :g.montant__c);                

                MapLa.put(key,la); 
            }
            g.Import_Status__c='2';
            
        }    
        upsert MapLa.values();     
        update scope ; 
        if(ListErreur.size()>0) {
            string s = string.join(ListErreur,'\n')+' ....'; 
            VIUtils.LogWrite('VISchedImportGEcart','3 Error',null,s);                
        }

    }

    global void finish(Database.BatchableContext BC){
        IDLog=VIUtils.LogWrite('VISchedImportGEcart','1 Normal',IDLog,'End '+num_record);
        //if(enchaine)
        //    Database.executeBatch(new VIBatchRegenerateLAM(AffaireAGenerer, enchaine), VIBatchRegenerateLAM.NBR_LOT());        
        
    }

    global void execute(SchedulableContext scon) {
        Database.executeBatch(new VISchedImportGEcart(AffaireAGenerer, enchaine, toute, DateImport),VISchedImportGEcart.NBR_LOT());
    }

    public static  integer NBR_LOT () {
         VIParametres__c param = VIParametres__c.getInstance(UserInfo.getUserId()); 
         integer i ; 
         if(param.Sans_Calcul_de_PRI__c) {
             i=500 ;
         } else {
             i=1;    
         }
         return i;
    }

}