force-app/main/default/objects/Int_Facture__c/Int_Facture__c.object-meta.xml
<CustomObject>
    <label>Int_Facture</label>
    <nameField>
        <displayFormat>F{000000000}</displayFormat>
        <label>Nom de Int_Facture</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Int_Facture</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Int_Facture__c/fields/Date_de_comptabilisation__c.field-meta.xml
<CustomField>
    <fullName>Date_de_comptabilisation__c</fullName>
    <label>Date de comptabilisation</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Int_Facture__c/fields/MtHT__c.field-meta.xml
<CustomField>
    <fullName>MtHT__c</fullName>
    <label>MtHT</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Int_Facture__c/fields/Type_enregistrement__c.field-meta.xml
<CustomField>
    <fullName>Type_enregistrement__c</fullName>
    <label>Type enregistrement</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VICentre_Section__c/VICentre_Section__c.object-meta.xml
<CustomObject>
    <label>Centre / Section</label>
    <nameField>
        <label>Nom de Centre / Section</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Centres / Sections</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VICompte_general__c/VICompte_general__c.object-meta.xml
<CustomObject>
    <label>Compte général</label>
    <nameField>
        <label>Nom de Compte général</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Comptes généraux</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VICompte_general__c/fields/Type_enregistrement__c.field-meta.xml
<CustomField>
    <fullName>Type_enregistrement__c</fullName>
    <formula>if( Alimentation_PR_PV__c =&apos;PR&apos;, &apos;R&apos;, if(Alimentation_PR_PV__c =&apos;PV&apos;, &apos;A&apos;,&apos;&apos;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type d&apos;enregistrement</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/VISchedImportFacture_test.cls
@isTest
public class VISchedImportFacture_test {

    static testmethod void VISchedImportFacture_test() {
    
        VIInsertDataTest.VIInsertData_EUR_Affaire();

        VICentre_Section__c cs = new VICentre_Section__c (name ='800');
        insert cs; 

        VICompte_General__c cg = new VICompte_General__c(name='700000', libelle__c='7000000');
        insert cg ; 
        
        int_Facture__c fac = new int_facture__c (
                               codeAffaire__c='B80000',
                               libelle__c='toto',
                               date_de_comptabilisation__c=System.today(),
                               Compte__c ='123' ,
                               Date__c =System.today(),
                               MtHT__c    =1,
                               type_enregistrement__c='FAC') ;
        insert fac;
        
        int_Facture__c fac1 = new int_facture__c (
                               codeAffaire__c='B80000',
                               libelle__c='toto',            
                               date_de_comptabilisation__c=System.today(),
                               Compte__c ='700000' ,
                               Date__c =System.today(),
                               MtHT__c    =1,
                               type_enregistrement__c='ECR') ;
        insert fac1;
        
        VISchedImportFacture v1 = new VISchedImportFacture('B80000',false,false);
        v1.execute(null);

    }
}