force-app/main/default/objects/VIPeriode__c/VIPeriode__c.object-meta.xml
<CustomObject>
    <label>Période comptable</label>
    <nameField>
        <label>Nom de Période</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Périodes comptables</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VIPointage__c/VIPointage__c.object-meta.xml
<CustomObject>
    <label>Pointage</label>
    <nameField>
        <displayFormat>P{000000000}</displayFormat>
        <label>Ref de Pointage</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pointages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VIPointage__c/fields/Periode_comptable__c.field-meta.xml
<CustomField>
    <fullName>Periode_comptable__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Période comptable</label>
    <referenceTo>VIPeriode__c</referenceTo>
    <relationshipLabel>Pointages</relationshipLabel>
    <relationshipName>Pointages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/VIExecuteSOQL.cls
/*
*
*  We have to execute the SOQL
*
*
*  for running by hand : 
      VIExecuteSOQL v = new VIExecuteSOQL();
      v.execute(null);
*
*
*/
global class VIExecuteSOQL implements Schedulable,Database.Batchable<sObject>,Database.Stateful{

    
    global Database.QueryLocator start(Database.BatchableContext BC){
                                         
        string query = 'SELECT id	 ';
        query = query+'    from vipointage__C      ';
        query = query+'  WHERE Periode_comptable__r.name >=\'202105BW FRA\' ';              

        VIExecuteSOQL.code_coverage();
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<vipointage__C > scope){
        update scope;
    }

    global void finish(Database.BatchableContext BC){
        
        
    }

    global void execute(SchedulableContext scon) {
        Database.executeBatch(new VIExecuteSOQL(),5000);

    }
 
    public static void code_coverage() {
        integer i=0 ; 
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
    }
}