force-app/main/default/objects/int_gdatedesav__c/int_gdatedesav__c.object-meta.xml
<CustomObject>
    <label>int_gdatedesav</label>
    <nameField>
        <label>Nom de int_gdatedefin</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>int_gdatedesav</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/int_gdatedesav__c/fields/Code_affaire__c.field-meta.xml
<CustomField>
    <fullName>Code_affaire__c</fullName>
    <label>Code_affaire</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/int_gdatedesav__c/fields/Date_de_sav__c.field-meta.xml
<CustomField>
    <fullName>Date_de_sav__c</fullName>
    <label>Date_de_sav</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/int_gecart__c/int_gecart__c.object-meta.xml
<CustomObject>
    <label>int_gecart</label>
    <nameField>
        <label>Nom de int_gecart</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>int_gecart</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/int_gecart__c/fields/Centre__c.field-meta.xml
<CustomField>
    <fullName>Centre__c</fullName>
    <label>Centre</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/int_gecart__c/fields/Code_Affaire__c.field-meta.xml
<CustomField>
    <fullName>Code_Affaire__c</fullName>
    <label>Code_Affaire</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/int_gecart__c/fields/Montant__c.field-meta.xml
<CustomField>
    <fullName>Montant__c</fullName>
    <label>Montant</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/int_gecart__c/fields/Type_de_depense__c.field-meta.xml
<CustomField>
    <fullName>Type_de_depense__c</fullName>
    <label>Type_de_depense</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VIAffaire__c/VIAffaire__c.object-meta.xml
<CustomObject>
    <label>Affaire</label>
    <nameField>
        <label>Code Affaire</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Affaires</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VICentre_Section__c/VICentre_Section__c.object-meta.xml
<CustomObject>
    <label>Centre / Section</label>
    <nameField>
        <label>Nom de Centre / Section</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Centres / Sections</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VIPeriode__c/VIPeriode__c.object-meta.xml
<CustomObject>
    <label>Période comptable</label>
    <nameField>
        <label>Nom de Période</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Périodes comptables</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VIPeriode__c/fields/Date_de_debut__c.field-meta.xml
<CustomField>
    <fullName>Date_de_debut__c</fullName>
    <label>Date de début</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VIPeriode__c/fields/Date_de_fin__c.field-meta.xml
<CustomField>
    <fullName>Date_de_fin__c</fullName>
    <label>Date de fin</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VIPeriode__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Periode_comptable_statut</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/VIType_de_depense__c/VIType_de_depense__c.object-meta.xml
<CustomObject>
    <label>Type de dépense</label>
    <nameField>
        <label>Nom de Type de dépense</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Types de dépenses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/VISchedImportGDateDeSAV_test.cls
@isTest
public class VISchedImportGDateDeSAV_test {

    static testmethod void VISchedImportGDateDeSAV_test() {
    
 
        VIInsertDataTest.VIInsertData_EUR_Affaire();
        VIAffaire__c aff = [select id,name from VIaffaire__c LIMIT 1];

        list<VIperiode__c>ListPeriode=[SELECT id,date_de_fin__c ,date_de_debut__c
                                         FROM VIperiode__c 
                                       WHERE Statut__c =:VIConstant.PERIODE_OUVERTE
                                     ORDER BY NAME LIMIT 1];
        
        int_gdatedesav__c i = new int_gdatedesav__c(code_affaire__c=aff.name, date_de_sav__c=ListPeriode[0].date_de_fin__c);
        insert i;


        VIType_de_depense__c td = [select name from VIType_de_depense__c limit 1];
        VICentre_Section__c cs = [select name from VICentre_Section__c limit 1];
        
        int_gecart__c e = new int_gecart__c(code_affaire__c=aff.name,date__c=ListPeriode[0].date_de_debut__c,
                                            type_de_depense__c=td.name,
                                            centre__c=cs.name,
                                            montant__c=1);
        insert e; 
        
                
        VISchedImportGDateDeSAV v1 = new VISchedImportGDateDeSAV('B80000',false,false);
        v1.execute(null);

        VISchedImportGecart v2 = new VISchedImportGecart('B80000',false,false,ListPeriode[0].date_de_debut__c);
        v2.execute(null);

    }
}