force-app/main/default/objects/Type__c/Type__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Transcodification Type</description>
    <label>Type</label>
</CustomObject>

force-app/main/default/objects/VIAffaire__c/VIAffaire__c.object-meta.xml
<CustomObject>
    <label>Affaire</label>
    <nameField>
        <label>Code Affaire</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Affaires</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VIFacture__c/VIFacture__c.object-meta.xml
<CustomObject>
    <label>Facture</label>
    <nameField>
        <label>Nom de Facture</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Factures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VIFacture__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>RGC</fullName>
            </value>
            <value>
                <fullName>ECR</fullName>
            </value>
            <value>
                <fullName>FAC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VILigne_d_affaire_mensuelle__c/VILigne_d_affaire_mensuelle__c.object-meta.xml
<CustomObject>
    <label>Ligne d&apos;affaire mensuelle</label>
    <nameField>
        <label>Ref de Ligne d&apos;affaire mensuelle</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lignes d&apos;affaire mensuelles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/VIZoomFacturesController_Test.cls
@isTest
public class VIZoomFacturesController_Test {

    static testmethod void VIZoomFacturesController_Test() {
    
        VIInsertDataTest.VIInsertData_GBP_Avenant();
        VIInsertDataTest.VIInsertData_Facture();
        
        VIFacture__c fac=[select type__C from VIFacture__c limit 1];
        fac.type__C='FAC';
        update fac;

        VIAffaire__c affaire = [select id from VIAffaire__c LIMIT 1];
        VILigne_d_affaire_mensuelle__c Lam = [SELECT id FROM VILigne_d_affaire_mensuelle__c Limit 1];
        
        PageReference pageRef = Page.VIZoomFactures; 
        test.setCurrentPageReference(pageRef);
        ApexPages.currentPage().getParameters().put('aff',affaire.Id);
        ApexPages.currentPage().getParameters().put('per','209901');
        ApexPages.currentPage().getParameters().put('lam',lam.id);
        

                
        VIZoomFacturesController testPage = new VIZoomFacturesController ();  
                
        
    }
}