force-app/main/default/objects/VIAchat__c/VIAchat__c.object-meta.xml
<CustomObject>
    <label>Dépense</label>
    <nameField>
        <label>Ref d&apos;achat</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dépenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VIAchat__c/fields/Affaire__c.field-meta.xml
<CustomField>
    <fullName>Affaire__c</fullName>
    <label>Affaire</label>
    <referenceTo>VIAffaire__c</referenceTo>
    <relationshipName>Achats</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VIAchat__c/fields/Centre_Section__c.field-meta.xml
<CustomField>
    <fullName>Centre_Section__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Centre / Section</label>
    <referenceTo>VICentre_Section__c</referenceTo>
    <relationshipName>Achats</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VIAchat__c/fields/ComptabiliseD__c.field-meta.xml
<CustomField>
    <fullName>ComptabiliseD__c</fullName>
    <label>ComptabiliséD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VIAchat__c/fields/CompteGeneral__c.field-meta.xml
<CustomField>
    <fullName>CompteGeneral__c</fullName>
    <label>Compte général</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VIAchat__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Date de commande</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VIAchat__c/fields/Num_cde__c.field-meta.xml
<CustomField>
    <fullName>Num_cde__c</fullName>
    <externalId>true</externalId>
    <label>Num_cde</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VIAchat__c/fields/Origine__c.field-meta.xml
<CustomField>
    <fullName>Origine__c</fullName>
    <label>Origine</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VIAchat__c/fields/Periode_comptable__c.field-meta.xml
<CustomField>
    <fullName>Periode_comptable__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Période comptable</label>
    <referenceTo>VIPeriode__c</referenceTo>
    <relationshipName>Achats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VIAchat__c/fields/Sous_chapitre__c.field-meta.xml
<CustomField>
    <fullName>Sous_chapitre__c</fullName>
    <label>Sous chapitre</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sous_chapitre</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/VIAchat__c/fields/Type_depense__c.field-meta.xml
<CustomField>
    <fullName>Type_depense__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Type de dépense</label>
    <referenceTo>VIType_de_depense__c</referenceTo>
    <relationshipName>Achats</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VIFacture__c/VIFacture__c.object-meta.xml
<CustomObject>
    <label>Facture</label>
    <nameField>
        <label>Nom de Facture</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Factures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VIFacture__c/fields/Affaire__c.field-meta.xml
<CustomField>
    <fullName>Affaire__c</fullName>
    <label>Affaire</label>
    <referenceTo>VIAffaire__c</referenceTo>
    <relationshipLabel>Factures</relationshipLabel>
    <relationshipName>Factures</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VIFacture__c/fields/Compte_general__c.field-meta.xml
<CustomField>
    <fullName>Compte_general__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compte général</label>
    <referenceTo>VICompte_general__c</referenceTo>
    <relationshipLabel>Factures</relationshipLabel>
    <relationshipName>Factures</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VIFacture__c/fields/Periode_comptable__c.field-meta.xml
<CustomField>
    <fullName>Periode_comptable__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Période comptable</label>
    <referenceTo>VIPeriode__c</referenceTo>
    <relationshipLabel>Factures</relationshipLabel>
    <relationshipName>Factures</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VIFacture__c/fields/Sous_chapitre__c.field-meta.xml
<CustomField>
    <fullName>Sous_chapitre__c</fullName>
    <label>Sous_chapitre</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VILigne_affaire__c/VILigne_affaire__c.object-meta.xml
<CustomObject>
    <label>Ligne d&apos;affaire</label>
    <nameField>
        <displayFormat>L{000000000}</displayFormat>
        <label>Ref de Ligne d&apos;affaire</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lignes d&apos;affaire</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VILigne_affaire__c/fields/Centre_Section__c.field-meta.xml
<CustomField>
    <fullName>Centre_Section__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Centre / Section</label>
    <referenceTo>VICentre_Section__c</referenceTo>
    <relationshipLabel>Lignes d&apos;affaire</relationshipLabel>
    <relationshipName>Lignes_d_affaire</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VILigne_affaire__c/fields/Type_depense__c.field-meta.xml
<CustomField>
    <fullName>Type_depense__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Type de dépense</label>
    <referenceTo>VIType_de_depense__c</referenceTo>
    <relationshipLabel>Lignes d&apos;affaire</relationshipLabel>
    <relationshipName>Lignes_d_affaire</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VILigne_comptable__c/VILigne_comptable__c.object-meta.xml
<CustomObject>
    <label>Ligne comptable</label>
    <nameField>
        <displayFormat>L{000000000}</displayFormat>
        <label>Ref de la ligne comptable</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lignes comptables</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VILigne_comptable__c/fields/Affaire__c.field-meta.xml
<CustomField>
    <fullName>Affaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Affaire</label>
    <referenceTo>VIAffaire__c</referenceTo>
    <relationshipLabel>Lignes comptables (Affaire)</relationshipLabel>
    <relationshipName>Ecritures_comptables</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VILigne_comptable__c/fields/Periode_comptable__c.field-meta.xml
<CustomField>
    <fullName>Periode_comptable__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Période comptable</label>
    <referenceTo>VIPeriode__c</referenceTo>
    <relationshipName>Ecritures_comptables</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VILigne_comptable__c/fields/Sous_Chapitre__c.field-meta.xml
<CustomField>
    <fullName>Sous_Chapitre__c</fullName>
    <label>Sous-Chapitre</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sous_chapitre</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/VIPeriode__c/VIPeriode__c.object-meta.xml
<CustomObject>
    <label>Période comptable</label>
    <nameField>
        <label>Nom de Période</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Périodes comptables</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VIPeriode__c/fields/Date_de_fin__c.field-meta.xml
<CustomField>
    <fullName>Date_de_fin__c</fullName>
    <label>Date de fin</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VIPeriode__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Periode_comptable_statut</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/VIPointage__c/VIPointage__c.object-meta.xml
<CustomObject>
    <label>Pointage</label>
    <nameField>
        <displayFormat>P{000000000}</displayFormat>
        <label>Ref de Pointage</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pointages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VIPointage__c/fields/Affaire__c.field-meta.xml
<CustomField>
    <fullName>Affaire__c</fullName>
    <label>Affaire</label>
    <referenceTo>VIAffaire__c</referenceTo>
    <relationshipLabel>Pointages</relationshipLabel>
    <relationshipName>Pointages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VIPointage__c/fields/Centre_Section__c.field-meta.xml
<CustomField>
    <fullName>Centre_Section__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Centre / Section</label>
    <referenceTo>VICentre_Section__c</referenceTo>
    <relationshipLabel>Pointages</relationshipLabel>
    <relationshipName>Pointages</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VIPointage__c/fields/Complet__c.field-meta.xml
<CustomField>
    <fullName>Complet__c</fullName>
    <label>Complet</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VIPointage__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Date Pointage</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VIPointage__c/fields/Date_comptabilisation__c.field-meta.xml
<CustomField>
    <fullName>Date_comptabilisation__c</fullName>
    <label>Date comptabilisation</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VIPointage__c/fields/Debours__c.field-meta.xml
<CustomField>
    <fullName>Debours__c</fullName>
    <label>Debours</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VIPointage__c/fields/Employe__c.field-meta.xml
<CustomField>
    <fullName>Employe__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employé</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Pointages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VIPointage__c/fields/Heures__c.field-meta.xml
<CustomField>
    <fullName>Heures__c</fullName>
    <label>Heures</label>
    <precision>4</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VIPointage__c/fields/Periode_comptable__c.field-meta.xml
<CustomField>
    <fullName>Periode_comptable__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Période comptable</label>
    <referenceTo>VIPeriode__c</referenceTo>
    <relationshipLabel>Pointages</relationshipLabel>
    <relationshipName>Pointages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VIPointage__c/fields/Sous_chapitre__c.field-meta.xml
<CustomField>
    <fullName>Sous_chapitre__c</fullName>
    <label>Sous chapitre</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sous_chapitre</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/VISousDomaine__c/VISousDomaine__c.object-meta.xml
<CustomObject>
    <label>Produit - SousDomaine</label>
    <nameField>
        <label>SousDomaine</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Produits - SousDomaines</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VISousDomaine__c/fields/Mode_de_calcul_de_l_avancement__c.field-meta.xml
<CustomField>
    <fullName>Mode_de_calcul_de_l_avancement__c</fullName>
    <label>Mode de calcul de l&apos;avancement</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Mode_de_calcul_de_l_avancement</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/VISchedGenereCentralis_test.cls
@isTest
public class VISchedGenereCentralis_test {

    static testmethod void VISchedGenereCentralis_test() {
    
        VIInsertDataTest.VIInsertData_EUR_Affaire();
        VIInsertDataTest.VIInsertData_Achat();
        VIInsertDataTest.VIInsertData_Pointage();
        VIInsertDataTest.VIInsertData_Facture();
        
        
        VISousDomaine__c sd = [select  Mode_de_calcul_de_l_avancement__c from VISousDomaine__c];
        sd.Mode_de_calcul_de_l_avancement__c='2';
        update sd ; 

        VIPeriode__c per_ouverte ; 
        VIPeriode__c per_preouverte ;

        for(VIperiode__c per:[SELECT id,date_de_fin__c ,statut__c
                                FROM VIperiode__c 
                              ORDER BY NAME]) {
           if(per.statut__c==VIConstant.PERIODE_OUVERTE) 
               per_ouverte=per; 
           if(per.statut__c==VIConstant.PERIODE_PREOUVERTE) 
               per_preouverte=per; 
       }
        
        VICompte_general__c cc = new  VICompte_general__c  (name='7');
        VICompte_general__c c706000 = new  VICompte_general__c  (name='706000');
        VICompte_general__c c473000 = new  VICompte_general__c  (name='473000');        
        list<VICompte_general__c>ListCompteGeneral = new list<VICompte_general__c>();
        ListCompteGeneral.add(cc);
        ListCompteGeneral.add(c706000);        
        ListCompteGeneral.add(c473000);        
        
        insert ListCompteGeneral ; 
        
       
        VIAchat__c ac = [SELECT id, CompteGeneral__c , ComptabiliseD__c , periode_comptable__c , affaire__c,
                                Centre_Section__r.id,Type_depense__r.id,
                                CurrencyIsoCode, sous_chapitre__c,
                                num_cde__c,
                                origine__c
                           FROM VIachat__c 
                          WHERE periode_comptable__r.statut__c=:VIConstant.PERIODE_OUVERTE ];

        VIAchat__c newac = new VIAchat__c (name='aaa', CompteGeneral__c=ac.CompteGeneral__c , ComptabiliseD__c=1, affaire__c=ac.affaire__c,
                                           periode_comptable__c=per_preouverte.id,date__c=per_preouverte.date_de_fin__c,
                                           Centre_Section__c=ac.Centre_Section__r.id,Type_depense__c=ac.Type_depense__r.id,
                                           CurrencyIsoCode=ac.CurrencyIsoCode, sous_chapitre__c=ac.sous_chapitre__c,
                                           num_cde__c=ac.num_cde__c,
                                           origine__c=ac.origine__c);
        insert newac ; 
        
                       

        VIpointage__C point = [SELECT id , affaire__c, Centre_Section__c , Complet__c ,CompteGeneral__c ,date__c, Date_comptabilisation__c ,
                                      Debours__c ,Employe__c ,heures__c,Numero_unique__c , Sous_chapitre__c 
                                 FROM VIpointage__C 
                                WHERE periode_comptable__c=:Per_ouverte.id limit 1];
		VIpointage__c newpoint = new VIPointage__c (
                                        affaire__c=point.affaire__c, 
                                        Centre_Section__c=point.Centre_Section__c , 
                                        CompteGeneral__c=point.CompteGeneral__c ,
                                        date__c=per_preouverte.date_de_fin__c, 
                                        Date_comptabilisation__c=per_preouverte.date_de_fin__c ,
                                        Employe__c=point.Employe__c ,
                                        heures__c=point.heures__c,
                                        Numero_unique__c=point.Numero_unique__c+'zz' , 
                                        Sous_chapitre__c=point.Sous_chapitre__c );
        insert newPoint ;         


        VIfacture__C fac = [SELECT id , affaire__c, Compte__c  ,Compte_general__c,date__c, Date_de_comptabilisation__c ,
                                      Montant_HT__c, Periode_comptable__c ,Type__c  
                                 FROM VIfacture__C 
                                WHERE periode_comptable__c=:Per_ouverte.id limit 1];
		VIfacture__C newfac = new VIfacture__C (
                                        affaire__c=fac.affaire__c, 
                                        Compte__c=fac.Compte__c , 
                                        Compte_general__c =fac.Compte_general__c ,
                                        date__c=per_preouverte.date_de_fin__c, 
                                        Date_de_comptabilisation__c=per_preouverte.date_de_fin__c ,
                                        Montant_HT__c=fac.Montant_HT__c,
                                        Type__c=fac.Type__c );
        insert newfac ;         
        
        
        VIInsertDataTest.VIInsertData_ligne_comptable();
        
        list<VILigne_comptable__c>ListLc = [SELECT id,CompteComptable_local__c,Statut_ecriture_comptable__c  FROM VILigne_comptable__c];
        for(VILigne_comptable__c lc : ListLc) {
            lc.CompteComptable_local__c=c706000.id;
            lc.Statut_ecriture_comptable__c='40';
            lc.type_de_depense__c='AVT';
        }
        update listLc ; 
        Database.executeBatch(new VISchedGenereCentralis1(),VISchedGenereCentralis1.NBR_LOT());                
        for(VILigne_comptable__c lc : ListLc) {
            lc.CompteComptable_local__c=c473000.id;
        }
        update listLc ; 

        //VISchedGenereCentralis4 v = new VISchedGenereCentralis4();
        //v.execute(null);

        
/*      henri
        list<VILigne_Affaire__c>ListLa= [SELECT id, Cout_terminaison_MontantD__c, Engage_brut_arrete_MontantD__c,Ecart_C_A_F_MontantD__c   
                                           FROM VILigne_Affaire__c ] ;

        ListLa[0].Ecart_C_A_F_MontantD__c=1;
        update ListLa ; 
        System.assertEquals(2, listLa.size());
        System.assertEquals(101, listLa[0].Engage_brut_arrete_MontantD__c);
*/
        
    }
}