force-app/main/default/objects/VIAchat__c/VIAchat__c.object-meta.xml
<CustomObject>
    <label>Dépense</label>
    <nameField>
        <label>Ref d&apos;achat</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dépenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VIAchat__c/fields/Affaire__c.field-meta.xml
<CustomField>
    <fullName>Affaire__c</fullName>
    <label>Affaire</label>
    <referenceTo>VIAffaire__c</referenceTo>
    <relationshipName>Achats</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VIAchat__c/fields/Centre_Section__c.field-meta.xml
<CustomField>
    <fullName>Centre_Section__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Centre / Section</label>
    <referenceTo>VICentre_Section__c</referenceTo>
    <relationshipName>Achats</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VIAchat__c/fields/CommandeC__c.field-meta.xml
<CustomField>
    <fullName>CommandeC__c</fullName>
    <label>CommandéC</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VIAchat__c/fields/CommandeC_E__c.field-meta.xml
<CustomField>
    <fullName>CommandeC_E__c</fullName>
    <label>CommandéC €</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VIAchat__c/fields/CommandeD__c.field-meta.xml
<CustomField>
    <fullName>CommandeD__c</fullName>
    <label>CommandéD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VIAchat__c/fields/CommandeD_E__c.field-meta.xml
<CustomField>
    <fullName>CommandeD_E__c</fullName>
    <label>CommandéD €</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VIAchat__c/fields/CommandeI__c.field-meta.xml
<CustomField>
    <fullName>CommandeI__c</fullName>
    <label>CommandéI</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VIAchat__c/fields/CommandeI_E__c.field-meta.xml
<CustomField>
    <fullName>CommandeI_E__c</fullName>
    <label>CommandéI €</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VIAchat__c/fields/ComptabiliseC__c.field-meta.xml
<CustomField>
    <fullName>ComptabiliseC__c</fullName>
    <label>ComptabiliséC</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VIAchat__c/fields/ComptabiliseC_E__c.field-meta.xml
<CustomField>
    <fullName>ComptabiliseC_E__c</fullName>
    <label>ComptabiliséC €</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VIAchat__c/fields/ComptabiliseD__c.field-meta.xml
<CustomField>
    <fullName>ComptabiliseD__c</fullName>
    <label>ComptabiliséD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VIAchat__c/fields/ComptabiliseD_E__c.field-meta.xml
<CustomField>
    <fullName>ComptabiliseD_E__c</fullName>
    <label>ComptabiliséD €</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VIAchat__c/fields/ComptabiliseI__c.field-meta.xml
<CustomField>
    <fullName>ComptabiliseI__c</fullName>
    <label>ComptabiliséI</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VIAchat__c/fields/ComptabiliseI_E__c.field-meta.xml
<CustomField>
    <fullName>ComptabiliseI_E__c</fullName>
    <label>ComptabiliséI €</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VIAchat__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Date de commande</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VIAchat__c/fields/Origine__c.field-meta.xml
<CustomField>
    <fullName>Origine__c</fullName>
    <label>Origine</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VIAchat__c/fields/Periode_comptable__c.field-meta.xml
<CustomField>
    <fullName>Periode_comptable__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Période comptable</label>
    <referenceTo>VIPeriode__c</referenceTo>
    <relationshipName>Achats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VIAchat__c/fields/Sous_chapitre__c.field-meta.xml
<CustomField>
    <fullName>Sous_chapitre__c</fullName>
    <label>Sous chapitre</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sous_chapitre</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/VIAchat__c/fields/Type_depense__c.field-meta.xml
<CustomField>
    <fullName>Type_depense__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Type de dépense</label>
    <referenceTo>VIType_de_depense__c</referenceTo>
    <relationshipName>Achats</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VIAffaire__c/VIAffaire__c.object-meta.xml
<CustomObject>
    <label>Affaire</label>
    <nameField>
        <label>Code Affaire</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Affaires</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VIAffaire__c/fields/Date_de_fin_de_garantie__c.field-meta.xml
<CustomField>
    <fullName>Date_de_fin_de_garantie__c</fullName>
    <formula>if(!isnull(Date_de_SAV_reelle__c) , 
     ADDMONTHS( Date_de_SAV_reelle__c, Produit_SousDomaine__r.Duree_garantie__c  ),
     null)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Date de fin de garantie</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VIAffaire__c/fields/Date_de_SAV_reelle__c.field-meta.xml
<CustomField>
    <fullName>Date_de_SAV_reelle__c</fullName>
    <label>Date de SAV réelle</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VIAffaire__c/fields/Date_ouverture_affaire__c.field-meta.xml
<CustomField>
    <fullName>Date_ouverture_affaire__c</fullName>
    <label>Date d&apos;ouverture d&apos;affaire</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VIAffaire__c/fields/Entite_BW__c.field-meta.xml
<CustomField>
    <fullName>Entite_BW__c</fullName>
    <label>Entité BW</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>EntiteBW</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/VIAffaire__c/fields/Produit_SousDomaine__c.field-meta.xml
<CustomField>
    <fullName>Produit_SousDomaine__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Produit - SousDomaine</label>
    <referenceTo>VISousDomaine__c</referenceTo>
    <relationshipLabel>Affaires</relationshipLabel>
    <relationshipName>Affaires</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VIParametres__c/VIParametres__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>VIParametres</label>
</CustomObject>

force-app/main/default/objects/VIParametres__c/fields/Sans_Calcul_de_PRI__c.field-meta.xml
<CustomField>
    <fullName>Sans_Calcul_de_PRI__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Si coché, on fait le calcul avec les taux.Sinon, on prend les montants tel quel</inlineHelpText>
    <label>Sans Calcul de PRI ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VIPeriode__c/VIPeriode__c.object-meta.xml
<CustomObject>
    <label>Période comptable</label>
    <nameField>
        <label>Nom de Période</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Périodes comptables</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VIPeriode__c/fields/Date_de_debut__c.field-meta.xml
<CustomField>
    <fullName>Date_de_debut__c</fullName>
    <label>Date de début</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VIPeriode__c/fields/Date_de_fin__c.field-meta.xml
<CustomField>
    <fullName>Date_de_fin__c</fullName>
    <label>Date de fin</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VIPeriode__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Periode_comptable_statut</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/VISousDomaine__c/VISousDomaine__c.object-meta.xml
<CustomObject>
    <label>Produit - SousDomaine</label>
    <nameField>
        <label>SousDomaine</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Produits - SousDomaines</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VISousDomaine__c/fields/FGX__c.field-meta.xml
<CustomField>
    <fullName>FGX__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Faut il calculer des FGX / PRI ?</inlineHelpText>
    <label>FGX</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VISousDomaine__c/fields/K3__c.field-meta.xml
<CustomField>
    <fullName>K3__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Faut il calculer du K3 / Complet pour ce produit ?</inlineHelpText>
    <label>K3</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VITauxIncorporation__c/VITauxIncorporation__c.object-meta.xml
<CustomObject>
    <label>Taux d&apos;incorporation</label>
    <nameField>
        <displayFormat>TI{00000}</displayFormat>
        <label>Ref de Taux d&apos;incorporation</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Taux d&apos;incorporation</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VITauxIncorporation__c/fields/Date_de_debut__c.field-meta.xml
<CustomField>
    <fullName>Date_de_debut__c</fullName>
    <label>Date de début</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VITauxIncorporation__c/fields/Date_de_fin__c.field-meta.xml
<CustomField>
    <fullName>Date_de_fin__c</fullName>
    <label>Date de fin</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VITauxIncorporation__c/fields/Entite_BW__c.field-meta.xml
<CustomField>
    <fullName>Entite_BW__c</fullName>
    <label>Entité BW</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>EntiteBW</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/VITauxIncorporation__c/fields/Produit_SousDomaine__c.field-meta.xml
<CustomField>
    <fullName>Produit_SousDomaine__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produit - SousDomaine</label>
    <referenceTo>VISousDomaine__c</referenceTo>
    <relationshipLabel>Taux d&apos;incorporation</relationshipLabel>
    <relationshipName>Taux_d_incorporation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VITauxIncorporation__c/fields/Taux_complet__c.field-meta.xml
<CustomField>
    <fullName>Taux_complet__c</fullName>
    <label>Taux complet</label>
    <precision>16</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VITauxIncorporation__c/fields/Taux_PRI__c.field-meta.xml
<CustomField>
    <fullName>Taux_PRI__c</fullName>
    <label>Taux PRI</label>
    <precision>16</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VITauxIncorporation__c/fields/Type_de_depense__c.field-meta.xml
<CustomField>
    <fullName>Type_de_depense__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Type de dépense</label>
    <referenceTo>VIType_de_depense__c</referenceTo>
    <relationshipLabel>Taux d&apos;incorporation</relationshipLabel>
    <relationshipName>Taux_d_incorporation</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/VI01_VIAchat.cls
/*
* @author: Henri Saslawsky
* @description: 
*/

public class VI01_VIAchat {
/*
* @description: Method to fill up the Periode_comptable at the insert of the line
* 
* @param: List of VIAchat
* @return : void
* 
*/

    public static void Load_period (List <VIAchat__c> listAc) { 
        // Let's load all thxe involved Affaire. 
        List<string>ListIdAffaire = new List<string>();
        date date_minimum=null ; 
        date date_maximum=null ; 
        
        VIParametres__c param = VIParametres__c.getInstance(UserInfo.getUserId());  
        
        for(VIAchat__c ac:ListAc) {
            listIdAffaire.add(ac.affaire__c);
            
            if(date_minimum==null || date_minimum>ac.Date__c)
                date_minimum=ac.Date__c ; 
                                                       
            if(date_maximum==null || date_maximum<ac.Date__c)
                date_maximum=ac.Date__c ; 
        }

        if(date_minimum<=date.newinstance(2018,01,01) ) {
            date_minimum=date.newinstance(2018,01,01);
        }
        if(date_maximum<date_minimum)
            date_maximum=date_minimum;
        
        date_minimum=date_minimum.addmonths(-1).toStartOfMonth();
        date_maximum=date_maximum.addmonths(+2).toStartOfMonth();        
        
        Map<string,id>MapPeriodeOuverte = new Map<string,id>();

        // Let's load all the open periode
        map<string,VIPeriode__c>MapPeriode = new map<string,VIPeriode__c>();
        for(VIperiode__c pe :[SELECT id, name, entite_bw__c,statut__c  
                                FROM VIperiode__c
                               WHERE (date_de_debut__c>=:date_minimum
                                 AND date_de_fin__c<=:date_maximum)
                                  OR statut__c =:VIConstant.PERIODE_OUVERTE]) {
            MapPeriode.put(pe.name,pe);
            if(pe.statut__c==VIConstant.PERIODE_OUVERTE)  {
                MapPeriodeOuverte.put(pe.entite_bw__c,pe.id);
            }                
        }
        
        
        map<id, string>Mapentite_bw = new map<id, string>();
        map<id,list<Date>>MapDateAffaire = new map<id,list<Date>>();
        for(VIAffaire__c aff: [SELECT id, tolabel(entite_bw__c), 
                                      date_ouverture_affaire__c,Date_de_SAV_reelle__c ,Date_de_fin_de_garantie__c
                                  FROM VIAffaire__c
                                 WHERE id in :ListIdAffaire]) {
            MapEntite_BW.put(aff.id,aff.entite_bw__c);
            list<date>ListDate = new list<date>();
            ListDate.add(aff.date_ouverture_affaire__c) ;
            ListDate.add(aff.Date_de_SAV_reelle__c) ;                                                                          
            ListDate.add(aff.Date_de_fin_de_garantie__c) ;
            MapDateAffaire.put(aff.id,ListDate);                                     
        }
        
        //Let's load
        for(VIAchat__c ac:ListAc) {
            date d = ac.date__c;
            if(d<=date.newinstance(2018,01,01) ) {
                d=date.newinstance(2018,01,01);
            }

            if(param.Sans_Calcul_de_PRI__c) {
                string key=string.valueof(d.Year())+string.valueof(d.month()).leftpad(2,'0')+MapEntite_bw.get(ac.affaire__c) ;                
                ac.periode_comptable__c= MapPeriode.get(key).id;
            } else {
                date date_min = MapDateAffaire.get(ac.affaire__c)[0];
                date date_sav = MapDateAffaire.get(ac.affaire__c)[1];                        
                date date_max = MapDateAffaire.get(ac.affaire__c)[2];
                if(d<date_min || d>date_max) {
                    ac.AddError(label.VIErreur008+ac.name+' '+ac.affaire__C);                
                } else  if(date_sav==null && (ac.Sous_chapitre__c=='98' ||ac.Sous_chapitre__c=='99') ) {
                    ac.AddError(label.VIErreur009+ac.name+' '+ac.affaire__C);                
                } else if(date_sav!=null && (ac.Sous_chapitre__c=='00') ) {
                    ac.AddError(label.VIErreur010+ac.name+' '+ac.affaire__C);                
                } else {
                    string key=string.valueof(d.Year())+string.valueof(d.month()).leftpad(2,'0')+MapEntite_bw.get(ac.affaire__c) ;
                    VIperiode__C per = MapPeriode.get(key);
                    if(per.statut__c==VIConstant.PERIODE_FERMEE) {
                        ac.periode_comptable__c= MapPeriodeOuverte.get(MapEntite_bw.get(ac.affaire__c));
                    } else {
                        ac.periode_comptable__c= MapPeriode.get(key).id;
                    }
                }
            }                
        }
    
    }

/*
* @description: Method to compute the total on VILigne_affaire from VIAchat
* 
* @param: List of VIAchat
* @return : void
* 
*/
    public static list<id> ReProcess_LA (List <VIAchat__c> listAc) { 

        system.debug('entrée dans reprocess_la');
        Map<id,id>MapIDAff = new Map<id,id>();
        for(VIAchat__c ac : listAc) {
            MapIDAff.put(ac.affaire__c,ac.affaire__c);   // NE faire le recalcul que quand ça vaut le coup
        }

        return MapIDAff.values() ;


    }

/*
* @description: From Debours, we need to compute "industriel" and "complet"
* 
* @param: List of VIAchat
* @return : void
* 
*/ 
    
    public static void Compute_Value (List <VIAchat__c> listAc) {
       
        list<String> ListCurrency         = new list<string>();
        list<String> ListIdAffaire        = new list<string>();         
        Map<String,string> MapSousDomaine = new Map<String,string>(); 
        Map<String,string> MapAffCurrency = new Map<String,string>(); 
        Map<String,string> MapAffEntite_BW= new Map<String,string>();         
        Map<String,boolean> MapAffFgx     = new Map<String,boolean>();                 
        Map<String,boolean> MapAffk3      = new Map<String,boolean>();                         
        
        date date_minimum=null; //We don't need the currency rates below this date
        
        
        // Let's fetch the affaire and centre
        for(VIAchat__c ac:ListAc){
            ListCurrency.add(ac.currencyIsoCode);
            ListIdAffaire.add(ac.affaire__c);
            if(date_minimum==null || ac.date__c<date_minimum) 
                date_minimum=ac.date__c ;
        }

        // Lets fetch the Sous-domaine
        for(VIAffaire__c aff: [SELECT id, name, Produit_SousDomaine__c,
                                      Produit_SousDomaine__r.fgx__c,Produit_SousDomaine__r.k3__c ,
                                      currencyIsoCode,entite_bw__c
                                 FROM VIAffaire__c
                               WHERE id in :ListIdAffaire ]) {
            MapSousDomaine.put(aff.id, aff.Produit_SousDomaine__c );
            MapAffCurrency.put(aff.id,aff.currencyIsoCode);
            MapAffEntite_bw.put(aff.id,aff.entite_bw__c);
            MapAffFgx.put(aff.id, aff.Produit_SousDomaine__r.fgx__c );
            MapAffk3.put(aff.id, aff.Produit_SousDomaine__r.k3__c );                                   
        }
        
        // Let's fetch the currency rates needed
        List<DatedConversionRate> currencyTypeList = [SELECT Id, IsoCode, ConversionRate, StartDate, NextStartDate 
                                                        FROM DatedConversionRate 
                                                       WHERE IsoCode in :ListCurrency
                                                         AND (NextStartDate<:date_minimum or NextStartDate>9998-01-01 ) 
                                                    ORDER BY IsoCode, NextStartDate DESC];
        
        // Let's fetch all the rates we need to use later
        // WHERE   AND CurrencyIsoCode in :ListCurrency
        //                  AND Centre_Section__c in :ListCentreSection
        // 
        list<VITauxIncorporation__c >ListTaux = new List<VITauxIncorporation__c >();

        for(VITauxIncorporation__c  t:[SELECT entite_bw__c,Produit_SousDomaine__c , type_de_depense__c, CurrencyIsoCode,Date_de_debut__c,Date_de_fin__c,
                                              Taux_PRI__c , Taux_complet__c
                                         FROM VITauxIncorporation__c 
                                        WHERE CurrencyIsoCode in :ListCurrency
                                          AND Produit_SousDomaine__c in :MapSousDomaine.values()
                                          AND date_de_debut__c<=:date_minimum
                                          AND date_de_fin__c>=:date_minimum ]) {
              ListTaux.add(t);             
         }

        for(VIAchat__c ac:ListAc){     
            if(ac.origine__c=='Contrepartie') {
                ac.CommandeD_E__c = ac.CommandeD__c ; 
                ac.CommandeI_E__c = ac.CommandeI__c ; 
                ac.CommandeC_E__c = ac.CommandeC__c ;                 
                ac.ComptabiliseD_E__c = ac.ComptabiliseD__c ; 
                ac.ComptabiliseI_E__c = ac.ComptabiliseI__c ; 
                ac.ComptabiliseC_E__c = ac.ComptabiliseC__c ;    
                continue ; 
            }
            
            // We need to find the correct line in the list
            VITauxIncorporation__c t_correct = new VITauxIncorporation__c();
            t_correct = null;
            for(VITauxIncorporation__c t:ListTaux) {
                
                if(t.entite_bw__c    == MapAffentite_bw.get(ac.affaire__c) && 
                   t.CurrencyIsoCode == MapAffCurrency.get(ac.affaire__c) && 
                   t.type_de_depense__c == ac.type_depense__c && 
                   t.Produit_SousDomaine__c == MapSousDomaine.get(ac.affaire__c) &&
                   t.date_de_debut__c  <= ac.date__c && 
                   t.date_de_fin__c    >= ac.date__c  ) {
                  t_correct=t ; 
                  break ;     
               }   
            }
                        
            // Hope we found the correct line
            if(t_correct!=null) {
                if(!MapAffFgx.get(ac.affaire__c))
                    t_correct.taux_PRI__c=1;

                if(!MapAffk3.get(ac.affaire__c))
                    t_correct.taux_complet__c=t_correct.taux_PRI__c;
                
                ac.CommandeI__c     = (ac.CommandeD__c==null ? 0:ac.CommandeD__c)          * t_correct.taux_PRI__c;
                ac.CommandeC__c     = (ac.CommandeD__c==null ? 0:ac.CommandeD__c)          * t_correct.taux_Complet__c;                
                ac.ComptabiliseI__c = (ac.ComptabiliseD__c==null ? 0:ac.ComptabiliseD__c)  * t_correct.taux_PRI__c;
                ac.ComptabiliseC__c = (ac.ComptabiliseD__c==null ? 0:ac.ComptabiliseD__c)  * t_correct.taux_Complet__c;                
            }  else {
                ac.CommandeI__c = ac.CommandeD__c ;
                ac.CommandeC__c = ac.CommandeD__c ;                
                ac.ComptabiliseI__c = ac.ComptabiliseD__c ;
                ac.ComptabiliseC__c = ac.ComptabiliseD__c ;                               
            } 

            // If we are in EUR,we don't have to do any currency conversion
            if(ac.currencyIsoCode=='EUR') {
                ac.CommandeD_E__c = ac.CommandeD__c ; 
                ac.CommandeI_E__c = ac.CommandeI__c ; 
                ac.CommandeC_E__c = ac.CommandeC__c ;                 
                ac.ComptabiliseD_E__c = ac.ComptabiliseD__c ; 
                ac.ComptabiliseI_E__c = ac.ComptabiliseI__c ; 
                ac.ComptabiliseC_E__c = ac.ComptabiliseC__c ;                 
            } else {
                // We are in a currency
                // So let's loop until we find the correct line
                DatedConversionRate r_correct = null ; 
                for(DatedConversionRate r: currencyTypeList) {
                    if(r.IsoCode==ac.currencyIsoCode &&
                       r.StartDate<=ac.date__c && 
                       r.NextStartDate>=ac.date__c) {
                        r_correct = r;
                        break ; 
                    }
                }
                if(r_correct!=null) {
                    if(ac.CommandeD__c!=null) {
                        ac.CommandeD_E__c=(ac.CommandeD__c*(1/r_correct.ConversionRate)).SetScale(2);
                        ac.CommandeI_E__c=(ac.CommandeI__c*(1/r_correct.ConversionRate)).SetScale(2);
                        ac.CommandeC_E__c=(ac.CommandeC__c*(1/r_correct.ConversionRate)).SetScale(2);
                    }
                    if(ac.ComptabiliseD__c!=null) {
                        ac.ComptabiliseD_E__c=(ac.ComptabiliseD__c*(1/r_correct.ConversionRate)).SetScale(2);
                        ac.ComptabiliseI_E__c=(ac.ComptabiliseI__c*(1/r_correct.ConversionRate)).SetScale(2);
                        ac.ComptabiliseC_E__c=(ac.ComptabiliseC__c*(1/r_correct.ConversionRate)).SetScale(2);
                    }
                }
            }
        }           
    }
}