force-app/main/default/objects/VIAchat__c/VIAchat__c.object-meta.xml
<CustomObject>
    <label>Dépense</label>
    <nameField>
        <label>Ref d&apos;achat</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dépenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VIAchat__c/fields/Affaire__c.field-meta.xml
<CustomField>
    <fullName>Affaire__c</fullName>
    <label>Affaire</label>
    <referenceTo>VIAffaire__c</referenceTo>
    <relationshipName>Achats</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VIAchat__c/fields/Centre_Section__c.field-meta.xml
<CustomField>
    <fullName>Centre_Section__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Centre / Section</label>
    <referenceTo>VICentre_Section__c</referenceTo>
    <relationshipName>Achats</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VIAchat__c/fields/ComptabiliseD__c.field-meta.xml
<CustomField>
    <fullName>ComptabiliseD__c</fullName>
    <label>ComptabiliséD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VIAchat__c/fields/CompteGeneral__c.field-meta.xml
<CustomField>
    <fullName>CompteGeneral__c</fullName>
    <label>Compte général</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VIAchat__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Date de commande</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VIAchat__c/fields/Origine__c.field-meta.xml
<CustomField>
    <fullName>Origine__c</fullName>
    <label>Origine</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VIAchat__c/fields/Periode_comptable__c.field-meta.xml
<CustomField>
    <fullName>Periode_comptable__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Période comptable</label>
    <referenceTo>VIPeriode__c</referenceTo>
    <relationshipName>Achats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VIAchat__c/fields/Sous_chapitre__c.field-meta.xml
<CustomField>
    <fullName>Sous_chapitre__c</fullName>
    <label>Sous chapitre</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sous_chapitre</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/VIAchat__c/fields/Type_depense__c.field-meta.xml
<CustomField>
    <fullName>Type_depense__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Type de dépense</label>
    <referenceTo>VIType_de_depense__c</referenceTo>
    <relationshipName>Achats</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VIAffaire__c/VIAffaire__c.object-meta.xml
<CustomObject>
    <label>Affaire</label>
    <nameField>
        <label>Code Affaire</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Affaires</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VIAffaire__c/fields/Entite_BW__c.field-meta.xml
<CustomField>
    <fullName>Entite_BW__c</fullName>
    <label>Entité BW</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>EntiteBW</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/VIAffaire__c/fields/Mode_de_calcul_de_l_avancement__c.field-meta.xml
<CustomField>
    <fullName>Mode_de_calcul_de_l_avancement__c</fullName>
    <formula>Case(text( Produit_SousDomaine__r.Mode_de_calcul_de_l_avancement__c ),
   &apos;1&apos;, &apos;1- Avancement par les coûts&apos;, 
   &apos;2&apos;, &apos;2- En fonction de la facturation client&apos;, 
   &apos;3&apos;, &apos;3- Au prorata temporis&apos;,
   &apos;9&apos;, &apos;9-Pas de calcul à l avancement&apos;,
   &apos;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mode de calcul de l&apos;avancement</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VIAffaire__c/fields/Produit_SousDomaine__c.field-meta.xml
<CustomField>
    <fullName>Produit_SousDomaine__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Produit - SousDomaine</label>
    <referenceTo>VISousDomaine__c</referenceTo>
    <relationshipLabel>Affaires</relationshipLabel>
    <relationshipName>Affaires</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VICentre_Section__c/VICentre_Section__c.object-meta.xml
<CustomObject>
    <label>Centre / Section</label>
    <nameField>
        <label>Nom de Centre / Section</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Centres / Sections</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VICompte_general__c/VICompte_general__c.object-meta.xml
<CustomObject>
    <label>Compte général</label>
    <nameField>
        <label>Nom de Compte général</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Comptes généraux</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VILigne_affaire__c/VILigne_affaire__c.object-meta.xml
<CustomObject>
    <label>Ligne d&apos;affaire</label>
    <nameField>
        <displayFormat>L{000000000}</displayFormat>
        <label>Ref de Ligne d&apos;affaire</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lignes d&apos;affaire</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VILigne_affaire__c/fields/Centre_Section__c.field-meta.xml
<CustomField>
    <fullName>Centre_Section__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Centre / Section</label>
    <referenceTo>VICentre_Section__c</referenceTo>
    <relationshipLabel>Lignes d&apos;affaire</relationshipLabel>
    <relationshipName>Lignes_d_affaire</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VILigne_affaire__c/fields/Ecart_C_A_F_MontantD__c.field-meta.xml
<CustomField>
    <fullName>Ecart_C_A_F_MontantD__c</fullName>
    <label>Ecart C.A.F - MontantD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VILigne_affaire__c/fields/Engage_brut_arrete_MontantD__c.field-meta.xml
<CustomField>
    <fullName>Engage_brut_arrete_MontantD__c</fullName>
    <label>Engagé brut à l&apos;arrêté - MontantD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VILigne_affaire__c/fields/Entite_BW__c.field-meta.xml
<CustomField>
    <fullName>Entite_BW__c</fullName>
    <formula>Text( Ligne_d_affaire_mensuelle__r.Affaire__r.Entite_BW__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Entité BW</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VILigne_affaire__c/fields/Type_depense__c.field-meta.xml
<CustomField>
    <fullName>Type_depense__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Type de dépense</label>
    <referenceTo>VIType_de_depense__c</referenceTo>
    <relationshipLabel>Lignes d&apos;affaire</relationshipLabel>
    <relationshipName>Lignes_d_affaire</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VILigne_comptable__c/VILigne_comptable__c.object-meta.xml
<CustomObject>
    <label>Ligne comptable</label>
    <nameField>
        <displayFormat>L{000000000}</displayFormat>
        <label>Ref de la ligne comptable</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lignes comptables</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VILigne_comptable__c/fields/Affaire__c.field-meta.xml
<CustomField>
    <fullName>Affaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Affaire</label>
    <referenceTo>VIAffaire__c</referenceTo>
    <relationshipLabel>Lignes comptables (Affaire)</relationshipLabel>
    <relationshipName>Ecritures_comptables</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VILigne_comptable__c/fields/Affaire_de_rattachement__c.field-meta.xml
<CustomField>
    <fullName>Affaire_de_rattachement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Affaire de rattachement</label>
    <referenceTo>VIAffaire__c</referenceTo>
    <relationshipLabel>Lignes comptables (Affaire de rattachement)</relationshipLabel>
    <relationshipName>Lignes_comptables</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VILigne_comptable__c/fields/CompteComptable_local__c.field-meta.xml
<CustomField>
    <fullName>CompteComptable_local__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Compte comptable local</label>
    <referenceTo>VICompte_general__c</referenceTo>
    <relationshipLabel>Lignes comptables</relationshipLabel>
    <relationshipName>Lignes_comptables</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VILigne_comptable__c/fields/Montant__c.field-meta.xml
<CustomField>
    <fullName>Montant__c</fullName>
    <label>Montant</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VILigne_comptable__c/fields/Periode_comptable__c.field-meta.xml
<CustomField>
    <fullName>Periode_comptable__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Période comptable</label>
    <referenceTo>VIPeriode__c</referenceTo>
    <relationshipName>Ecritures_comptables</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VILigne_comptable__c/fields/Sens__c.field-meta.xml
<CustomField>
    <fullName>Sens__c</fullName>
    <label>Sens</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sens_ecriture_comptable</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/VILigne_comptable__c/fields/Sous_Chapitre__c.field-meta.xml
<CustomField>
    <fullName>Sous_Chapitre__c</fullName>
    <label>Sous-Chapitre</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sous_chapitre</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/VILigne_comptable__c/fields/Statut_ecriture_comptable__c.field-meta.xml
<CustomField>
    <fullName>Statut_ecriture_comptable__c</fullName>
    <defaultValue>&apos;10&apos;</defaultValue>
    <label>Statut écriture comptable</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Statut_ecriture_comptable</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/VIPeriode__c/VIPeriode__c.object-meta.xml
<CustomObject>
    <label>Période comptable</label>
    <nameField>
        <label>Nom de Période</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Périodes comptables</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VIPeriode__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Periode_comptable_statut</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/VISousDomaine__c/VISousDomaine__c.object-meta.xml
<CustomObject>
    <label>Produit - SousDomaine</label>
    <nameField>
        <label>SousDomaine</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Produits - SousDomaines</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VISousDomaine__c/fields/Mode_de_calcul_de_l_avancement__c.field-meta.xml
<CustomField>
    <fullName>Mode_de_calcul_de_l_avancement__c</fullName>
    <label>Mode de calcul de l&apos;avancement</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Mode_de_calcul_de_l_avancement</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/VISousDomaine__c/fields/Type_d_imputation__c.field-meta.xml
<CustomField>
    <fullName>Type_d_imputation__c</fullName>
    <label>Type d&apos;imputation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type_d_imputation</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/VIType_de_depense__c/VIType_de_depense__c.object-meta.xml
<CustomObject>
    <label>Type de dépense</label>
    <nameField>
        <label>Nom de Type de dépense</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Types de dépenses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/VIGenereLigne1_test.cls
@isTest
public class VIGenereLigne1_test {
 
    static testmethod void VIGenereLigne_type1_test() {
    
        VIInsertDataTest.VIInsertData_EUR_affaire();
        //VIInsertDataTest.VIInsertData_Achat();
        //VIInsertDataTest.VIInsertData_Pointage();
        //VIInsertDataTest.VIInsertData_Facture();
        

        VIType_de_depense__c tdMat=[select id from VIType_de_depense__c where name like 'MAT%' ];
        VIType_de_depense__c tdMo=[select id from VIType_de_depense__c where name like 'MO%' ];
        VIType_de_depense__c tdGAR=[select id from VIType_de_depense__c where name like 'GAR%' ];
        VIType_de_depense__c tdPFG=[select id from VIType_de_depense__c where name like 'PFG%' ];
        
        VIcentre_section__c cs=[select id from VIcentre_section__c LIMIT 1 ];
       
        list<VICompte_general__c>ListCG = new list<VICompte_general__c>();
        listCG.add(new  VICompte_general__c  (name='7'));
        listCG.add(new  VICompte_general__c  (name='920100'));
        listCG.add(new  VICompte_general__c  (name='930100'));
        listCG.add(new  VICompte_general__c  (name='940100'));
        listCG.add(new  VICompte_general__c  (name='606000'));        
        listCG.add(new  VICompte_general__c  (name='903000'));        

        insert ListCG ; 
        VICompte_general__c cg = [select id from VICompte_general__c LIMIT 1];

        VIperiode__c per_ouverte =[SELECT id,name
                                     FROM VIperiode__c 
                                    WHERE statut__c=:VIConstant.PERIODE_OUVERTE ];

        VIperiode__c per_derniere =[SELECT id,name
                                     FROM VIperiode__c 
                                    WHERE statut__c=:VIConstant.PERIODE_DERNIERE ];

        VIAffaire__c aff= [select id, Produit_SousDomaine__c, Entite_BW__c   from VIAffaire__c];

            
        VISousDomaine__c sousdomaine = [select id, Type_d_imputation__c,Mode_de_calcul_de_l_avancement__c  from VISousDomaine__c ];
        sousdomaine.Type_d_imputation__c ='1';
        sousdomaine.Mode_de_calcul_de_l_avancement__c='2';
        update sousdomaine ; 

        VIInsertDataTest.VIInsertData_Achat();
        VIInsertDataTest.VIInsertData_pointage();

        VIAchat__c ac = [SELECT id, origine__c 
                           FROM VIAchat__c] ;
        ac.origine__c='SQL-SERVER-Facture-Fournisseur';
        update ac;

        VILigne_comptable__c lc = new VILigne_comptable__c(affaire_de_rattachement__c=aff.id, 
                                                           Periode_comptable__c=per_ouverte.id,
                                                           statut_ecriture_comptable__c='40',
                                                           sens__c='D',
                                                           montant__c=1,
                                                           CompteComptable_local__c=cg.id,
                                                           sous_chapitre__c='00-00',
                                                           libelle__c='ll');
        insert lc;
        
        VIGenereLigne1 v = new VIGenereLigne1('','1');
        v.execute(null);

        
    }
   
    static testmethod void VIGenereLigne_type4_test() {
    
        VIInsertDataTest.VIInsertData_EUR_affaire();
        

        VIType_de_depense__c tdMat=[select id from VIType_de_depense__c where name like 'MAT%' ];
        VIType_de_depense__c tdMo=[select id from VIType_de_depense__c where name like 'MO%' ];
        VIType_de_depense__c tdGAR=[select id from VIType_de_depense__c where name like 'GAR%' ];
        VIType_de_depense__c tdPFG=[select id from VIType_de_depense__c where name like 'PFG%' ];
        
        VIcentre_section__c cs=[select id from VIcentre_section__c LIMIT 1 ];
       
        list<VICompte_general__c>ListCG = new list<VICompte_general__c>();
        listCG.add(new  VICompte_general__c  (name='7'));
        listCG.add(new  VICompte_general__c  (name='920100'));
        listCG.add(new  VICompte_general__c  (name='930100'));
        listCG.add(new  VICompte_general__c  (name='940100'));
        listCG.add(new  VICompte_general__c  (name='606000'));        
        listCG.add(new  VICompte_general__c  (name='903000'));        

        insert ListCG ; 
        VICompte_general__c cg = [select id,name from VICompte_general__c LIMIT 1];
        

        VIperiode__c per_ouverte =[SELECT id,name
                                     FROM VIperiode__c 
                                    WHERE statut__c=:VIConstant.PERIODE_OUVERTE ];

        VIperiode__c per_derniere =[SELECT id,name
                                     FROM VIperiode__c 
                                    WHERE statut__c=:VIConstant.PERIODE_DERNIERE ];

        VIAffaire__c aff= [select id, Produit_SousDomaine__c, Entite_BW__c   from VIAffaire__c];

            
        VISousDomaine__c sousdomaine = [select id, Type_d_imputation__c,Mode_de_calcul_de_l_avancement__c  from VISousDomaine__c ];
        sousdomaine.Type_d_imputation__c ='4';
        sousdomaine.Mode_de_calcul_de_l_avancement__c='2';
        update sousdomaine ; 

        VIInsertDataTest.VIInsertData_Achat();
        VIInsertDataTest.VIInsertData_pointage();

        VIAchat__c ac = [SELECT id, origine__c ,CompteGeneral__c,type_depense__c, affaire__c,Centre_Section__c,
                                Sous_chapitre__c,Periode_comptable__c
                           FROM VIAchat__c] ;
        ac.origine__c='SQL-SERVER-Facture-Fournisseur';  
        ac.CompteGeneral__c=cg.name;
        ac.type_depense__c=tdMAT.id;
        update ac;
        
        VIAchat__c ac1 = new VIAchat__c() ; 
        ac1.origine__c='Mvt_stock';
        ac1.CompteGeneral__c=ac.CompteGeneral__c;
        ac1.type_depense__c=tdPFG.id; 
        ac1.affaire__c = ac.affaire__c;
        ac1.Centre_Section__c = ac.Centre_Section__c;
        ac1.Sous_chapitre__c = ac.Sous_chapitre__c;     
        ac1.Periode_comptable__c = ac.Periode_comptable__c;
        ac1.date__c=system.today();
        ac1.ComptabiliseD__c=1;
        insert ac1 ; 
        
        VIAchat__c ac2 = new VIAchat__c() ; 
        ac2.origine__c='Mvt_stock';
        ac2.CompteGeneral__c=ac.CompteGeneral__c;
        ac2.type_depense__c=ac.type_depense__c; 
        ac2.affaire__c = ac.affaire__c;
        ac2.Centre_Section__c = ac.Centre_Section__c;
        ac2.Sous_chapitre__c = ac.Sous_chapitre__c;     
        ac2.Periode_comptable__c = ac.Periode_comptable__c;
        ac2.date__c=system.today();
        ac2.ComptabiliseD__c=1;
        insert ac2 ; 
        
            
        VIGenereLigne1 v = new VIGenereLigne1('','1');
        v.execute(null);

        
        
        
/*      henri
        list<VILigne_Affaire__c>ListLa= [SELECT id, Cout_terminaison_MontantD__c, Engage_brut_arrete_MontantD__c,Ecart_C_A_F_MontantD__c   
                                           FROM VILigne_Affaire__c ] ;

        ListLa[0].Ecart_C_A_F_MontantD__c=1;
        update ListLa ; 
        System.assertEquals(2, listLa.size());
        System.assertEquals(101, listLa[0].Engage_brut_arrete_MontantD__c);
*/
        
    }   
    static testmethod void VIGenereLigne_type8_test() {
    
        VIInsertDataTest.VIInsertData_EUR_affaire();
        //VIInsertDataTest.VIInsertData_Achat();
        //VIInsertDataTest.VIInsertData_Pointage();
        //VIInsertDataTest.VIInsertData_Facture();
        

        VIType_de_depense__c tdMat=[select id from VIType_de_depense__c where name like 'MAT%' ];
        VIType_de_depense__c tdMo=[select id from VIType_de_depense__c where name like 'MO%' ];
        VIType_de_depense__c tdGAR=[select id from VIType_de_depense__c where name like 'GAR%' ];
        VIType_de_depense__c tdPFG=[select id from VIType_de_depense__c where name like 'PFG%' ];
        
        VIcentre_section__c cs=[select id from VIcentre_section__c LIMIT 1 ];
       
        list<VICompte_general__c>ListCG = new list<VICompte_general__c>();
        listCG.add(new  VICompte_general__c  (name='7'));
        listCG.add(new  VICompte_general__c  (name='920100'));
        listCG.add(new  VICompte_general__c  (name='930100'));
        listCG.add(new  VICompte_general__c  (name='940100'));
        listCG.add(new  VICompte_general__c  (name='606000'));        
        listCG.add(new  VICompte_general__c  (name='903000'));        

        insert ListCG ; 

        VIperiode__c per_ouverte =[SELECT id,name
                                     FROM VIperiode__c 
                                    WHERE statut__c=:VIConstant.PERIODE_OUVERTE ];

        VIperiode__c per_derniere =[SELECT id,name
                                     FROM VIperiode__c 
                                    WHERE statut__c=:VIConstant.PERIODE_DERNIERE ];

        VIAffaire__c aff= [select id, Produit_SousDomaine__c, Entite_BW__c   from VIAffaire__c];

            
        VISousDomaine__c sousdomaine = [select id, Type_d_imputation__c,Mode_de_calcul_de_l_avancement__c  from VISousDomaine__c ];
        sousdomaine.Type_d_imputation__c ='8';
        sousdomaine.Mode_de_calcul_de_l_avancement__c='2';
        update sousdomaine ; 

        VIInsertDataTest.VIInsertData_Achat();
        VIInsertDataTest.VIInsertData_pointage();

        VIAchat__c ac = [SELECT id, origine__c ,type_depense__c, affaire__c,Centre_Section__c,CompteGeneral__c,
                                Sous_chapitre__c,Periode_comptable__c
                           FROM VIAchat__c] ;
        ac.origine__c='SQL-SERVER-Facture-Fournisseur';
        ac.type_depense__c=tdMAT.id;        
        update ac;
        
        VIAchat__c ac1 = new VIAchat__c() ; 
        ac1.origine__c='Mvt_stock';
        ac1.CompteGeneral__c=ac.CompteGeneral__c;
        ac1.type_depense__c=tdPFG.id; 
        ac1.affaire__c = ac.affaire__c;
        ac1.Centre_Section__c = ac.Centre_Section__c;
        ac1.Sous_chapitre__c = ac.Sous_chapitre__c;     
        ac1.Periode_comptable__c = ac.Periode_comptable__c;
        ac1.date__c=system.today();
        ac1.ComptabiliseD__c=1;
        insert ac1 ; 
        
        
        VIAchat__c ac2 = new VIAchat__c() ; 
        ac2.origine__c='Mvt_stock';
        ac2.CompteGeneral__c=ac.CompteGeneral__c;
        ac2.type_depense__c=tdMAT.id; 
        ac2.affaire__c = ac.affaire__c;
        ac2.Centre_Section__c = ac.Centre_Section__c;
        ac2.Sous_chapitre__c = ac.Sous_chapitre__c;     
        ac2.Periode_comptable__c = ac.Periode_comptable__c;
        ac2.date__c=system.today();
        ac2.ComptabiliseD__c=1;
        insert ac2 ; 
        
            
        VIGenereLigne1 v = new VIGenereLigne1('','1');
        v.execute(null);

        
        
        
/*      henri
        list<VILigne_Affaire__c>ListLa= [SELECT id, Cout_terminaison_MontantD__c, Engage_brut_arrete_MontantD__c,Ecart_C_A_F_MontantD__c   
                                           FROM VILigne_Affaire__c ] ;

        ListLa[0].Ecart_C_A_F_MontantD__c=1;
        update ListLa ; 
        System.assertEquals(2, listLa.size());
        System.assertEquals(101, listLa[0].Engage_brut_arrete_MontantD__c);
*/
        
    }
    
}