force-app/main/default/objects/Int_achat__c/Int_achat__c.object-meta.xml
<CustomObject>
    <label>Int_Achat</label>
    <nameField>
        <label>Nom de Int</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Int_Achat</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Int_achat__c/fields/CodeAffaire__c.field-meta.xml
<CustomField>
    <fullName>CodeAffaire__c</fullName>
    <label>CodeAffaire</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Int_achat__c/fields/CodeCentre__c.field-meta.xml
<CustomField>
    <fullName>CodeCentre__c</fullName>
    <label>CodeCentre</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Int_achat__c/fields/Mtcommande__c.field-meta.xml
<CustomField>
    <fullName>Mtcommande__c</fullName>
    <label>Mtcommandé</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Int_achat__c/fields/MtCompatabilise__c.field-meta.xml
<CustomField>
    <fullName>MtCompatabilise__c</fullName>
    <label>MtCompatabilisé</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Int_achat__c/fields/TypeDeDepense__c.field-meta.xml
<CustomField>
    <fullName>TypeDeDepense__c</fullName>
    <label>TypeDeDepense</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VICentre_Section__c/VICentre_Section__c.object-meta.xml
<CustomObject>
    <label>Centre / Section</label>
    <nameField>
        <label>Nom de Centre / Section</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Centres / Sections</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VIType_de_depense__c/VIType_de_depense__c.object-meta.xml
<CustomObject>
    <label>Type de dépense</label>
    <nameField>
        <label>Nom de Type de dépense</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Types de dépenses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/VISchedImportAchat_test.cls
@isTest
public class VISchedImportAchat_test {

    static testmethod void VISchedImportAchat_test() {
    
        VIInsertDataTest.VIInsertData_EUR_Affaire();

        VIType_de_depense__c td = [select name from VIType_de_depense__c limit 1];
        VICentre_Section__c cs = [select name from VICentre_Section__c limit 1];

        VIInsertDataTest.VIInsertData_Achat(); 
        
        int_achat__c ac = new int_achat__c (
                               codeAffaire__c='B80000',
                               codeCentre__c=cs.name.left(3) ,
                               codeChapitre__c='00',
                               codesousChapitre__c='00',            
                               Date__c =System.today(),
                               Mtcommande__c  =123,
                               Mtcompatabilise__c  =123,
                               TypeDeDepense__c =td.name.left(3)) ;
        insert ac;
        
        VISchedImportAchat v1 = new VISchedImportAchat('B80000',false,false);
        v1.execute(null);

    }
}