force-app/main/default/objects/Int_achat__c/Int_achat__c.object-meta.xml
<CustomObject>
    <label>Int_Achat</label>
    <nameField>
        <label>Nom de Int</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Int_Achat</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Int_achat__c/fields/CodeAffaire__c.field-meta.xml
<CustomField>
    <fullName>CodeAffaire__c</fullName>
    <label>CodeAffaire</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Int_achat__c/fields/CodeCentre__c.field-meta.xml
<CustomField>
    <fullName>CodeCentre__c</fullName>
    <label>CodeCentre</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Int_achat__c/fields/Date_de_commande__c.field-meta.xml
<CustomField>
    <fullName>Date_de_commande__c</fullName>
    <label>Date de commande</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Int_achat__c/fields/Import_Status__c.field-meta.xml
<CustomField>
    <fullName>Import_Status__c</fullName>
    <label>Import Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Import_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Int_achat__c/fields/lib_frn__c.field-meta.xml
<CustomField>
    <fullName>lib_frn__c</fullName>
    <label>lib_frn</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Int_achat__c/fields/mnt_frg__c.field-meta.xml
<CustomField>
    <fullName>mnt_frg__c</fullName>
    <label>mnt_frg</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Int_achat__c/fields/mnt_frk__c.field-meta.xml
<CustomField>
    <fullName>mnt_frk__c</fullName>
    <label>mnt_frk</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Int_achat__c/fields/Mtcommande__c.field-meta.xml
<CustomField>
    <fullName>Mtcommande__c</fullName>
    <label>Mtcommandé</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Int_achat__c/fields/MtCompatabilise__c.field-meta.xml
<CustomField>
    <fullName>MtCompatabilise__c</fullName>
    <label>MtCompatabilisé</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Int_achat__c/fields/Name_ref_achat__c.field-meta.xml
<CustomField>
    <fullName>Name_ref_achat__c</fullName>
    <label>Name_ref_achat</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Int_achat__c/fields/Num_cde__c.field-meta.xml
<CustomField>
    <fullName>Num_cde__c</fullName>
    <label>Num_cde</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Int_achat__c/fields/Num_fac__c.field-meta.xml
<CustomField>
    <fullName>Num_fac__c</fullName>
    <label>Num_fac</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Int_achat__c/fields/num_frn__c.field-meta.xml
<CustomField>
    <fullName>num_frn__c</fullName>
    <label>num_frn</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Int_achat__c/fields/Origine__c.field-meta.xml
<CustomField>
    <fullName>Origine__c</fullName>
    <label>Origine</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Int_achat__c/fields/TypeDeDepense__c.field-meta.xml
<CustomField>
    <fullName>TypeDeDepense__c</fullName>
    <label>TypeDeDepense</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Int_achat__c/fields/TypeOda__c.field-meta.xml
<CustomField>
    <fullName>TypeOda__c</fullName>
    <label>TypeOda</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VIAchat__c/VIAchat__c.object-meta.xml
<CustomObject>
    <label>Dépense</label>
    <nameField>
        <label>Ref d&apos;achat</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dépenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VIAchat__c/fields/Affaire__c.field-meta.xml
<CustomField>
    <fullName>Affaire__c</fullName>
    <label>Affaire</label>
    <referenceTo>VIAffaire__c</referenceTo>
    <relationshipName>Achats</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VIAchat__c/fields/Centre_Section__c.field-meta.xml
<CustomField>
    <fullName>Centre_Section__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Centre / Section</label>
    <referenceTo>VICentre_Section__c</referenceTo>
    <relationshipName>Achats</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VIAchat__c/fields/CommandeC__c.field-meta.xml
<CustomField>
    <fullName>CommandeC__c</fullName>
    <label>CommandéC</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VIAchat__c/fields/CommandeD__c.field-meta.xml
<CustomField>
    <fullName>CommandeD__c</fullName>
    <label>CommandéD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VIAchat__c/fields/CommandeI__c.field-meta.xml
<CustomField>
    <fullName>CommandeI__c</fullName>
    <label>CommandéI</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VIAchat__c/fields/ComptabiliseD__c.field-meta.xml
<CustomField>
    <fullName>ComptabiliseD__c</fullName>
    <label>ComptabiliséD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VIAchat__c/fields/CompteGeneral__c.field-meta.xml
<CustomField>
    <fullName>CompteGeneral__c</fullName>
    <label>Compte général</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VIAchat__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Date de commande</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VIAchat__c/fields/Date_de_comptabilisation__c.field-meta.xml
<CustomField>
    <fullName>Date_de_comptabilisation__c</fullName>
    <label>Date de comptabilisation</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VIAchat__c/fields/Description_de_la_commande__c.field-meta.xml
<CustomField>
    <fullName>Description_de_la_commande__c</fullName>
    <label>Description de la commande</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VIAchat__c/fields/Nom_du_fournisseur__c.field-meta.xml
<CustomField>
    <fullName>Nom_du_fournisseur__c</fullName>
    <label>Nom du fournisseur</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VIAchat__c/fields/Num_cde__c.field-meta.xml
<CustomField>
    <fullName>Num_cde__c</fullName>
    <externalId>true</externalId>
    <label>Num_cde</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VIAchat__c/fields/num_fac__c.field-meta.xml
<CustomField>
    <fullName>num_fac__c</fullName>
    <label>Numéro Facture</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VIAchat__c/fields/num_frn__c.field-meta.xml
<CustomField>
    <fullName>num_frn__c</fullName>
    <label>num_frn</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VIAchat__c/fields/Origine__c.field-meta.xml
<CustomField>
    <fullName>Origine__c</fullName>
    <label>Origine</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VIAchat__c/fields/Sous_chapitre__c.field-meta.xml
<CustomField>
    <fullName>Sous_chapitre__c</fullName>
    <label>Sous chapitre</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sous_chapitre</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/VIAchat__c/fields/Type_depense__c.field-meta.xml
<CustomField>
    <fullName>Type_depense__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Type de dépense</label>
    <referenceTo>VIType_de_depense__c</referenceTo>
    <relationshipName>Achats</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VIAchat__c/fields/TypeOda__c.field-meta.xml
<CustomField>
    <fullName>TypeOda__c</fullName>
    <label>TypeOda</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VIAffaire__c/VIAffaire__c.object-meta.xml
<CustomObject>
    <label>Affaire</label>
    <nameField>
        <label>Code Affaire</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Affaires</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VIAffaire__c/fields/Date_max_mouvement__c.field-meta.xml
<CustomField>
    <fullName>Date_max_mouvement__c</fullName>
    <label>Date max mouvement</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VICentre_Section__c/VICentre_Section__c.object-meta.xml
<CustomObject>
    <label>Centre / Section</label>
    <nameField>
        <label>Nom de Centre / Section</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Centres / Sections</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VIParametres__c/VIParametres__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>VIParametres</label>
</CustomObject>

force-app/main/default/objects/VIParametres__c/fields/Sans_Calcul_de_PRI__c.field-meta.xml
<CustomField>
    <fullName>Sans_Calcul_de_PRI__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Si coché, on fait le calcul avec les taux.Sinon, on prend les montants tel quel</inlineHelpText>
    <label>Sans Calcul de PRI ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VIPays__c/VIPays__c.object-meta.xml
<CustomObject>
    <label>Pays</label>
    <nameField>
        <label>Nom de Pays</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pays</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/VIType_de_depense__c/VIType_de_depense__c.object-meta.xml
<CustomObject>
    <label>Type de dépense</label>
    <nameField>
        <label>Nom de Type de dépense</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Types de dépenses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/VISchedImportAchat.cls
/*
*
*  We have to launch the import files 
*
*
*  for running by hand : 
 VISchedImportAchat v = new VISchedImportAchat();
 v.execute(null);
*
*  for running every hour at xx:16
     VISchedImportAchat m = new VISchedImportAchat();
     String sch = '0 16 * * * ?';
     String jobID = system.schedule('VISchedImportAchat', sch, m);
*
*
*/
global class VISchedImportAchat implements Schedulable,Database.Batchable<sObject>,Database.Stateful{

    Global double num_record = 0;
    Global String IDLog ='';    
    Global id PaysFr = null ; 
    Global Map<string, VICentre_Section__c>MapCentre = new Map<string, VICentre_Section__c>();
    Global Map<string, VIType_de_depense__c>MapDepense = new Map<string, VIType_de_depense__c>();
    
    Global VICentre_section__c CS800;
    
    private string AffaireAGenerer; 
    private boolean Enchaine ;
    private boolean toute ;
    
     public VISchedImportAchat(String Param1,Boolean Param2,Boolean Param3 ) {
        AffaireAGenerer = Param1;        
        Enchaine = Param2;                
        toute = Param3;                         
    }

    
    global Database.QueryLocator start(Database.BatchableContext BC){
        IDLog=VIUtils.LogWrite('VISchedImportAchat','4 Running','','Start ');

        for(VIType_de_depense__c td : [Select name, id from VIType_de_depense__c]) {
            MapDepense.put(td.name.Left(3), td);
        }
        for(VICentre_Section__c cs : [Select name, id from VICentre_Section__c]) {
            MapCentre.put(cs.name.Left(3), cs);
        }
        
        
        PaysFr = [SELECT id from VIpays__c where name='FR'].id; 
                                         
        string query = 'SELECT id,codeAffaire__c, codecentre__c,codechapitre__c, codesousChapitre__c,Name_ref_achat__c ,date_de_commande__c, ';
        query = query+'        Date__c, Mtcommande__c ,MtCompatabilise__c , Import_Status__c, typededepense__c,num_cde__c,num_frn__c,lib_frn__c, libelle__c, typeODA__c,   ';
        query = query+'        Mnt_frg__c ,Mnt_frk__c ,origine__c, name, CompteGeneral__c,num_fac__c    ';        
        query = query+'   FROM Int_achat__c ';
        query = query+'   WHERE codeaffaire__c!=null ';

        if(!toute)
            query = query+'     AND (Import_Status__c =\'1\' or Import_Status__c =null) ';

        query = query+'     AND (codeAffaire__c Like \''+AffaireAGenerer+'%\')  ';
        //query = query+'     AND Origine__c =\'SQL-SERVER-Facture-Fournisseur\'  ';
        //query = query+'     AND Date__c>=2021-04-01  ';
       // query = query+'     AND (not codeAffaire__c Like \'8%\')  ';        
       // query = query+'     AND ( codecentre__c not in (\'94O\',\'94Y\',\'430\',\'331\',\'94R\',\'C92\',\'99O\'))  '; 
                      
        query = query+'   Order by codeaffaire__c,date__c desc  ';        
        system.debug(query);
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<Int_achat__c> scope){
        num_record = 0;
        Map<string, VIAffaire__c>MapAffaire  = new Map<string, VIAffaire__c>();
        Map<string, VIAchat__c>MapAchat  = new Map<string, VIAchat__c>();
        
        List<string>ListIDAffaire = new List<string>();
        date date_min ; 
        date date_max ;
        
        for(Int_achat__c ac:scope) {
            num_record = num_record+1;
            ListIDAffaire.add(ac.codeAffaire__c);
            if(date_max==null || date_max<ac.date__c)
                date_max=ac.date__c; 
            
            if(date_min==null || date_min>ac.date__c)
                date_min=ac.date__c; 
            
        }       
        system.debug('Dates '+date_min+' '+date_max);

        for(VIAffaire__c aff : [SELECT id,name,date_max_mouvement__c
                                  FROM VIAffaire__c 
                                 WHERE name in :ListIDAffaire]) {
            MapAffaire.put(aff.name, aff);
        }
        system.debug('Affaire '+MapAffaire);
        

        for(VIAchat__c ac : [SELECT id,name,Num_cde__c,affaire__r.name,Num_frn__c
                               FROM VIAchat__c 
                              WHERE affaire__r.name in :ListIDAffaire
                                AND date__c>=:date_min
                                AND date__c<=:date_max]) {
            MapAchat.put(ac.name, ac);
        }

        list<VIAchat__c>listInsertAchat = new List<VIAchat__c>();
        for(Int_achat__c ac:scope) {
            String num_cde='';
            if(ac.origine__c=='SQL-SERVER-Facture-Fournisseur') {
                num_cde='F'+'-'+ac.Name_ref_achat__c.toplainstring();
            } else if(ac.origine__c=='reprise' || ac.origine__c=='stock' || ac.origine__c=='Mvt_stock'  ) {
                num_cde='M-'+ac.Name.removestart(ac.codeaffaire__c+'-');
            } else {
                if(ac.num_cde__c==null && ac.num_frn__c==null) {
                    num_cde=ac.name.replace('-null','');
                } else {
                    if(ac.Name_ref_achat__c!=null) {
                        num_cde = ac.Name_ref_achat__c.toPlainString() +'-';
                    } else {
                        num_cde = ac.num_cde__c+'-'+ac.num_frn__c;
                    }
                } 
                if(ac.origine__c!='SQL-SERVER-ISA_V2' ) { 
                    num_cde='S'+'-'+num_cde;
                } else {
                    num_cde='M'+'-'+num_cde+'-'+ac.date_de_commande__c;
                }
             

            }
            num_cde=num_cde.left(80);
            
            if(MapAchat.containskey(ac.codeAffaire__c+'-'+num_cde)) {
                ac.Import_Status__c='2';
                continue ; 
            }
            
            if(ac.Mtcommande__c==0 && ac.MtCompatabilise__c==0 ) {
                ac.Import_Status__c='2';
                continue ; 
            }

            VIAchat__c Achat = new VIAchat__c();
            
            system.debug(ac.codeaffaire__c+'-'+num_cde);
            
            if(MapAffaire.containskey(ac.codeAffaire__c)) {
                VIAffaire__c Affaire=MapAffaire.get(ac.codeAffaire__c);
                Achat.affaire__c=Affaire.id;
                Achat.name = ac.codeAffaire__c+'-'+num_cde;
                
                if(affaire.date_max_mouvement__c==null || affaire.date_max_mouvement__c<ac.date__c)
                    affaire.date_max_mouvement__c=ac.date__c;

                
                if(!MapCentre.containskey(ac.codecentre__c)) {
                    VIUtils.LogWrite('VISchedImportAchat','3 Error','','code centre inconnu '+ac.codecentre__c+' '+ac.id);
                    continue ; 
                }
                if(!MapDepense.containskey((ac.typedeDepense__c+' ').left(3))) {
                    VIUtils.LogWrite('VISchedImportAchat','3 Error','','code depense inconnu '+ac.typedeDepense__c+' '+ac.id);
                    continue ; 
                }
                
                Achat.Centre_Section__c =MapCentre.get(ac.codecentre__c).id;
                Achat.type_depense__c= MapDepense.get( (ac.typedeDepense__c+' ').left(3)).id;
       
                Achat.Sous_chapitre__c =('0'+ac.Codechapitre__c).right(2)+'-'+('0'+ac.Codesouschapitre__c).right(2);
                if(ac.origine__c=='reprise') {
                    achat.origine__c='SQL-SERVER-Facture-Fournisseur';
                } else if (ac.origine__c=='stock') {
                    achat.origine__c='Mvt_stock';
                } else {
                    Achat.Origine__c = ac.origine__c;
                }

                Achat.CommandeD__c =(ac.Mtcommande__c==null ? 0 :ac.Mtcommande__c);
                Achat.ComptabiliseD__c =(ac.Mtcompatabilise__c==null ? 0 :ac.Mtcompatabilise__c);

                Achat.Date__c =ac.date__c;

                if(Achat.ComptabiliseD__c!=0)
                    Achat.Date_de_comptabilisation__c =ac.date__c;
                
                Achat.CommandeI__c =Achat.CommandeD__c +(ac.mnt_frg__c==null ? 0 : ac.mnt_frg__c) ;            
                Achat.CommandeC__c =Achat.CommandeI__c +(ac.mnt_frk__c==null ? 0 : ac.mnt_frk__c) ;                        
                Achat.Num_cde__c  = ac.Num_cde__c ;

                if(ac.num_frn__c!=null)
                    Achat.num_frn__c  = ac.num_frn__c ;
                
                Achat.Nom_du_fournisseur__c          = ac.lib_frn__c ; 
                Achat.Description_de_la_commande__c  = ac.libelle__c ;                                
                Achat.TypeOda__c = ac.TypeOda__c;  
                Achat.num_fac__c = ac.num_fac__c;
                Achat.CompteGeneral__c  = ac.CompteGeneral__c ;
                MapAchat.put(ac.codeAffaire__c+'-'+num_cde, achat);

                listInsertAchat.add(Achat);
            } else {
                VIUtils.LogWrite('VISchedImportAchat','3 Error','','code affaire inconnue '+ac.codeaffaire__c+' '+ac.id);
                continue ;
            }
            ac.Import_Status__c='2';

        }
        update scope ; 
        update MapAffaire.values();
        insert listInsertAchat;        

    }

    global void finish(Database.BatchableContext BC){
        IDLog=VIUtils.LogWrite('VISchedImportAchat','1 Normal',IDLog,'End '+num_record);
        if(enchaine)
            Database.executeBatch(new VISchedImportPointage(AffaireAGenerer, enchaine,toute),VISchedImportPointage.NBR_LOT());
        
    }

    global void execute(SchedulableContext scon) {
        Database.executeBatch(new VISchedImportAchat(AffaireAGenerer, enchaine, toute),VISchedImportAchat.NBR_LOT());

    }

    public static  integer NBR_LOT () {
         VIParametres__c param = VIParametres__c.getInstance(UserInfo.getUserId()); 
         integer i ; 
         if(param.Sans_Calcul_de_PRI__c) {
             i=80 ;  // ça plantait à 100
         } else {
             i=10;    
         }
         i=80;
         return i;
    }
    
}